<?php
return array_map('trim', [
  ["province" => "AURORA", "municipality" => "Baler", "zip_code" => "3200"],
  ["province" => "AURORA", "municipality" => "Casiguran", "zip_code" => "3204"],
  ["province" => "AURORA", "municipality" => "Dilasag", "zip_code" => "3205"],
  ["province" => "AURORA", "municipality" => "Dinalungan", "zip_code" => "3206"],
  ["province" => "AURORA", "municipality" => "Dingalan", "zip_code" => "3207"],
  ["province" => "AURORA", "municipality" => "Dipaculao", "zip_code" => "3203"],
  ["province" => "AURORA", "municipality" => "Maria Aurora", "zip_code" => "3202"],
  ["province" => "AURORA", "municipality" => "San Luis", "zip_code" => "3201"],

  ["province" => "BATAAN", "municipality" => "Abucay", "zip_code" => "2114"],
  ["province" => "BATAAN", "municipality" => "Cabcaben", "zip_code" => "2109"],
  ["province" => "BATAAN", "municipality" => "Bagac", "zip_code" => "2107"],
  ["province" => "BATAAN", "municipality" => "Balanga", "zip_code" => "2100"],
  ["province" => "BATAAN", "municipality" => "FAB (Freefort Area of  Bataan) ", "zip_code" => "2106"],
  ["province" => "BATAAN", "municipality" => "Dinalupihan", "zip_code" => "2110"],
  ["province" => "BATAAN", "municipality" => "Hermosa", "zip_code" => "2111"],
  ["province" => "BATAAN", "municipality" => "Lamao", "zip_code" => "2104"],
  ["province" => "BATAAN", "municipality" => "Limay", "zip_code" => "2103"],
  ["province" => "BATAAN", "municipality" => "Mariveles", "zip_code" => "2105"],
  ["province" => "BATAAN", "municipality" => "Morong", "zip_code" => "2108"],
  ["province" => "BATAAN", "municipality" => "Orani", "zip_code" => "2112"],
  ["province" => "BATAAN", "municipality" => "Orion", "zip_code" => "2102"],
  ["province" => "BATAAN", "municipality" => "Pilar", "zip_code" => "2101"],
  ["province" => "BATAAN", "municipality" => "Samal", "zip_code" => "2113"],

  ["province" => "BULACAN", "municipality" => "Angat", "zip_code" => "3012"],
  ["province" => "BULACAN", "municipality" => "Balagtas", "zip_code" => "3016"],
  ["province" => "BULACAN", "municipality" => "Baliuag", "zip_code" => "3006"],
  ["province" => "BULACAN", "municipality" => "Bocaue", "zip_code" => "3018"],
  ["province" => "BULACAN", "municipality" => "Bulacan", "zip_code" => "3017"],
  ["province" => "BULACAN", "municipality" => "Bustos", "zip_code" => "3007"],
  ["province" => "BULACAN", "municipality" => "Calumpit", "zip_code" => "3003"],
  ["province" => "BULACAN", "municipality" => "Cruz na Daan", "zip_code" => "3025"],
  ["province" => "BULACAN", "municipality" => "Doña Remedios Trinidad", "zip_code" => "3009"],
  ["province" => "BULACAN", "municipality" => "Guiguinto", "zip_code" => "3015"],
  ["province" => "BULACAN", "municipality" => "Hagonoy", "zip_code" => "3002"],
  ["province" => "BULACAN", "municipality" => "Malolos", "zip_code" => "3000"],
  ["province" => "BULACAN", "municipality" => "Marilao", "zip_code" => "3019"],
  ["province" => "BULACAN", "municipality" => "Meycauayan", "zip_code" => "3020"],
  ["province" => "BULACAN", "municipality" => "Norzagaray", "zip_code" => "3013"],
  ["province" => "BULACAN", "municipality" => "Obando", "zip_code" => "3021"],
  ["province" => "BULACAN", "municipality" => "Pandi", "zip_code" => "3014"],
  ["province" => "BULACAN", "municipality" => "Paombong", "zip_code" => "3001"],
  ["province" => "BULACAN", "municipality" => "Plaridel", "zip_code" => "3004"],
  ["province" => "BULACAN", "municipality" => "Pulilan", "zip_code" => "3005"],
  ["province" => "BULACAN", "municipality" => "San Ildefonso", "zip_code" => "3010"],
  ["province" => "BULACAN", "municipality" => "San Jose Del Monte", "zip_code" => "3023"],
  ["province" => "BULACAN", "municipality" => "San Miguel", "zip_code" => "3011"],
  ["province" => "BULACAN", "municipality" => "San Rafael", "zip_code" => "3008"],
  ["province" => "BULACAN", "municipality" => "Sapang Palay", "zip_code" => "3024"],
  ["province" => "BULACAN", "municipality" => "Sta. Maria", "zip_code" => "3022"],

  ["province" => "NUEVA ECIJA", "municipality" => "Aliaga", "zip_code" => "3111"],
  ["province" => "NUEVA ECIJA", "municipality" => "Bongabon", "zip_code" => "3128"],
  ["province" => "NUEVA ECIJA", "municipality" => "Cabanatuan City", "zip_code" => "3100"],
  ["province" => "NUEVA ECIJA", "municipality" => "Cabiao", "zip_code" => "3107"],
  ["province" => "NUEVA ECIJA", "municipality" => "Carrangalan", "zip_code" => "3123"],
  ["province" => "NUEVA ECIJA", "municipality" => "Central Luzon State University", "zip_code" => "3120"],
  ["province" => "NUEVA ECIJA", "municipality" => "Cuyapo", "zip_code" => "3117"],
  ["province" => "NUEVA ECIJA", "municipality" => "Fort Magsaysay", "zip_code" => "3130"],
  ["province" => "NUEVA ECIJA", "municipality" => "Gabaldon", "zip_code" => "3131"],
  ["province" => "NUEVA ECIJA", "municipality" => "Gapan City", "zip_code" => "3105"],
  ["province" => "NUEVA ECIJA", "municipality" => "Gen. M. Natividad", "zip_code" => "3125"],
  ["province" => "NUEVA ECIJA", "municipality" => "Gen. Tinio", "zip_code" => "3104"],
  ["province" => "NUEVA ECIJA", "municipality" => "Guimba", "zip_code" => "3115"],
  ["province" => "NUEVA ECIJA", "municipality" => "Jaen", "zip_code" => "3109"],
  ["province" => "NUEVA ECIJA", "municipality" => "Laur", "zip_code" => "3129"],
  ["province" => "NUEVA ECIJA", "municipality" => "Licab", "zip_code" => "3112"],
  ["province" => "NUEVA ECIJA", "municipality" => "Llanera", "zip_code" => "3126"],
  ["province" => "NUEVA ECIJA", "municipality" => "Lupao", "zip_code" => "3122"],
  ["province" => "NUEVA ECIJA", "municipality" => "Muñoz", "zip_code" => "3119"],
  ["province" => "NUEVA ECIJA", "municipality" => "Nampicuan", "zip_code" => "3116"],
  ["province" => "NUEVA ECIJA", "municipality" => "Palayan City", "zip_code" => "3132"],
  ["province" => "NUEVA ECIJA", "municipality" => "Pantabangan", "zip_code" => "3124"],
  ["province" => "NUEVA ECIJA", "municipality" => "Peñaranda", "zip_code" => "3103"],
  ["province" => "NUEVA ECIJA", "municipality" => "Quezon", "zip_code" => "3113"],
  ["province" => "NUEVA ECIJA", "municipality" => "Rizal", "zip_code" => "3127"],
  ["province" => "NUEVA ECIJA", "municipality" => "San Antonio", "zip_code" => "3108"],
  ["province" => "NUEVA ECIJA", "municipality" => "San Isidro", "zip_code" => "3106"],
  ["province" => "NUEVA ECIJA", "municipality" => "San Jose City", "zip_code" => "3121"],
  ["province" => "NUEVA ECIJA", "municipality" => "San Leonardo", "zip_code" => "3102"],
  ["province" => "NUEVA ECIJA", "municipality" => "Sta. Rosa", "zip_code" => "3101"],
  ["province" => "NUEVA ECIJA", "municipality" => "Sto. Domingo", "zip_code" => "3133"],
  ["province" => "NUEVA ECIJA", "municipality" => "Talavera", "zip_code" => "3114"],
  ["province" => "NUEVA ECIJA", "municipality" => "Talugtog", "zip_code" => "3118"],
  ["province" => "NUEVA ECIJA", "municipality" => "Zaragoza", "zip_code" => "3110"],

  ["province" => "PAMPANGA", "municipality" => "Angeles City", "zip_code" => "2009"],
  ["province" => "PAMPANGA", "municipality" => "Apalit", "zip_code" => "2016"],
  ["province" => "PAMPANGA", "municipality" => "Arayat", "zip_code" => "2012"],
  ["province" => "PAMPANGA", "municipality" => "Bacolor", "zip_code" => "2001"],
  ["province" => "PAMPANGA", "municipality" => "Balibago", "zip_code" => "2024"],
  ["province" => "PAMPANGA", "municipality" => "Basa airbase", "zip_code" => "2007"],
  ["province" => "PAMPANGA", "municipality" => "Candaba", "zip_code" => "2013"],
  ["province" => "PAMPANGA", "municipality" => "CSEZ, Clark", "zip_code" => "2023"],
  ["province" => "PAMPANGA", "municipality" => "Dau, Mabalacat", "zip_code" => "2026"],
  ["province" => "PAMPANGA", "municipality" => "Floridablanca", "zip_code" => "2006"],
  ["province" => "PAMPANGA", "municipality" => "Guagua", "zip_code" => "2003"],
  ["province" => "PAMPANGA", "municipality" => "Lubao", "zip_code" => "2005"],
  ["province" => "PAMPANGA", "municipality" => "Mabalacat", "zip_code" => "2010"],
  ["province" => "PAMPANGA", "municipality" => "Macabebe", "zip_code" => "2018"],
  ["province" => "PAMPANGA", "municipality" => "Magalang", "zip_code" => "2011"],
  ["province" => "PAMPANGA", "municipality" => "Masantol", "zip_code" => "2017"],
  ["province" => "PAMPANGA", "municipality" => "Mexico", "zip_code" => "2021"],
  ["province" => "PAMPANGA", "municipality" => "Minalin", "zip_code" => "2019"],
  ["province" => "PAMPANGA", "municipality" => "Porac", "zip_code" => "2008"],
  ["province" => "PAMPANGA", "municipality" => "San Fernando", "zip_code" => "2000"],
  ["province" => "PAMPANGA", "municipality" => "San Luis", "zip_code" => "2014"],
  ["province" => "PAMPANGA", "municipality" => "San Simon", "zip_code" => "2015"],
  ["province" => "PAMPANGA", "municipality" => "Sasmuan", "zip_code" => "2004"],
  ["province" => "PAMPANGA", "municipality" => "Santa Ana", "zip_code" => "2022"],
  ["province" => "PAMPANGA", "municipality" => "Santa Cruz, Lubao", "zip_code" => "2025"],
  ["province" => "PAMPANGA", "municipality" => "Santa Rita", "zip_code" => "2002"],
  ["province" => "PAMPANGA", "municipality" => "Santo Tomas", "zip_code" => "2020"],

  ["province" => "TARLAC", "municipality" => "Anao", "zip_code" => "2310"],
  ["province" => "TARLAC", "municipality" => "Bamban", "zip_code" => "2317"],
  ["province" => "TARLAC", "municipality" => "Camiling", "zip_code" => "2306"],
  ["province" => "TARLAC", "municipality" => "Capas", "zip_code" => "2315"],
  ["province" => "TARLAC", "municipality" => "Concepcion", "zip_code" => "2316"],
  ["province" => "TARLAC", "municipality" => "Gerona", "zip_code" => "2302"],
  ["province" => "TARLAC", "municipality" => "La Paz", "zip_code" => "2314"],
  ["province" => "TARLAC", "municipality" => "Mayantoc", "zip_code" => "2304"],
  ["province" => "TARLAC", "municipality" => "Moncada", "zip_code" => "2308"],
  ["province" => "TARLAC", "municipality" => "Paniqui", "zip_code" => "2307"],
  ["province" => "TARLAC", "municipality" => "Pura", "zip_code" => "2312"],
  ["province" => "TARLAC", "municipality" => "Ramos", "zip_code" => "2311"],
  ["province" => "TARLAC", "municipality" => "San Clemente", "zip_code" => "2305"],
  ["province" => "TARLAC", "municipality" => "San Jose", "zip_code" => "2318"],
  ["province" => "TARLAC", "municipality" => "San Manuel", "zip_code" => "2309"],
  ["province" => "TARLAC", "municipality" => "San Miguel", "zip_code" => "2301"],
  ["province" => "TARLAC", "municipality" => "Sta. Ignacia", "zip_code" => "2303"],
  ["province" => "TARLAC", "municipality" => "Tarlac", "zip_code" => "2300"],
  ["province" => "TARLAC", "municipality" => "Victoria", "zip_code" => "2313"],

  ["province" => "ZAMBALES", "municipality" => "Botolan", "zip_code" => "2202"],
  ["province" => "ZAMBALES", "municipality" => "Cabangan", "zip_code" => "2203"],
  ["province" => "ZAMBALES", "municipality" => "Candelaria", "zip_code" => "2212"],
  ["province" => "ZAMBALES", "municipality" => "Castillejos", "zip_code" => "2208"],
  ["province" => "ZAMBALES", "municipality" => "Iba", "zip_code" => "2201"],
  ["province" => "ZAMBALES", "municipality" => "Masinloc", "zip_code" => "2211"],
  ["province" => "ZAMBALES", "municipality" => "Olongapo City", "zip_code" => "2200"],
  ["province" => "ZAMBALES", "municipality" => "Palauig", "zip_code" => "2210"],
  ["province" => "ZAMBALES", "municipality" => "San Antonio", "zip_code" => "2206"],
  ["province" => "ZAMBALES", "municipality" => "San Felipe", "zip_code" => "2204"],
  ["province" => "ZAMBALES", "municipality" => "San Marcelino", "zip_code" => "2207"],
  ["province" => "ZAMBALES", "municipality" => "San Narciso", "zip_code" => "2205"],
  ["province" => "ZAMBALES", "municipality" => "Sta. Cruz", "zip_code" => "2213"],
  ["province" => "ZAMBALES", "municipality" => "Subic", "zip_code" => "2209"],
]);
