<?php

declare(strict_types=1);
return [
    ['province' => 'AURORA', 'municipality' => 'BALER', 'zip_code' => '3200'],
    ['province' => 'AURORA', 'municipality' => 'CASIGURAN', 'zip_code' => '3204'],
    ['province' => 'AURORA', 'municipality' => 'DILASAG', 'zip_code' => '3205'],
    ['province' => 'AURORA', 'municipality' => 'DINALUNGAN', 'zip_code' => '3206'],
    ['province' => 'AURORA', 'municipality' => 'DINGALAN', 'zip_code' => '3207'],
    ['province' => 'AURORA', 'municipality' => 'DIPACULAO', 'zip_code' => '3203'],
    ['province' => 'AURORA', 'municipality' => 'MARIA AURORA', 'zip_code' => '3202'],
    ['province' => 'AURORA', 'municipality' => 'SAN LUIS', 'zip_code' => '3201'],

    ['province' => 'BATAAN', 'municipality' => 'ABUCAY', 'zip_code' => '2114'],
    ['province' => 'BATAAN', 'municipality' => 'CABCABEN', 'zip_code' => '2109'],
    ['province' => 'BATAAN', 'municipality' => 'BAGAC', 'zip_code' => '2107'],
    ['province' => 'BATAAN', 'municipality' => 'BALANGA', 'zip_code' => '2100'],
    ['province' => 'BATAAN', 'municipality' => 'FAB (FREEFORT AREA OF  BATAAN) ', 'zip_code' => '2106'],
    ['province' => 'BATAAN', 'municipality' => 'DINALUPIHAN', 'zip_code' => '2110'],
    ['province' => 'BATAAN', 'municipality' => 'HERMOSA', 'zip_code' => '2111'],
    ['province' => 'BATAAN', 'municipality' => 'LAMAO', 'zip_code' => '2104'],
    ['province' => 'BATAAN', 'municipality' => 'LIMAY', 'zip_code' => '2103'],
    ['province' => 'BATAAN', 'municipality' => 'MARIVELES', 'zip_code' => '2105'],
    ['province' => 'BATAAN', 'municipality' => 'MORONG', 'zip_code' => '2108'],
    ['province' => 'BATAAN', 'municipality' => 'ORANI', 'zip_code' => '2112'],
    ['province' => 'BATAAN', 'municipality' => 'ORION', 'zip_code' => '2102'],
    ['province' => 'BATAAN', 'municipality' => 'PILAR', 'zip_code' => '2101'],
    ['province' => 'BATAAN', 'municipality' => 'SAMAL', 'zip_code' => '2113'],

    ['province' => 'BULACAN', 'municipality' => 'ANGAT', 'zip_code' => '3012'],
    ['province' => 'BULACAN', 'municipality' => 'BALAGTAS', 'zip_code' => '3016'],
    ['province' => 'BULACAN', 'municipality' => 'BALIUAG', 'zip_code' => '3006'],
    ['province' => 'BULACAN', 'municipality' => 'BOCAUE', 'zip_code' => '3018'],
    ['province' => 'BULACAN', 'municipality' => 'BULACAN', 'zip_code' => '3017'],
    ['province' => 'BULACAN', 'municipality' => 'BUSTOS', 'zip_code' => '3007'],
    ['province' => 'BULACAN', 'municipality' => 'CALUMPIT', 'zip_code' => '3003'],
    ['province' => 'BULACAN', 'municipality' => 'CRUZ NA DAAN', 'zip_code' => '3025'],
    ['province' => 'BULACAN', 'municipality' => 'DOÑA REMEDIOS TRINIDAD', 'zip_code' => '3009'],
    ['province' => 'BULACAN', 'municipality' => 'GUIGUINTO', 'zip_code' => '3015'],
    ['province' => 'BULACAN', 'municipality' => 'HAGONOY', 'zip_code' => '3002'],
    ['province' => 'BULACAN', 'municipality' => 'MALOLOS', 'zip_code' => '3000'],
    ['province' => 'BULACAN', 'municipality' => 'MARILAO', 'zip_code' => '3019'],
    ['province' => 'BULACAN', 'municipality' => 'MEYCAUAYAN', 'zip_code' => '3020'],
    ['province' => 'BULACAN', 'municipality' => 'NORZAGARAY', 'zip_code' => '3013'],
    ['province' => 'BULACAN', 'municipality' => 'OBANDO', 'zip_code' => '3021'],
    ['province' => 'BULACAN', 'municipality' => 'PANDI', 'zip_code' => '3014'],
    ['province' => 'BULACAN', 'municipality' => 'PAOMBONG', 'zip_code' => '3001'],
    ['province' => 'BULACAN', 'municipality' => 'PLARIDEL', 'zip_code' => '3004'],
    ['province' => 'BULACAN', 'municipality' => 'PULILAN', 'zip_code' => '3005'],
    ['province' => 'BULACAN', 'municipality' => 'SAN ILDEFONSO', 'zip_code' => '3010'],
    ['province' => 'BULACAN', 'municipality' => 'SAN JOSE DEL MONTE', 'zip_code' => '3023'],
    ['province' => 'BULACAN', 'municipality' => 'SAN MIGUEL', 'zip_code' => '3011'],
    ['province' => 'BULACAN', 'municipality' => 'SAN RAFAEL', 'zip_code' => '3008'],
    ['province' => 'BULACAN', 'municipality' => 'SAPANG PALAY', 'zip_code' => '3024'],
    ['province' => 'BULACAN', 'municipality' => 'STA. MARIA', 'zip_code' => '3022'],

    ['province' => 'NUEVA ECIJA', 'municipality' => 'ALIAGA', 'zip_code' => '3111'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'BONGABON', 'zip_code' => '3128'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'CABANATUAN CITY', 'zip_code' => '3100'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'CABIAO', 'zip_code' => '3107'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'CARRANGALAN', 'zip_code' => '3123'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'CENTRAL LUZON STATE UNIVERSITY', 'zip_code' => '3120'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'CUYAPO', 'zip_code' => '3117'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'FORT MAGSAYSAY', 'zip_code' => '3130'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'GABALDON', 'zip_code' => '3131'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'GAPAN CITY', 'zip_code' => '3105'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'GEN. M. NATIVIDAD', 'zip_code' => '3125'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'GEN. TINIO', 'zip_code' => '3104'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'GUIMBA', 'zip_code' => '3115'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'JAEN', 'zip_code' => '3109'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'LAUR', 'zip_code' => '3129'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'LICAB', 'zip_code' => '3112'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'LLANERA', 'zip_code' => '3126'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'LUPAO', 'zip_code' => '3122'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'MUÑOZ', 'zip_code' => '3119'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'NAMPICUAN', 'zip_code' => '3116'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'PALAYAN CITY', 'zip_code' => '3132'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'PANTABANGAN', 'zip_code' => '3124'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'PEÑARANDA', 'zip_code' => '3103'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'QUEZON', 'zip_code' => '3113'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'RIZAL', 'zip_code' => '3127'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'SAN ANTONIO', 'zip_code' => '3108'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'SAN ISIDRO', 'zip_code' => '3106'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'SAN JOSE CITY', 'zip_code' => '3121'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'SAN LEONARDO', 'zip_code' => '3102'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'STA. ROSA', 'zip_code' => '3101'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'STO. DOMINGO', 'zip_code' => '3133'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'TALAVERA', 'zip_code' => '3114'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'TALUGTOG', 'zip_code' => '3118'],
    ['province' => 'NUEVA ECIJA', 'municipality' => 'ZARAGOZA', 'zip_code' => '3110'],

    ['province' => 'PAMPANGA', 'municipality' => 'ANGELES CITY', 'zip_code' => '2009'],
    ['province' => 'PAMPANGA', 'municipality' => 'APALIT', 'zip_code' => '2016'],
    ['province' => 'PAMPANGA', 'municipality' => 'ARAYAT', 'zip_code' => '2012'],
    ['province' => 'PAMPANGA', 'municipality' => 'BACOLOR', 'zip_code' => '2001'],
    ['province' => 'PAMPANGA', 'municipality' => 'BALIBAGO', 'zip_code' => '2024'],
    ['province' => 'PAMPANGA', 'municipality' => 'BASA AIRBASE', 'zip_code' => '2007'],
    ['province' => 'PAMPANGA', 'municipality' => 'CANDABA', 'zip_code' => '2013'],
    ['province' => 'PAMPANGA', 'municipality' => 'CSEZ, CLARK', 'zip_code' => '2023'],
    ['province' => 'PAMPANGA', 'municipality' => 'DAU, MABALACAT', 'zip_code' => '2026'],
    ['province' => 'PAMPANGA', 'municipality' => 'FLORIDABLANCA', 'zip_code' => '2006'],
    ['province' => 'PAMPANGA', 'municipality' => 'GUAGUA', 'zip_code' => '2003'],
    ['province' => 'PAMPANGA', 'municipality' => 'LUBAO', 'zip_code' => '2005'],
    ['province' => 'PAMPANGA', 'municipality' => 'MABALACAT', 'zip_code' => '2010'],
    ['province' => 'PAMPANGA', 'municipality' => 'MACABEBE', 'zip_code' => '2018'],
    ['province' => 'PAMPANGA', 'municipality' => 'MAGALANG', 'zip_code' => '2011'],
    ['province' => 'PAMPANGA', 'municipality' => 'MASANTOL', 'zip_code' => '2017'],
    ['province' => 'PAMPANGA', 'municipality' => 'MEXICO', 'zip_code' => '2021'],
    ['province' => 'PAMPANGA', 'municipality' => 'MINALIN', 'zip_code' => '2019'],
    ['province' => 'PAMPANGA', 'municipality' => 'PORAC', 'zip_code' => '2008'],
    ['province' => 'PAMPANGA', 'municipality' => 'SAN FERNANDO', 'zip_code' => '2000'],
    ['province' => 'PAMPANGA', 'municipality' => 'SAN LUIS', 'zip_code' => '2014'],
    ['province' => 'PAMPANGA', 'municipality' => 'SAN SIMON', 'zip_code' => '2015'],
    ['province' => 'PAMPANGA', 'municipality' => 'SASMUAN', 'zip_code' => '2004'],
    ['province' => 'PAMPANGA', 'municipality' => 'SANTA ANA', 'zip_code' => '2022'],
    ['province' => 'PAMPANGA', 'municipality' => 'SANTA CRUZ, LUBAO', 'zip_code' => '2025'],
    ['province' => 'PAMPANGA', 'municipality' => 'SANTA RITA', 'zip_code' => '2002'],
    ['province' => 'PAMPANGA', 'municipality' => 'SANTO TOMAS', 'zip_code' => '2020'],

    ['province' => 'TARLAC', 'municipality' => 'ANAO', 'zip_code' => '2310'],
    ['province' => 'TARLAC', 'municipality' => 'BAMBAN', 'zip_code' => '2317'],
    ['province' => 'TARLAC', 'municipality' => 'CAMILING', 'zip_code' => '2306'],
    ['province' => 'TARLAC', 'municipality' => 'CAPAS', 'zip_code' => '2315'],
    ['province' => 'TARLAC', 'municipality' => 'CONCEPCION', 'zip_code' => '2316'],
    ['province' => 'TARLAC', 'municipality' => 'GERONA', 'zip_code' => '2302'],
    ['province' => 'TARLAC', 'municipality' => 'LA PAZ', 'zip_code' => '2314'],
    ['province' => 'TARLAC', 'municipality' => 'MAYANTOC', 'zip_code' => '2304'],
    ['province' => 'TARLAC', 'municipality' => 'MONCADA', 'zip_code' => '2308'],
    ['province' => 'TARLAC', 'municipality' => 'PANIQUI', 'zip_code' => '2307'],
    ['province' => 'TARLAC', 'municipality' => 'PURA', 'zip_code' => '2312'],
    ['province' => 'TARLAC', 'municipality' => 'RAMOS', 'zip_code' => '2311'],
    ['province' => 'TARLAC', 'municipality' => 'SAN CLEMENTE', 'zip_code' => '2305'],
    ['province' => 'TARLAC', 'municipality' => 'SAN JOSE', 'zip_code' => '2318'],
    ['province' => 'TARLAC', 'municipality' => 'SAN MANUEL', 'zip_code' => '2309'],
    ['province' => 'TARLAC', 'municipality' => 'SAN MIGUEL', 'zip_code' => '2301'],
    ['province' => 'TARLAC', 'municipality' => 'STA. IGNACIA', 'zip_code' => '2303'],
    ['province' => 'TARLAC', 'municipality' => 'TARLAC', 'zip_code' => '2300'],
    ['province' => 'TARLAC', 'municipality' => 'VICTORIA', 'zip_code' => '2313'],

    ['province' => 'ZAMBALES', 'municipality' => 'BOTOLAN', 'zip_code' => '2202'],
    ['province' => 'ZAMBALES', 'municipality' => 'CABANGAN', 'zip_code' => '2203'],
    ['province' => 'ZAMBALES', 'municipality' => 'CANDELARIA', 'zip_code' => '2212'],
    ['province' => 'ZAMBALES', 'municipality' => 'CASTILLEJOS', 'zip_code' => '2208'],
    ['province' => 'ZAMBALES', 'municipality' => 'IBA', 'zip_code' => '2201'],
    ['province' => 'ZAMBALES', 'municipality' => 'MASINLOC', 'zip_code' => '2211'],
    ['province' => 'ZAMBALES', 'municipality' => 'OLONGAPO CITY', 'zip_code' => '2200'],
    ['province' => 'ZAMBALES', 'municipality' => 'PALAUIG', 'zip_code' => '2210'],
    ['province' => 'ZAMBALES', 'municipality' => 'SAN ANTONIO', 'zip_code' => '2206'],
    ['province' => 'ZAMBALES', 'municipality' => 'SAN FELIPE', 'zip_code' => '2204'],
    ['province' => 'ZAMBALES', 'municipality' => 'SAN MARCELINO', 'zip_code' => '2207'],
    ['province' => 'ZAMBALES', 'municipality' => 'SAN NARCISO', 'zip_code' => '2205'],
    ['province' => 'ZAMBALES', 'municipality' => 'STA. CRUZ', 'zip_code' => '2213'],
    ['province' => 'ZAMBALES', 'municipality' => 'SUBIC', 'zip_code' => '2209'],
];
