<?php
return array_map('trim', [
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Compostela", "zip_code" => "8803"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Laak (formerly San Vicente)", "zip_code" => "8810"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Mabini", "zip_code" => "8807"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Maco", "zip_code" => "8806"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Maragusan (formerly San Mariano)", "zip_code" => "8808"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Mawab", "zip_code" => "8802"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Monkayo", "zip_code" => "8805"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Montevista", "zip_code" => "8801"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Nabunturan", "zip_code" => "8800"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "New Bataan", "zip_code" => "8804"],
  ["province" => "COMPOSTELA VALLEY", "municipality" => "Pantukan", "zip_code" => "8809"],

  ["province" => "DAVAO DEL NORTE", "municipality" => "Asuncion (formerly Saug)", "zip_code" => "8102"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Babak", "zip_code" => "8118"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Braulio E. Dujali", "zip_code" => "8106"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Carmen", "zip_code" => "8101"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Kapalong", "zip_code" => "8113"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Kaputian", "zip_code" => "8120"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "New Corella", "zip_code" => "8104"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Panabo", "zip_code" => "8105"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Samal", "zip_code" => "8119"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "San Isidro", "zip_code" => "8121"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Santo Tomas", "zip_code" => "8112"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Tagum", "zip_code" => "8100"],
  ["province" => "DAVAO DEL NORTE", "municipality" => "Talaingod", "zip_code" => "8107"],

  ["province" => "DAVAO DEL SUR ", "municipality" => "Ateneo", "zip_code" => "8016"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Bansalan", "zip_code" => "8005"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Bunawan", "zip_code" => "8017"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Calinan", "zip_code" => "8018"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Davao City", "zip_code" => "8000"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Davao International Airport", "zip_code" => "8019"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Digos", "zip_code" => "8002"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Hagonoy", "zip_code" => "8006"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Kiblawan", "zip_code" => "8008"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Magsaysay", "zip_code" => "8004"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Malalag", "zip_code" => "8010"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Mandug", "zip_code" => "8020"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Matanao", "zip_code" => "8003"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Matina", "zip_code" => "8021"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Mintal", "zip_code" => "8022"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Padada", "zip_code" => "8007"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Santa Cruz", "zip_code" => "8001"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Sulop", "zip_code" => "8009"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Talomo", "zip_code" => "8023"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Tibungco", "zip_code" => "8024"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "Toril", "zip_code" => "8025"],
  ["province" => "DAVAO DEL SUR ", "municipality" => "University of Mindanao", "zip_code" => "8026"],

  ["province" => "DAVAO OCCIDENTAL", "municipality" => "Don Marcelino", "zip_code" => "8013"],
  ["province" => "DAVAO OCCIDENTAL", "municipality" => "Jose Abad Santos", "zip_code" => "8014"],
  ["province" => "DAVAO OCCIDENTAL", "municipality" => "Malita", "zip_code" => "8012"],
  ["province" => "DAVAO OCCIDENTAL", "municipality" => "Santa Maria", "zip_code" => "8011"],
  ["province" => "DAVAO OCCIDENTAL", "municipality" => "Sarangani", "zip_code" => "8015"],

  ["province" => "DAVAO ORIENTAL", "municipality" => "Baganga", "zip_code" => "8204"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Banaybanay", "zip_code" => "8208"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Boston", "zip_code" => "8206"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Caraga", "zip_code" => "8203"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Cateel", "zip_code" => "8205"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Gov. Generoso", "zip_code" => "8210"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Lupon", "zip_code" => "8207"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Manay", "zip_code" => "8202"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Mati", "zip_code" => "8200"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "San Isidro", "zip_code" => "8209"],
  ["province" => "DAVAO ORIENTAL", "municipality" => "Tarragona", "zip_code" => "8201"],
]);
