<?php

declare(strict_types=1);
return [
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'COMPOSTELA', 'zip_code' => '8803'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'LAAK (FORMERLY SAN VICENTE)', 'zip_code' => '8810'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MABINI', 'zip_code' => '8807'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MACO', 'zip_code' => '8806'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MARAGUSAN (FORMERLY SAN MARIANO)', 'zip_code' => '8808'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MAWAB', 'zip_code' => '8802'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MONKAYO', 'zip_code' => '8805'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'MONTEVISTA', 'zip_code' => '8801'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'NABUNTURAN', 'zip_code' => '8800'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'NEW BATAAN', 'zip_code' => '8804'],
    ['province' => 'COMPOSTELA VALLEY', 'municipality' => 'PANTUKAN', 'zip_code' => '8809'],

    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'ASUNCION (FORMERLY SAUG)', 'zip_code' => '8102'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'BABAK', 'zip_code' => '8118'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'BRAULIO E. DUJALI', 'zip_code' => '8106'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'CARMEN', 'zip_code' => '8101'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'KAPALONG', 'zip_code' => '8113'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'KAPUTIAN', 'zip_code' => '8120'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'NEW CORELLA', 'zip_code' => '8104'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'PANABO', 'zip_code' => '8105'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'SAMAL', 'zip_code' => '8119'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'SAN ISIDRO', 'zip_code' => '8121'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'SANTO TOMAS', 'zip_code' => '8112'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'TAGUM', 'zip_code' => '8100'],
    ['province' => 'DAVAO DEL NORTE', 'municipality' => 'TALAINGOD', 'zip_code' => '8107'],

    ['province' => 'DAVAO DEL SUR', 'municipality' => 'ATENEO', 'zip_code' => '8016'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'BANSALAN', 'zip_code' => '8005'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'BUNAWAN', 'zip_code' => '8017'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'CALINAN', 'zip_code' => '8018'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'DAVAO CITY', 'zip_code' => '8000'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'DAVAO INTERNATIONAL AIRPORT', 'zip_code' => '8019'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'DIGOS', 'zip_code' => '8002'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'HAGONOY', 'zip_code' => '8006'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'KIBLAWAN', 'zip_code' => '8008'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MAGSAYSAY', 'zip_code' => '8004'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MALALAG', 'zip_code' => '8010'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MANDUG', 'zip_code' => '8020'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MATANAO', 'zip_code' => '8003'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MATINA', 'zip_code' => '8021'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'MINTAL', 'zip_code' => '8022'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'PADADA', 'zip_code' => '8007'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'SANTA CRUZ', 'zip_code' => '8001'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'SULOP', 'zip_code' => '8009'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'TALOMO', 'zip_code' => '8023'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'TIBUNGCO', 'zip_code' => '8024'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'TORIL', 'zip_code' => '8025'],
    ['province' => 'DAVAO DEL SUR', 'municipality' => 'UNIVERSITY OF MINDANAO', 'zip_code' => '8026'],

    ['province' => 'DAVAO OCCIDENTAL', 'municipality' => 'DON MARCELINO', 'zip_code' => '8013'],
    ['province' => 'DAVAO OCCIDENTAL', 'municipality' => 'JOSE ABAD SANTOS', 'zip_code' => '8014'],
    ['province' => 'DAVAO OCCIDENTAL', 'municipality' => 'MALITA', 'zip_code' => '8012'],
    ['province' => 'DAVAO OCCIDENTAL', 'municipality' => 'SANTA MARIA', 'zip_code' => '8011'],
    ['province' => 'DAVAO OCCIDENTAL', 'municipality' => 'SARANGANI', 'zip_code' => '8015'],

    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'BAGANGA', 'zip_code' => '8204'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'BANAYBANAY', 'zip_code' => '8208'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'BOSTON', 'zip_code' => '8206'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'CARAGA', 'zip_code' => '8203'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'CATEEL', 'zip_code' => '8205'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'GOV. GENEROSO', 'zip_code' => '8210'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'LUPON', 'zip_code' => '8207'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'MANAY', 'zip_code' => '8202'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'MATI', 'zip_code' => '8200'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'SAN ISIDRO', 'zip_code' => '8209'],
    ['province' => 'DAVAO ORIENTAL', 'municipality' => 'TARRAGONA', 'zip_code' => '8201'],
];
