<?php
return array_map('trim', [
  ["province" => "MARINDUQUE", "municipality" => "Boac", "zip_code" => "4900"],
  ["province" => "MARINDUQUE", "municipality" => "Buenavista", "zip_code" => "4904"],
  ["province" => "MARINDUQUE", "municipality" => "Gasan", "zip_code" => "4905"],
  ["province" => "MARINDUQUE", "municipality" => "Mogpog", "zip_code" => "4901"],
  ["province" => "MARINDUQUE", "municipality" => "Sta. Cruz", "zip_code" => "4902"],
  ["province" => "MARINDUQUE", "municipality" => "Torrijos", "zip_code" => "4903"],

  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Abra de Ilog", "zip_code" => "5108"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Calintaan", "zip_code" => "5102"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Looc", "zip_code" => "5111"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Lubang", "zip_code" => "5109"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Magsaysay", "zip_code" => "5101"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Mamburao", "zip_code" => "5106"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Palauan", "zip_code" => "5107"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Rizal", "zip_code" => "5103"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Sablayan", "zip_code" => "5104"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "San Jose", "zip_code" => "5100"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Sta. Cruz", "zip_code" => "5105"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "Tilik", "zip_code" => "5110"],

  ["province" => "ORIENTAL MINDORO", "municipality" => "Baco", "zip_code" => "5201"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Bansud", "zip_code" => "5210"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Bongabong", "zip_code" => "5211"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Bulalacao", "zip_code" => "5214"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Calapan", "zip_code" => "5200"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Gloria", "zip_code" => "5209"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Mansalay", "zip_code" => "5213"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Naujan", "zip_code" => "5204"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Pinamalayan", "zip_code" => "5208"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Pola", "zip_code" => "5206"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Puerto Galera", "zip_code" => "5203"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Roxas", "zip_code" => "5212"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "San Teodoro", "zip_code" => "5202"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Socorro", "zip_code" => "5207"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "Victoria", "zip_code" => "5205"],

  ["province" => "PALAWAN", "municipality" => "Aborlan", "zip_code" => "5302"],
  ["province" => "PALAWAN", "municipality" => "Agutaya", "zip_code" => "5320"],
  ["province" => "PALAWAN", "municipality" => "Araceli", "zip_code" => "5311"],
  ["province" => "PALAWAN", "municipality" => "Balabac", "zip_code" => "5307"],
  ["province" => "PALAWAN", "municipality" => "Batazara", "zip_code" => "5306"],
  ["province" => "PALAWAN", "municipality" => "Brooke's Point", "zip_code" => "5305"],
  ["province" => "PALAWAN", "municipality" => "Busuanga", "zip_code" => "5317"],
  ["province" => "PALAWAN", "municipality" => "Cagayancillo", "zip_code" => "5321"],
  ["province" => "PALAWAN", "municipality" => "Coron", "zip_code" => "5316"],
  ["province" => "PALAWAN", "municipality" => "Culion", "zip_code" => "5315"],
  ["province" => "PALAWAN", "municipality" => "Cuyo", "zip_code" => "5318"],
  ["province" => "PALAWAN", "municipality" => "Dumaran", "zip_code" => "5310"],
  ["province" => "PALAWAN", "municipality" => "El Nido (Baquit)", "zip_code" => "5313"],
  ["province" => "PALAWAN", "municipality" => "Iwahig Penal Colony", "zip_code" => "5301"],
  ["province" => "PALAWAN", "municipality" => "Kalayaan", "zip_code" => "5322"],
  ["province" => "PALAWAN", "municipality" => "Linapacan", "zip_code" => "5314"],
  ["province" => "PALAWAN", "municipality" => "Magsaysay", "zip_code" => "5319"],
  ["province" => "PALAWAN", "municipality" => "Narra (Panacan)", "zip_code" => "5303"],
  ["province" => "PALAWAN", "municipality" => "Puerto Princesa City", "zip_code" => "5300"],
  ["province" => "PALAWAN", "municipality" => "Quezon", "zip_code" => "5304"],
  ["province" => "PALAWAN", "municipality" => "Roxas", "zip_code" => "5308"],
  ["province" => "PALAWAN", "municipality" => "Rizal (Marcos)", "zip_code" => "5323"],
  ["province" => "PALAWAN", "municipality" => "San Vicente", "zip_code" => "5309"],
  ["province" => "PALAWAN", "municipality" => "Sofronio Española", "zip_code" => "5324"],
  ["province" => "PALAWAN", "municipality" => "Taytay", "zip_code" => "5312"],

  ["province" => "ROMBLON", "municipality" => "Alcantara", "zip_code" => "5509"],
  ["province" => "ROMBLON", "municipality" => "Banton (Jones)", "zip_code" => "5515"],
  ["province" => "ROMBLON", "municipality" => "Cajidiocan", "zip_code" => "5512"],
  ["province" => "ROMBLON", "municipality" => "Calatrava", "zip_code" => "5503"],
  ["province" => "ROMBLON", "municipality" => "Concepcion", "zip_code" => "5516"],
  ["province" => "ROMBLON", "municipality" => "Corcuera", "zip_code" => "5514"],
  ["province" => "ROMBLON", "municipality" => "Ferrol", "zip_code" => "5506"],
  ["province" => "ROMBLON", "municipality" => "Sta. Maria (Imelda)", "zip_code" => "5502"],
  ["province" => "ROMBLON", "municipality" => "Looc", "zip_code" => "5507"],
  ["province" => "ROMBLON", "municipality" => "Magdiwang", "zip_code" => "5511"],
  ["province" => "ROMBLON", "municipality" => "Odiongan", "zip_code" => "5505"],
  ["province" => "ROMBLON", "municipality" => "Romblon     ", "zip_code" => "5500"],
  ["province" => "ROMBLON", "municipality" => "San Agustin", "zip_code" => "5501"],
  ["province" => "ROMBLON", "municipality" => "San Andres", "zip_code" => "5504"],
  ["province" => "ROMBLON", "municipality" => "San fernando", "zip_code" => "5513"],
  ["province" => "ROMBLON", "municipality" => "San Jose", "zip_code" => "5510"],
  ["province" => "ROMBLON", "municipality" => "Sta. Fe", "zip_code" => "5508"],
]);
