<?php
return [
  ["province" => "MARINDUQUE", "municipality" => "BOAC", "zip_code" => "4900"],
  ["province" => "MARINDUQUE", "municipality" => "BUENAVISTA", "zip_code" => "4904"],
  ["province" => "MARINDUQUE", "municipality" => "GASAN", "zip_code" => "4905"],
  ["province" => "MARINDUQUE", "municipality" => "MOGPOG", "zip_code" => "4901"],
  ["province" => "MARINDUQUE", "municipality" => "STA. CRUZ", "zip_code" => "4902"],
  ["province" => "MARINDUQUE", "municipality" => "TORRIJOS", "zip_code" => "4903"],

  ["province" => "OCCIDENTAL MINDORO", "municipality" => "ABRA DE ILOG", "zip_code" => "5108"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "CALINTAAN", "zip_code" => "5102"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "LOOC", "zip_code" => "5111"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "LUBANG", "zip_code" => "5109"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "MAGSAYSAY", "zip_code" => "5101"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "MAMBURAO", "zip_code" => "5106"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "PALAUAN", "zip_code" => "5107"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "RIZAL", "zip_code" => "5103"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "SABLAYAN", "zip_code" => "5104"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "SAN JOSE", "zip_code" => "5100"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "STA. CRUZ", "zip_code" => "5105"],
  ["province" => "OCCIDENTAL MINDORO", "municipality" => "TILIK", "zip_code" => "5110"],

  ["province" => "ORIENTAL MINDORO", "municipality" => "BACO", "zip_code" => "5201"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "BANSUD", "zip_code" => "5210"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "BONGABONG", "zip_code" => "5211"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "BULALACAO", "zip_code" => "5214"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "CALAPAN", "zip_code" => "5200"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "GLORIA", "zip_code" => "5209"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "MANSALAY", "zip_code" => "5213"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "NAUJAN", "zip_code" => "5204"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "PINAMALAYAN", "zip_code" => "5208"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "POLA", "zip_code" => "5206"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "PUERTO GALERA", "zip_code" => "5203"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "ROXAS", "zip_code" => "5212"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "SAN TEODORO", "zip_code" => "5202"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "SOCORRO", "zip_code" => "5207"],
  ["province" => "ORIENTAL MINDORO", "municipality" => "VICTORIA", "zip_code" => "5205"],

  ["province" => "PALAWAN", "municipality" => "ABORLAN", "zip_code" => "5302"],
  ["province" => "PALAWAN", "municipality" => "AGUTAYA", "zip_code" => "5320"],
  ["province" => "PALAWAN", "municipality" => "ARACELI", "zip_code" => "5311"],
  ["province" => "PALAWAN", "municipality" => "BALABAC", "zip_code" => "5307"],
  ["province" => "PALAWAN", "municipality" => "BATAZARA", "zip_code" => "5306"],
  ["province" => "PALAWAN", "municipality" => "BROOKE'S POINT", "zip_code" => "5305"],
  ["province" => "PALAWAN", "municipality" => "BUSUANGA", "zip_code" => "5317"],
  ["province" => "PALAWAN", "municipality" => "CAGAYANCILLO", "zip_code" => "5321"],
  ["province" => "PALAWAN", "municipality" => "CORON", "zip_code" => "5316"],
  ["province" => "PALAWAN", "municipality" => "CULION", "zip_code" => "5315"],
  ["province" => "PALAWAN", "municipality" => "CUYO", "zip_code" => "5318"],
  ["province" => "PALAWAN", "municipality" => "DUMARAN", "zip_code" => "5310"],
  ["province" => "PALAWAN", "municipality" => "EL NIDO (BAQUIT)", "zip_code" => "5313"],
  ["province" => "PALAWAN", "municipality" => "IWAHIG PENAL COLONY", "zip_code" => "5301"],
  ["province" => "PALAWAN", "municipality" => "KALAYAAN", "zip_code" => "5322"],
  ["province" => "PALAWAN", "municipality" => "LINAPACAN", "zip_code" => "5314"],
  ["province" => "PALAWAN", "municipality" => "MAGSAYSAY", "zip_code" => "5319"],
  ["province" => "PALAWAN", "municipality" => "NARRA (PANACAN)", "zip_code" => "5303"],
  ["province" => "PALAWAN", "municipality" => "PUERTO PRINCESA CITY", "zip_code" => "5300"],
  ["province" => "PALAWAN", "municipality" => "QUEZON", "zip_code" => "5304"],
  ["province" => "PALAWAN", "municipality" => "ROXAS", "zip_code" => "5308"],
  ["province" => "PALAWAN", "municipality" => "RIZAL (MARCOS)", "zip_code" => "5323"],
  ["province" => "PALAWAN", "municipality" => "SAN VICENTE", "zip_code" => "5309"],
  ["province" => "PALAWAN", "municipality" => "SOFRONIO ESPAÑOLA", "zip_code" => "5324"],
  ["province" => "PALAWAN", "municipality" => "TAYTAY", "zip_code" => "5312"],

  ["province" => "ROMBLON", "municipality" => "ALCANTARA", "zip_code" => "5509"],
  ["province" => "ROMBLON", "municipality" => "BANTON (JONES)", "zip_code" => "5515"],
  ["province" => "ROMBLON", "municipality" => "CAJIDIOCAN", "zip_code" => "5512"],
  ["province" => "ROMBLON", "municipality" => "CALATRAVA", "zip_code" => "5503"],
  ["province" => "ROMBLON", "municipality" => "CONCEPCION", "zip_code" => "5516"],
  ["province" => "ROMBLON", "municipality" => "CORCUERA", "zip_code" => "5514"],
  ["province" => "ROMBLON", "municipality" => "FERROL", "zip_code" => "5506"],
  ["province" => "ROMBLON", "municipality" => "STA. MARIA (IMELDA)", "zip_code" => "5502"],
  ["province" => "ROMBLON", "municipality" => "LOOC", "zip_code" => "5507"],
  ["province" => "ROMBLON", "municipality" => "MAGDIWANG", "zip_code" => "5511"],
  ["province" => "ROMBLON", "municipality" => "ODIONGAN", "zip_code" => "5505"],
  ["province" => "ROMBLON", "municipality" => "ROMBLON", "zip_code" => "5500"],
  ["province" => "ROMBLON", "municipality" => "SAN AGUSTIN", "zip_code" => "5501"],
  ["province" => "ROMBLON", "municipality" => "SAN ANDRES", "zip_code" => "5504"],
  ["province" => "ROMBLON", "municipality" => "SAN FERNANDO", "zip_code" => "5513"],
  ["province" => "ROMBLON", "municipality" => "SAN JOSE", "zip_code" => "5510"],
  ["province" => "ROMBLON", "municipality" => "STA. FE", "zip_code" => "5508"],
];
