<?php
return  [
  ["province" => "AGUSAN DEL NORTE", "municipality" => "AGUSAN DEL NORTE", "zip_code" => ""],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Buenavista", "zip_code" => "8601"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Butuan City", "zip_code" => "8600"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Cabadbaran", "zip_code" => "8605"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Carmen", "zip_code" => "8603"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Jabonga", "zip_code" => "8607"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Kitcharao", "zip_code" => "8609"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Las Nieves", "zip_code" => "8610"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Magallanes", "zip_code" => "8604"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Nasipit", "zip_code" => "8602"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Remedios T. Romualdez", "zip_code" => "8611"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Santiago", "zip_code" => "8608"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "Tubay", "zip_code" => "8606"],

  ["province" => "AGUSAN DEL SUR", "municipality" => "Bayugan", "zip_code" => "8502"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Bunawan", "zip_code" => "8506"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Esperanza", "zip_code" => "8513"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "La Paz", "zip_code" => "8508"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Loreto", "zip_code" => "8507"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Prosperidad", "zip_code" => "8500"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Rosario", "zip_code" => "8504"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "San Francisco", "zip_code" => "8501"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "San Luis", "zip_code" => "8511"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Sibagat", "zip_code" => "8503"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Sta. Josefa", "zip_code" => "8512"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Talacogon", "zip_code" => "8510"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Trento", "zip_code" => "8505"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "Veruela", "zip_code" => "8509"],

  ["province" => "SURIGAO DEL NORTE", "municipality" => "Alegria", "zip_code" => "8425"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Bacuag", "zip_code" => "8408"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Burgos", "zip_code" => "8424"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Claver", "zip_code" => "8410"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Dapa", "zip_code" => "8417"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Del Carmen", "zip_code" => "8418"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Gen. Luna", "zip_code" => "8419"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Gigaquit", "zip_code" => "8409"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Mainit", "zip_code" => "8407"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Malimono", "zip_code" => "8402"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Pilar", "zip_code" => "8420"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Placer", "zip_code" => "8405"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "San Benito", "zip_code" => "8423"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "San Francisco", "zip_code" => "8401"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "San Isidro", "zip_code" => "8421"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Sison", "zip_code" => "8404"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Socorro", "zip_code" => "8416"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Sta. Monica", "zip_code" => "8422"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Surigao City", "zip_code" => "8400"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Tagana-an", "zip_code" => "8403"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "Tubod", "zip_code" => "8406"],

  ["province" => "DINAGAT ISLAND", "municipality" => "Basilisa (formerly Rizal)", "zip_code" => "8413"],
  ["province" => "DINAGAT ISLAND", "municipality" => "Cagdianao", "zip_code" => "8411"],
  ["province" => "DINAGAT ISLAND", "municipality" => "Dinagat", "zip_code" => "8412"],
  ["province" => "DINAGAT ISLAND", "municipality" => "Libjo (formerly Albor)", "zip_code" => "8414"],
  ["province" => "DINAGAT ISLAND", "municipality" => "Loreto", "zip_code" => "8415"],
  ["province" => "DINAGAT ISLAND", "municipality" => "San Jose", "zip_code" => "8427"],
  ["province" => "DINAGAT ISLAND", "municipality" => "Tubajon", "zip_code" => "8426"],

  ["province" => "SURIGAO DEL SUR", "municipality" => "Barobo", "zip_code" => "8309"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Bayabas", "zip_code" => "8303"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Bislig", "zip_code" => "8311"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Cagwait", "zip_code" => "8304"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Cantilan", "zip_code" => "8317"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Carmen", "zip_code" => "8315"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Carrascal", "zip_code" => "8318"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Cortez", "zip_code" => "8313"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Hinatuan", "zip_code" => "8310"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Lanuza", "zip_code" => "8314"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Lianga", "zip_code" => "8307"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Lingig", "zip_code" => "8312"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Madrid", "zip_code" => "8316"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Malixi", "zip_code" => "8319"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Marihatag", "zip_code" => "8306"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "San Agustin", "zip_code" => "8305"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "San Miguel", "zip_code" => "8301"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Tagbina", "zip_code" => "8308"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Tago", "zip_code" => "8302"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "Tandag", "zip_code" => "8300"],
];
