<?php
return [
  ["province" => "AGUSAN DEL NORTE", "municipality" => "BUENAVISTA", "zip_code" => "8601"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "BUTUAN CITY", "zip_code" => "8600"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "CABADBARAN", "zip_code" => "8605"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "CARMEN", "zip_code" => "8603"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "JABONGA", "zip_code" => "8607"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "KITCHARAO", "zip_code" => "8609"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "LAS NIEVES", "zip_code" => "8610"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "MAGALLANES", "zip_code" => "8604"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "NASIPIT", "zip_code" => "8602"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "REMEDIOS T. ROMUALDEZ", "zip_code" => "8611"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "SANTIAGO", "zip_code" => "8608"],
  ["province" => "AGUSAN DEL NORTE", "municipality" => "TUBAY", "zip_code" => "8606"],

  ["province" => "AGUSAN DEL SUR", "municipality" => "BAYUGAN", "zip_code" => "8502"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "BUNAWAN", "zip_code" => "8506"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "ESPERANZA", "zip_code" => "8513"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "LA PAZ", "zip_code" => "8508"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "LORETO", "zip_code" => "8507"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "PROSPERIDAD", "zip_code" => "8500"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "ROSARIO", "zip_code" => "8504"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "SAN FRANCISCO", "zip_code" => "8501"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "SAN LUIS", "zip_code" => "8511"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "SIBAGAT", "zip_code" => "8503"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "STA. JOSEFA", "zip_code" => "8512"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "TALACOGON", "zip_code" => "8510"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "TRENTO", "zip_code" => "8505"],
  ["province" => "AGUSAN DEL SUR", "municipality" => "VERUELA", "zip_code" => "8509"],

  ["province" => "SURIGAO DEL NORTE", "municipality" => "ALEGRIA", "zip_code" => "8425"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "BACUAG", "zip_code" => "8408"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "BURGOS", "zip_code" => "8424"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "CLAVER", "zip_code" => "8410"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "DAPA", "zip_code" => "8417"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "DEL CARMEN", "zip_code" => "8418"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "GEN. LUNA", "zip_code" => "8419"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "GIGAQUIT", "zip_code" => "8409"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "MAINIT", "zip_code" => "8407"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "MALIMONO", "zip_code" => "8402"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "PILAR", "zip_code" => "8420"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "PLACER", "zip_code" => "8405"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SAN BENITO", "zip_code" => "8423"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SAN FRANCISCO", "zip_code" => "8401"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SAN ISIDRO", "zip_code" => "8421"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SISON", "zip_code" => "8404"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SOCORRO", "zip_code" => "8416"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "STA. MONICA", "zip_code" => "8422"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "SURIGAO CITY", "zip_code" => "8400"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "TAGANA-AN", "zip_code" => "8403"],
  ["province" => "SURIGAO DEL NORTE", "municipality" => "TUBOD", "zip_code" => "8406"],

  ["province" => "DINAGAT ISLAND", "municipality" => "BASILISA (FORMERLY RIZAL)", "zip_code" => "8413"],
  ["province" => "DINAGAT ISLAND", "municipality" => "CAGDIANAO", "zip_code" => "8411"],
  ["province" => "DINAGAT ISLAND", "municipality" => "DINAGAT", "zip_code" => "8412"],
  ["province" => "DINAGAT ISLAND", "municipality" => "LIBJO (FORMERLY ALBOR)", "zip_code" => "8414"],
  ["province" => "DINAGAT ISLAND", "municipality" => "LORETO", "zip_code" => "8415"],
  ["province" => "DINAGAT ISLAND", "municipality" => "SAN JOSE", "zip_code" => "8427"],
  ["province" => "DINAGAT ISLAND", "municipality" => "TUBAJON", "zip_code" => "8426"],

  ["province" => "SURIGAO DEL SUR", "municipality" => "BAROBO", "zip_code" => "8309"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "BAYABAS", "zip_code" => "8303"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "BISLIG", "zip_code" => "8311"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "CAGWAIT", "zip_code" => "8304"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "CANTILAN", "zip_code" => "8317"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "CARMEN", "zip_code" => "8315"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "CARRASCAL", "zip_code" => "8318"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "CORTEZ", "zip_code" => "8313"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "HINATUAN", "zip_code" => "8310"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "LANUZA", "zip_code" => "8314"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "LIANGA", "zip_code" => "8307"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "LINGIG", "zip_code" => "8312"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "MADRID", "zip_code" => "8316"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "MALIXI", "zip_code" => "8319"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "MARIHATAG", "zip_code" => "8306"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "SAN AGUSTIN", "zip_code" => "8305"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "SAN MIGUEL", "zip_code" => "8301"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "TAGBINA", "zip_code" => "8308"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "TAGO", "zip_code" => "8302"],
  ["province" => "SURIGAO DEL SUR", "municipality" => "TANDAG", "zip_code" => "8300"],
];
