<?php

// require __DIR__ . '/vendor/autoload.php';

// use KangBabi\PhZipCodes\PhZipCode;

// $zipCodes = new PhZipCode();

// print_r($zipCodes->regions);

$data = [

  "TOBOSO" => [
    "barangay_list" => [
      "BANDILA",
      "BUG-ANG",
      "GENERAL LUNA",
      "MAGTICOL",
      "POBLACION",
      "SALAMANCA",
      "SAN ISIDRO",
      "SAN JOSE",
      "TABUN-AC",
    ],
  ],

  "LA CASTELLANA" => [
    "barangay_list" => [
      "BIAKNABATO",
      "CABACUNGAN",
      "CABAGNAAN",
      "CAMANDAG",
      "LALAGSAN",
      "MANGHANOY",
      "MANSALANAO",
      "MASULOG",
      "NATO",
      "PUSO",
      "ROBLES (POB.)",
      "SAG-ANG",
      "TALAPTAP",
    ],
  ],

  "SALVADOR BENEDICTO" => [
    "barangay_list" => [
      "BAGO (LALUNG)",
      "BAGONG SILANG (MARCELO)",
      "BUNGA",
      "IGMAYA-AN",
      "KUMALISKIS",
      "PANDANON",
      "PINOWAYAN (PROSPERIDAD)",
    ],
  ],

  "HINOBA-AN (ASIA)" => [
    "barangay_list" => [
      "ALIM",
      "ASIA",
      "BACUYANGAN",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BULWANGAN",
      "CULIPAPA",
      "DAMUTAN",
      "DAUG",
      "PO-OK",
      "SAN RAFAEL",
      "SANGKE",
      "TALACAGAY",
    ],
  ],

  "LA CARLOTA CITY" => [
    "barangay_list" => [
      "ARA-AL",
      "AYUNGON",
      "BALABAG",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BATUAN",
      "CUBAY",
      "HAGUIMIT",
      "LA GRANJA",
      "NAGASI",
      "ROBERTO S. BENEDICTO (CONSUELO)",
      "SAN MIGUEL",
      "YUBO",
    ],
  ],

  "PONTEVEDRA" => [
    "barangay_list" => [
      "ANTIPOLO",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BUENAVISTA GIBONG",
      "BUENAVISTA RIZAL",
      "BURGOS",
      "CAMBARUS",
      "CANROMA",
      "DON SALVADOR BENEDICTO (CARMEN)",
      "GENERAL MALVAR",
      "GOMEZ",
      "M. H. DEL PILAR",
      "MABINI",
      "MIRANDA",
      "PANDAN",
      "RECREO",
      "SAN ISIDRO",
      "SAN JUAN",
      "ZAMORA",
    ],
  ],

  "PULUPANDAN" => [
    "barangay_list" => [
      "BARANGAY ZONE 1 (POB.)",
      "BARANGAY ZONE 1-A (POB.)",
      "BARANGAY ZONE 2 (POB.)",
      "BARANGAY ZONE 3 (POB.)",
      "BARANGAY ZONE 4 (POB.)",
      "BARANGAY ZONE 4-A (POB.)",
      "BARANGAY ZONE 5 (POB.)",
      "BARANGAY ZONE 6 (POB.)",
      "BARANGAY ZONE 7 (POB.)",
      "CANJUSA",
      "CROSSING PULUPANDAN",
      "CULO",
      "MABINI",
      "PAG-AYON",
      "PALAKA NORTE",
      "PALAKA SUR",
      "PATIC",
      "TAPONG",
      "UBAY",
      "UTOD",
    ],
  ],

  "SILAY CITY" => [
    "barangay_list" => [
      "BAGTIC",
      "BALARING",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BARANGAY IV (POB.)",
      "BARANGAY V (POB.)",
      "BARANGAY VI POB. (HAWAIIAN)",
      "EUSTAQUIO LOPEZ",
      "GUIMBALA-ON",
      "GUINHALARAN",
      "KAPITAN RAMON",
      "LANTAD",
      "MAMBULAC",
      "PATAG",
      "RIZAL",
    ],
  ],

  "ISABELA" => [
    "barangay_list" => [
      "AMIN",
      "BANOGBANOG",
      "BARANGAY 1 (POB.)",
      "BARANGAY 2 (POB.)",
      "BARANGAY 3 (POB.)",
      "BARANGAY 4 (POB.)",
      "BARANGAY 5 (POB.)",
      "BARANGAY 6 (POB.)",
      "BARANGAY 7 (POB.)",
      "BARANGAY 8 (POB.)",
      "BARANGAY 9 (POB.)",
      "BULAD",
      "BUNGAHIN",
      "CABCAB",
      "CAMANGCAMANG",
      "CAMP CLARK",
      "CANSALONGON",
      "GUINTUBHAN",
      "LIBAS",
      "LIMALIMA",
      "MAKILIGNIT",
      "MANSABLAY",
      "MAYTUBIG",
      "PANAQUIAO",
      "RIVERSIDE",
      "RUMIRANG",
      "SAN AGUSTIN",
      "SEBUCAWAN",
      "SIKATUNA",
      "TINONGAN",
    ],
  ],

  "CADIZ CITY" => [
    "barangay_list" => [
      "ANDRES BONIFACIO",
      "BANQUEROHAN",
      "BARANGAY 1 POB. (ZONE 1)",
      "BARANGAY 2 POB. (ZONE 2)",
      "BARANGAY 3 POB. (ZONE 3)",
      "BARANGAY 4 POB. (ZONE 4)",
      "BARANGAY 5 POB. (ZONE 5)",
      "BARANGAY 6 POB. (ZONE 6)",
      "BURGOS",
      "CABAHUG",
      "CADIZ VIEJO",
      "CADUHA-AN",
      "CELESTINO VILLACIN",
      "DAGA",
      "JERUSALEM",
      "LUNA",
      "MABINI",
      "MAGSAYSAY",
      "SICABA",
      "TIGLAWIGAN",
      "TINAMPA-AN",
      "V. F. GUSTILO",
    ],
  ],

  "CANDONI" => [
    "barangay_list" => [
      "AGBOY",
      "BANGA",
      "CABIA-AN",
      "CANINGAY",
      "GATUSLAO",
      "HABA",
      "PAYAUAN",
      "POBLACION EAST",
      "POBLACION WEST",
    ],
  ],

  "BINALBAGAN" => [
    "barangay_list" => [
      "AMONTAY",
      "BAGROY",
      "BI-AO",
      "CANMOROS (POB.)",
      "ENCLARO",
      "MARINA (POB.)",
      "PAGLAUM (POB.)",
      "PAYAO",
      "PROGRESO (POB.)",
      "SAN JOSE",
      "SAN JUAN (POB.)",
      "SAN PEDRO (POB.)",
      "SAN TEODORO (POB.)",
      "SAN VICENTE (POB.)",
      "SANTO ROSARIO (POB.)",
      "SANTOL",
    ],
  ],

  "SAGAY CITY" => [
    "barangay_list" => [
      "ANDRES BONIFACIO",
      "BATO",
      "BAVIERA",
      "BULANON",
      "CAMPO HIMOGA-AN",
      "CAMPO SANTIAGO",
      "COLONIA DIVINA",
      "FABRICA",
      "GENERAL LUNA",
      "HIMOGA-AN BAYBAY",
      "LOPEZ JAENA",
      "MAKILING",
      "MALUBON",
      "MOLOCABOC",
      "OLD SAGAY",
      "PARAISO",
      "PLARIDEL",
      "POBLACION I (BARANGAY 1)",
      "POBLACION II (BARANGAY 2)",
      "PUEY",
      "RAFAELA BARRERA",
      "RIZAL",
      "TABA-AO",
      "TADLONG",
      "VITO",
    ],
  ],

  "TALISAY CITY" => [
    "barangay_list" => [
      "BUBOG",
      "CABATANGAN",
      "CONCEPCION",
      "DOS HERMANAS",
      "EFIGENIO LIZARES",
      "KATILINGBAN",
      "MATAB-ANG",
      "SAN FERNANDO",
      "ZONE 1 (POB.)",
      "ZONE 2 (POB.)",
      "ZONE 3 (POB.)",
      "ZONE 4 (POB.)",
      "ZONE 4-A (POB.)",
      "ZONE 5 (POB.)",
      "ZONE 6 (POB.)",
      "ZONE 7 (POB.)",
      "ZONE 8 (POB.)",
      "ZONE 9 (POB.)",
      "ZONE 10 (POB.)",
      "ZONE 11 (POB.)",
      "ZONE 12 (POB.)",
      "ZONE 12-A (POB.)",
      "ZONE 14 (POB.)",
      "ZONE 14-A (POB.)",
      "ZONE 14-B (POB.)",
      "ZONE 15 (POB.)",
      "ZONE 16 (POB.)",
    ],
  ],

  "VICTORIAS CITY" => [
    "barangay_list" => [
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BARANGAY IV (POB.)",
      "BARANGAY IX (DAAN BANWA)",
      "BARANGAY V (POB.)",
      "BARANGAY VI (POB.)",
      "BARANGAY VI-A",
      "BARANGAY VII (POB.)",
      "BARANGAY VIII (POB.)",
      "BARANGAY X (ESTADO)",
      "BARANGAY XI (GAWAHON)",
      "BARANGAY XII",
      "BARANGAY XIII",
      "BARANGAY XIV",
      "BARANGAY XIX",
      "BARANGAY XIX-A",
      "BARANGAY XV",
      "BARANGAY XV-A",
      "BARANGAY XVI",
      "BARANGAY XVI-A",
      "BARANGAY XVII",
      "BARANGAY XVIII",
      "BARANGAY XVIII-A",
      "BARANGAY XX",
      "BARANGAY XXI",
    ],
  ],

  "BACOLOD CITY" => [
    "barangay_list" => [
      "ALANGILAN",
      "ALIJIS",
      "BANAGO",
      "BARANGAY 10 (POB.)",
      "BARANGAY 11 (POB.)",
      "BARANGAY 12 (POB.)",
      "BARANGAY 13 (POB.)",
      "BARANGAY 14 (POB.)",
      "BARANGAY 15 (POB.)",
      "BARANGAY 16 (POB.)",
      "BARANGAY 17 (POB.)",
      "BARANGAY 18 (POB.)",
      "BARANGAY 19 (POB.)",
      "BARANGAY 20 (POB.)",
      "BARANGAY 21 (POB.)",
      "BARANGAY 22 (POB.)",
      "BARANGAY 23 (POB.)",
      "BARANGAY 24 (POB.)",
      "BARANGAY 25 (POB.)",
      "BARANGAY 26 (POB.)",
      "BARANGAY 27 (POB.)",
      "BARANGAY 28 (POB.)",
      "BARANGAY 29 (POB.)",
      "BARANGAY 30 (POB.)",
      "BARANGAY 31 (POB.)",
      "BARANGAY 32 (POB.)",
      "BARANGAY 33 (POB.)",
      "BARANGAY 34 (POB.)",
      "BARANGAY 35 (POB.)",
      "BARANGAY 36 (POB.)",
      "BARANGAY 37 (POB.)",
      "BARANGAY 38 (POB.)",
      "BARANGAY 39 (POB.)",
      "BARANGAY 40 (POB.)",
      "BARANGAY 41 (POB.)",
      "BARANGAY  1 (POB.)",
      "BARANGAY  2 (POB.)",
      "BARANGAY  3 (POB.)",
      "BARANGAY  4 (POB.)",
      "BARANGAY  5 (POB.)",
      "BARANGAY  6 (POB.)",
      "BARANGAY  7 (POB.)",
      "BARANGAY  8 (POB.)",
      "BARANGAY  9 (POB.)",
      "BATA",
      "CABUG",
      "ESTEFANIA",
      "FELISA",
      "GRANADA",
      "HANDUMANAN",
      "MANDALAGAN",
      "MANSILINGAN",
      "MONTEVISTA",
      "PAHANOCOY",
      "PUNTA TAYTAY",
      "SINGCANG-AIRPORT",
      "SUM-AG",
      "TACULING",
      "TANGUB",
      "VILLAMONTE",
      "VISTA ALEGRE",
    ],
  ],

  "SAN ENRIQUE" => [
    "barangay_list" => [
      "BAGONAWA",
      "BALIWAGAN",
      "BATUAN",
      "GUINTORILAN",
      "NAYON",
      "POBLACION",
      "SIBUCAO",
      "TABAO BAYBAY",
      "TABAO RIZAL",
      "TIBSOC",
    ],
  ],

  "ESCALANTE CITY" => [
    "barangay_list" => [
      "ALIMANGO",
      "BALINTAWAK (POB.)",
      "BINAGUIOHAN",
      "BUENAVISTA",
      "CERVANTES",
      "DIAN-AY",
      "HACIENDA FE",
      "JAPITAN",
      "JONOBJONOB",
      "LANGUB",
      "LIBERTAD",
      "MABINI",
      "MAGSAYSAY (BINABONGOL)",
      "MALASIBOG",
      "OLD POBLACION",
      "PAITAN",
      "PINAPUGASAN",
      "RIZAL",
      "TAMLANG",
      "UDTONGAN",
      "WASHINGTON",
    ],
  ],

  "MANAPLA" => [
    "barangay_list" => [
      "BARANGAY I (POB.)",
      "BARANGAY I-A (POB.)",
      "BARANGAY I-B (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY II-A (POB.)",
      "CHAMBERY",
      "PUNTA MESA",
      "PUNTA SALONG",
      "PURISIMA",
      "SAN PABLO",
      "SANTA TERESA",
      "TORTOSA",
    ],
  ],

  "SIPALAY CITY" => [
    "barangay_list" => [
      "BARANGAY 1 (POB.)",
      "BARANGAY 2 (POB.)",
      "BARANGAY 3 (POB.)",
      "BARANGAY 4 (POB.)",
      "BARANGAY 5 (POB.)",
      "CABADIANGAN",
      "CAMINDANGAN",
      "CANTURAY",
      "CARTAGENA",
      "CAYHAGAN",
      "GIL MONTILLA",
      "MAMBAROTO",
      "MANLUCAHOC",
      "MARICALUM",
      "NABULAO",
      "NAUHANG",
      "SAN JOSE",
    ],
  ],

  "HINIGARAN" => [
    "barangay_list" => [
      "ANAHAW",
      "ARANDA",
      "BAGA-AS",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BARANGAY IV (POB.)",
      "BATO",
      "CALAPI",
      "CAMALOBALO",
      "CAMBA-OG",
      "CAMBUGSA",
      "CANDUMARAO",
      "GARGATO",
      "HIMAYA",
      "MIRANDA",
      "NANUNGA",
      "NARAUIS",
      "PALAYOG",
      "PATICUI",
      "PILAR",
      "QUIWI",
      "TAGDA",
      "TUGUIS",
    ],
  ],

  "ILOG" => [
    "barangay_list" => [
      "ANDULAUAN",
      "BALICOTOC",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BOCANA",
      "CALUBANG",
      "CANLAMAY",
      "CONSUELO",
      "DANCALAN",
      "DELICIOSO",
      "GALICIA",
      "MANALAD",
      "PINGGOT",
      "TABU",
      "VISTA ALEGRE",
    ],
  ],

  "MURCIA" => [
    "barangay_list" => [
      "ABO-ABO",
      "ALEGRIA",
      "AMAYCO",
      "BLUMENTRITT",
      "BUENAVISTA",
      "CALIBAN",
      "CANLANDOG",
      "CANSILAYAN",
      "DAMSITE",
      "IGLAU-AN",
      "LOPEZ JAENA",
      "MINOYAN",
      "PANDANON",
      "SALVACION",
      "SAN MIGUEL",
      "SANTA CRUZ",
      "SANTA ROSA",
      "TALOTOG",
      "ZONE I (POB.)",
      "ZONE II (POB.)",
      "ZONE III (POB.)",
      "ZONE IV (POB.)",
      "ZONE V (POB.)",
    ],
  ],

  "CAUAYAN" => [
    "barangay_list" => [
      "ABACA",
      "BACLAO",
      "BASAK",
      "BULATA",
      "CALILING",
      "CAMALANDA-AN",
      "CAMINDANGAN",
      "ELIHAN",
      "GUILJUNGAN",
      "INAYAWAN",
      "ISIO",
      "LINAON",
      "LUMBIA",
      "MAMBUGSAY",
      "MAN-ULING",
      "MASALING",
      "MOLOBOLO",
      "POBLACION",
      "SURA",
      "TALACDAN",
      "TAMBAD",
      "TILING",
      "TOMINA",
      "TUYOM",
      "YAO-YAO",
    ],
  ],

  "KABANKALAN CITY" => [
    "barangay_list" => [
      "BANTAYAN",
      "BARANGAY 1 (POB.)",
      "BARANGAY 2 (POB.)",
      "BARANGAY 3 (POB.)",
      "BARANGAY 4 (POB.)",
      "BARANGAY 5 (POB.)",
      "BARANGAY 6 (POB.)",
      "BARANGAY 7 (POB.)",
      "BARANGAY 8 (POB.)",
      "BARANGAY 9 (POB.)",
      "BINICUIL",
      "CAMANSI",
      "CAMINGAWAN",
      "CAMUGAO",
      "CAROL-AN",
      "DAAN BANUA",
      "HILAMONAN",
      "INAPOY",
      "LINAO",
      "LOCOTAN",
      "MAGBALLO",
      "ORINGAO",
      "ORONG",
      "PINAGUINPINAN",
      "SALONG",
      "TABUGON",
      "TAGOC",
      "TAGUKON",
      "TALUBANGI",
      "TAMPALON",
      "TAN-AWAN",
      "TAPI",
    ],
  ],

  "MOISES PADILLA (MAGALLON)" => [
    "barangay_list" => [
      "BARANGAY 1 (POB.)",
      "BARANGAY 2 (POB.)",
      "BARANGAY 3 (POB.)",
      "BARANGAY 4 (POB.)",
      "BARANGAY 5 (POB.)",
      "BARANGAY 6 (POB.)",
      "BARANGAY 7 (POB.)",
      "CROSSING MAGALLON",
      "GUINPANA-AN",
      "INOLINGAN",
      "MACAGAHAY",
      "MAGALLON CADRE",
      "MONTILLA",
      "ODIONG",
      "QUINTIN REMO",
    ],
  ],

  "VALLADOLID" => [
    "barangay_list" => [
      "ALIJIS",
      "AYUNGON",
      "BAGUMBAYAN",
      "BATUAN",
      "BAYABAS",
      "CENTRAL TABAO",
      "DOLDOL",
      "GUINTORILAN",
      "LACARON",
      "MABINI",
      "PACOL",
      "PALAKA",
      "PALOMA",
      "POBLACION",
      "SAGUA BANUA",
      "TABAO PROPER",
    ],
  ],

  "SAN CARLOS CITY" => [
    "barangay_list" => [
      "BAGONBON",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BARANGAY IV (POB.)",
      "BARANGAY V (POB.)",
      "BARANGAY VI (POB.)",
      "BULUANGAN",
      "CODCOD",
      "ERMITA",
      "GUADALUPE",
      "NATABAN",
      "PALAMPAS",
      "PROSPERIDAD",
      "PUNAO",
      "QUEZON",
      "RIZAL",
      "SAN JUAN",
    ],
  ],

  "CALATRAVA" => [
    "barangay_list" => [
      "AGPANGI",
      "ANI-E",
      "BAGACAY",
      "BANTAYANON",
      "BUENAVISTA",
      "CABUNGAHAN",
      "CALAMPISAWAN",
      "CAMBAYOBO",
      "CASTELLANO",
      "CRUZ",
      "DOLIS",
      "HILUB-ANG",
      "HINAB-ONGAN",
      "ILAYA",
      "LAGA-AN",
      "LALONG",
      "LEMERY",
      "LIPAT-ON",
      "LO-OK (POB.)",
      "MA-ASLOB",
      "MACASILAO",
      "MAHILUM",
      "MALANOG",
      "MALATAS",
      "MARCELO",
      "MENCHACA",
      "MINA-UTOK",
      "MINAPASUK",
      "PAGHUMAYAN",
      "PANTAO",
      "PATUN-AN",
      "PINOCUTAN",
      "REFUGIO",
      "SAN BENITO",
      "SAN ISIDRO",
      "SUBA (POB.)",
      "TELIM",
      "TIGBAO",
      "TIGBON",
      "WINASWASAN",
    ],
  ],

  "ENRIQUE B. MAGALONA (SARAVIA)" => [
    "barangay_list" => [
      "ALACAYGAN",
      "ALICANTE",
      "BATEA",
      "CANLUSONG",
      "CONSING",
      "CUDANGDANG",
      "DAMGO",
      "GAHIT",
      "LATASAN",
      "MADALAG",
      "MANTA-ANGAN",
      "NANCA",
      "PASIL",
      "POBLACION I (BARANGAY 1)",
      "POBLACION II (BARANGAY 2)",
      "POBLACION III (BARANGAY 3)",
      "SAN ISIDRO",
      "SAN JOSE",
      "SANTO NIÑO",
      "TABIGUE",
      "TANZA",
      "TOMONGTONG",
      "TUBURAN",
    ],
  ],

  "HIMAMAYLAN CITY" => [
    "barangay_list" => [
      "AGUISAN",
      "BARANGAY I (POB.)",
      "BARANGAY II (POB.)",
      "BARANGAY III (POB.)",
      "BARANGAY IV (POB.)",
      "BUENAVISTA",
      "CABADIANGAN",
      "CABANBANAN",
      "CARABALAN",
      "CARADIO-AN",
      "LIBACAO",
      "MAHALANG",
      "MAMBAGATON",
      "NABALI-AN",
      "SAN ANTONIO",
      "SARA-ET",
      "SU-AY",
      "TALABAN",
      "TO-OY",
    ],
  ],

  "BAGO CITY" => [
    "barangay_list" => [
      "ABUANAN",
      "ALIANZA",
      "ATIPULUAN",
      "BACONG-MONTILLA",
      "BAGROY",
      "BALINGASAG",
      "BINUBUHAN",
      "BUSAY",
      "CALUMANGAN",
      "CARIDAD",
      "DULAO",
      "ILIJAN",
      "JORGE L. ARANETA (MA-AO CENTRAL)",
      "LAG-ASAN",
      "MA-AO BARRIO",
      "MAILUM",
      "MALINGIN",
      "NAPOLES",
      "PACOL",
      "POBLACION",
      "SAGASA",
      "SAMPINIT",
      "TABUNAN",
      "TALOC",
    ],
  ],
];


$merged = array_merge_recursive($data);

ksort($merged);

foreach ($merged as $municipality => $barangays) {
  // $municipality = str_replace(' ', '_', $municipality);
  # replace non-alphanumeric with underscore
  $municipality = preg_replace('/[^a-zA-Z0-9]/', '_', $municipality);

  echo '<pre>';
  echo "{$municipality}: , \"barangays\" => [";
  echo implode(', ', array_map(fn($item) => '"' . $item . '"', $barangays['barangay_list']));
  echo "]";
  echo "</pre>";
}
