<?php
return array_map('trim', [
  ["province" => "BILIRAN", "municipality" => "Almeria", "zip_code" => "6544"],
  ["province" => "BILIRAN", "municipality" => "Biliran", "zip_code" => "6549"],
  ["province" => "BILIRAN", "municipality" => "Cabucgayan", "zip_code" => "6550"],
  ["province" => "BILIRAN", "municipality" => "Caibiran", "zip_code" => "6548"],
  ["province" => "BILIRAN", "municipality" => "Culaba", "zip_code" => "6547"],
  ["province" => "BILIRAN", "municipality" => "Kawayan", "zip_code" => "6545"],
  ["province" => "BILIRAN", "municipality" => "Maripipi", "zip_code" => "6546"],
  ["province" => "BILIRAN", "municipality" => "Naval", "zip_code" => "6543"],

  ["province" => "EASTERN SAMAR", "municipality" => "Arteche", "zip_code" => "6822"],
  ["province" => "EASTERN SAMAR", "municipality" => "Balangiga", "zip_code" => "6812"],
  ["province" => "EASTERN SAMAR", "municipality" => "Balangkayan", "zip_code" => "6801"],
  ["province" => "EASTERN SAMAR", "municipality" => "Borongan", "zip_code" => "6800"],
  ["province" => "EASTERN SAMAR", "municipality" => "Can-Avid", "zip_code" => "6806"],
  ["province" => "EASTERN SAMAR", "municipality" => "Dolores", "zip_code" => "6817"],
  ["province" => "EASTERN SAMAR", "municipality" => "General  MacArthur", "zip_code" => "6805"],
  ["province" => "EASTERN SAMAR", "municipality" => "Giporlos", "zip_code" => "6811"],
  ["province" => "EASTERN SAMAR", "municipality" => "Guiuan", "zip_code" => "6809"],
  ["province" => "EASTERN SAMAR", "municipality" => "Hernani", "zip_code" => "6804"],
  ["province" => "EASTERN SAMAR", "municipality" => "Jipapad", "zip_code" => "6819"],
  ["province" => "EASTERN SAMAR", "municipality" => "Lawaan", "zip_code" => "6813"],
  ["province" => "EASTERN SAMAR", "municipality" => "Llorente", "zip_code" => "6803"],
  ["province" => "EASTERN SAMAR", "municipality" => "Maslog", "zip_code" => "6820"],
  ["province" => "EASTERN SAMAR", "municipality" => "Maydolong", "zip_code" => "6802"],
  ["province" => "EASTERN SAMAR", "municipality" => "Mercedes", "zip_code" => "6808"],
  ["province" => "EASTERN SAMAR", "municipality" => "Oras", "zip_code" => "6818"],
  ["province" => "EASTERN SAMAR", "municipality" => "Quinapondan", "zip_code" => "6810"],
  ["province" => "EASTERN SAMAR", "municipality" => "Salcedo", "zip_code" => "6807"],
  ["province" => "EASTERN SAMAR", "municipality" => "San Julian", "zip_code" => "6814"],
  ["province" => "EASTERN SAMAR", "municipality" => "San Policarpio", "zip_code" => "6821"],
  ["province" => "EASTERN SAMAR", "municipality" => "Sulat", "zip_code" => "6815"],
  ["province" => "EASTERN SAMAR", "municipality" => "Taft", "zip_code" => "6816"],

  ["province" => "LEYTE", "municipality" => "Abuyog", "zip_code" => "6510"],
  ["province" => "LEYTE", "municipality" => "Alangalang", "zip_code" => "6517"],
  ["province" => "LEYTE", "municipality" => "Albuera", "zip_code" => "6542"],
  ["province" => "LEYTE", "municipality" => "Babatngon", "zip_code" => "6520"],
  ["province" => "LEYTE", "municipality" => "Burauen", "zip_code" => "6516"],
  ["province" => "LEYTE", "municipality" => "Barugo", "zip_code" => "6519"],
  ["province" => "LEYTE", "municipality" => "Bato", "zip_code" => "6525"],
  ["province" => "LEYTE", "municipality" => "Baybay", "zip_code" => "6521"],
  ["province" => "LEYTE", "municipality" => "Calubian", "zip_code" => "6534"],
  ["province" => "LEYTE", "municipality" => "Capoocan", "zip_code" => "6530"],
  ["province" => "LEYTE", "municipality" => "Carigara", "zip_code" => "6529"],
  ["province" => "LEYTE", "municipality" => "Dagami", "zip_code" => "6515"],
  ["province" => "LEYTE", "municipality" => "Dulag", "zip_code" => "6505"],
  ["province" => "LEYTE", "municipality" => "Hilongos", "zip_code" => "6524"],
  ["province" => "LEYTE", "municipality" => "Hindang", "zip_code" => "6523"],
  ["province" => "LEYTE", "municipality" => "Inopacan", "zip_code" => "6522"],
  ["province" => "LEYTE", "municipality" => "Isabel", "zip_code" => "6539"],
  ["province" => "LEYTE", "municipality" => "Jaro", "zip_code" => "6527"],
  ["province" => "LEYTE", "municipality" => "Javier (Bugho)", "zip_code" => "6511"],
  ["province" => "LEYTE", "municipality" => "Julita", "zip_code" => "6506"],
  ["province" => "LEYTE", "municipality" => "Kananga", "zip_code" => "6531"],
  ["province" => "LEYTE", "municipality" => "La Paz", "zip_code" => "6508"],
  ["province" => "LEYTE", "municipality" => "Leyte   ", "zip_code" => "6533"],
  ["province" => "LEYTE", "municipality" => "Macarthur", "zip_code" => "6509"],
  ["province" => "LEYTE", "municipality" => "Mahaplag", "zip_code" => "6512"],
  ["province" => "LEYTE", "municipality" => "Matag-ob", "zip_code" => "6532"],
  ["province" => "LEYTE", "municipality" => "Matalom", "zip_code" => "6526"],
  ["province" => "LEYTE", "municipality" => "Mayorga", "zip_code" => "6507"],
  ["province" => "LEYTE", "municipality" => "Merida", "zip_code" => "6540"],
  ["province" => "LEYTE", "municipality" => "Ormoc City", "zip_code" => "6541"],
  ["province" => "LEYTE", "municipality" => "Palo", "zip_code" => "6501"],
  ["province" => "LEYTE", "municipality" => "Palompon", "zip_code" => "6538"],
  ["province" => "LEYTE", "municipality" => "Pastrana", "zip_code" => "6514"],
  ["province" => "LEYTE", "municipality" => "San Isidro", "zip_code" => "6535"],
  ["province" => "LEYTE", "municipality" => "San Miguel", "zip_code" => "6518"],
  ["province" => "LEYTE", "municipality" => "Sta. Fe", "zip_code" => "6513"],
  ["province" => "LEYTE", "municipality" => "Tabango", "zip_code" => "6536"],
  ["province" => "LEYTE", "municipality" => "Tabontabon", "zip_code" => "6504"],
  ["province" => "LEYTE", "municipality" => "Tacloban City", "zip_code" => "6500"],
  ["province" => "LEYTE", "municipality" => "Tanauan", "zip_code" => "6502"],
  ["province" => "LEYTE", "municipality" => "Tolosa", "zip_code" => "6503"],
  ["province" => "LEYTE", "municipality" => "Tunga", "zip_code" => "6528"],
  ["province" => "LEYTE", "municipality" => "Villaba", "zip_code" => "6537"],

  ["province" => "NORTHERN SAMAR", "municipality" => "Allen", "zip_code" => "6405"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Biri", "zip_code" => "6410"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Bobon", "zip_code" => "6401"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Capul", "zip_code" => "6408"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Catarman", "zip_code" => "6400"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Catubig", "zip_code" => "6418"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Gamay", "zip_code" => "6422"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Las Navas", "zip_code" => "6420"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Laoang", "zip_code" => "6411"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Lapinig", "zip_code" => "6423"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Lavezares", "zip_code" => "6404"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Lope de Vega", "zip_code" => "6403"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Mapanas", "zip_code" => "6412"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Mondragon", "zip_code" => "6417"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Palapag", "zip_code" => "6421"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Pambujan", "zip_code" => "6413"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Rosario", "zip_code" => "6416"],
  ["province" => "NORTHERN SAMAR", "municipality" => "San Antonio", "zip_code" => "6407"],
  ["province" => "NORTHERN SAMAR", "municipality" => "San Isidro", "zip_code" => "6409"],
  ["province" => "NORTHERN SAMAR", "municipality" => "San Jose", "zip_code" => "6402"],
  ["province" => "NORTHERN SAMAR", "municipality" => "San Roque", "zip_code" => "6415"],
  ["province" => "NORTHERN SAMAR", "municipality" => "San Vicente", "zip_code" => "6419"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Silvino Lobos", "zip_code" => "6414"],
  ["province" => "NORTHERN SAMAR", "municipality" => "Victoria", "zip_code" => "6406"],

  ["province" => "SOUTHERN LEYTE", "municipality" => "Anahawan", "zip_code" => "6610"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Bontoc", "zip_code" => "6604"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Hinunangan", "zip_code" => "6608"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Hinundayan", "zip_code" => "6609"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Libagon", "zip_code" => "6615"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Liloan", "zip_code" => "6612"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Limasawa", "zip_code" => "6618"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Maasin", "zip_code" => "6600"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Macrohon", "zip_code" => "6601"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Malitbog", "zip_code" => "6603"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Padre Burgos", "zip_code" => "6602"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Pintuyan", "zip_code" => "6614"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "San Francisco", "zip_code" => "6613"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "San Juan (Cabalian)", "zip_code" => "6611"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "San Ricardo", "zip_code" => "6617"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Silago", "zip_code" => "6607"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Sogod", "zip_code" => "6606"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Saint Bernard", "zip_code" => "6616"],
  ["province" => "SOUTHERN LEYTE", "municipality" => "Tomas Oppus", "zip_code" => "6605"],

  ["province" => "WESTERN SAMAR", "municipality" => "Almagro", "zip_code" => "6724"],
  ["province" => "WESTERN SAMAR", "municipality" => "Basey", "zip_code" => "6720"],
  ["province" => "WESTERN SAMAR", "municipality" => "Calbayog City", "zip_code" => "6710"],
  ["province" => "WESTERN SAMAR", "municipality" => "Calbiga", "zip_code" => "6715"],
  ["province" => "WESTERN SAMAR", "municipality" => "Catbalogan", "zip_code" => "6700"],
  ["province" => "WESTERN SAMAR", "municipality" => "Daram", "zip_code" => "6722"],
  ["province" => "WESTERN SAMAR", "municipality" => "Gandara", "zip_code" => "6706"],
  ["province" => "WESTERN SAMAR", "municipality" => "Hinabangan", "zip_code" => "6713"],
  ["province" => "WESTERN SAMAR", "municipality" => "Jiabong", "zip_code" => "6701"],
  ["province" => "WESTERN SAMAR", "municipality" => "Marabut", "zip_code" => "6721"],
  ["province" => "WESTERN SAMAR", "municipality" => "Matuguinao", "zip_code" => "6708"],
  ["province" => "WESTERN SAMAR", "municipality" => "Motiong", "zip_code" => "6702"],
  ["province" => "WESTERN SAMAR", "municipality" => "Pagsanghan", "zip_code" => "6705"],
  ["province" => "WESTERN SAMAR", "municipality" => "Pinabacdao", "zip_code" => "6716"],
  ["province" => "WESTERN SAMAR", "municipality" => "San Jorge", "zip_code" => "6707"],
  ["province" => "WESTERN SAMAR", "municipality" => "San Jose de Buan", "zip_code" => "6723"],
  ["province" => "WESTERN SAMAR", "municipality" => "San Sebastian", "zip_code" => "6714"],
  ["province" => "WESTERN SAMAR", "municipality" => "Sta. Margarita", "zip_code" => "6709"],
  ["province" => "WESTERN SAMAR", "municipality" => "Sta. Rita", "zip_code" => "6718"],
  ["province" => "WESTERN SAMAR", "municipality" => "Sto. Niño", "zip_code" => "6711"],
  ["province" => "WESTERN SAMAR", "municipality" => "Tagapul-an", "zip_code" => "6712"],
  ["province" => "WESTERN SAMAR", "municipality" => "Talalora", "zip_code" => "6719"],
  ["province" => "WESTERN SAMAR", "municipality" => "Tarangnan", "zip_code" => "6704"],
  ["province" => "WESTERN SAMAR", "municipality" => "Villareal", "zip_code" => "6717"],
  ["province" => "WESTERN SAMAR", "municipality" => "Wright", "zip_code" => "6703"],
  ["province" => "WESTERN SAMAR", "municipality" => "Zumarraga", "zip_code" => "6725"],
]);
