<?php

declare(strict_types=1);
return [
    ['province' => 'BILIRAN', 'municipality' => 'ALMERIA', 'zip_code' => '6544'],
    ['province' => 'BILIRAN', 'municipality' => 'BILIRAN', 'zip_code' => '6549'],
    ['province' => 'BILIRAN', 'municipality' => 'CABUCGAYAN', 'zip_code' => '6550'],
    ['province' => 'BILIRAN', 'municipality' => 'CAIBIRAN', 'zip_code' => '6548'],
    ['province' => 'BILIRAN', 'municipality' => 'CULABA', 'zip_code' => '6547'],
    ['province' => 'BILIRAN', 'municipality' => 'KAWAYAN', 'zip_code' => '6545'],
    ['province' => 'BILIRAN', 'municipality' => 'MARIPIPI', 'zip_code' => '6546'],
    ['province' => 'BILIRAN', 'municipality' => 'NAVAL', 'zip_code' => '6543'],

    ['province' => 'EASTERN SAMAR', 'municipality' => 'ARTECHE', 'zip_code' => '6822'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'BALANGIGA', 'zip_code' => '6812'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'BALANGKAYAN', 'zip_code' => '6801'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'BORONGAN', 'zip_code' => '6800'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'CAN-AVID', 'zip_code' => '6806'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'DOLORES', 'zip_code' => '6817'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'GENERAL MACARTHUR', 'zip_code' => '6805'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'GIPORLOS', 'zip_code' => '6811'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'GUIUAN', 'zip_code' => '6809'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'HERNANI', 'zip_code' => '6804'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'JIPAPAD', 'zip_code' => '6819'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'LAWAAN', 'zip_code' => '6813'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'LLORENTE', 'zip_code' => '6803'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'MASLOG', 'zip_code' => '6820'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'MAYDOLONG', 'zip_code' => '6802'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'MERCEDES', 'zip_code' => '6808'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'ORAS', 'zip_code' => '6818'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'QUINAPONDAN', 'zip_code' => '6810'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'SALCEDO', 'zip_code' => '6807'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'SAN JULIAN', 'zip_code' => '6814'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'SAN POLICARPIO', 'zip_code' => '6821'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'SULAT', 'zip_code' => '6815'],
    ['province' => 'EASTERN SAMAR', 'municipality' => 'TAFT', 'zip_code' => '6816'],

    ['province' => 'LEYTE', 'municipality' => 'ABUYOG', 'zip_code' => '6510'],
    ['province' => 'LEYTE', 'municipality' => 'ALANGALANG', 'zip_code' => '6517'],
    ['province' => 'LEYTE', 'municipality' => 'ALBUERA', 'zip_code' => '6542'],
    ['province' => 'LEYTE', 'municipality' => 'BABATNGON', 'zip_code' => '6520'],
    ['province' => 'LEYTE', 'municipality' => 'BURAUEN', 'zip_code' => '6516'],
    ['province' => 'LEYTE', 'municipality' => 'BARUGO', 'zip_code' => '6519'],
    ['province' => 'LEYTE', 'municipality' => 'BATO', 'zip_code' => '6525'],
    ['province' => 'LEYTE', 'municipality' => 'BAYBAY', 'zip_code' => '6521'],
    ['province' => 'LEYTE', 'municipality' => 'CALUBIAN', 'zip_code' => '6534'],
    ['province' => 'LEYTE', 'municipality' => 'CAPOOCAN', 'zip_code' => '6530'],
    ['province' => 'LEYTE', 'municipality' => 'CARIGARA', 'zip_code' => '6529'],
    ['province' => 'LEYTE', 'municipality' => 'DAGAMI', 'zip_code' => '6515'],
    ['province' => 'LEYTE', 'municipality' => 'DULAG', 'zip_code' => '6505'],
    ['province' => 'LEYTE', 'municipality' => 'HILONGOS', 'zip_code' => '6524'],
    ['province' => 'LEYTE', 'municipality' => 'HINDANG', 'zip_code' => '6523'],
    ['province' => 'LEYTE', 'municipality' => 'INOPACAN', 'zip_code' => '6522'],
    ['province' => 'LEYTE', 'municipality' => 'ISABEL', 'zip_code' => '6539'],
    ['province' => 'LEYTE', 'municipality' => 'JARO', 'zip_code' => '6527'],
    ['province' => 'LEYTE', 'municipality' => 'JAVIER (BUGHO)', 'zip_code' => '6511'],
    ['province' => 'LEYTE', 'municipality' => 'JULITA', 'zip_code' => '6506'],
    ['province' => 'LEYTE', 'municipality' => 'KANANGA', 'zip_code' => '6531'],
    ['province' => 'LEYTE', 'municipality' => 'LA PAZ', 'zip_code' => '6508'],
    ['province' => 'LEYTE', 'municipality' => 'LEYTE', 'zip_code' => '6533'],
    ['province' => 'LEYTE', 'municipality' => 'MACARTHUR', 'zip_code' => '6509'],
    ['province' => 'LEYTE', 'municipality' => 'MAHAPLAG', 'zip_code' => '6512'],
    ['province' => 'LEYTE', 'municipality' => 'MATAG-OB', 'zip_code' => '6532'],
    ['province' => 'LEYTE', 'municipality' => 'MATALOM', 'zip_code' => '6526'],
    ['province' => 'LEYTE', 'municipality' => 'MAYORGA', 'zip_code' => '6507'],
    ['province' => 'LEYTE', 'municipality' => 'MERIDA', 'zip_code' => '6540'],
    ['province' => 'LEYTE', 'municipality' => 'ORMOC CITY', 'zip_code' => '6541'],
    ['province' => 'LEYTE', 'municipality' => 'PALO', 'zip_code' => '6501'],
    ['province' => 'LEYTE', 'municipality' => 'PALOMPON', 'zip_code' => '6538'],
    ['province' => 'LEYTE', 'municipality' => 'PASTRANA', 'zip_code' => '6514'],
    ['province' => 'LEYTE', 'municipality' => 'SAN ISIDRO', 'zip_code' => '6535'],
    ['province' => 'LEYTE', 'municipality' => 'SAN MIGUEL', 'zip_code' => '6518'],
    ['province' => 'LEYTE', 'municipality' => 'STA. FE', 'zip_code' => '6513'],
    ['province' => 'LEYTE', 'municipality' => 'TABANGO', 'zip_code' => '6536'],
    ['province' => 'LEYTE', 'municipality' => 'TABONTABON', 'zip_code' => '6504'],
    ['province' => 'LEYTE', 'municipality' => 'TACLOBAN CITY', 'zip_code' => '6500'],
    ['province' => 'LEYTE', 'municipality' => 'TANAUAN', 'zip_code' => '6502'],
    ['province' => 'LEYTE', 'municipality' => 'TOLOSA', 'zip_code' => '6503'],
    ['province' => 'LEYTE', 'municipality' => 'TUNGA', 'zip_code' => '6528'],
    ['province' => 'LEYTE', 'municipality' => 'VILLABA', 'zip_code' => '6537'],

    ['province' => 'NORTHERN SAMAR', 'municipality' => 'ALLEN', 'zip_code' => '6405'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'BIRI', 'zip_code' => '6410'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'BOBON', 'zip_code' => '6401'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'CAPUL', 'zip_code' => '6408'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'CATARMAN', 'zip_code' => '6400'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'CATUBIG', 'zip_code' => '6418'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'GAMAY', 'zip_code' => '6422'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'LAS NAVAS', 'zip_code' => '6420'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'LAOANG', 'zip_code' => '6411'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'LAPINIG', 'zip_code' => '6423'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'LAVEZARES', 'zip_code' => '6404'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'LOPE DE VEGA', 'zip_code' => '6403'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'MAPANAS', 'zip_code' => '6412'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'MONDRAGON', 'zip_code' => '6417'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'PALAPAG', 'zip_code' => '6421'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'PAMBUJAN', 'zip_code' => '6413'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'ROSARIO', 'zip_code' => '6416'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SAN ANTONIO', 'zip_code' => '6407'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SAN ISIDRO', 'zip_code' => '6409'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SAN JOSE', 'zip_code' => '6402'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SAN ROQUE', 'zip_code' => '6415'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SAN VICENTE', 'zip_code' => '6419'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'SILVINO LOBOS', 'zip_code' => '6414'],
    ['province' => 'NORTHERN SAMAR', 'municipality' => 'VICTORIA', 'zip_code' => '6406'],

    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'ANAHAWAN', 'zip_code' => '6610'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'BONTOC', 'zip_code' => '6604'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'HINUNANGAN', 'zip_code' => '6608'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'HINUNDAYAN', 'zip_code' => '6609'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'LIBAGON', 'zip_code' => '6615'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'LILOAN', 'zip_code' => '6612'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'LIMASAWA', 'zip_code' => '6618'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'MAASIN', 'zip_code' => '6600'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'MACROHON', 'zip_code' => '6601'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'MALITBOG', 'zip_code' => '6603'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'PADRE BURGOS', 'zip_code' => '6602'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'PINTUYAN', 'zip_code' => '6614'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SAN FRANCISCO', 'zip_code' => '6613'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SAN JUAN (CABALIAN)', 'zip_code' => '6611'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SAN RICARDO', 'zip_code' => '6617'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SILAGO', 'zip_code' => '6607'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SOGOD', 'zip_code' => '6606'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'SAINT BERNARD', 'zip_code' => '6616'],
    ['province' => 'SOUTHERN LEYTE', 'municipality' => 'TOMAS OPPUS', 'zip_code' => '6605'],

    ['province' => 'WESTERN SAMAR', 'municipality' => 'ALMAGRO', 'zip_code' => '6724'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'BASEY', 'zip_code' => '6720'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'CALBAYOG CITY', 'zip_code' => '6710'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'CALBIGA', 'zip_code' => '6715'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'CATBALOGAN', 'zip_code' => '6700'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'DARAM', 'zip_code' => '6722'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'GANDARA', 'zip_code' => '6706'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'HINABANGAN', 'zip_code' => '6713'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'JIABONG', 'zip_code' => '6701'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'MARABUT', 'zip_code' => '6721'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'MATUGUINAO', 'zip_code' => '6708'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'MOTIONG', 'zip_code' => '6702'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'PAGSANGHAN', 'zip_code' => '6705'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'PINABACDAO', 'zip_code' => '6716'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'SAN JORGE', 'zip_code' => '6707'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'SAN JOSE DE BUAN', 'zip_code' => '6723'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'SAN SEBASTIAN', 'zip_code' => '6714'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'STA. MARGARITA', 'zip_code' => '6709'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'STA. RITA', 'zip_code' => '6718'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'STO. NIÑO', 'zip_code' => '6711'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'TAGAPUL-AN', 'zip_code' => '6712'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'TALALORA', 'zip_code' => '6719'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'TARANGNAN', 'zip_code' => '6704'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'VILLAREAL', 'zip_code' => '6717'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'WRIGHT', 'zip_code' => '6703'],
    ['province' => 'WESTERN SAMAR', 'municipality' => 'ZUMARRAGA', 'zip_code' => '6725'],
];
