<?php

declare(strict_types=1);

return [
    [
        'province' => 'BUKIDNON',
        'zip_codes' => [
            ['municipality' => 'BAUNGON', 'zip_code' => '8707'],
            ['municipality' => 'CABANGLASAN', 'zip_code' => '8723'],
            ['municipality' => 'DAMULOG', 'zip_code' => '8721'],
            ['municipality' => 'DANGCAGAN', 'zip_code' => '8719'],
            ['municipality' => 'DON CARLOS', 'zip_code' => '8712'],
            ['municipality' => 'IMPASUGONG', 'zip_code' => '8702'],
            ['municipality' => 'KADINGILAN', 'zip_code' => '8713'],
            ['municipality' => 'KALILANGAN', 'zip_code' => '8718'],
            ['municipality' => 'KIBAWE', 'zip_code' => '8720'],
            ['municipality' => 'KITAOTAO', 'zip_code' => '8716'],
            ['municipality' => 'LANTAPAN', 'zip_code' => '8722'],
            ['municipality' => 'LIBONA', 'zip_code' => '8706'],
            ['municipality' => 'MALAYBALAY', 'zip_code' => '8700'],
            ['municipality' => 'MALITBOG', 'zip_code' => '8704'],
            ['municipality' => 'MANOLO FORTICH', 'zip_code' => '8703'],
            ['municipality' => 'MARAMAG', 'zip_code' => '8714'],
            ['municipality' => 'MUSUAN', 'zip_code' => '8710'],
            ['municipality' => 'PANGANTUCAN', 'zip_code' => '8717'],
            ['municipality' => 'PHILLIPS', 'zip_code' => '8705'],
            ['municipality' => 'QUEZON', 'zip_code' => '8715'],
            ['municipality' => 'SAN FERNANDO', 'zip_code' => '8711'],
            ['municipality' => 'SUMILAO', 'zip_code' => '8701'],
            ['municipality' => 'TALAKAG', 'zip_code' => '8708'],
            ['municipality' => 'VALENCIA', 'zip_code' => '8709'],
        ]
    ],

    [
        'province' => 'CAMIGUIN',
        'zip_codes' => [
            ['municipality' => 'CATARMAN', 'zip_code' => '9104'],
            ['municipality' => 'GUINSILIBAN', 'zip_code' => '9102'],
            ['municipality' => 'MAHINOG', 'zip_code' => '9101'],
            ['municipality' => 'MAMBAJAO', 'zip_code' => '9100'],
            ['municipality' => 'SAGAY', 'zip_code' => '9103'],
        ]
    ],

    [
        'province' => 'LANAO DEL NORTE',
        'zip_codes' => [
            ['municipality' => 'BACOLOD', 'zip_code' => '9205'],
            ['municipality' => 'BALOI', 'zip_code' => '9217'],
            ['municipality' => 'BAROY', 'zip_code' => '9210'],
            ['municipality' => 'ILIGAN CITY', 'zip_code' => '9200'],
            ['municipality' => 'KAPATAGAN', 'zip_code' => '9214'],
            ['municipality' => 'KAUSWAGAN', 'zip_code' => '9202'],
            ['municipality' => 'KOLAMBUGAN', 'zip_code' => '9207'],
            ['municipality' => 'LALA', 'zip_code' => '9211'],
            ['municipality' => 'LINAMON', 'zip_code' => '9201'],
            ['municipality' => 'MAGSAYSAY', 'zip_code' => '9221'],
            ['municipality' => 'MAIGO', 'zip_code' => '9206'],
            ['municipality' => 'MATUNGAO', 'zip_code' => '9203'],
            ['municipality' => 'MUNAI', 'zip_code' => '9219'],
            ['municipality' => 'NUNUNGAN', 'zip_code' => '9216'],
            ['municipality' => 'PANTAO RAGAT', 'zip_code' => '9208'],
            ['municipality' => 'PANTAR', 'zip_code' => '9218'],
            ['municipality' => 'POONA PIAGAPO', 'zip_code' => '9204'],
            ['municipality' => 'SALVADOR', 'zip_code' => '9212'],
            ['municipality' => 'SAPAD', 'zip_code' => '9213'],
            ['municipality' => 'SULTAN NAGA DIMAPORO (FORMERLY KAROMATAN) ', 'zip_code' => '9215'],
            ['municipality' => 'TAGOLOAN', 'zip_code' => '9222'],
            ['municipality' => 'TANGCAL', 'zip_code' => '9220'],
            ['municipality' => 'TUBOD', 'zip_code' => '9209'],
        ]
    ],

    [
        'province' => 'MISAMIS OCCIDENTAL',
        'zip_codes' => [
            ['municipality' => 'ALORAN', 'zip_code' => '7206'],
            ['municipality' => 'BALIANGAO', 'zip_code' => '7211'],
            ['municipality' => 'BONIFACIO', 'zip_code' => '7215'],
            ['municipality' => 'CALAMBA', 'zip_code' => '7210'],
            ['municipality' => 'CLARIN', 'zip_code' => '7201'],
            ['municipality' => 'CONCEPCION', 'zip_code' => '7213'],
            ['municipality' => 'DON VICTORIANO CHIONGBIAN', 'zip_code' => '7216'],
            ['municipality' => 'JIMENEZ', 'zip_code' => '7204'],
            ['municipality' => 'LOPEZ JAENA', 'zip_code' => '7208'],
            ['municipality' => 'OROQUIETA CITY', 'zip_code' => '7207'],
            ['municipality' => 'OZAMIS CITY', 'zip_code' => '7200'],
            ['municipality' => 'PANAON', 'zip_code' => '7205'],
            ['municipality' => 'PLARIDEL', 'zip_code' => '7209'],
            ['municipality' => 'SAPANG DALAGA', 'zip_code' => '7212'],
            ['municipality' => 'SINACABAN', 'zip_code' => '7203'],
            ['municipality' => 'TANGUB CITY', 'zip_code' => '7214'],
            ['municipality' => 'TUDELA', 'zip_code' => '7202'],
        ]
    ],

    [
        'province' => 'MISAMIS ORIENTAL',
        'zip_codes' => [
            ['municipality' => 'ALUBIJID', 'zip_code' => '9018'],
            ['municipality' => 'BALINGASAG', 'zip_code' => '9005'],
            ['municipality' => 'BALINGOAN', 'zip_code' => '9011'],
            ['municipality' => 'BINUANGAN', 'zip_code' => '9008'],
            ['municipality' => 'CAGAYAN DE ORO CITY', 'zip_code' => '9000'],
            ['municipality' => 'CLAVERIA', 'zip_code' => '9004'],
            ['municipality' => 'EL SALVADOR', 'zip_code' => '9017'],
            ['municipality' => 'GINGOOG CITY', 'zip_code' => '9014'],
            ['municipality' => 'GITAGUM', 'zip_code' => '9020'],
            ['municipality' => 'INITAO', 'zip_code' => '9022'],
            ['municipality' => 'JASAAN', 'zip_code' => '9003'],
            ['municipality' => 'KINOGUITAN', 'zip_code' => '9010'],
            ['municipality' => 'LAGUINDINGAN', 'zip_code' => '9019'],
            ['municipality' => 'LAGONGLONG', 'zip_code' => '9006'],
            ['municipality' => 'LIBERTAD', 'zip_code' => '9021'],
            ['municipality' => 'LUGAIT', 'zip_code' => '9025'],
            ['municipality' => 'MAGSAYSAY', 'zip_code' => '9015'],
            ['municipality' => 'MANTICAO', 'zip_code' => '9024'],
            ['municipality' => 'MEDINA', 'zip_code' => '9013'],
            ['municipality' => 'NAAWAN', 'zip_code' => '9023'],
            ['municipality' => 'OPOL', 'zip_code' => '9016'],
            ['municipality' => 'SALAY', 'zip_code' => '9007'],
            ['municipality' => 'SUGBONGCOGON', 'zip_code' => '9009'],
            ['municipality' => 'TAGOLOAN', 'zip_code' => '9001'],
            ['municipality' => 'TALISAYAN', 'zip_code' => '9012'],
            ['municipality' => 'VILLANUEVA', 'zip_code' => '9002'],
        ]
    ],
];
