<?php
return [
  ["province" => "BUKIDNON", "municipality" => "BAUNGON", "zip_code" => "8707"],
  ["province" => "BUKIDNON", "municipality" => "CABANGLASAN", "zip_code" => "8723"],
  ["province" => "BUKIDNON", "municipality" => "DAMULOG", "zip_code" => "8721"],
  ["province" => "BUKIDNON", "municipality" => "DANGCAGAN", "zip_code" => "8719"],
  ["province" => "BUKIDNON", "municipality" => "DON CARLOS", "zip_code" => "8712"],
  ["province" => "BUKIDNON", "municipality" => "IMPASUGONG", "zip_code" => "8702"],
  ["province" => "BUKIDNON", "municipality" => "KADINGILAN", "zip_code" => "8713"],
  ["province" => "BUKIDNON", "municipality" => "KALILANGAN", "zip_code" => "8718"],
  ["province" => "BUKIDNON", "municipality" => "KIBAWE", "zip_code" => "8720"],
  ["province" => "BUKIDNON", "municipality" => "KITAOTAO", "zip_code" => "8716"],
  ["province" => "BUKIDNON", "municipality" => "LANTAPAN", "zip_code" => "8722"],
  ["province" => "BUKIDNON", "municipality" => "LIBONA", "zip_code" => "8706"],
  ["province" => "BUKIDNON", "municipality" => "MALAYBALAY", "zip_code" => "8700"],
  ["province" => "BUKIDNON", "municipality" => "MALITBOG", "zip_code" => "8704"],
  ["province" => "BUKIDNON", "municipality" => "MANOLO FORTICH", "zip_code" => "8703"],
  ["province" => "BUKIDNON", "municipality" => "MARAMAG", "zip_code" => "8714"],
  ["province" => "BUKIDNON", "municipality" => "MUSUAN", "zip_code" => "8710"],
  ["province" => "BUKIDNON", "municipality" => "PANGANTUCAN", "zip_code" => "8717"],
  ["province" => "BUKIDNON", "municipality" => "PHILLIPS", "zip_code" => "8705"],
  ["province" => "BUKIDNON", "municipality" => "QUEZON", "zip_code" => "8715"],
  ["province" => "BUKIDNON", "municipality" => "SAN FERNANDO", "zip_code" => "8711"],
  ["province" => "BUKIDNON", "municipality" => "SUMILAO", "zip_code" => "8701"],
  ["province" => "BUKIDNON", "municipality" => "TALAKAG", "zip_code" => "8708"],
  ["province" => "BUKIDNON", "municipality" => "VALENCIA", "zip_code" => "8709"],

  ["province" => "CAMIGUIN", "municipality" => "CATARMAN", "zip_code" => "9104"],
  ["province" => "CAMIGUIN", "municipality" => "GUINSILIBAN", "zip_code" => "9102"],
  ["province" => "CAMIGUIN", "municipality" => "MAHINOG", "zip_code" => "9101"],
  ["province" => "CAMIGUIN", "municipality" => "MAMBAJAO", "zip_code" => "9100"],
  ["province" => "CAMIGUIN", "municipality" => "SAGAY", "zip_code" => "9103"],

  ["province" => "LANAO DEL NORTE", "municipality" => "BACOLOD", "zip_code" => "9205"],
  ["province" => "LANAO DEL NORTE", "municipality" => "BALOI", "zip_code" => "9217"],
  ["province" => "LANAO DEL NORTE", "municipality" => "BAROY", "zip_code" => "9210"],
  ["province" => "LANAO DEL NORTE", "municipality" => "ILIGAN CITY", "zip_code" => "9200"],
  ["province" => "LANAO DEL NORTE", "municipality" => "KAPATAGAN", "zip_code" => "9214"],
  ["province" => "LANAO DEL NORTE", "municipality" => "KAUSWAGAN", "zip_code" => "9202"],
  ["province" => "LANAO DEL NORTE", "municipality" => "KOLAMBUGAN", "zip_code" => "9207"],
  ["province" => "LANAO DEL NORTE", "municipality" => "LALA", "zip_code" => "9211"],
  ["province" => "LANAO DEL NORTE", "municipality" => "LINAMON", "zip_code" => "9201"],
  ["province" => "LANAO DEL NORTE", "municipality" => "MAGSAYSAY", "zip_code" => "9221"],
  ["province" => "LANAO DEL NORTE", "municipality" => "MAIGO", "zip_code" => "9206"],
  ["province" => "LANAO DEL NORTE", "municipality" => "MATUNGAO", "zip_code" => "9203"],
  ["province" => "LANAO DEL NORTE", "municipality" => "MUNAI", "zip_code" => "9219"],
  ["province" => "LANAO DEL NORTE", "municipality" => "NUNUNGAN", "zip_code" => "9216"],
  ["province" => "LANAO DEL NORTE", "municipality" => "PANTAO RAGAT", "zip_code" => "9208"],
  ["province" => "LANAO DEL NORTE", "municipality" => "PANTAR", "zip_code" => "9218"],
  ["province" => "LANAO DEL NORTE", "municipality" => "POONA PIAGAPO", "zip_code" => "9204"],
  ["province" => "LANAO DEL NORTE", "municipality" => "SALVADOR", "zip_code" => "9212"],
  ["province" => "LANAO DEL NORTE", "municipality" => "SAPAD", "zip_code" => "9213"],
  ["province" => "LANAO DEL NORTE", "municipality" => "SULTAN NAGA DIMAPORO (FORMERLY KAROMATAN) ", "zip_code" => "9215"],
  ["province" => "LANAO DEL NORTE", "municipality" => "TAGOLOAN", "zip_code" => "9222"],
  ["province" => "LANAO DEL NORTE", "municipality" => "TANGCAL", "zip_code" => "9220"],
  ["province" => "LANAO DEL NORTE", "municipality" => "TUBOD", "zip_code" => "9209"],

  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "ALORAN", "zip_code" => "7206"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "BALIANGAO", "zip_code" => "7211"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "BONIFACIO", "zip_code" => "7215"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "CALAMBA", "zip_code" => "7210"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "CLARIN", "zip_code" => "7201"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "CONCEPCION", "zip_code" => "7213"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "DON VICTORIANO CHIONGBIAN", "zip_code" => "7216"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "JIMENEZ", "zip_code" => "7204"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "LOPEZ JAENA", "zip_code" => "7208"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "OROQUIETA CITY", "zip_code" => "7207"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "OZAMIS CITY", "zip_code" => "7200"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "PANAON", "zip_code" => "7205"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "PLARIDEL", "zip_code" => "7209"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "SAPANG DALAGA", "zip_code" => "7212"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "SINACABAN", "zip_code" => "7203"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "TANGUB CITY", "zip_code" => "7214"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "TUDELA", "zip_code" => "7202"],

  ["province" => "MISAMIS ORIENTAL", "municipality" => "ALUBIJID", "zip_code" => "9018"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "BALINGASAG", "zip_code" => "9005"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "BALINGOAN", "zip_code" => "9011"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "BINUANGAN", "zip_code" => "9008"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "CAGAYAN DE ORO CITY", "zip_code" => "9000"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "CLAVERIA", "zip_code" => "9004"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "EL SALVADOR", "zip_code" => "9017"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "GINGOOG CITY", "zip_code" => "9014"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "GITAGUM", "zip_code" => "9020"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "INITAO", "zip_code" => "9022"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "JASAAN", "zip_code" => "9003"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "KINOGUITAN", "zip_code" => "9010"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "LAGUINDINGAN", "zip_code" => "9019"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "LAGONGLONG", "zip_code" => "9006"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "LIBERTAD", "zip_code" => "9021"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "LUGAIT", "zip_code" => "9025"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "MAGSAYSAY", "zip_code" => "9015"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "MANTICAO", "zip_code" => "9024"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "MEDINA", "zip_code" => "9013"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "NAAWAN", "zip_code" => "9023"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "OPOL", "zip_code" => "9016"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "SALAY", "zip_code" => "9007"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "SUGBONGCOGON", "zip_code" => "9009"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "TAGOLOAN", "zip_code" => "9001"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "TALISAYAN", "zip_code" => "9012"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "VILLANUEVA", "zip_code" => "9002"],
];
