<?php
return  [
  ["province" => "MANILA", "municipality" => "Binondo", "zip_code" => "1006", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Intramuros", "zip_code" => "1002", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Malate", "zip_code" => "1004", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Manila CPO - Ermita", "zip_code" => "1000", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Paco", "zip_code" => "1007", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Pandacan", "zip_code" => "1011", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Port Area (South)", "zip_code" => "1018", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Quiapo", "zip_code" => "1001", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sampaloc East", "zip_code" => "1008", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sampaloc West ", "zip_code" => "1015", "barangays" => []],
  ["province" => "MANILA", "municipality" => "San Andres Bukid", "zip_code" => "1017", "barangays" => []],
  ["province" => "MANILA", "municipality" => "San Miguel", "zip_code" => "1005", "barangays" => []],
  ["province" => "MANILA", "municipality" => "San Nicolas ", "zip_code" => "1010", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sta. Ana", "zip_code" => "1009", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sta Cruz North", "zip_code" => "1014", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sta Cruz South", "zip_code" => "1003", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Sta Mesa", "zip_code" => "1016", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Tondo North", "zip_code" => "1013", "barangays" => []],
  ["province" => "MANILA", "municipality" => "Tondo South", "zip_code" => "1012", "barangays" => []],

  ["province" => "CALOOCAN CITY", "municipality" => "Amparo Subdivision", "zip_code" => "1425", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Bagong Silang", "zip_code" => "1428", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Bagumbong / Pag-asa", "zip_code" => "1421", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Bankers Village", "zip_code" => "1426", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Capitol Parkland Subdivision", "zip_code" => "1424", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Kaybiga/Deparo", "zip_code" => "1420", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Lilles Ville Subdivision", "zip_code" => "1423", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Novaliches North (Camarin North)", "zip_code" => "1422", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Tala Leprosarium", "zip_code" => "1427", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Victory Heights", "zip_code" => "1427", "barangays" => []],

  ["province" => "CALOOCAN CITY", "municipality" => "1st Ave. to 7th Ave. - West", "zip_code" => "1405", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Baesa", "zip_code" => "1401", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Fish Market", "zip_code" => "1411", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Grace Park East", "zip_code" => "1403", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Grace Park West", "zip_code" => "1406", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Isla de Cocomo", "zip_code" => "1412", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Caloocan City CPO", "zip_code" => "1400", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Kapitbahayan East", "zip_code" => "1413", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Kaunlaran Village", "zip_code" => "1409", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Maypajo", "zip_code" => "1410", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "San Jose", "zip_code" => "1404", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Sangandaan", "zip_code" => "1408", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "Santa Quiteria", "zip_code" => "1402", "barangays" => []],
  ["province" => "CALOOCAN CITY", "municipality" => "University Hills", "zip_code" => "1407", "barangays" => []],

  ["province" => "LAS PIÑAS", "municipality" => "Almanza", "zip_code" => "1750", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Angela Village", "zip_code" => "1749", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Cut-cut", "zip_code" => "1743", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Gatchalian Subdivision", "zip_code" => "1745", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Las Piñas CPO", "zip_code" => "1740", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Manila Doctors Village", "zip_code" => "1748", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Manuyo", "zip_code" => "1744", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Pulang Lupa", "zip_code" => "1742", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Remarville Subdivision", "zip_code" => "1741", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Soldiers Hills Subdivision", "zip_code" => "1752", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "T. S. Cruz Subdivision", "zip_code" => "1751", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Talon, Moonwalk", "zip_code" => "1747", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Verdant Acres Subdivision", "zip_code" => "1746", "barangays" => []],
  ["province" => "LAS PIÑAS", "municipality" => "Zapote", "zip_code" => "1742", "barangays" => []],

  ["province" => "MAKATI CITY", "municipality" => "Ayala-Paseo De Roxas", "zip_code" => "1226", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Bangkal", "zip_code" => "1233", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Bel-air", "zip_code" => "1209", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Cembo", "zip_code" => "1214", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Comembo", "zip_code" => "1217", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Dasmarinas Village North", "zip_code" => "1221", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Dasmarinas Village South", "zip_code" => "1222", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Forbes Park North", "zip_code" => "1219", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Forbes Park South", "zip_code" => "1220", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Fort Bonifacio (Camp)", "zip_code" => "1201", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Fort Bonifacio Naval Stn.", "zip_code" => "1202", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Greenbelt", "zip_code" => "1228", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Guadalupe Nuevo (Inc. Visayan Village)", "zip_code" => "1212", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Guadalupe Viejo (Inc. Palm Village)", "zip_code" => "1211", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Kasilawan", "zip_code" => "1206", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "La Paz-Singkamas-Tejeros", "zip_code" => "1204", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Legaspi Village", "zip_code" => "1229", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Magallanes Village", "zip_code" => "1232", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Makati Commercial Center", "zip_code" => "1224", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Makati CPO (Inc. Buendia Up To Edsa)", "zip_code" => "1200", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Olympia And Carmona", "zip_code" => "1207", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Palanan", "zip_code" => "1235", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Pasong Tamo 2000 Up, Ecology Village", "zip_code" => "1231", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Pembo", "zip_code" => "1218", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Pinagkaisahan-pitogo", "zip_code" => "1213", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Pio Del Pilar", "zip_code" => "1230", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Poblacion", "zip_code" => "1210", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Rembo (East) & Malapad Na Bato", "zip_code" => "1216", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Rembo(west)", "zip_code" => "1215", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Salcedo Village", "zip_code" => "1227", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "San Antonio Village (Inc. Malugay-Yakal)", "zip_code" => "1203", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "San Isidro", "zip_code" => "1234", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "San Lorenzo Village", "zip_code" => "1223", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Sta. Cruz", "zip_code" => "1205", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Urdaneta Village", "zip_code" => "1225", "barangays" => []],
  ["province" => "MAKATI CITY", "municipality" => "Valenzuela (Inc. Santiago, San Miguel & Rizal Vill.)", "zip_code" => "1208", "barangays" => []],

  ["province" => "MALABON CITY", "municipality" => "Acacia", "zip_code" => "1474", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Araneta Subdivision", "zip_code" => "1476", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Dampalit", "zip_code" => "1480", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Flores", "zip_code" => "1471", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Kaunlaran Village", "zip_code" => "1409", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Longos", "zip_code" => "1472", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Malabon", "zip_code" => "1470", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Maysilo", "zip_code" => "1477", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Muzon", "zip_code" => "1479", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Potrero", "zip_code" => "1475", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Santolan", "zip_code" => "1478", "barangays" => []],
  ["province" => "MALABON CITY", "municipality" => "Tonsuya", "zip_code" => "1473", "barangays" => []],

  ["province" => "MANDALUYONG CITY", "municipality" => "East Edsa", "zip_code" => "1554", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Greenhills South", "zip_code" => "1556", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Mandaluyong CPO", "zip_code" => "1550", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Phil. Natl. Mental Hospital", "zip_code" => "1553", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Shaw Boulevard", "zip_code" => "1552", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Vergara", "zip_code" => "1551", "barangays" => []],
  ["province" => "MANDALUYONG CITY", "municipality" => "Wack Wack Golf", "zip_code" => "1555", "barangays" => []],

  ["province" => "MARIKINA CITY", "municipality" => "Barangka", "zip_code" => "1803", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Concepcion 1", "zip_code" => "1807", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Concepcion 2", "zip_code" => "1811", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Fortune    ", "zip_code" => "1812", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Industrial Valley", "zip_code" => "1802", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "J. De La Peña", "zip_code" => "1804", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Malanday", "zip_code" => "1805", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Marikina CPO - Santa Elena - Santo Niño", "zip_code" => "1800", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Marikina Heights", "zip_code" => "1810", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Nangka", "zip_code" => "1808", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Tumana", "zip_code" => "1806", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Parang", "zip_code" => "1809", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "San Roque - Calumpang", "zip_code" => "1801", "barangays" => []],
  ["province" => "MARIKINA CITY", "municipality" => "Tañong", "zip_code" => "1803", "barangays" => []],

  ["province" => "MUNTINLUPA CITY", "municipality" => "Ayala Alabang P.O. Boxes", "zip_code" => "1799", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Ayala Alabang Subdivision", "zip_code" => "1780", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Bayanan/Putatan", "zip_code" => "1772", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Bule/Cupang", "zip_code" => "1771", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Filinvest Corp. City", "zip_code" => "1781", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Muntinlupa CPO    ", "zip_code" => "1770", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Pearl Heights", "zip_code" => "1775", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Pleasant Village", "zip_code" => "1777", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Poblacion", "zip_code" => "1776", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Susana Heights", "zip_code" => "1774", "barangays" => []],
  ["province" => "MUNTINLUPA CITY", "municipality" => "Tunasan", "zip_code" => "1773", "barangays" => []],

  ["province" => "NAVOTAS", "municipality" => "Fish Market", "zip_code" => "1411", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Isla De Cocomo", "zip_code" => "1412", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Kapitbahayan East", "zip_code" => "1413", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Kaunlaran Village", "zip_code" => "1409", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Navotas     ", "zip_code" => "1485", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Tangos ", "zip_code" => "1489", "barangays" => []],
  ["province" => "NAVOTAS", "municipality" => "Tanza", "zip_code" => "1490", "barangays" => []],

  ["province" => "PARAÑAQUE", "municipality" => "Aeropark Subdivision", "zip_code" => "1714", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Baclaran", "zip_code" => "1702", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Better Living Subdivision", "zip_code" => "1711", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Bf Homes 1", "zip_code" => "1720", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Bf Homes 2", "zip_code" => "1718", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Executive Heights Subd.", "zip_code" => "1710", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Ireneville Ii", "zip_code" => "1714", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Ireneville Subdivision I & Ii", "zip_code" => "1719", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Manila Memorial Park", "zip_code" => "1717", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Marina Subd. (Reclamation)", "zip_code" => "1703", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Maywood I", "zip_code" => "1719", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Maywood Village Ii", "zip_code" => "1716", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Merville Park", "zip_code" => "1709", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Miramar Subdivision", "zip_code" => "1712", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Moonwalk", "zip_code" => "1709", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Multinational Village", "zip_code" => "1708", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Ninoy Aquino Int’l. Airport", "zip_code" => "1705", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Parañaque Cpo", "zip_code" => "1700", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Pulo", "zip_code" => "1706", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "San Antonio Valley 11 & 12", "zip_code" => "1707", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "San Antonio Valley I", "zip_code" => "1715", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "South Admiral Village", "zip_code" => "1709", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Sto. Nino", "zip_code" => "1704", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "Tambo", "zip_code" => "1701", "barangays" => []],
  ["province" => "PARAÑAQUE", "municipality" => "United Subd.", "zip_code" => "1713", "barangays" => []],

  ["province" => "PASAY CITY", "municipality" => "Domestic Airport Po", "zip_code" => "1301", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "Manila Bay (Reclamation)", "zip_code" => "1308", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "Pasay City CPO Malibay", "zip_code" => "1300", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "PICC (Reclamation Area)", "zip_code" => "1307", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "San Isidro", "zip_code" => "1306", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "San Jose", "zip_code" => "1305", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "San Rafael", "zip_code" => "1302", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "San Roque", "zip_code" => "1303", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "Santa Clara", "zip_code" => "1304", "barangays" => []],
  ["province" => "PASAY CITY", "municipality" => "Villamor Airbase", "zip_code" => "1309", "barangays" => []],

  ["province" => "PASIG CITY", "municipality" => "Caniogan", "zip_code" => "1606", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Green Park", "zip_code" => "1612", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Kapitolyo", "zip_code" => "1603", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Manggahan", "zip_code" => "1611", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Maybunga ", "zip_code" => "1607", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Ortigas PO", "zip_code" => "1605", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Pasig CPO", "zip_code" => "1600", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Pinagbuhatan", "zip_code" => "1602", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Rosario", "zip_code" => "1609", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "San Joaquin", "zip_code" => "1601", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Santolan", "zip_code" => "1610", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Sta. Lucia", "zip_code" => "1608", "barangays" => []],
  ["province" => "PASIG CITY", "municipality" => "Ugong", "zip_code" => "1604", "barangays" => []],

  ["province" => "PATEROS", "municipality" => "Aguho", "zip_code" => "1620", "barangays" => []],
  ["province" => "PATEROS", "municipality" => "Sta. Ana", "zip_code" => "1621", "barangays" => []],

  ["province" => "QUEZON CITY", "municipality" => "Alicia", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Amihan", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Apolonio Samson", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Baesa", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagbag", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagong Bayan", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagong Buhay", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagong Lipunan", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagong Pag-asa", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bagong Silangan", "zip_code" => "1119", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bahay Toro", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Balingasa", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Balintawak", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Balumbato", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Batasan Hills", "zip_code" => "1126", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bayanihan", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "BF Homes", "zip_code" => "1120", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Blue Ridge", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Botocan", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Bungad", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Camp Aguinaldo", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Capitol Hills/Park", "zip_code" => "1126", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Capri", "zip_code" => "1117", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Central", "zip_code" => "1100", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Claro", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Commonwealth", "zip_code" => "1121", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Crame", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Cubao", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Culiat", "zip_code" => "1128", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Damar", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Damayan", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Damayan Lagi", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Damong Maliit", "zip_code" => "1123", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Del Monte", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Diliman", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Dioquino Zobel", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Doña Imelda", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Don Manuel", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Doña Aurora", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Doña Faustina Subd", "zip_code" => "1125", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Doña Josefa", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Duyan-duyan", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "E. Rodriguez ", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Escopa", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Fairview", "zip_code" => "1118", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Fairview North", "zip_code" => "1121", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Fairview South", "zip_code" => "1122", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Gintong Silahis", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Gulod", "zip_code" => "1117", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Holy Spirit", "zip_code" => "1127", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Horseshoe", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Immaculate Concepcion", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kaligayahan", "zip_code" => "1124", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kalusugan", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kamias", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kamuning", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Katipunan", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kaunlaran", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Kristong Hari", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Krus Na Ligas", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "La Loma", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Langing Handa", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Libis", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Lourdes", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Loyola Heights", "zip_code" => "1108", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Maharlika", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Malaya", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Mangga", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Manresa", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Mariana", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Mariblo", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Marilag", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Masagana", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Masambong", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Matalahib", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Matandang Balara", "zip_code" => "1119", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Milagrosa", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Nagkaisang Nayon", "zip_code" => "1125", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Nayon Kaunlaran", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "New Era", "zip_code" => "1107", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Novaliches Proper", "zip_code" => "1121", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Obrero", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Old Capitol Site", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Paang Bundok", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Pag-ibig Sa Nayon", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Paligsahan", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Paltok", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Pansol", "zip_code" => "1108", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Paraiso", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Pasong Putik", "zip_code" => "1118", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Pasong Tamo", "zip_code" => "1107", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Payatas", "zip_code" => "1119", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Phil-am", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Pinagkaisahan", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Piñahan", "zip_code" => "1100", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Project 4", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Project 6", "zip_code" => "1100", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Project 7", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Project 8", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Quezon City CPO", "zip_code" => "1100", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Quirino Dist. (Proj. 2 & 3)", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "R. Magsaysay", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Roxas District", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Sacred Heart", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Salumbato", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Salvacion", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Agustin", "zip_code" => "1117", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Antonio", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Bartolome", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Isidro", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Isidro Labrador", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Jose", "zip_code" => "1115", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Roque", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santol", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "San Vicente", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Sangandaan", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santa Cruz", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santa Lucia", "zip_code" => "1117", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santa Monica", "zip_code" => "1117", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santa Teresita", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Sauyo", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Sienna", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Sikatuna Village", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Silangan", "zip_code" => "1102", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Socorro", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "South Triangle", "zip_code" => "1103", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "St. Ignatius", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "St. Martin De Porres", "zip_code" => "1111", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "St. Peter", "zip_code" => "1114", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santo Cristo", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Santo Nino", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Tagumpay", "zip_code" => "1109", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Talampas", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Talayan", "zip_code" => "1104", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Talipapa", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Tandang Sora", "zip_code" => "1116", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Tatalon", "zip_code" => "1113", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Teachers Village", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Ugong Norte", "zip_code" => "1110", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Unang Sigaw", "zip_code" => "1106", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Univ. of the Phils. PO", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "UP Village", "zip_code" => "1101", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Valencia", "zip_code" => "1112", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Vasra", "zip_code" => "1128", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Veterans Village", "zip_code" => "1105", "barangays" => []],
  ["province" => "QUEZON CITY", "municipality" => "Villa Maria Clara", "zip_code" => "1109", "barangays" => []],

  ["province" => "SAN JUAN CITY", "municipality" => "Eisenhower-Crame", "zip_code" => "1504", "barangays" => []],
  ["province" => "SAN JUAN CITY", "municipality" => "Greenhills North", "zip_code" => "1503", "barangays" => []],
  ["province" => "SAN JUAN CITY", "municipality" => "Greenhills PO", "zip_code" => "1502", "barangays" => []],
  ["province" => "SAN JUAN CITY", "municipality" => "San Juan CPO", "zip_code" => "1500", "barangays" => []],

  ["province" => "TAGUIG CITY", "municipality" => "Bay Breeze Exec. Village", "zip_code" => "1636", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Bicutan", "zip_code" => "1631", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Bicutan Lower", "zip_code" => "1632", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Bicutan Upper", "zip_code" => "1633", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Bicutan Western", "zip_code" => "1630", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Bonifacio Global City", "zip_code" => "1635", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Ligid", "zip_code" => "1638", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Nichols - Mckinley", "zip_code" => "1634", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Tuktukan", "zip_code" => "1637", "barangays" => []],
  ["province" => "TAGUIG CITY", "municipality" => "Ususan", "zip_code" => "1639", "barangays" => []],

  ["province" => "VALENZUELA CITY", "municipality" => "Arkong Bato-Rincon-Pasolo-Malanday-Mabolo-Polo", "zip_code" => "1444", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Balangkas-Caloong", "zip_code" => "1445", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Dalandan - West Canumay", "zip_code" => "1443", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "East Canumay - Lawang Bato Punturin", "zip_code" => "1447", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Fortune Vil. - Paso De Blas - Gen. T. De Leon", "zip_code" => "1442", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Karuhatan", "zip_code" => "1441", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Lingunan", "zip_code" => "1446", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Mapulang Lupa", "zip_code" => "1448", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Valenzuela CPO - Malinta", "zip_code" => "1440", "barangays" => []],
  ["province" => "VALENZUELA CITY", "municipality" => "Valenzuela P.O. Boxes", "zip_code" => "1469", "barangays" => []],
];
