<?php
return [
  ["province" => "AKLAN", "municipality" => "ALTAVAS", "zip_code" => "5616"],
  ["province" => "AKLAN", "municipality" => "BALETE", "zip_code" => "5614"],
  ["province" => "AKLAN", "municipality" => "BANGA", "zip_code" => "5601"],
  ["province" => "AKLAN", "municipality" => "BATAN", "zip_code" => "5615"],
  ["province" => "AKLAN", "municipality" => "BURUANGA", "zip_code" => "5609"],
  ["province" => "AKLAN", "municipality" => "IBAJAY", "zip_code" => "5613"],
  ["province" => "AKLAN", "municipality" => "KALIBO", "zip_code" => "5600"],
  ["province" => "AKLAN", "municipality" => "LEZO", "zip_code" => "5605"],
  ["province" => "AKLAN", "municipality" => "LIBACAO", "zip_code" => "5602"],
  ["province" => "AKLAN", "municipality" => "MADALAG", "zip_code" => "5603"],
  ["province" => "AKLAN", "municipality" => "MAKATO", "zip_code" => "5611"],
  ["province" => "AKLAN", "municipality" => "MALAY", "zip_code" => "5608"],
  ["province" => "AKLAN", "municipality" => "MALINAO", "zip_code" => "5606"],
  ["province" => "AKLAN", "municipality" => "NABAS", "zip_code" => "5607"],
  ["province" => "AKLAN", "municipality" => "NEW WASHINGTON", "zip_code" => "5610"],
  ["province" => "AKLAN", "municipality" => "NUMANCIA", "zip_code" => "5604"],
  ["province" => "AKLAN", "municipality" => "TANGALAN", "zip_code" => "5612"],

  ["province" => "ANTIQUE", "municipality" => "ANINI-Y", "zip_code" => "5717"],
  ["province" => "ANTIQUE", "municipality" => "BARBAZA", "zip_code" => "5706"],
  ["province" => "ANTIQUE", "municipality" => "BELISON", "zip_code" => "5701"],
  ["province" => "ANTIQUE", "municipality" => "BUGASONG", "zip_code" => "5704"],
  ["province" => "ANTIQUE", "municipality" => "CALUYA", "zip_code" => "5711"],
  ["province" => "ANTIQUE", "municipality" => "CULASI", "zip_code" => "5708"],
  ["province" => "ANTIQUE", "municipality" => "HAMTIC", "zip_code" => "5715"],
  ["province" => "ANTIQUE", "municipality" => "LAUA-AN", "zip_code" => "5705"],
  ["province" => "ANTIQUE", "municipality" => "LIBERTAD", "zip_code" => "5710"],
  ["province" => "ANTIQUE", "municipality" => "PANDAN", "zip_code" => "5712"],
  ["province" => "ANTIQUE", "municipality" => "PATNONGON", "zip_code" => "5702"],
  ["province" => "ANTIQUE", "municipality" => "SAN JOSE DE BUANAVISTA", "zip_code" => "5700"],
  ["province" => "ANTIQUE", "municipality" => "SAN REMEGIO", "zip_code" => "5714"],
  ["province" => "ANTIQUE", "municipality" => "SEBASTE", "zip_code" => "5709"],
  ["province" => "ANTIQUE", "municipality" => "SIBALOM", "zip_code" => "5713"],
  ["province" => "ANTIQUE", "municipality" => "TIBIAO", "zip_code" => "5707"],
  ["province" => "ANTIQUE", "municipality" => "TOBIAS FORNIER (DAO)", "zip_code" => "5716"],
  ["province" => "ANTIQUE", "municipality" => "VALDERRAMA", "zip_code" => "5703"],

  ["province" => "CAPIZ", "municipality" => "CUARTERO", "zip_code" => "5811"],
  ["province" => "CAPIZ", "municipality" => "DAO", "zip_code" => "5810"],
  ["province" => "CAPIZ", "municipality" => "DUMALAG", "zip_code" => "5813"],
  ["province" => "CAPIZ", "municipality" => "DUMARAO", "zip_code" => "5812"],
  ["province" => "CAPIZ", "municipality" => "IVISAN", "zip_code" => "5805"],
  ["province" => "CAPIZ", "municipality" => "JAMINDAN", "zip_code" => "5808"],
  ["province" => "CAPIZ", "municipality" => "MAAYON", "zip_code" => "5809"],
  ["province" => "CAPIZ", "municipality" => "MAMBUSAO", "zip_code" => "5807"],
  ["province" => "CAPIZ", "municipality" => "PANAY", "zip_code" => "5801"],
  ["province" => "CAPIZ", "municipality" => "PANITAN", "zip_code" => "5815"],
  ["province" => "CAPIZ", "municipality" => "PILAR", "zip_code" => "5804"],
  ["province" => "CAPIZ", "municipality" => "PRESIDENT ROXAS", "zip_code" => "5803"],
  ["province" => "CAPIZ", "municipality" => "PONTEVEDRA", "zip_code" => "5802"],
  ["province" => "CAPIZ", "municipality" => "ROXAS CITY", "zip_code" => "5800"],
  ["province" => "CAPIZ", "municipality" => "SAPIAN", "zip_code" => "5806"],
  ["province" => "CAPIZ", "municipality" => "SIGMA", "zip_code" => "5816"],
  ["province" => "CAPIZ", "municipality" => "TAPAZ", "zip_code" => "5814"],

  ["province" => "GUIMARAS", "municipality" => "BUENAVISTA", "zip_code" => "5044"],
  ["province" => "GUIMARAS", "municipality" => "JORDAN", "zip_code" => "5045"],
  ["province" => "GUIMARAS", "municipality" => "NUEVA VALENCIA", "zip_code" => "5046"],
  ["province" => "GUIMARAS", "municipality" => "SAN LORENZO", "zip_code" => "5047"],
  ["province" => "GUIMARAS", "municipality" => "SIBUNAG", "zip_code" => "5048"],

  ["province" => "ILOILO", "municipality" => "AJUY", "zip_code" => "5012"],
  ["province" => "ILOILO", "municipality" => "ALIMODIAN", "zip_code" => "5028"],
  ["province" => "ILOILO", "municipality" => "ANILAO", "zip_code" => "5009"],
  ["province" => "ILOILO", "municipality" => "BADIANGAN", "zip_code" => "5033"],
  ["province" => "ILOILO", "municipality" => "BALASAN", "zip_code" => "5018"],
  ["province" => "ILOILO", "municipality" => "BANATE", "zip_code" => "5010"],
  ["province" => "ILOILO", "municipality" => "BAROTAC NUEVO", "zip_code" => "5007"],
  ["province" => "ILOILO", "municipality" => "BAROTAC VIEJO", "zip_code" => "5011"],
  ["province" => "ILOILO", "municipality" => "BATAD", "zip_code" => "5016"],
  ["province" => "ILOILO", "municipality" => "BINGAWAN", "zip_code" => "5041"],
  ["province" => "ILOILO", "municipality" => "CABATUAN", "zip_code" => "5031"],
  ["province" => "ILOILO", "municipality" => "CALINOG", "zip_code" => "5040"],
  ["province" => "ILOILO", "municipality" => "CARLES", "zip_code" => "5019"],
  ["province" => "ILOILO", "municipality" => "CONCEPCION", "zip_code" => "5013"],
  ["province" => "ILOILO", "municipality" => "DINGLE", "zip_code" => "5035"],
  ["province" => "ILOILO", "municipality" => "DUEÑAS", "zip_code" => "5038"],
  ["province" => "ILOILO", "municipality" => "DUMANGAS", "zip_code" => "5006"],
  ["province" => "ILOILO", "municipality" => "ESTANCIA", "zip_code" => "5017"],
  ["province" => "ILOILO", "municipality" => "GUIMBAL", "zip_code" => "5022"],
  ["province" => "ILOILO", "municipality" => "IGBARAS", "zip_code" => "5029"],
  ["province" => "ILOILO", "municipality" => "ILOILO CITY", "zip_code" => "5000"],
  ["province" => "ILOILO", "municipality" => "JANIUAY", "zip_code" => "5034"],
  ["province" => "ILOILO", "municipality" => "LAMBUNAO", "zip_code" => "5042"],
  ["province" => "ILOILO", "municipality" => "LEGANES", "zip_code" => "5003"],
  ["province" => "ILOILO", "municipality" => "LEMERY", "zip_code" => "5043"],
  ["province" => "ILOILO", "municipality" => "LEON", "zip_code" => "5026"],
  ["province" => "ILOILO", "municipality" => "MAASIN", "zip_code" => "5030"],
  ["province" => "ILOILO", "municipality" => "MIAGAO", "zip_code" => "5023"],
  ["province" => "ILOILO", "municipality" => "MINA", "zip_code" => "5032"],
  ["province" => "ILOILO", "municipality" => "NEW LUCENA", "zip_code" => "5005"],
  ["province" => "ILOILO", "municipality" => "OTON", "zip_code" => "5020"],
  ["province" => "ILOILO", "municipality" => "PASSI", "zip_code" => "5037"],
  ["province" => "ILOILO", "municipality" => "PAVIA", "zip_code" => "5001"],
  ["province" => "ILOILO", "municipality" => "POTOTAN", "zip_code" => "5008"],
  ["province" => "ILOILO", "municipality" => "SAN DIONISIO", "zip_code" => "5015"],
  ["province" => "ILOILO", "municipality" => "SAN ENRIQUE", "zip_code" => "5036"],
  ["province" => "ILOILO", "municipality" => "SAN JOAQUIN", "zip_code" => "5024"],
  ["province" => "ILOILO", "municipality" => "SAN MIGUEL", "zip_code" => "5025"],
  ["province" => "ILOILO", "municipality" => "SAN RAFAEL", "zip_code" => "5039"],
  ["province" => "ILOILO", "municipality" => "SANTA BARBARA", "zip_code" => "5002"],
  ["province" => "ILOILO", "municipality" => "SARA", "zip_code" => "5014"],
  ["province" => "ILOILO", "municipality" => "TIGBAUAN", "zip_code" => "5021"],
  ["province" => "ILOILO", "municipality" => "TUBUNGAN", "zip_code" => "5027"],
  ["province" => "ILOILO", "municipality" => "ZARRAGA", "zip_code" => "5004"],

  ["province" => "NEGROS OCCIDENTAL", "municipality" => "BACOLOD CITY", "zip_code" => "6100"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "BAGO CITY", "zip_code" => "6101"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "BINALBAGAN", "zip_code" => "6107"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "CADIZ CITY", "zip_code" => "6121"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "CALATRAVA", "zip_code" => "6126"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "CANDONI", "zip_code" => "6110"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "CAUAYAN", "zip_code" => "6112"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "DON SALVADOR BENEDICTO", "zip_code" => "6133"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "ENRIQUE MAGALONA", "zip_code" => "6118"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "ESCALANTE", "zip_code" => "6124"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "HIMAMAYLAN", "zip_code" => "6108"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "HINIGARAN", "zip_code" => "6106"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "HINOBA-AN (ASIA)", "zip_code" => "6114"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "ILOG", "zip_code" => "6109"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "ISABELA", "zip_code" => "6128"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "KABANKALAN", "zip_code" => "6111"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "LA CARLOTA CITY", "zip_code" => "6130"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "LA CASTELLANA", "zip_code" => "6131"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "MANAPLA", "zip_code" => "6120"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "MOISES PADILLA (MAGALLON)", "zip_code" => "6132"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "MURCIA", "zip_code" => "6129"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "PARAISO (FABRICA)", "zip_code" => "6123"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "PONTEVEDRA", "zip_code" => "6105"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "PULUPANDAN", "zip_code" => "6102"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SAGAY", "zip_code" => "6122"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SAN CARLOS CITY", "zip_code" => "6127"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SAN ENRIQUE", "zip_code" => "6104"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SILAY CITY", "zip_code" => "6116"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SILAY HAWAIIAN CENTRAL", "zip_code" => "6117"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "SIPALAY", "zip_code" => "6113"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "TALISAY", "zip_code" => "6115"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "TOBOSO", "zip_code" => "6125"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "VALLADOLID", "zip_code" => "6103"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "VICTORIAS", "zip_code" => "6119"],
];
