<?php

declare(strict_types=1);

return [
    [
        'province' => 'AKLAN',
        'zip_codes' => [
            ['municipality' => 'ALTAVAS', 'zip_code' => '5616'],
            ['municipality' => 'BALETE', 'zip_code' => '5614'],
            ['municipality' => 'BANGA', 'zip_code' => '5601'],
            ['municipality' => 'BATAN', 'zip_code' => '5615'],
            ['municipality' => 'BURUANGA', 'zip_code' => '5609'],
            ['municipality' => 'IBAJAY', 'zip_code' => '5613'],
            ['municipality' => 'KALIBO', 'zip_code' => '5600'],
            ['municipality' => 'LEZO', 'zip_code' => '5605'],
            ['municipality' => 'LIBACAO', 'zip_code' => '5602'],
            ['municipality' => 'MADALAG', 'zip_code' => '5603'],
            ['municipality' => 'MAKATO', 'zip_code' => '5611'],
            ['municipality' => 'MALAY', 'zip_code' => '5608'],
            ['municipality' => 'MALINAO', 'zip_code' => '5606'],
            ['municipality' => 'NABAS', 'zip_code' => '5607'],
            ['municipality' => 'NEW WASHINGTON', 'zip_code' => '5610'],
            ['municipality' => 'NUMANCIA', 'zip_code' => '5604'],
            ['municipality' => 'TANGALAN', 'zip_code' => '5612'],
        ]
    ],

    [
        'province' => 'ANTIQUE',
        'zip_codes' => [
            ['municipality' => 'ANINI-Y', 'zip_code' => '5717'],
            ['municipality' => 'BARBAZA', 'zip_code' => '5706'],
            ['municipality' => 'BELISON', 'zip_code' => '5701'],
            ['municipality' => 'BUGASONG', 'zip_code' => '5704'],
            ['municipality' => 'CALUYA', 'zip_code' => '5711'],
            ['municipality' => 'CULASI', 'zip_code' => '5708'],
            ['municipality' => 'HAMTIC', 'zip_code' => '5715'],
            ['municipality' => 'LAUA-AN', 'zip_code' => '5705'],
            ['municipality' => 'LIBERTAD', 'zip_code' => '5710'],
            ['municipality' => 'PANDAN', 'zip_code' => '5712'],
            ['municipality' => 'PATNONGON', 'zip_code' => '5702'],
            ['municipality' => 'SAN JOSE DE BUANAVISTA', 'zip_code' => '5700'],
            ['municipality' => 'SAN REMEGIO', 'zip_code' => '5714'],
            ['municipality' => 'SEBASTE', 'zip_code' => '5709'],
            ['municipality' => 'SIBALOM', 'zip_code' => '5713'],
            ['municipality' => 'TIBIAO', 'zip_code' => '5707'],
            ['municipality' => 'TOBIAS FORNIER (DAO)', 'zip_code' => '5716'],
            ['municipality' => 'VALDERRAMA', 'zip_code' => '5703'],
        ]
    ],

    [
        'province' => 'CAPIZ',
        'zip_codes' => [
            ['municipality' => 'CUARTERO', 'zip_code' => '5811'],
            ['municipality' => 'DAO', 'zip_code' => '5810'],
            ['municipality' => 'DUMALAG', 'zip_code' => '5813'],
            ['municipality' => 'DUMARAO', 'zip_code' => '5812'],
            ['municipality' => 'IVISAN', 'zip_code' => '5805'],
            ['municipality' => 'JAMINDAN', 'zip_code' => '5808'],
            ['municipality' => 'MAAYON', 'zip_code' => '5809'],
            ['municipality' => 'MAMBUSAO', 'zip_code' => '5807'],
            ['municipality' => 'PANAY', 'zip_code' => '5801'],
            ['municipality' => 'PANITAN', 'zip_code' => '5815'],
            ['municipality' => 'PILAR', 'zip_code' => '5804'],
            ['municipality' => 'PRESIDENT ROXAS', 'zip_code' => '5803'],
            ['municipality' => 'PONTEVEDRA', 'zip_code' => '5802'],
            ['municipality' => 'ROXAS CITY', 'zip_code' => '5800'],
            ['municipality' => 'SAPIAN', 'zip_code' => '5806'],
            ['municipality' => 'SIGMA', 'zip_code' => '5816'],
            ['municipality' => 'TAPAZ', 'zip_code' => '5814'],
        ]
    ],

    [
        'province' => 'GUIMARAS',
        'zip_codes' => [
            ['municipality' => 'BUENAVISTA', 'zip_code' => '5044'],
            ['municipality' => 'JORDAN', 'zip_code' => '5045'],
            ['municipality' => 'NUEVA VALENCIA', 'zip_code' => '5046'],
            ['municipality' => 'SAN LORENZO', 'zip_code' => '5047'],
            ['municipality' => 'SIBUNAG', 'zip_code' => '5048'],
        ]
    ],

    [
        'province' => 'ILOILO',
        'zip_codes' => [
            ['municipality' => 'AJUY', 'zip_code' => '5012'],
            ['municipality' => 'ALIMODIAN', 'zip_code' => '5028'],
            ['municipality' => 'ANILAO', 'zip_code' => '5009'],
            ['municipality' => 'BADIANGAN', 'zip_code' => '5033'],
            ['municipality' => 'BALASAN', 'zip_code' => '5018'],
            ['municipality' => 'BANATE', 'zip_code' => '5010'],
            ['municipality' => 'BAROTAC NUEVO', 'zip_code' => '5007'],
            ['municipality' => 'BAROTAC VIEJO', 'zip_code' => '5011'],
            ['municipality' => 'BATAD', 'zip_code' => '5016'],
            ['municipality' => 'BINGAWAN', 'zip_code' => '5041'],
            ['municipality' => 'CABATUAN', 'zip_code' => '5031'],
            ['municipality' => 'CALINOG', 'zip_code' => '5040'],
            ['municipality' => 'CARLES', 'zip_code' => '5019'],
            ['municipality' => 'CONCEPCION', 'zip_code' => '5013'],
            ['municipality' => 'DINGLE', 'zip_code' => '5035'],
            ['municipality' => 'DUEÑAS', 'zip_code' => '5038'],
            ['municipality' => 'DUMANGAS', 'zip_code' => '5006'],
            ['municipality' => 'ESTANCIA', 'zip_code' => '5017'],
            ['municipality' => 'GUIMBAL', 'zip_code' => '5022'],
            ['municipality' => 'IGBARAS', 'zip_code' => '5029'],
            ['municipality' => 'ILOILO CITY', 'zip_code' => '5000'],
            ['municipality' => 'JANIUAY', 'zip_code' => '5034'],
            ['municipality' => 'LAMBUNAO', 'zip_code' => '5042'],
            ['municipality' => 'LEGANES', 'zip_code' => '5003'],
            ['municipality' => 'LEMERY', 'zip_code' => '5043'],
            ['municipality' => 'LEON', 'zip_code' => '5026'],
            ['municipality' => 'MAASIN', 'zip_code' => '5030'],
            ['municipality' => 'MIAGAO', 'zip_code' => '5023'],
            ['municipality' => 'MINA', 'zip_code' => '5032'],
            ['municipality' => 'NEW LUCENA', 'zip_code' => '5005'],
            ['municipality' => 'OTON', 'zip_code' => '5020'],
            ['municipality' => 'PASSI', 'zip_code' => '5037'],
            ['municipality' => 'PAVIA', 'zip_code' => '5001'],
            ['municipality' => 'POTOTAN', 'zip_code' => '5008'],
            ['municipality' => 'SAN DIONISIO', 'zip_code' => '5015'],
            ['municipality' => 'SAN ENRIQUE', 'zip_code' => '5036'],
            ['municipality' => 'SAN JOAQUIN', 'zip_code' => '5024'],
            ['municipality' => 'SAN MIGUEL', 'zip_code' => '5025'],
            ['municipality' => 'SAN RAFAEL', 'zip_code' => '5039'],
            ['municipality' => 'SANTA BARBARA', 'zip_code' => '5002'],
            ['municipality' => 'SARA', 'zip_code' => '5014'],
            ['municipality' => 'TIGBAUAN', 'zip_code' => '5021'],
            ['municipality' => 'TUBUNGAN', 'zip_code' => '5027'],
            ['municipality' => 'ZARRAGA', 'zip_code' => '5004'],
        ]
    ],

    [
        'province' => 'NEGROS OCCIDENTAL',
        'zip_codes' => [
            ['municipality' => 'BACOLOD CITY', 'zip_code' => '6100'],
            ['municipality' => 'BAGO CITY', 'zip_code' => '6101'],
            ['municipality' => 'BINALBAGAN', 'zip_code' => '6107'],
            ['municipality' => 'CADIZ CITY', 'zip_code' => '6121'],
            ['municipality' => 'CALATRAVA', 'zip_code' => '6126'],
            ['municipality' => 'CANDONI', 'zip_code' => '6110'],
            ['municipality' => 'CAUAYAN', 'zip_code' => '6112'],
            ['municipality' => 'DON SALVADOR BENEDICTO', 'zip_code' => '6133'],
            ['municipality' => 'ENRIQUE MAGALONA', 'zip_code' => '6118'],
            ['municipality' => 'ESCALANTE', 'zip_code' => '6124'],
            ['municipality' => 'HIMAMAYLAN', 'zip_code' => '6108'],
            ['municipality' => 'HINIGARAN', 'zip_code' => '6106'],
            ['municipality' => 'HINOBA-AN (ASIA)', 'zip_code' => '6114'],
            ['municipality' => 'ILOG', 'zip_code' => '6109'],
            ['municipality' => 'ISABELA', 'zip_code' => '6128'],
            ['municipality' => 'KABANKALAN', 'zip_code' => '6111'],
            ['municipality' => 'LA CARLOTA CITY', 'zip_code' => '6130'],
            ['municipality' => 'LA CASTELLANA', 'zip_code' => '6131'],
            ['municipality' => 'MANAPLA', 'zip_code' => '6120'],
            ['municipality' => 'MOISES PADILLA (MAGALLON)', 'zip_code' => '6132'],
            ['municipality' => 'MURCIA', 'zip_code' => '6129'],
            ['municipality' => 'PARAISO (FABRICA)', 'zip_code' => '6123'],
            ['municipality' => 'PONTEVEDRA', 'zip_code' => '6105'],
            ['municipality' => 'PULUPANDAN', 'zip_code' => '6102'],
            ['municipality' => 'SAGAY', 'zip_code' => '6122'],
            ['municipality' => 'SAN CARLOS CITY', 'zip_code' => '6127'],
            ['municipality' => 'SAN ENRIQUE', 'zip_code' => '6104'],
            ['municipality' => 'SILAY CITY', 'zip_code' => '6116'],
            ['municipality' => 'SILAY HAWAIIAN CENTRAL', 'zip_code' => '6117'],
            ['municipality' => 'SIPALAY', 'zip_code' => '6113'],
            ['municipality' => 'TALISAY', 'zip_code' => '6115'],
            ['municipality' => 'TOBOSO', 'zip_code' => '6125'],
            ['municipality' => 'VALLADOLID', 'zip_code' => '6103'],
            ['municipality' => 'VICTORIAS', 'zip_code' => '6119'],
        ]
    ],
];
