<?php

declare(strict_types=1);
return [
    [
        'province' => 'ALBAY',
        'zip_codes' => [
            ['municipality' => 'BACACAY', 'zip_code' => '4509'],
            ['municipality' => 'CAMALIG', 'zip_code' => '4502'],
            ['municipality' => 'DARAGA (LOCSIN)', 'zip_code' => '4501'],
            ['municipality' => 'GUINOBATAN', 'zip_code' => '4503'],
            ['municipality' => 'JOVELLAR', 'zip_code' => '4515'],
            ['municipality' => 'LEGAZPI CITY', 'zip_code' => '4500'],
            ['municipality' => 'LIBON', 'zip_code' => '4507'],
            ['municipality' => 'LIGAO', 'zip_code' => '4504'],
            ['municipality' => 'MALILIPOT', 'zip_code' => '4510'],
            ['municipality' => 'MALINAO', 'zip_code' => '4512'],
            ['municipality' => 'MANITO', 'zip_code' => '4514'],
            ['municipality' => 'OAS', 'zip_code' => '4505'],
            ['municipality' => 'PIO DURAN (MALACBALAC)', 'zip_code' => '4516'],
            ['municipality' => 'POLANGUI', 'zip_code' => '4506'],
            ['municipality' => 'RAPU-RAPU', 'zip_code' => '4517'],
            ['municipality' => 'STO. DOMINGO', 'zip_code' => '4508'],
            ['municipality' => 'TABACO', 'zip_code' => '4511'],
            ['municipality' => 'TIWI', 'zip_code' => '4513'],
        ]
    ],

    [
        'province' => 'CAMARINES NORTE',
        'zip_codes' => [
            ['municipality' => 'BASUD', 'zip_code' => '4608'],
            ['municipality' => 'CAPALONGA', 'zip_code' => '4607'],
            ['municipality' => 'DAET', 'zip_code' => '4600'],
            ['municipality' => 'SAN LORENZO RUIZ (FORMERLY IMELDA)', 'zip_code' => '4610'],
            ['municipality' => 'JOSE PANGANIBAN', 'zip_code' => '4606'],
            ['municipality' => 'LABO', 'zip_code' => '4604'],
            ['municipality' => 'MERCEDES', 'zip_code' => '4601'],
            ['municipality' => 'PARACALE', 'zip_code' => '4605'],
            ['municipality' => 'SAN VICENTE', 'zip_code' => '4609'],
            ['municipality' => 'STA. ELENA', 'zip_code' => '4611'],
            ['municipality' => 'TALISAY', 'zip_code' => '4602'],
            ['municipality' => 'TULAY NA LUPA', 'zip_code' => '4612'],
            ['municipality' => 'VINZONS', 'zip_code' => '4603'],
        ]
    ],

    [
        'province' => 'CAMARINES SUR',
        'zip_codes' => [
            ['municipality' => 'BAAO', 'zip_code' => '4432'],
            ['municipality' => 'BALATAN', 'zip_code' => '4436'],
            ['municipality' => 'BATO', 'zip_code' => '4435'],
            ['municipality' => 'BOMBON', 'zip_code' => '4404'],
            ['municipality' => 'BUHI', 'zip_code' => '4433'],
            ['municipality' => 'BULA', 'zip_code' => '4430'],
            ['municipality' => 'CABUSAO', 'zip_code' => '4406'],
            ['municipality' => 'CALABANGA', 'zip_code' => '4405'],
            ['municipality' => 'CAMALIGAN', 'zip_code' => '4401'],
            ['municipality' => 'CANAMAN', 'zip_code' => '4402'],
            ['municipality' => 'CARAMOAN', 'zip_code' => '4429'],
            ['municipality' => 'DEL GALLEGO', 'zip_code' => '4411'],
            ['municipality' => 'GAINZA', 'zip_code' => '4412'],
            ['municipality' => 'GARCHITORENA', 'zip_code' => '4428'],
            ['municipality' => 'GOA', 'zip_code' => '4422'],
            ['municipality' => 'IRIGA CITY', 'zip_code' => '4431'],
            ['municipality' => 'LAGONOY', 'zip_code' => '4425'],
            ['municipality' => 'LIBMANAN', 'zip_code' => '4407'],
            ['municipality' => 'LUPI', 'zip_code' => '4409'],
            ['municipality' => 'MAGARAO', 'zip_code' => '4403'],
            ['municipality' => 'MILAOR', 'zip_code' => '4413'],
            ['municipality' => 'MINALABAC', 'zip_code' => '4414'],
            ['municipality' => 'NABUA', 'zip_code' => '4434'],
            ['municipality' => 'NAGA CITY', 'zip_code' => '4400'],
            ['municipality' => 'OCAMPO', 'zip_code' => '4419'],
            ['municipality' => 'PAMPLONA', 'zip_code' => '4416'],
            ['municipality' => 'PASACAO', 'zip_code' => '4417'],
            ['municipality' => 'PILI', 'zip_code' => '4418'],
            ['municipality' => 'PRESENTACION', 'zip_code' => '4424'],
            ['municipality' => 'RAGAY', 'zip_code' => '4410'],
            ['municipality' => 'SAGNAY', 'zip_code' => '4421'],
            ['municipality' => 'SAN FERNANDO', 'zip_code' => '4415'],
            ['municipality' => 'SAN JOSE', 'zip_code' => '4423'],
            ['municipality' => 'SIPOCOT', 'zip_code' => '4408'],
            ['municipality' => 'SIRUMA', 'zip_code' => '4427'],
            ['municipality' => 'TIGAON', 'zip_code' => '4420'],
            ['municipality' => 'TINAMBAC', 'zip_code' => '4426'],
        ]
    ],

    [
        'province' => 'CATANDUANES',
        'zip_codes' => [
            ['municipality' => 'BAGAMANOC', 'zip_code' => '4807'],
            ['municipality' => 'BARAS', 'zip_code' => '4803'],
            ['municipality' => 'BATO', 'zip_code' => '4801'],
            ['municipality' => 'CARAMORAN', 'zip_code' => '4808'],
            ['municipality' => 'GIGMOTO', 'zip_code' => '4804'],
            ['municipality' => 'PANDAN', 'zip_code' => '4809'],
            ['municipality' => 'PANGANIBAN', 'zip_code' => '4806'],
            ['municipality' => 'SAN ANDRES', 'zip_code' => '4810'],
            ['municipality' => 'SAN MIGUEL', 'zip_code' => '4802'],
            ['municipality' => 'VIGA', 'zip_code' => '4805'],
            ['municipality' => 'VIRAC', 'zip_code' => '4800'],
        ]
    ],

    [
        'province' => 'MASBATE',
        'zip_codes' => [
            ['municipality' => 'AROROY', 'zip_code' => '5414'],
            ['municipality' => 'BALENO', 'zip_code' => '5413'],
            ['municipality' => 'BALUD', 'zip_code' => '5412'],
            ['municipality' => 'BATUAN', 'zip_code' => '5415'],
            ['municipality' => 'BUENAVISTA', 'zip_code' => '5421'],
            ['municipality' => 'CATAINGAN', 'zip_code' => '5405'],
            ['municipality' => 'CAWAYAN', 'zip_code' => '5409'],
            ['municipality' => 'CLAVERIA', 'zip_code' => '5419'],
            ['municipality' => 'DIMASALANG', 'zip_code' => '5403'],
            ['municipality' => 'ESPERANZA', 'zip_code' => '5407'],
            ['municipality' => 'MANDAON', 'zip_code' => '5411'],
            ['municipality' => 'MASBATE', 'zip_code' => '5400'],
            ['municipality' => 'MILAGROS', 'zip_code' => '5410'],
            ['municipality' => 'MOBO', 'zip_code' => '5401'],
            ['municipality' => 'MONREAL ', 'zip_code' => '5418'],
            ['municipality' => 'PALANAS', 'zip_code' => '5404'],
            ['municipality' => 'PIO V. CORPUZ', 'zip_code' => '5406'],
            ['municipality' => 'PLACER', 'zip_code' => '5408'],
            ['municipality' => 'SAN FERNANDO', 'zip_code' => '5416'],
            ['municipality' => 'SAN JACINTO', 'zip_code' => '5417'],
            ['municipality' => 'SAN PASCUAL', 'zip_code' => '5420'],
            ['municipality' => 'USON', 'zip_code' => '5402'],
        ]
    ],

    [
        'province' => 'SORSOGON',
        'zip_codes' => [
            ['municipality' => 'BACON', 'zip_code' => '4701'],
            ['municipality' => 'BARCELONA', 'zip_code' => '4712'],
            ['municipality' => 'BULAN', 'zip_code' => '4706'],
            ['municipality' => 'BULUSAN', 'zip_code' => '4704'],
            ['municipality' => 'CASIGURAN', 'zip_code' => '4702'],
            ['municipality' => 'CASTILLA', 'zip_code' => '4713'],
            ['municipality' => 'DONSOL', 'zip_code' => '4715'],
            ['municipality' => 'GUBAT', 'zip_code' => '4710'],
            ['municipality' => 'IROSIN', 'zip_code' => '4707'],
            ['municipality' => 'JUBAN', 'zip_code' => '4703'],
            ['municipality' => 'MAGALLANES', 'zip_code' => '4705'],
            ['municipality' => 'MATNOG', 'zip_code' => '4708'],
            ['municipality' => 'PILAR', 'zip_code' => '4714'],
            ['municipality' => 'PRIETO DIAZ', 'zip_code' => '4711'],
            ['municipality' => 'SORSOGON', 'zip_code' => '4700'],
            ['municipality' => 'STA. MAGDALENA', 'zip_code' => '4709'],
        ]
    ],
];
