<?php
return [
  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "BALER", "zip_code" => "3200"],
      ["municipality" => "CASIGURAN", "zip_code" => "3204"],
      ["municipality" => "DILASAG", "zip_code" => "3205"],
      ["municipality" => "DINALUNGAN", "zip_code" => "3206"],
      ["municipality" => "DINGALAN", "zip_code" => "3207"],
      ["municipality" => "DIPACULAO", "zip_code" => "3203"],
      ["municipality" => "MARIA AURORA", "zip_code" => "3202"],
      ["municipality" => "SAN LUIS", "zip_code" => "3201"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "ABUCAY", "zip_code" => "2114"],
      ["municipality" => "CABCABEN", "zip_code" => "2109"],
      ["municipality" => "BAGAC", "zip_code" => "2107"],
      ["municipality" => "BALANGA", "zip_code" => "2100"],
      ["municipality" => "FAB (FREEFORT AREA OF  BATAAN) ", "zip_code" => "2106"],
      ["municipality" => "DINALUPIHAN", "zip_code" => "2110"],
      ["municipality" => "HERMOSA", "zip_code" => "2111"],
      ["municipality" => "LAMAO", "zip_code" => "2104"],
      ["municipality" => "LIMAY", "zip_code" => "2103"],
      ["municipality" => "MARIVELES", "zip_code" => "2105"],
      ["municipality" => "MORONG", "zip_code" => "2108"],
      ["municipality" => "ORANI", "zip_code" => "2112"],
      ["municipality" => "ORION", "zip_code" => "2102"],
      ["municipality" => "PILAR", "zip_code" => "2101"],
      ["municipality" => "SAMAL", "zip_code" => "2113"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "ANGAT", "zip_code" => "3012"],
      ["municipality" => "BALAGTAS", "zip_code" => "3016"],
      ["municipality" => "BALIUAG", "zip_code" => "3006"],
      ["municipality" => "BOCAUE", "zip_code" => "3018"],
      ["municipality" => "BULACAN", "zip_code" => "3017"],
      ["municipality" => "BUSTOS", "zip_code" => "3007"],
      ["municipality" => "CALUMPIT", "zip_code" => "3003"],
      ["municipality" => "CRUZ NA DAAN", "zip_code" => "3025"],
      ["municipality" => "DOÑA REMEDIOS TRINIDAD", "zip_code" => "3009"],
      ["municipality" => "GUIGUINTO", "zip_code" => "3015"],
      ["municipality" => "HAGONOY", "zip_code" => "3002"],
      ["municipality" => "MALOLOS", "zip_code" => "3000"],
      ["municipality" => "MARILAO", "zip_code" => "3019"],
      ["municipality" => "MEYCAUAYAN", "zip_code" => "3020"],
      ["municipality" => "NORZAGARAY", "zip_code" => "3013"],
      ["municipality" => "OBANDO", "zip_code" => "3021"],
      ["municipality" => "PANDI", "zip_code" => "3014"],
      ["municipality" => "PAOMBONG", "zip_code" => "3001"],
      ["municipality" => "PLARIDEL", "zip_code" => "3004"],
      ["municipality" => "PULILAN", "zip_code" => "3005"],
      ["municipality" => "SAN ILDEFONSO", "zip_code" => "3010"],
      ["municipality" => "SAN JOSE DEL MONTE", "zip_code" => "3023"],
      ["municipality" => "SAN MIGUEL", "zip_code" => "3011"],
      ["municipality" => "SAN RAFAEL", "zip_code" => "3008"],
      ["municipality" => "SAPANG PALAY", "zip_code" => "3024"],
      ["municipality" => "STA. MARIA", "zip_code" => "3022"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "ALIAGA", "zip_code" => "3111"],
      ["municipality" => "BONGABON", "zip_code" => "3128"],
      ["municipality" => "CABANATUAN CITY", "zip_code" => "3100"],
      ["municipality" => "CABIAO", "zip_code" => "3107"],
      ["municipality" => "CARRANGALAN", "zip_code" => "3123"],
      ["municipality" => "CENTRAL LUZON STATE UNIVERSITY", "zip_code" => "3120"],
      ["municipality" => "CUYAPO", "zip_code" => "3117"],
      ["municipality" => "FORT MAGSAYSAY", "zip_code" => "3130"],
      ["municipality" => "GABALDON", "zip_code" => "3131"],
      ["municipality" => "GAPAN CITY", "zip_code" => "3105"],
      ["municipality" => "GEN. M. NATIVIDAD", "zip_code" => "3125"],
      ["municipality" => "GEN. TINIO", "zip_code" => "3104"],
      ["municipality" => "GUIMBA", "zip_code" => "3115"],
      ["municipality" => "JAEN", "zip_code" => "3109"],
      ["municipality" => "LAUR", "zip_code" => "3129"],
      ["municipality" => "LICAB", "zip_code" => "3112"],
      ["municipality" => "LLANERA", "zip_code" => "3126"],
      ["municipality" => "LUPAO", "zip_code" => "3122"],
      ["municipality" => "MUÑOZ", "zip_code" => "3119"],
      ["municipality" => "NAMPICUAN", "zip_code" => "3116"],
      ["municipality" => "PALAYAN CITY", "zip_code" => "3132"],
      ["municipality" => "PANTABANGAN", "zip_code" => "3124"],
      ["municipality" => "PEÑARANDA", "zip_code" => "3103"],
      ["municipality" => "QUEZON", "zip_code" => "3113"],
      ["municipality" => "RIZAL", "zip_code" => "3127"],
      ["municipality" => "SAN ANTONIO", "zip_code" => "3108"],
      ["municipality" => "SAN ISIDRO", "zip_code" => "3106"],
      ["municipality" => "SAN JOSE CITY", "zip_code" => "3121"],
      ["municipality" => "SAN LEONARDO", "zip_code" => "3102"],
      ["municipality" => "STA. ROSA", "zip_code" => "3101"],
      ["municipality" => "STO. DOMINGO", "zip_code" => "3133"],
      ["municipality" => "TALAVERA", "zip_code" => "3114"],
      ["municipality" => "TALUGTOG", "zip_code" => "3118"],
      ["municipality" => "ZARAGOZA", "zip_code" => "3110"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "ANGELES CITY", "zip_code" => "2009"],
      ["municipality" => "APALIT", "zip_code" => "2016"],
      ["municipality" => "ARAYAT", "zip_code" => "2012"],
      ["municipality" => "BACOLOR", "zip_code" => "2001"],
      ["municipality" => "BALIBAGO", "zip_code" => "2024"],
      ["municipality" => "BASA AIRBASE", "zip_code" => "2007"],
      ["municipality" => "CANDABA", "zip_code" => "2013"],
      ["municipality" => "CSEZ, CLARK", "zip_code" => "2023"],
      ["municipality" => "DAU, MABALACAT", "zip_code" => "2026"],
      ["municipality" => "FLORIDABLANCA", "zip_code" => "2006"],
      ["municipality" => "GUAGUA", "zip_code" => "2003"],
      ["municipality" => "LUBAO", "zip_code" => "2005"],
      ["municipality" => "MABALACAT", "zip_code" => "2010"],
      ["municipality" => "MACABEBE", "zip_code" => "2018"],
      ["municipality" => "MAGALANG", "zip_code" => "2011"],
      ["municipality" => "MASANTOL", "zip_code" => "2017"],
      ["municipality" => "MEXICO", "zip_code" => "2021"],
      ["municipality" => "MINALIN", "zip_code" => "2019"],
      ["municipality" => "PORAC", "zip_code" => "2008"],
      ["municipality" => "SAN FERNANDO", "zip_code" => "2000"],
      ["municipality" => "SAN LUIS", "zip_code" => "2014"],
      ["municipality" => "SAN SIMON", "zip_code" => "2015"],
      ["municipality" => "SASMUAN", "zip_code" => "2004"],
      ["municipality" => "SANTA ANA", "zip_code" => "2022"],
      ["municipality" => "SANTA CRUZ, LUBAO", "zip_code" => "2025"],
      ["municipality" => "SANTA RITA", "zip_code" => "2002"],
      ["municipality" => "SANTO TOMAS", "zip_code" => "2020"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "ANAO", "zip_code" => "2310"],
      ["municipality" => "BAMBAN", "zip_code" => "2317"],
      ["municipality" => "CAMILING", "zip_code" => "2306"],
      ["municipality" => "CAPAS", "zip_code" => "2315"],
      ["municipality" => "CONCEPCION", "zip_code" => "2316"],
      ["municipality" => "GERONA", "zip_code" => "2302"],
      ["municipality" => "LA PAZ", "zip_code" => "2314"],
      ["municipality" => "MAYANTOC", "zip_code" => "2304"],
      ["municipality" => "MONCADA", "zip_code" => "2308"],
      ["municipality" => "PANIQUI", "zip_code" => "2307"],
      ["municipality" => "PURA", "zip_code" => "2312"],
      ["municipality" => "RAMOS", "zip_code" => "2311"],
      ["municipality" => "SAN CLEMENTE", "zip_code" => "2305"],
      ["municipality" => "SAN JOSE", "zip_code" => "2318"],
      ["municipality" => "SAN MANUEL", "zip_code" => "2309"],
      ["municipality" => "SAN MIGUEL", "zip_code" => "2301"],
      ["municipality" => "STA. IGNACIA", "zip_code" => "2303"],
      ["municipality" => "TARLAC", "zip_code" => "2300"],
      ["municipality" => "VICTORIA", "zip_code" => "2313"],
    ]
  ],

  [
    "province" => "BATANES",
    "zip_codes" => [
      ["municipality" => "BOTOLAN", "zip_code" => "2202"],
      ["municipality" => "CABANGAN", "zip_code" => "2203"],
      ["municipality" => "CANDELARIA", "zip_code" => "2212"],
      ["municipality" => "CASTILLEJOS", "zip_code" => "2208"],
      ["municipality" => "IBA", "zip_code" => "2201"],
      ["municipality" => "MASINLOC", "zip_code" => "2211"],
      ["municipality" => "OLONGAPO CITY", "zip_code" => "2200"],
      ["municipality" => "PALAUIG", "zip_code" => "2210"],
      ["municipality" => "SAN ANTONIO", "zip_code" => "2206"],
      ["municipality" => "SAN FELIPE", "zip_code" => "2204"],
      ["municipality" => "SAN MARCELINO", "zip_code" => "2207"],
      ["municipality" => "SAN NARCISO", "zip_code" => "2205"],
      ["municipality" => "STA. CRUZ", "zip_code" => "2213"],
      ["municipality" => "SUBIC", "zip_code" => "2209"],
    ]
  ]
];
