<?php
return [
  ["province" => "BASILAN", "municipality" => "AKBAR", "zip_code" => "7307"],
  ["province" => "BASILAN", "municipality" => "AL-BARKA", "zip_code" => "7308"],
  ["province" => "BASILAN", "municipality" => "HADJI MOHAMMAD AJUL", "zip_code" => "7309"],
  ["province" => "BASILAN", "municipality" => "HADJI MUHTAMAD", "zip_code" => "7310"],
  ["province" => "BASILAN", "municipality" => "ISABELA DE BASILAN", "zip_code" => "7300"],
  ["province" => "BASILAN", "municipality" => "LAMITAN", "zip_code" => "7302"],
  ["province" => "BASILAN", "municipality" => "LANTAWAN", "zip_code" => "7301"],
  ["province" => "BASILAN", "municipality" => "MALUSO", "zip_code" => "7303"],
  ["province" => "BASILAN", "municipality" => "SUMISIP", "zip_code" => "7305"],
  ["province" => "BASILAN", "municipality" => "TABUAN-LASA", "zip_code" => "7312"],
  ["province" => "BASILAN", "municipality" => "TIPO-TIPO", "zip_code" => "7304"],
  ["province" => "BASILAN", "municipality" => "TUBURAN", "zip_code" => "7306"],
  ["province" => "BASILAN", "municipality" => "UNGKAYA PUKAN", "zip_code" => "7311"],

  ["province" => "LANAO DEL SUR", "municipality" => "BACOLOD GRANDE", "zip_code" => "9316"],
  ["province" => "LANAO DEL SUR", "municipality" => "BALABAGAN", "zip_code" => "9302"],
  ["province" => "LANAO DEL SUR", "municipality" => "BAYANG", "zip_code" => "9309"],
  ["province" => "LANAO DEL SUR", "municipality" => "BALINDONG", "zip_code" => "9318"],
  ["province" => "LANAO DEL SUR", "municipality" => "BINIDAYAN", "zip_code" => "9310"],
  ["province" => "LANAO DEL SUR", "municipality" => "BUADIPOSO BUNTONG", "zip_code" => "9714"],
  ["province" => "LANAO DEL SUR", "municipality" => "BUBONG", "zip_code" => "9708"],
  ["province" => "LANAO DEL SUR", "municipality" => "BUMBARAN", "zip_code" => "9320"],
  ["province" => "LANAO DEL SUR", "municipality" => "BUTIG", "zip_code" => "9305"],
  ["province" => "LANAO DEL SUR", "municipality" => "CALANOGAS", "zip_code" => "9319"],
  ["province" => "LANAO DEL SUR", "municipality" => "GANASSI", "zip_code" => "9311"],
  ["province" => "LANAO DEL SUR", "municipality" => "KAPAI", "zip_code" => "9709"],
  ["province" => "LANAO DEL SUR", "municipality" => "KAPATAGAN", "zip_code" => "9322"],
  ["province" => "LANAO DEL SUR", "municipality" => "LUMBA BAYABAO", "zip_code" => "9703"],
  ["province" => "LANAO DEL SUR", "municipality" => "LUMBACA UNAYAN", "zip_code" => "9323"],
  ["province" => "LANAO DEL SUR", "municipality" => "LUMBATAN", "zip_code" => "9307"],
  ["province" => "LANAO DEL SUR", "municipality" => "LUMBAYANAGUE", "zip_code" => "9306"],
  ["province" => "LANAO DEL SUR", "municipality" => "MACADOR ANDONG", "zip_code" => "9308"],
  ["province" => "LANAO DEL SUR", "municipality" => "MADALUM", "zip_code" => "9315"],
  ["province" => "LANAO DEL SUR", "municipality" => "MADAMBA", "zip_code" => "9314"],
  ["province" => "LANAO DEL SUR", "municipality" => "MAGUING", "zip_code" => "9715"],
  ["province" => "LANAO DEL SUR", "municipality" => "MALABANG", "zip_code" => "9300"],
  ["province" => "LANAO DEL SUR", "municipality" => "MARANTAO", "zip_code" => "9711"],
  ["province" => "LANAO DEL SUR", "municipality" => "MARAWI CITY", "zip_code" => "9700"],
  ["province" => "LANAO DEL SUR", "municipality" => "MAROGONG", "zip_code" => "9303"],
  ["province" => "LANAO DEL SUR", "municipality" => "MASIU", "zip_code" => "9706"],
  ["province" => "LANAO DEL SUR", "municipality" => "MULONDO", "zip_code" => "9702"],
  ["province" => "LANAO DEL SUR", "municipality" => "PAGAYAWAN", "zip_code" => "9312"],
  ["province" => "LANAO DEL SUR", "municipality" => "PIAGAPO", "zip_code" => "9710"],
  ["province" => "LANAO DEL SUR", "municipality" => "PICONG (FORMERLY SULTAN GUMANDER)", "zip_code" => "9301"],
  ["province" => "LANAO DEL SUR", "municipality" => "POONA BAYABAO", "zip_code" => "9705"],
  ["province" => "LANAO DEL SUR", "municipality" => "PUALAS", "zip_code" => "9313"],
  ["province" => "LANAO DEL SUR", "municipality" => "RAMAIN-DITSAAN", "zip_code" => "9713"],
  ["province" => "LANAO DEL SUR", "municipality" => "SAGUIARAN", "zip_code" => "9701"],
  ["province" => "LANAO DEL SUR", "municipality" => "SULTAN DOMALONDONG", "zip_code" => "9324"],
  ["province" => "LANAO DEL SUR", "municipality" => "SULTAN GUMANDER", "zip_code" => "9301"],
  ["province" => "LANAO DEL SUR", "municipality" => "TAGOLOAN II", "zip_code" => "9321"],
  ["province" => "LANAO DEL SUR", "municipality" => "TAMPARAN", "zip_code" => "9704"],
  ["province" => "LANAO DEL SUR", "municipality" => "TARAKA", "zip_code" => "9712"],
  ["province" => "LANAO DEL SUR", "municipality" => "TUBARAN", "zip_code" => "9304"],
  ["province" => "LANAO DEL SUR", "municipality" => "TUGAYA", "zip_code" => "9317"],
  ["province" => "LANAO DEL SUR", "municipality" => "WAO", "zip_code" => "9716"],

  ["province" => "MAGUINDANAO", "municipality" => "AMPATUAN", "zip_code" => "9609"],
  ["province" => "MAGUINDANAO", "municipality" => "BARIRA", "zip_code" => "9614"],
  ["province" => "MAGUINDANAO", "municipality" => "BULDON", "zip_code" => "9615"],
  ["province" => "MAGUINDANAO", "municipality" => "BULUAN", "zip_code" => "9616"],
  ["province" => "MAGUINDANAO", "municipality" => "COTABATO CITY", "zip_code" => "9600"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU ODIN SINSUAT (DINAIG)", "zip_code" => "9601"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU PAGLAS", "zip_code" => "9617"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU PIANG", "zip_code" => "9607"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU ABDULLAH SANGKI", "zip_code" => "9621"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU ANGGAL MIDTIMBANG", "zip_code" => "9622"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU BLAH T. SINSUAT", "zip_code" => "9623"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU HOFFER AMPATUAN", "zip_code" => "9624"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU MONTAWAL (FORMERLY PAGAGAWAN)", "zip_code" => "9631"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU SALIBO", "zip_code" => "9625"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU SAUDI-AMPATUAN", "zip_code" => "9626"],
  ["province" => "MAGUINDANAO", "municipality" => "DATU UNSAY", "zip_code" => "9627"],
  ["province" => "MAGUINDANAO", "municipality" => "GENERAL SALIPADA K. PENDATUN", "zip_code" => "9618"],
  ["province" => "MAGUINDANAO", "municipality" => "GUINDULUNGAN", "zip_code" => "9628"],
  ["province" => "MAGUINDANAO", "municipality" => "KABUNTULAN", "zip_code" => "9606"],
  ["province" => "MAGUINDANAO", "municipality" => "SHARIFF AGUAK (FORMERLY MAGANOY)", "zip_code" => "9608"],
  ["province" => "MAGUINDANAO", "municipality" => "MAMASAPANO", "zip_code" => "9629"],
  ["province" => "MAGUINDANAO", "municipality" => "MANGUDADATU", "zip_code" => "9620"],
  ["province" => "MAGUINDANAO", "municipality" => "MATANOG", "zip_code" => "9613"],
  ["province" => "MAGUINDANAO", "municipality" => "NORTHERN KABUNTALAN", "zip_code" => "9630"],
  ["province" => "MAGUINDANAO", "municipality" => "PAGLAT", "zip_code" => "9632"],
  ["province" => "MAGUINDANAO", "municipality" => "PANDAG", "zip_code" => "9633"],
  ["province" => "MAGUINDANAO", "municipality" => "PAGALUNGAN", "zip_code" => "9610"],
  ["province" => "MAGUINDANAO", "municipality" => "PARANG", "zip_code" => "9604"],
  ["province" => "MAGUINDANAO", "municipality" => "RAJAH BUAYAN", "zip_code" => "9634"],
  ["province" => "MAGUINDANAO", "municipality" => "SHARIFF SAYDONA MUSTAPHA", "zip_code" => "9635"],
  ["province" => "MAGUINDANAO", "municipality" => "SULTAN MASTURA", "zip_code" => "9636"],
  ["province" => "MAGUINDANAO", "municipality" => "SULTAN SUMAGKA (FORMERLY TALITAY)", "zip_code" => "9637"],
  ["province" => "MAGUINDANAO", "municipality" => "SOUTH UPI", "zip_code" => "9603"],
  ["province" => "MAGUINDANAO", "municipality" => "SULTAN KUDARAT", "zip_code" => "9605"],
  ["province" => "MAGUINDANAO", "municipality" => "SULTAN SA BARONGIS", "zip_code" => "9611"],
  ["province" => "MAGUINDANAO", "municipality" => "TALAYAN", "zip_code" => "9612"],
  ["province" => "MAGUINDANAO", "municipality" => "UPI", "zip_code" => "9602"],

  ["province" => "SULU", "municipality" => "BANGUINGUI (FORMERLY TONGKIL) ", "zip_code" => "7406"],
  ["province" => "SULU", "municipality" => "HADJI PANGLIMA TAHIL (FORMERLY MARUNGAS)", "zip_code" => "7413"],
  ["province" => "SULU", "municipality" => "INDANAN", "zip_code" => "7407"],
  ["province" => "SULU", "municipality" => "JOLO", "zip_code" => "7400"],
  ["province" => "SULU", "municipality" => "KALINGALAN KALAUANG", "zip_code" => "7416"],
  ["province" => "SULU", "municipality" => "LUGUS", "zip_code" => "7411"],
  ["province" => "SULU", "municipality" => "LUUK", "zip_code" => "7404"],
  ["province" => "SULU", "municipality" => "MAIMBUNG", "zip_code" => "7409"],
  ["province" => "SULU", "municipality" => "OMAR", "zip_code" => "7417"],
  ["province" => "SULU", "municipality" => "PANAMAO", "zip_code" => "7402"],
  ["province" => "SULU", "municipality" => "PANDAMI", "zip_code" => "7418"],
  ["province" => "SULU", "municipality" => "PANGLIMA ESTINO", "zip_code" => "7415"],
  ["province" => "SULU", "municipality" => "PANGUNTARAN", "zip_code" => "7414"],
  ["province" => "SULU", "municipality" => "PARANG", "zip_code" => "7408"],
  ["province" => "SULU", "municipality" => "PATA", "zip_code" => "7405"],
  ["province" => "SULU", "municipality" => "PATIKUL", "zip_code" => "7401"],
  ["province" => "SULU", "municipality" => "SIASI", "zip_code" => "7412"],
  ["province" => "SULU", "municipality" => "TALIPAO", "zip_code" => "7403"],
  ["province" => "SULU", "municipality" => "TAPUL", "zip_code" => "7410"],

  ["province" => "TAWI-TAWI", "municipality" => "BONGAO", "zip_code" => "7500"],
  ["province" => "TAWI-TAWI", "municipality" => "LANGUYAN ", "zip_code" => "7509"],
  ["province" => "TAWI-TAWI", "municipality" => "MAPUN (FORMERLY CAGAYAN DE SULU)", "zip_code" => "7508"],
  ["province" => "TAWI-TAWI", "municipality" => "PANGLIMA SUGALA (FORMERLY BALIMBING)", "zip_code" => "7501"],
  ["province" => "TAWI-TAWI", "municipality" => "SAPA-SAPA", "zip_code" => "7503"],
  ["province" => "TAWI-TAWI", "municipality" => "SIBUTU", "zip_code" => "7510"],
  ["province" => "TAWI-TAWI", "municipality" => "SIMUNUL", "zip_code" => "7505"],
  ["province" => "TAWI-TAWI", "municipality" => "SITANGKAI", "zip_code" => "7506"],
  ["province" => "TAWI-TAWI", "municipality" => "SOUTH UBIAN", "zip_code" => "7504"],
  ["province" => "TAWI-TAWI", "municipality" => "TURTLE ISLAND (TAGANAK)", "zip_code" => "7507"],
  ["province" => "TAWI-TAWI", "municipality" => "TANDU BAS", "zip_code" => "7502"],
];
