<?php

declare(strict_types=1);

return [
    [
        'province' => 'MANILA',
        'municipalities' => [
            [
                'municipality' => 'MANILA',
                'zip_codes' => [
                    ['location' => 'BINONDO', 'zip_code' => '1006'],
                    ['location' => 'INTRAMUROS', 'zip_code' => '1002'],
                    ['location' => 'MALATE', 'zip_code' => '1004'],
                    ['location' => 'MANILA CPO - ERMITA', 'zip_code' => '1000'],
                    ['location' => 'PACO', 'zip_code' => '1007'],
                    ['location' => 'PANDACAN', 'zip_code' => '1011'],
                    ['location' => 'PORT AREA (SOUTH)', 'zip_code' => '1018'],
                    ['location' => 'QUIAPO', 'zip_code' => '1001'],
                    ['location' => 'SAMPALOC EAST', 'zip_code' => '1008'],
                    ['location' => 'SAMPALOC WEST ', 'zip_code' => '1015'],
                    ['location' => 'SAN ANDRES BUKID', 'zip_code' => '1017'],
                    ['location' => 'SAN MIGUEL', 'zip_code' => '1005'],
                    ['location' => 'SAN NICOLAS ', 'zip_code' => '1010'],
                    ['location' => 'STA. ANA', 'zip_code' => '1009'],
                    ['location' => 'STA CRUZ NORTH', 'zip_code' => '1014'],
                    ['location' => 'STA CRUZ SOUTH', 'zip_code' => '1003'],
                    ['location' => 'STA MESA', 'zip_code' => '1016'],
                    ['location' => 'TONDO NORTH', 'zip_code' => '1013'],
                    ['location' => 'TONDO SOUTH', 'zip_code' => '1012'],
                ],
            ],
        ]
    ],

    [
        'province' => 'SECOND DISTRICT',
        'municipalities' => [
            [
                'municipality' => 'MANDALUYONG CITY',
                'zip_codes' => [
                    ['location' => 'East Edsa', 'zip_code' => '1554'],
                    ['location' => 'Greenhills South', 'zip_code' => '1556'],
                    ['location' => 'Mandaluyong CPO', 'zip_code' => '1550'],
                    ['location' => 'Phil. Natl. Mental Hospital', 'zip_code' => '1553'],
                    ['location' => 'Shaw Boulevard', 'zip_code' => '1552'],
                    ['location' => 'Vergara', 'zip_code' => '1551'],
                    ['location' => 'Wack Wack Golf', 'zip_code' => '1555'],
                ],
            ],
            [
                'municipality' => 'MARIKINA CITY',
                'zip_codes' => [
                    ['location' => 'BARANGKA', 'zip_code' => '1803'],
                    ['location' => 'CONCEPCION 1', 'zip_code' => '1807'],
                    ['location' => 'CONCEPCION 2', 'zip_code' => '1811'],
                    ['location' => 'FORTUNE', 'zip_code' => '1812'],
                    ['location' => 'INDUSTRIAL VALLEY', 'zip_code' => '1802'],
                    ['location' => 'J. DE LA PEÑA', 'zip_code' => '1804'],
                    ['location' => 'MALANDAY', 'zip_code' => '1805'],
                    ['location' => 'MARIKINA CPO - SANTA ELENA - SANTO NIÑO', 'zip_code' => '1800'],
                    ['location' => 'MARIKINA HEIGHTS', 'zip_code' => '1810'],
                    ['location' => 'NANGKA', 'zip_code' => '1808'],
                    ['location' => 'TUMANA', 'zip_code' => '1806'],
                    ['location' => 'PARANG', 'zip_code' => '1809'],
                    ['location' => 'SAN ROQUE - CALUMPANG', 'zip_code' => '1801'],
                    ['location' => 'TAÑONG', 'zip_code' => '1803'],
                ],
            ],
            [
                'municipality' => 'PASIG CITY',
                'zip_codes' => [
                    ['location' => 'CANIOGAN', 'zip_code' => '1606'],
                    ['location' => 'GREEN PARK', 'zip_code' => '1612'],
                    ['location' => 'KAPITOLYO', 'zip_code' => '1603'],
                    ['location' => 'MANGGAHAN', 'zip_code' => '1611'],
                    ['location' => 'MAYBUNGA ', 'zip_code' => '1607'],
                    ['location' => 'ORTIGAS PO', 'zip_code' => '1605'],
                    ['location' => 'PASIG CPO', 'zip_code' => '1600'],
                    ['location' => 'PINAGBUHATAN', 'zip_code' => '1602'],
                    ['location' => 'ROSARIO', 'zip_code' => '1609'],
                    ['location' => 'SAN JOAQUIN', 'zip_code' => '1601'],
                    ['location' => 'SANTOLAN', 'zip_code' => '1610'],
                    ['location' => 'STA. LUCIA', 'zip_code' => '1608'],
                    ['location' => 'UGONG', 'zip_code' => '1604'],
                ],
            ],
            [
                'municipality' => 'QUEZON CITY',
                'zip_codes' => [
                    ['location' => 'ALICIA', 'zip_code' => '1105'],
                    ['location' => 'AMIHAN', 'zip_code' => '1102'],
                    ['location' => 'APOLONIO SAMSON', 'zip_code' => '1106'],
                    ['location' => 'BAESA', 'zip_code' => '1106'],
                    ['location' => 'BAGBAG', 'zip_code' => '1116'],
                    ['location' => 'BAGONG BAYAN', 'zip_code' => '1110'],
                    ['location' => 'BAGONG BUHAY', 'zip_code' => '1109'],
                    ['location' => 'BAGONG LIPUNAN', 'zip_code' => '1111'],
                    ['location' => 'BAGONG PAG-ASA', 'zip_code' => '1105'],
                    ['location' => 'BAGONG SILANGAN', 'zip_code' => '1119'],
                    ['location' => 'BAHAY TORO', 'zip_code' => '1106'],
                    ['location' => 'BALINGASA', 'zip_code' => '1115'],
                    ['location' => 'BALINTAWAK', 'zip_code' => '1106'],
                    ['location' => 'BALUMBATO', 'zip_code' => '1106'],
                    ['location' => 'BATASAN HILLS', 'zip_code' => '1126'],
                    ['location' => 'BAYANIHAN', 'zip_code' => '1109'],
                    ['location' => 'BF HOMES', 'zip_code' => '1120'],
                    ['location' => 'BLUE RIDGE', 'zip_code' => '1109'],
                    ['location' => 'BOTOCAN', 'zip_code' => '1101'],
                    ['location' => 'BUNGAD', 'zip_code' => '1105'],
                    ['location' => 'CAMP AGUINALDO', 'zip_code' => '1110'],
                    ['location' => 'CAPITOL HILLS/PARK', 'zip_code' => '1126'],
                    ['location' => 'CAPRI', 'zip_code' => '1117'],
                    ['location' => 'CENTRAL', 'zip_code' => '1100'],
                    ['location' => 'CLARO', 'zip_code' => '1102'],
                    ['location' => 'COMMONWEALTH', 'zip_code' => '1121'],
                    ['location' => 'CRAME', 'zip_code' => '1111'],
                    ['location' => 'CUBAO', 'zip_code' => '1109'],
                    ['location' => 'CULIAT', 'zip_code' => '1128'],
                    ['location' => 'DAMAR', 'zip_code' => '1115'],
                    ['location' => 'DAMAYAN', 'zip_code' => '1104'],
                    ['location' => 'DAMAYAN LAGI', 'zip_code' => '1112'],
                    ['location' => 'DAMONG MALIIT', 'zip_code' => '1123'],
                    ['location' => 'DEL MONTE', 'zip_code' => '1105'],
                    ['location' => 'DILIMAN', 'zip_code' => '1101'],
                    ['location' => 'DIOQUINO ZOBEL', 'zip_code' => '1109'],
                    ['location' => 'DOÑA IMELDA', 'zip_code' => '1113'],
                    ['location' => 'DON MANUEL', 'zip_code' => '1113'],
                    ['location' => 'DOÑA AURORA', 'zip_code' => '1113'],
                    ['location' => 'DOÑA FAUSTINA SUBD', 'zip_code' => '1125'],
                    ['location' => 'DOÑA JOSEFA', 'zip_code' => '1113'],
                    ['location' => 'DUYAN-DUYAN', 'zip_code' => '1102'],
                    ['location' => 'E. RODRIGUEZ ', 'zip_code' => '1102'],
                    ['location' => 'ESCOPA', 'zip_code' => '1109'],
                    ['location' => 'FAIRVIEW', 'zip_code' => '1118'],
                    ['location' => 'FAIRVIEW NORTH', 'zip_code' => '1121'],
                    ['location' => 'FAIRVIEW SOUTH', 'zip_code' => '1122'],
                    ['location' => 'GINTONG SILAHIS', 'zip_code' => '1114'],
                    ['location' => 'GULOD', 'zip_code' => '1117'],
                    ['location' => 'HOLY SPIRIT', 'zip_code' => '1127'],
                    ['location' => 'HORSESHOE', 'zip_code' => '1112'],
                    ['location' => 'IMMACULATE CONCEPCION', 'zip_code' => '1111'],
                    ['location' => 'KALIGAYAHAN', 'zip_code' => '1124'],
                    ['location' => 'KALUSUGAN', 'zip_code' => '1112'],
                    ['location' => 'KAMIAS', 'zip_code' => '1102'],
                    ['location' => 'KAMUNING', 'zip_code' => '1103'],
                    ['location' => 'KATIPUNAN', 'zip_code' => '1105'],
                    ['location' => 'KAUNLARAN', 'zip_code' => '1111'],
                    ['location' => 'KRISTONG HARI', 'zip_code' => '1112'],
                    ['location' => 'KRUS NA LIGAS', 'zip_code' => '1101'],
                    ['location' => 'LA LOMA', 'zip_code' => '1114'],
                    ['location' => 'LANGING HANDA', 'zip_code' => '1103'],
                    ['location' => 'LIBIS', 'zip_code' => '1110'],
                    ['location' => 'LOURDES', 'zip_code' => '1114'],
                    ['location' => 'LOYOLA HEIGHTS', 'zip_code' => '1108'],
                    ['location' => 'MAHARLIKA', 'zip_code' => '1114'],
                    ['location' => 'MALAYA', 'zip_code' => '1101'],
                    ['location' => 'MANGGA', 'zip_code' => '1109'],
                    ['location' => 'MANRESA', 'zip_code' => '1115'],
                    ['location' => 'MARIANA', 'zip_code' => '1112'],
                    ['location' => 'MARIBLO', 'zip_code' => '1104'],
                    ['location' => 'MARILAG', 'zip_code' => '1109'],
                    ['location' => 'MASAGANA', 'zip_code' => '1109'],
                    ['location' => 'MASAMBONG', 'zip_code' => '1115'],
                    ['location' => 'MATALAHIB', 'zip_code' => '1114'],
                    ['location' => 'MATANDANG BALARA', 'zip_code' => '1119'],
                    ['location' => 'MILAGROSA', 'zip_code' => '1109'],
                    ['location' => 'NAGKAISANG NAYON', 'zip_code' => '1125'],
                    ['location' => 'NAYON KAUNLARAN', 'zip_code' => '1104'],
                    ['location' => 'NEW ERA', 'zip_code' => '1107'],
                    ['location' => 'NOVALICHES PROPER', 'zip_code' => '1121'],
                    ['location' => 'OBRERO', 'zip_code' => '1103'],
                    ['location' => 'OLD CAPITOL SITE', 'zip_code' => '1101'],
                    ['location' => 'PAANG BUNDOK', 'zip_code' => '1114'],
                    ['location' => 'PAG-IBIG SA NAYON', 'zip_code' => '1115'],
                    ['location' => 'PALIGSAHAN', 'zip_code' => '1103'],
                    ['location' => 'PALTOK', 'zip_code' => '1105'],
                    ['location' => 'PANSOL', 'zip_code' => '1108'],
                    ['location' => 'PARAISO', 'zip_code' => '1104'],
                    ['location' => 'PASONG PUTIK', 'zip_code' => '1118'],
                    ['location' => 'PASONG TAMO', 'zip_code' => '1107'],
                    ['location' => 'PAYATAS', 'zip_code' => '1119'],
                    ['location' => 'PHIL-AM', 'zip_code' => '1104'],
                    ['location' => 'PINAGKAISAHAN', 'zip_code' => '1111'],
                    ['location' => 'PIÑAHAN', 'zip_code' => '1100'],
                    ['location' => 'PROJECT 4', 'zip_code' => '1109'],
                    ['location' => 'PROJECT 6', 'zip_code' => '1100'],
                    ['location' => 'PROJECT 7', 'zip_code' => '1105'],
                    ['location' => 'PROJECT 8', 'zip_code' => '1106'],
                    ['location' => 'QUEZON CITY CPO', 'zip_code' => '1100'],
                    ['location' => 'QUIRINO DIST. (PROJ. 2 & 3)', 'zip_code' => '1102'],
                    ['location' => 'R. MAGSAYSAY', 'zip_code' => '1105'],
                    ['location' => 'ROXAS DISTRICT', 'zip_code' => '1103'],
                    ['location' => 'SACRED HEART', 'zip_code' => '1103'],
                    ['location' => 'SALUMBATO', 'zip_code' => '1106'],
                    ['location' => 'SALVACION', 'zip_code' => '1114'],
                    ['location' => 'SAN AGUSTIN', 'zip_code' => '1117'],
                    ['location' => 'SAN ANTONIO', 'zip_code' => '1105'],
                    ['location' => 'SAN BARTOLOME', 'zip_code' => '1116'],
                    ['location' => 'SAN ISIDRO', 'zip_code' => '1113'],
                    ['location' => 'SAN ISIDRO LABRADOR', 'zip_code' => '1114'],
                    ['location' => 'SAN JOSE', 'zip_code' => '1115'],
                    ['location' => 'SAN ROQUE', 'zip_code' => '1109'],
                    ['location' => 'SANTOL', 'zip_code' => '1113'],
                    ['location' => 'SAN VICENTE', 'zip_code' => '1101'],
                    ['location' => 'SANGANDAAN', 'zip_code' => '1116'],
                    ['location' => 'SANTA CRUZ', 'zip_code' => '1104'],
                    ['location' => 'SANTA LUCIA', 'zip_code' => '1117'],
                    ['location' => 'SANTA MONICA', 'zip_code' => '1117'],
                    ['location' => 'SANTA TERESITA', 'zip_code' => '1114'],
                    ['location' => 'SAUYO', 'zip_code' => '1116'],
                    ['location' => 'SIENNA', 'zip_code' => '1114'],
                    ['location' => 'SIKATUNA VILLAGE', 'zip_code' => '1101'],
                    ['location' => 'SILANGAN', 'zip_code' => '1102'],
                    ['location' => 'SOCORRO', 'zip_code' => '1109'],
                    ['location' => 'SOUTH TRIANGLE', 'zip_code' => '1103'],
                    ['location' => 'ST. IGNATIUS', 'zip_code' => '1110'],
                    ['location' => 'ST. MARTIN DE PORRES', 'zip_code' => '1111'],
                    ['location' => 'ST. PETER', 'zip_code' => '1114'],
                    ['location' => 'SANTO CRISTO', 'zip_code' => '1105'],
                    ['location' => 'SANTO NINO', 'zip_code' => '1113'],
                    ['location' => 'TAGUMPAY', 'zip_code' => '1109'],
                    ['location' => 'TALAMPAS', 'zip_code' => '1110'],
                    ['location' => 'TALAYAN', 'zip_code' => '1104'],
                    ['location' => 'TALIPAPA', 'zip_code' => '1116'],
                    ['location' => 'TANDANG SORA', 'zip_code' => '1116'],
                    ['location' => 'TATALON', 'zip_code' => '1113'],
                    ['location' => 'TEACHERS VILLAGE', 'zip_code' => '1101'],
                    ['location' => 'UGONG NORTE', 'zip_code' => '1110'],
                    ['location' => 'UNANG SIGAW', 'zip_code' => '1106'],
                    ['location' => 'UNIV. OF THE PHILS. PO', 'zip_code' => '1101'],
                    ['location' => 'UP VILLAGE', 'zip_code' => '1101'],
                    ['location' => 'VALENCIA', 'zip_code' => '1112'],
                    ['location' => 'VASRA', 'zip_code' => '1128'],
                    ['location' => 'VETERANS VILLAGE', 'zip_code' => '1105'],
                    ['location' => 'VILLA MARIA CLARA', 'zip_code' => '1109'],
                ],
            ],
            [
                'municipality' => 'SAN JUAN CITY',
                'zip_codes' => [
                    ['location' => 'EISENHOWER-CRAME', 'zip_code' => '1504'],
                    ['location' => 'GREENHILLS NORTH', 'zip_code' => '1503'],
                    ['location' => 'GREENHILLS PO', 'zip_code' => '1502'],
                    ['location' => 'SAN JUAN CPO', 'zip_code' => '1500'],
                ],
            ],
        ]
    ],

    [
        'province' => 'THIRD DISTRICT',
        'municipalities' => [
            [
                'municipality' => 'CALOOCAN CITY',
                'zip_codes' => [
                    ['location' => 'AMPARO SUBDIVISION', 'zip_code' => '1425'],
                    ['location' => 'BAGONG SILANG', 'zip_code' => '1428'],
                    ['location' => 'BAGUMBONG / PAG-ASA', 'zip_code' => '1421'],
                    ['location' => 'BANKERS VILLAGE', 'zip_code' => '1426'],
                    ['location' => 'CAPITOL PARKLAND SUBDIVISION', 'zip_code' => '1424'],
                    ['location' => 'KAYBIGA/DEPARO', 'zip_code' => '1420'],
                    ['location' => 'LILLES VILLE SUBDIVISION', 'zip_code' => '1423'],
                    ['location' => 'NOVALICHES NORTH (CAMARIN NORTH)', 'zip_code' => '1422'],
                    ['location' => 'TALA LEPROSARIUM', 'zip_code' => '1427'],
                    ['location' => 'VICTORY HEIGHTS', 'zip_code' => '1427'],
                    ['location' => '1ST AVE. TO 7TH AVE. - WEST', 'zip_code' => '1405'],
                    ['location' => 'BAESA', 'zip_code' => '1401'],
                    ['location' => 'FISH MARKET', 'zip_code' => '1411'],
                    ['location' => 'GRACE PARK EAST', 'zip_code' => '1403'],
                    ['location' => 'GRACE PARK WEST', 'zip_code' => '1406'],
                    ['location' => 'ISLA DE COCOMO', 'zip_code' => '1412'],
                    ['location' => 'CALOOCAN CITY CPO', 'zip_code' => '1400'],
                    ['location' => 'KAPITBAHAYAN EAST', 'zip_code' => '1413'],
                    ['location' => 'KAUNLARAN VILLAGE', 'zip_code' => '1409'],
                    ['location' => 'MAYPAJO', 'zip_code' => '1410'],
                    ['location' => 'SAN JOSE', 'zip_code' => '1404'],
                    ['location' => 'SANGANDAAN', 'zip_code' => '1408'],
                    ['location' => 'SANTA QUITERIA', 'zip_code' => '1402'],
                    ['location' => 'UNIVERSITY HILLS', 'zip_code' => '1407'],
                ],
            ],

            [
                'municipality' => 'MALABON CITY',
                'zip_codes' => [
                    ['location' => 'ACACIA', 'zip_code' => '1474'],
                    ['location' => 'ARANETA SUBDIVISION', 'zip_code' => '1476'],
                    ['location' => 'DAMPALIT', 'zip_code' => '1480'],
                    ['location' => 'FLORES', 'zip_code' => '1471'],
                    ['location' => 'KAUNLARAN VILLAGE', 'zip_code' => '1409'],
                    ['location' => 'LONGOS', 'zip_code' => '1472'],
                    ['location' => 'MALABON', 'zip_code' => '1470'],
                    ['location' => 'MAYSILO', 'zip_code' => '1477'],
                    ['location' => 'MUZON', 'zip_code' => '1479'],
                    ['location' => 'POTRERO', 'zip_code' => '1475'],
                    ['location' => 'SANTOLAN', 'zip_code' => '1478'],
                    ['location' => 'TONSUYA', 'zip_code' => '1473'],
                ],
            ],

            [
                'municipality' => 'NAVOTAS CITY',
                'zip_codes' => [
                    ['location' => 'FISH MARKET', 'zip_code' => '1411'],
                    ['location' => 'ISLA DE COCOMO', 'zip_code' => '1412'],
                    ['location' => 'KAPITBAHAYAN EAST', 'zip_code' => '1413'],
                    ['location' => 'KAUNLARAN VILLAGE', 'zip_code' => '1409'],
                    ['location' => 'NAVOTAS', 'zip_code' => '1485'],
                    ['location' => 'TANGOS ', 'zip_code' => '1489'],
                    ['location' => 'TANZA', 'zip_code' => '1490'],
                ],
            ],

            [
                'municipality' => 'VALENZUELA CITY',
                'zip_codes' => [
                    ['location' => 'ARKONG BATO-RINCON-PASOLO-MALANDAY-MABOLO-POLO', 'zip_code' => '1444'],
                    ['location' => 'BALANGKAS-CALOONG', 'zip_code' => '1445'],
                    ['location' => 'DALANDAN - WEST CANUMAY', 'zip_code' => '1443'],
                    ['location' => 'EAST CANUMAY - LAWANG BATO PUNTURIN', 'zip_code' => '1447'],
                    ['location' => 'FORTUNE VIL. - PASO DE BLAS - GEN. T. DE LEON', 'zip_code' => '1442'],
                    ['location' => 'KARUHATAN', 'zip_code' => '1441'],
                    ['location' => 'LINGUNAN', 'zip_code' => '1446'],
                    ['location' => 'MAPULANG LUPA', 'zip_code' => '1448'],
                    ['location' => 'VALENZUELA CPO - MALINTA', 'zip_code' => '1440'],
                    ['location' => 'VALENZUELA P.O. BOXES', 'zip_code' => '1469'],
                ]
            ],
        ],
    ],

    [
        'province' => 'FOURTH DISTRICT',
        'municipalities' => [
            [
                'municipality' => 'LAS PIÑAS CITY',
                'zip_codes' => [
                    ['location' => 'ALMANZA', 'zip_code' => '1750'],
                    ['location' => 'ANGELA VILLAGE', 'zip_code' => '1749'],
                    ['location' => 'CUT-CUT', 'zip_code' => '1743'],
                    ['location' => 'GATCHALIAN SUBDIVISION', 'zip_code' => '1745'],
                    ['location' => 'LAS PIÑAS CPO', 'zip_code' => '1740'],
                    ['location' => 'MANILA DOCTORS VILLAGE', 'zip_code' => '1748'],
                    ['location' => 'MANUYO', 'zip_code' => '1744'],
                    ['location' => 'PULANG LUPA', 'zip_code' => '1742'],
                    ['location' => 'REMARVILLE SUBDIVISION', 'zip_code' => '1741'],
                    ['location' => 'SOLDIERS HILLS SUBDIVISION', 'zip_code' => '1752'],
                    ['location' => 'T. S. CRUZ SUBDIVISION', 'zip_code' => '1751'],
                    ['location' => 'TALON, MOONWALK', 'zip_code' => '1747'],
                    ['location' => 'VERDANT ACRES SUBDIVISION', 'zip_code' => '1746'],
                    ['location' => 'ZAPOTE', 'zip_code' => '1742'],
                ]
            ],

            [
                'municipality' => 'MAKATI CITY',
                'zip_codes' => [
                    ['location' => 'AYALA-PASEO DE ROXAS', 'zip_code' => '1226'],
                    ['location' => 'BANGKAL', 'zip_code' => '1233'],
                    ['location' => 'BEL-AIR', 'zip_code' => '1209'],
                    ['location' => 'CEMBO', 'zip_code' => '1214'],
                    ['location' => 'COMEMBO', 'zip_code' => '1217'],
                    ['location' => 'DASMARINAS VILLAGE NORTH', 'zip_code' => '1221'],
                    ['location' => 'DASMARINAS VILLAGE SOUTH', 'zip_code' => '1222'],
                    ['location' => 'FORBES PARK NORTH', 'zip_code' => '1219'],
                    ['location' => 'FORBES PARK SOUTH', 'zip_code' => '1220'],
                    ['location' => 'FORT BONIFACIO (CAMP)', 'zip_code' => '1201'],
                    ['location' => 'FORT BONIFACIO NAVAL STN.', 'zip_code' => '1202'],
                    ['location' => 'GREENBELT', 'zip_code' => '1228'],
                    ['location' => 'GUADALUPE NUEVO (INC. VISAYAN VILLAGE)', 'zip_code' => '1212'],
                    ['location' => 'GUADALUPE VIEJO (INC. PALM VILLAGE)', 'zip_code' => '1211'],
                    ['location' => 'KASILAWAN', 'zip_code' => '1206'],
                    ['location' => 'LA PAZ-SINGKAMAS-TEJEROS', 'zip_code' => '1204'],
                    ['location' => 'LEGASPI VILLAGE', 'zip_code' => '1229'],
                    ['location' => 'MAGALLANES VILLAGE', 'zip_code' => '1232'],
                    ['location' => 'MAKATI COMMERCIAL CENTER', 'zip_code' => '1224'],
                    ['location' => 'MAKATI CPO (INC. BUENDIA UP TO EDSA)', 'zip_code' => '1200'],
                    ['location' => 'OLYMPIA AND CARMONA', 'zip_code' => '1207'],
                    ['location' => 'PALANAN', 'zip_code' => '1235'],
                    ['location' => 'PASONG TAMO 2000 UP, ECOLOGY VILLAGE', 'zip_code' => '1231'],
                    ['location' => 'PEMBO', 'zip_code' => '1218'],
                    ['location' => 'PINAGKAISAHAN-PITOGO', 'zip_code' => '1213'],
                    ['location' => 'PIO DEL PILAR', 'zip_code' => '1230'],
                    ['location' => 'POBLACION', 'zip_code' => '1210'],
                    ['location' => 'REMBO (EAST) & MALAPAD NA BATO', 'zip_code' => '1216'],
                    ['location' => 'REMBO(WEST)', 'zip_code' => '1215'],
                    ['location' => 'SALCEDO VILLAGE', 'zip_code' => '1227'],
                    ['location' => 'SAN ANTONIO VILLAGE (INC. MALUGAY-YAKAL)', 'zip_code' => '1203'],
                    ['location' => 'SAN ISIDRO', 'zip_code' => '1234'],
                    ['location' => 'SAN LORENZO VILLAGE', 'zip_code' => '1223'],
                    ['location' => 'STA. CRUZ', 'zip_code' => '1205'],
                    ['location' => 'URDANETA VILLAGE', 'zip_code' => '1225'],
                    ['location' => 'VALENZUELA (INC. SANTIAGO, SAN MIGUEL & RIZAL VILL.)', 'zip_code' => '1208'],
                ]
            ],

            [
                'municipality' => 'MUNTINLUPA CITY',
                'zip_codes' => [
                    ['location' => 'AYALA ALABANG P.O. BOXES', 'zip_code' => '1799'],
                    ['location' => 'AYALA ALABANG SUBDIVISION', 'zip_code' => '1780'],
                    ['location' => 'BAYANAN/PUTATAN', 'zip_code' => '1772'],
                    ['location' => 'BULE/CUPANG', 'zip_code' => '1771'],
                    ['location' => 'FILINVEST CORP. CITY', 'zip_code' => '1781'],
                    ['location' => 'MUNTINLUPA CPO  ', 'zip_code' => '1770'],
                    ['location' => 'PEARL HEIGHTS', 'zip_code' => '1775'],
                    ['location' => 'PLEASANT VILLAGE', 'zip_code' => '1777'],
                    ['location' => 'POBLACION', 'zip_code' => '1776'],
                    ['location' => 'SUSANA HEIGHTS', 'zip_code' => '1774'],
                    ['location' => 'TUNASAN', 'zip_code' => '1773'],
                ]
            ],

            [
                'municipality' => 'PARAÑAQUE CITY',
                'zip_codes' => [
                    ['location' => 'AEROPARK SUBDIVISION', 'zip_code' => '1714'],
                    ['location' => 'BACLARAN', 'zip_code' => '1702'],
                    ['location' => 'BETTER LIVING SUBDIVISION', 'zip_code' => '1711'],
                    ['location' => 'BF HOMES 1', 'zip_code' => '1720'],
                    ['location' => 'BF HOMES 2', 'zip_code' => '1718'],
                    ['location' => 'EXECUTIVE HEIGHTS SUBD.', 'zip_code' => '1710'],
                    ['location' => 'IRENEVILLE II', 'zip_code' => '1714'],
                    ['location' => 'IRENEVILLE SUBDIVISION I & II', 'zip_code' => '1719'],
                    ['location' => 'MANILA MEMORIAL PARK', 'zip_code' => '1717'],
                    ['location' => 'MARINA SUBD. (RECLAMATION)', 'zip_code' => '1703'],
                    ['location' => 'MAYWOOD I', 'zip_code' => '1719'],
                    ['location' => 'MAYWOOD VILLAGE II', 'zip_code' => '1716'],
                    ['location' => 'MERVILLE PARK', 'zip_code' => '1709'],
                    ['location' => 'MIRAMAR SUBDIVISION', 'zip_code' => '1712'],
                    ['location' => 'MOONWALK', 'zip_code' => '1709'],
                    ['location' => 'MULTINATIONAL VILLAGE', 'zip_code' => '1708'],
                    ['location' => "NINOY AQUINO INT'L. AIRPORT", 'zip_code' => '1705'],
                    ['location' => 'PARAÑAQUE CPO', 'zip_code' => '1700'],
                    ['location' => 'PULO', 'zip_code' => '1706'],
                    ['location' => 'SAN ANTONIO VALLEY 11 & 12', 'zip_code' => '1707'],
                    ['location' => 'SAN ANTONIO VALLEY I', 'zip_code' => '1715'],
                    ['location' => 'SOUTH ADMIRAL VILLAGE', 'zip_code' => '1709'],
                    ['location' => 'STO. NINO', 'zip_code' => '1704'],
                    ['location' => 'TAMBO', 'zip_code' => '1701'],
                    ['location' => 'UNITED SUBD.', 'zip_code' => '1713'],
                ]
            ],

            [
                'municipality' => 'PASAY CITY',
                'zip_codes' => [
                    ['location' => 'DOMESTIC AIRPORT PO', 'zip_code' => '1301'],
                    ['location' => 'MANILA BAY (RECLAMATION)', 'zip_code' => '1308'],
                    ['location' => 'PASAY CITY CPO MALIBAY', 'zip_code' => '1300'],
                    ['location' => 'PICC (RECLAMATION AREA)', 'zip_code' => '1307'],
                    ['location' => 'SAN ISIDRO', 'zip_code' => '1306'],
                    ['location' => 'SAN JOSE', 'zip_code' => '1305'],
                    ['location' => 'SAN RAFAEL', 'zip_code' => '1302'],
                    ['location' => 'SAN ROQUE', 'zip_code' => '1303'],
                    ['location' => 'SANTA CLARA', 'zip_code' => '1304'],
                    ['location' => 'VILLAMOR AIRBASE', 'zip_code' => '1309'],
                ]
            ]
        ],
    ],

    [
        'province' => 'TAGUIG-PATEROS',
        'municipalities' => [
            [
                'municipality' => 'PATEROS',
                'zip_codes' => [
                    ['location' => 'AGUHO', 'zip_code' => '1620'],
                    ['location' => 'STA. ANA', 'zip_code' => '1621'],
                ]
            ],

            [
                'municipality' => 'TAGUIG CITY',
                'zip_codes' => [
                    ['location' => 'BAY BREEZE EXEC. VILLAGE', 'zip_code' => '1636'],
                    ['location' => 'BICUTAN', 'zip_code' => '1631'],
                    ['location' => 'BICUTAN LOWER', 'zip_code' => '1632'],
                    ['location' => 'BICUTAN UPPER', 'zip_code' => '1633'],
                    ['location' => 'BICUTAN WESTERN', 'zip_code' => '1630'],
                    ['location' => 'BONIFACIO GLOBAL CITY', 'zip_code' => '1635'],
                    ['location' => 'LIGID', 'zip_code' => '1638'],
                    ['location' => 'NICHOLS - MCKINLEY', 'zip_code' => '1634'],
                    ['location' => 'TUKTUKAN', 'zip_code' => '1637'],
                    ['location' => 'USUSAN', 'zip_code' => '1639'],
                ]
            ],
        ]
    ],
];
