<?php

return [
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Binondo", "zip_code" => "1006"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Intramuros", "zip_code" => "1002"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Malate", "zip_code" => "1004"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Manila CPO - Ermita", "zip_code" => "1000"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Paco", "zip_code" => "1007"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Pandacan", "zip_code" => "1011"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Port Area (South)", "zip_code" => "1018"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Quiapo", "zip_code" => "1001"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sampaloc East", "zip_code" => "1008"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sampaloc West ", "zip_code" => "1015"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "San Andres Bukid", "zip_code" => "1017"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "San Miguel", "zip_code" => "1005"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "San Nicolas ", "zip_code" => "1010"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sta. Ana", "zip_code" => "1009"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sta Cruz North", "zip_code" => "1014"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sta Cruz South", "zip_code" => "1003"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Sta Mesa", "zip_code" => "1016"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Tondo North", "zip_code" => "1013"],
  ["province" => "MANILA", "city" => "MANILA", "municipality" => "Tondo South", "zip_code" => "1012"],

  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Amparo Subdivision", "zip_code" => "1425"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Bagong Silang", "zip_code" => "1428"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Bagumbong / Pag-asa", "zip_code" => "1421"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Bankers Village", "zip_code" => "1426"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Capitol Parkland Subdivision", "zip_code" => "1424"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Kaybiga/Deparo", "zip_code" => "1420"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Lilles Ville Subdivision", "zip_code" => "1423"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Novaliches North (Camarin North)", "zip_code" => "1422"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Tala Leprosarium", "zip_code" => "1427"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Victory Heights", "zip_code" => "1427"],

  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "1st Ave. to 7th Ave. - West", "zip_code" => "1405"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Baesa", "zip_code" => "1401"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Fish Market", "zip_code" => "1411"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Grace Park East", "zip_code" => "1403"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Grace Park West", "zip_code" => "1406"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Isla de Cocomo", "zip_code" => "1412"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Caloocan City CPO", "zip_code" => "1400"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Kapitbahayan East", "zip_code" => "1413"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Kaunlaran Village", "zip_code" => "1409"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Maypajo", "zip_code" => "1410"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "San Jose", "zip_code" => "1404"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Sangandaan", "zip_code" => "1408"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "Santa Quiteria", "zip_code" => "1402"],
  ["province" => "THIRD DISTRICT", "city" => "CALOOCAN CITY", "municipality" => "University Hills", "zip_code" => "1407"],

  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Almanza", "zip_code" => "1750"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Angela Village", "zip_code" => "1749"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Cut-cut", "zip_code" => "1743"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Gatchalian Subdivision", "zip_code" => "1745"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Las Piñas CPO", "zip_code" => "1740"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Manila Doctors Village", "zip_code" => "1748"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Manuyo", "zip_code" => "1744"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Pulang Lupa", "zip_code" => "1742"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Remarville Subdivision", "zip_code" => "1741"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Soldiers Hills Subdivision", "zip_code" => "1752"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "T. S. Cruz Subdivision", "zip_code" => "1751"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Talon, Moonwalk", "zip_code" => "1747"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Verdant Acres Subdivision", "zip_code" => "1746"],
  ["province" => "FOURTH DISTRICT", "city" => "LAS PIÑAS CITY", "municipality" => "Zapote", "zip_code" => "1742"],

  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Ayala-Paseo De Roxas", "zip_code" => "1226"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Bangkal", "zip_code" => "1233"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Bel-air", "zip_code" => "1209"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Cembo", "zip_code" => "1214"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Comembo", "zip_code" => "1217"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Dasmarinas Village North", "zip_code" => "1221"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Dasmarinas Village South", "zip_code" => "1222"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Forbes Park North", "zip_code" => "1219"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Forbes Park South", "zip_code" => "1220"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Fort Bonifacio (Camp)", "zip_code" => "1201"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Fort Bonifacio Naval Stn.", "zip_code" => "1202"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Greenbelt", "zip_code" => "1228"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Guadalupe Nuevo (Inc. Visayan Village)", "zip_code" => "1212"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Guadalupe Viejo (Inc. Palm Village)", "zip_code" => "1211"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Kasilawan", "zip_code" => "1206"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "La Paz-Singkamas-Tejeros", "zip_code" => "1204"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Legaspi Village", "zip_code" => "1229"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Magallanes Village", "zip_code" => "1232"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Makati Commercial Center", "zip_code" => "1224"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Makati CPO (Inc. Buendia Up To Edsa)", "zip_code" => "1200"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Olympia And Carmona", "zip_code" => "1207"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Palanan", "zip_code" => "1235"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Pasong Tamo 2000 Up, Ecology Village", "zip_code" => "1231"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Pembo", "zip_code" => "1218"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Pinagkaisahan-pitogo", "zip_code" => "1213"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Pio Del Pilar", "zip_code" => "1230"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Poblacion", "zip_code" => "1210"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Rembo (East) & Malapad Na Bato", "zip_code" => "1216"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Rembo(west)", "zip_code" => "1215"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Salcedo Village", "zip_code" => "1227"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "San Antonio Village (Inc. Malugay-Yakal)", "zip_code" => "1203"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "San Isidro", "zip_code" => "1234"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "San Lorenzo Village", "zip_code" => "1223"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Sta. Cruz", "zip_code" => "1205"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Urdaneta Village", "zip_code" => "1225"],
  ["province" => "FOURTH DISTRICT", "city" => "MAKATI CITY", "municipality" => "Valenzuela (Inc. Santiago, San Miguel & Rizal Vill.)", "zip_code" => "1208"],

  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Acacia", "zip_code" => "1474"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Araneta Subdivision", "zip_code" => "1476"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Dampalit", "zip_code" => "1480"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Flores", "zip_code" => "1471"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Kaunlaran Village", "zip_code" => "1409"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Longos", "zip_code" => "1472"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Malabon", "zip_code" => "1470"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Maysilo", "zip_code" => "1477"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Muzon", "zip_code" => "1479"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Potrero", "zip_code" => "1475"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Santolan", "zip_code" => "1478"],
  ["province" => "THIRD DISTRICT", "city" => "MALABON CITY", "municipality" => "Tonsuya", "zip_code" => "1473"],

  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "East Edsa", "zip_code" => "1554"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Greenhills South", "zip_code" => "1556"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Mandaluyong CPO", "zip_code" => "1550"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Phil. Natl. Mental Hospital", "zip_code" => "1553"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Shaw Boulevard", "zip_code" => "1552"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Vergara", "zip_code" => "1551"],
  ["province" => "SECOND DISTRICT", "city" => "MANDALUYONG CITY", "municipality" => "Wack Wack Golf", "zip_code" => "1555"],

  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Barangka", "zip_code" => "1803"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Concepcion 1", "zip_code" => "1807"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Concepcion 2", "zip_code" => "1811"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Fortune", "zip_code" => "1812"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Industrial Valley", "zip_code" => "1802"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "J. De La Peña", "zip_code" => "1804"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Malanday", "zip_code" => "1805"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Marikina CPO - Santa Elena - Santo Niño", "zip_code" => "1800"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Marikina Heights", "zip_code" => "1810"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Nangka", "zip_code" => "1808"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Tumana", "zip_code" => "1806"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Parang", "zip_code" => "1809"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "San Roque - Calumpang", "zip_code" => "1801"],
  ["province" => "SECOND DISTRICT", "city" => "MARIKINA CITY", "municipality" => "Tañong", "zip_code" => "1803"],

  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Ayala Alabang P.O. Boxes", "zip_code" => "1799"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Ayala Alabang Subdivision", "zip_code" => "1780"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Bayanan/Putatan", "zip_code" => "1772"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Bule/Cupang", "zip_code" => "1771"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Filinvest Corp. City", "zip_code" => "1781"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Muntinlupa CPO  ", "zip_code" => "1770"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Pearl Heights", "zip_code" => "1775"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Pleasant Village", "zip_code" => "1777"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Poblacion", "zip_code" => "1776"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Susana Heights", "zip_code" => "1774"],
  ["province" => "FOURTH DISTRICT", "city" => "MUNTINLUPA CITY", "municipality" => "Tunasan", "zip_code" => "1773"],

  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Fish Market", "zip_code" => "1411"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Isla De Cocomo", "zip_code" => "1412"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Kapitbahayan East", "zip_code" => "1413"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Kaunlaran Village", "zip_code" => "1409"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Navotas", "zip_code" => "1485"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Tangos ", "zip_code" => "1489"],
  ["province" => "THIRD DISTRICT", "city" => "NAVOTAS CITY", "municipality" => "Tanza", "zip_code" => "1490"],

  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Aeropark Subdivision", "zip_code" => "1714"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Baclaran", "zip_code" => "1702"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Better Living Subdivision", "zip_code" => "1711"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Bf Homes 1", "zip_code" => "1720"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Bf Homes 2", "zip_code" => "1718"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Executive Heights Subd.", "zip_code" => "1710"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Ireneville II", "zip_code" => "1714"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Ireneville Subdivision I & II", "zip_code" => "1719"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Manila Memorial Park", "zip_code" => "1717"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Marina Subd. (Reclamation)", "zip_code" => "1703"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Maywood I", "zip_code" => "1719"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Maywood Village II", "zip_code" => "1716"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Merville Park", "zip_code" => "1709"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Miramar Subdivision", "zip_code" => "1712"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Moonwalk", "zip_code" => "1709"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Multinational Village", "zip_code" => "1708"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Ninoy Aquino Int'l. Airport", "zip_code" => "1705"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Parañaque Cpo", "zip_code" => "1700"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Pulo", "zip_code" => "1706"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "San Antonio Valley 11 & 12", "zip_code" => "1707"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "San Antonio Valley I", "zip_code" => "1715"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "South Admiral Village", "zip_code" => "1709"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Sto. Nino", "zip_code" => "1704"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "Tambo", "zip_code" => "1701"],
  ["province" => "FOURTH DISTRICT", "city" => "PARAÑAQUE CITY", "municipality" => "United Subd.", "zip_code" => "1713"],

  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "Domestic Airport PO", "zip_code" => "1301"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "Manila Bay (Reclamation)", "zip_code" => "1308"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "Pasay City CPO Malibay", "zip_code" => "1300"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "PICC (Reclamation Area)", "zip_code" => "1307"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "San Isidro", "zip_code" => "1306"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "San Jose", "zip_code" => "1305"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "San Rafael", "zip_code" => "1302"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "San Roque", "zip_code" => "1303"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "Santa Clara", "zip_code" => "1304"],
  ["province" => "FOURTH DISTRICT", "city" => "PASAY CITY", "municipality" => "Villamor Airbase", "zip_code" => "1309"],

  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Caniogan", "zip_code" => "1606"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Green Park", "zip_code" => "1612"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Kapitolyo", "zip_code" => "1603"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Manggahan", "zip_code" => "1611"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Maybunga ", "zip_code" => "1607"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Ortigas PO", "zip_code" => "1605"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Pasig CPO", "zip_code" => "1600"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Pinagbuhatan", "zip_code" => "1602"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Rosario", "zip_code" => "1609"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "San Joaquin", "zip_code" => "1601"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Santolan", "zip_code" => "1610"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Sta. Lucia", "zip_code" => "1608"],
  ["province" => "SECOND DISTRICT", "city" => "PASIG CITY", "municipality" => "Ugong", "zip_code" => "1604"],

  ["province" => "TAGUIG-PATEROS", "city" => "PATEROS", "municipality" => "Aguho", "zip_code" => "1620"],
  ["province" => "TAGUIG-PATEROS", "city" => "PATEROS", "municipality" => "Sta. Ana", "zip_code" => "1621"],

  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Alicia", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Amihan", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Apolonio Samson", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Baesa", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagbag", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagong Bayan", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagong Buhay", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagong Lipunan", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagong Pag-asa", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bagong Silangan", "zip_code" => "1119"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bahay Toro", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Balingasa", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Balintawak", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Balumbato", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Batasan Hills", "zip_code" => "1126"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bayanihan", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "BF Homes", "zip_code" => "1120"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Blue Ridge", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Botocan", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Bungad", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Camp Aguinaldo", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Capitol Hills/Park", "zip_code" => "1126"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Capri", "zip_code" => "1117"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Central", "zip_code" => "1100"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Claro", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Commonwealth", "zip_code" => "1121"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Crame", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Cubao", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Culiat", "zip_code" => "1128"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Damar", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Damayan", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Damayan Lagi", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Damong Maliit", "zip_code" => "1123"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Del Monte", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Diliman", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Dioquino Zobel", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Doña Imelda", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Don Manuel", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Doña Aurora", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Doña Faustina Subd", "zip_code" => "1125"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Doña Josefa", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Duyan-duyan", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "E. Rodriguez ", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Escopa", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Fairview", "zip_code" => "1118"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Fairview North", "zip_code" => "1121"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Fairview South", "zip_code" => "1122"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Gintong Silahis", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Gulod", "zip_code" => "1117"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Holy Spirit", "zip_code" => "1127"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Horseshoe", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Immaculate Concepcion", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kaligayahan", "zip_code" => "1124"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kalusugan", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kamias", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kamuning", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Katipunan", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kaunlaran", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Kristong Hari", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Krus Na Ligas", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "La Loma", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Langing Handa", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Libis", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Lourdes", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Loyola Heights", "zip_code" => "1108"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Maharlika", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Malaya", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Mangga", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Manresa", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Mariana", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Mariblo", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Marilag", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Masagana", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Masambong", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Matalahib", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Matandang Balara", "zip_code" => "1119"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Milagrosa", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Nagkaisang Nayon", "zip_code" => "1125"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Nayon Kaunlaran", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "New Era", "zip_code" => "1107"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Novaliches Proper", "zip_code" => "1121"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Obrero", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Old Capitol Site", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Paang Bundok", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Pag-ibig Sa Nayon", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Paligsahan", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Paltok", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Pansol", "zip_code" => "1108"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Paraiso", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Pasong Putik", "zip_code" => "1118"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Pasong Tamo", "zip_code" => "1107"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Payatas", "zip_code" => "1119"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Phil-am", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Pinagkaisahan", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Piñahan", "zip_code" => "1100"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Project 4", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Project 6", "zip_code" => "1100"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Project 7", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Project 8", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Quezon City CPO", "zip_code" => "1100"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Quirino Dist. (Proj. 2 & 3)", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "R. Magsaysay", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Roxas District", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Sacred Heart", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Salumbato", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Salvacion", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Agustin", "zip_code" => "1117"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Antonio", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Bartolome", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Isidro", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Isidro Labrador", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Jose", "zip_code" => "1115"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Roque", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santol", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "San Vicente", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Sangandaan", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santa Cruz", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santa Lucia", "zip_code" => "1117"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santa Monica", "zip_code" => "1117"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santa Teresita", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Sauyo", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Sienna", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Sikatuna Village", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Silangan", "zip_code" => "1102"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Socorro", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "South Triangle", "zip_code" => "1103"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "St. Ignatius", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "St. Martin De Porres", "zip_code" => "1111"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "St. Peter", "zip_code" => "1114"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santo Cristo", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Santo Nino", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Tagumpay", "zip_code" => "1109"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Talampas", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Talayan", "zip_code" => "1104"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Talipapa", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Tandang Sora", "zip_code" => "1116"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Tatalon", "zip_code" => "1113"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Teachers Village", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Ugong Norte", "zip_code" => "1110"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Unang Sigaw", "zip_code" => "1106"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Univ. of the Phils. PO", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "UP Village", "zip_code" => "1101"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Valencia", "zip_code" => "1112"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Vasra", "zip_code" => "1128"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Veterans Village", "zip_code" => "1105"],
  ["province" => "SECOND DISTRICT", "city" => "QUEZON CITY", "municipality" => "Villa Maria Clara", "zip_code" => "1109"],

  ["province" => "SECOND DISTRICT", "city" => "SAN JUAN CITY", "municipality" => "Eisenhower-Crame", "zip_code" => "1504"],
  ["province" => "SECOND DISTRICT", "city" => "SAN JUAN CITY", "municipality" => "Greenhills North", "zip_code" => "1503"],
  ["province" => "SECOND DISTRICT", "city" => "SAN JUAN CITY", "municipality" => "Greenhills PO", "zip_code" => "1502"],
  ["province" => "SECOND DISTRICT", "city" => "SAN JUAN CITY", "municipality" => "San Juan CPO", "zip_code" => "1500"],

  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bay Breeze Exec. Village", "zip_code" => "1636"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bicutan", "zip_code" => "1631"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bicutan Lower", "zip_code" => "1632"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bicutan Upper", "zip_code" => "1633"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bicutan Western", "zip_code" => "1630"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Bonifacio Global City", "zip_code" => "1635"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Ligid", "zip_code" => "1638"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Nichols - Mckinley", "zip_code" => "1634"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Tuktukan", "zip_code" => "1637"],
  ["province" => "TAGUIG-PATEROS", "city" => "TAGUIG CITY", "municipality" => "Ususan", "zip_code" => "1639"],

  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Arkong Bato-Rincon-Pasolo-Malanday-Mabolo-Polo", "zip_code" => "1444"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Balangkas-Caloong", "zip_code" => "1445"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Dalandan - West Canumay", "zip_code" => "1443"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "East Canumay - Lawang Bato Punturin", "zip_code" => "1447"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Fortune Vil. - Paso De Blas - Gen. T. De Leon", "zip_code" => "1442"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Karuhatan", "zip_code" => "1441"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Lingunan", "zip_code" => "1446"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Mapulang Lupa", "zip_code" => "1448"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Valenzuela CPO - Malinta", "zip_code" => "1440"],
  ["province" => "THIRD DISTRICT", "city" => "VALENZUELA CITY", "municipality" => "Valenzuela P.O. Boxes", "zip_code" => "1469"],
];
