<?php
return [
  [
    "province" => "BOHOL",
    "zip_codes" => [
      ["municipality" => "ALBURQUERQUE", "zip_code" => "6302"],
      ["municipality" => "ALICIA", "zip_code" => "6314"],
      ["municipality" => "ANDA", "zip_code" => "6311"],
      ["municipality" => "ANTEQUERA", "zip_code" => "6335"],
      ["municipality" => "BACLAYON", "zip_code" => "6301"],
      ["municipality" => "BALILIHAN", "zip_code" => "6342"],
      ["municipality" => "BATUAN", "zip_code" => "6318"],
      ["municipality" => "BIEN UNIDO", "zip_code" => "6326"],
      ["municipality" => "BILAR", "zip_code" => "6317"],
      ["municipality" => "BUENAVISTA", "zip_code" => "6333"],
      ["municipality" => "CALAPE", "zip_code" => "6328"],
      ["municipality" => "CANDIJAY", "zip_code" => "6312"],
      ["municipality" => "CARMEN", "zip_code" => "6319"],
      ["municipality" => "CATIGBIAN", "zip_code" => "6343"],
      ["municipality" => "CLARIN", "zip_code" => "6330"],
      ["municipality" => "CORELLA", "zip_code" => "6337"],
      ["municipality" => "CORTES", "zip_code" => "6341"],
      ["municipality" => "DAGOHOY", "zip_code" => "6322"],
      ["municipality" => "DANAO", "zip_code" => "6344"],
      ["municipality" => "DAUIS", "zip_code" => "6339"],
      ["municipality" => "DIMIAO", "zip_code" => "6305"],
      ["municipality" => "DUERO", "zip_code" => "6309"],
      ["municipality" => "GARCIA HERNANDEZ", "zip_code" => "6307"],
      ["municipality" => "GUINDULMAN", "zip_code" => "6310"],
      ["municipality" => "INABANGA", "zip_code" => "6332"],
      ["municipality" => "JAGNA", "zip_code" => "6308"],
      ["municipality" => "JETAFE", "zip_code" => "6334"],
      ["municipality" => "LILA", "zip_code" => "6304"],
      ["municipality" => "LOAY", "zip_code" => "6303"],
      ["municipality" => "LOBOC", "zip_code" => "6316"],
      ["municipality" => "LOON", "zip_code" => "6327"],
      ["municipality" => "MABINI", "zip_code" => "6313"],
      ["municipality" => "MARIBOJOC", "zip_code" => "6336"],
      ["municipality" => "PANGLAO", "zip_code" => "6340"],
      ["municipality" => "PILAR", "zip_code" => "6321"],
      ["municipality" => "PRESIDENT CARLOS P. GARCIA (PITOGO)", "zip_code" => "6346"],
      ["municipality" => "SAGBAYAN (BORJA)", "zip_code" => "6331"],
      ["municipality" => "SAN ISIDRO", "zip_code" => "6345"],
      ["municipality" => "SAN MIGUEL", "zip_code" => "6323"],
      ["municipality" => "SEVILLA", "zip_code" => "6347"],
      ["municipality" => "SIERRA BULLONES", "zip_code" => "6320"],
      ["municipality" => "SIKATUNA", "zip_code" => "6338"],
      ["municipality" => "TAGBILARAN CITY", "zip_code" => "6300"],
      ["municipality" => "TALIBON", "zip_code" => "6325"],
      ["municipality" => "TRINIDAD", "zip_code" => "6324"],
      ["municipality" => "TUBIGON", "zip_code" => "6329"],
      ["municipality" => "UBAY", "zip_code" => "6315"],
      ["municipality" => "VALENCIA", "zip_code" => "6306"],
    ]
  ],

  [
    "province" => "CEBU",
    "zip_codes" => [
      ["municipality" => "ALCANTARA", "zip_code" => "6033"],
      ["municipality" => "ALCOY", "zip_code" => "6023"],
      ["municipality" => "ALEGRIA", "zip_code" => "6030"],
      ["municipality" => "ALOGUINSAN", "zip_code" => "6040"],
      ["municipality" => "ARGAO", "zip_code" => "6021"],
      ["municipality" => "ASTURIAS", "zip_code" => "6042"],
      ["municipality" => "BADIAN", "zip_code" => "6031"],
      ["municipality" => "BALAMBAN", "zip_code" => "6041"],
      ["municipality" => "BANTAYAN", "zip_code" => "6052"],
      ["municipality" => "BARILI", "zip_code" => "6036"],
      ["municipality" => "BOGO", "zip_code" => "6010"],
      ["municipality" => "BOLJOON", "zip_code" => "6024"],
      ["municipality" => "BORBON", "zip_code" => "6008"],
      ["municipality" => "CARCAR", "zip_code" => "6019"],
      ["municipality" => "CARMEN", "zip_code" => "6005"],
      ["municipality" => "CATMON", "zip_code" => "6006"],
      ["municipality" => "CEBU CITY", "zip_code" => "6000"],
      ["municipality" => "COMPOSTELA", "zip_code" => "6003"],
      ["municipality" => "CONSOLACION", "zip_code" => "6001"],
      ["municipality" => "CORDOVA", "zip_code" => "6017"],
      ["municipality" => "DAANBANTAYAN", "zip_code" => "6013"],
      ["municipality" => "DALAGUETE", "zip_code" => "6022"],
      ["municipality" => "DANAO CITY", "zip_code" => "6004"],
      ["municipality" => "DUMANJUG", "zip_code" => "6035"],
      ["municipality" => "GINATILAN", "zip_code" => "6028"],
      ["municipality" => "LAPU-LAPU CITY", "zip_code" => "6015"],
      ["municipality" => "LILOAN", "zip_code" => "6002"],
      ["municipality" => "MACTAN AIRPORT", "zip_code" => "6016"],
      ["municipality" => "MADRIDEJOS", "zip_code" => "6053"],
      ["municipality" => "MALABUYOC", "zip_code" => "6029"],
      ["municipality" => "MANDAUE CITY", "zip_code" => "6014"],
      ["municipality" => "MEDELLIN", "zip_code" => "6012"],
      ["municipality" => "MINGLANILLA", "zip_code" => "6046"],
      ["municipality" => "MOALBOAL", "zip_code" => "6032"],
      ["municipality" => "NAGA", "zip_code" => "6037"],
      ["municipality" => "OSLOB", "zip_code" => "6025"],
      ["municipality" => "PILAR", "zip_code" => "6048"],
      ["municipality" => "PINAMUNGAJAN", "zip_code" => "6039"],
      ["municipality" => "PORO", "zip_code" => "6049"],
      ["municipality" => "RONDA", "zip_code" => "6034"],
      ["municipality" => "SAMBOAN", "zip_code" => "6027"],
      ["municipality" => "SAN FERNANDO", "zip_code" => "6018"],
      ["municipality" => "SAN FRANCISCO", "zip_code" => "6050"],
      ["municipality" => "SAN REMEGIO", "zip_code" => "6011"],
      ["municipality" => "SANTA FE", "zip_code" => "6047"],
      ["municipality" => "SANTANDER", "zip_code" => "6026"],
      ["municipality" => "SIBONGA", "zip_code" => "6020"],
      ["municipality" => "SOGOD", "zip_code" => "6007"],
      ["municipality" => "TABOGON", "zip_code" => "6009"],
      ["municipality" => "TABUELAN", "zip_code" => "6044"],
      ["municipality" => "TALISAY", "zip_code" => "6045"],
      ["municipality" => "TOLEDO CITY", "zip_code" => "6038"],
      ["municipality" => "TUBURAN", "zip_code" => "6043"],
      ["municipality" => "TUDELA", "zip_code" => "6051"],
    ]
  ],

  [
    "province" => "NEGROS ORIENTAL",
    "zip_codes" => [
      ["municipality" => "AMLAN (AYUQUITAN)", "zip_code" => "6203"],
      ["municipality" => "AYUNGON", "zip_code" => "6210"],
      ["municipality" => "BACONG", "zip_code" => "6216"],
      ["municipality" => "BAIS CITY", "zip_code" => "6206"],
      ["municipality" => "BASAY", "zip_code" => "6222"],
      ["municipality" => "BAYAWAN (TULONG)", "zip_code" => "6221"],
      ["municipality" => "BINDOY (PAYABON)", "zip_code" => "6209"],
      ["municipality" => "CANLAON CITY", "zip_code" => "6223"],
      ["municipality" => "DAUIN", "zip_code" => "6217"],
      ["municipality" => "DUMAGUETE CITY", "zip_code" => "6200"],
      ["municipality" => "GUIHULNGAN", "zip_code" => "6214"],
      ["municipality" => "JIMALALUD", "zip_code" => "6212"],
      ["municipality" => "LA LIBERTAD", "zip_code" => "6213"],
      ["municipality" => "MABINAY", "zip_code" => "6207"],
      ["municipality" => "MANJUYOD", "zip_code" => "6208"],
      ["municipality" => "PAMPLONA", "zip_code" => "6205"],
      ["municipality" => "SAN JOSE", "zip_code" => "6202"],
      ["municipality" => "SIATON", "zip_code" => "6219"],
      ["municipality" => "SIBULAN", "zip_code" => "6201"],
      ["municipality" => "SANTA CATALINA", "zip_code" => "6220"],
      ["municipality" => "TANJAY", "zip_code" => "6204"],
      ["municipality" => "TAYASAN", "zip_code" => "6211"],
      ["municipality" => "VALENCIA (LUZURRIAGA)", "zip_code" => "6215"],
      ["municipality" => "VALLEHERMOSO", "zip_code" => "6224"],
      ["municipality" => "ZAMBOANGUITA", "zip_code" => "6218"],
    ]
  ],

  [
    "province" => "SIQUIJOR",
    "zip_codes" => [
      ["municipality" => "ENRIQUE VILLANUEVA", "zip_code" => "6230"],
      ["municipality" => "LARENA", "zip_code" => "6226"],
      ["municipality" => "LAZI", "zip_code" => "6228"],
      ["municipality" => "MARIA", "zip_code" => "6229"],
      ["municipality" => "SAN JUAN", "zip_code" => "6227"],
      ["municipality" => "SIQUIJOR", "zip_code" => "6225"],
    ]
  ],
];
