<?php
return array_map('trim', [
  ["province" => "ALBAY", "municipality" => "Bacacay", "zip_code" => "4509"],
  ["province" => "ALBAY", "municipality" => "Camalig", "zip_code" => "4502"],
  ["province" => "ALBAY", "municipality" => "Daraga (Locsin)", "zip_code" => "4501"],
  ["province" => "ALBAY", "municipality" => "Guinobatan", "zip_code" => "4503"],
  ["province" => "ALBAY", "municipality" => "Jovellar", "zip_code" => "4515"],
  ["province" => "ALBAY", "municipality" => "Legazpi City", "zip_code" => "4500"],
  ["province" => "ALBAY", "municipality" => "Libon", "zip_code" => "4507"],
  ["province" => "ALBAY", "municipality" => "Ligao", "zip_code" => "4504"],
  ["province" => "ALBAY", "municipality" => "Malilipot", "zip_code" => "4510"],
  ["province" => "ALBAY", "municipality" => "Malinao", "zip_code" => "4512"],
  ["province" => "ALBAY", "municipality" => "Manito", "zip_code" => "4514"],
  ["province" => "ALBAY", "municipality" => "Oas", "zip_code" => "4505"],
  ["province" => "ALBAY", "municipality" => "Pio Duran (Malacbalac)", "zip_code" => "4516"],
  ["province" => "ALBAY", "municipality" => "Polangui", "zip_code" => "4506"],
  ["province" => "ALBAY", "municipality" => "Rapu-Rapu", "zip_code" => "4517"],
  ["province" => "ALBAY", "municipality" => "Sto. Domingo", "zip_code" => "4508"],
  ["province" => "ALBAY", "municipality" => "Tabaco", "zip_code" => "4511"],
  ["province" => "ALBAY", "municipality" => "Tiwi", "zip_code" => "4513"],

  ["province" => "CAMARINES NORTE", "municipality" => "Basud", "zip_code" => "4608"],
  ["province" => "CAMARINES NORTE", "municipality" => "Capalonga", "zip_code" => "4607"],
  ["province" => "CAMARINES NORTE", "municipality" => "Daet", "zip_code" => "4600"],
  ["province" => "CAMARINES NORTE", "municipality" => "San Lorenzo Ruiz (formerly Imelda)", "zip_code" => "4610"],
  ["province" => "CAMARINES NORTE", "municipality" => "Jose Panganiban", "zip_code" => "4606"],
  ["province" => "CAMARINES NORTE", "municipality" => "Labo", "zip_code" => "4604"],
  ["province" => "CAMARINES NORTE", "municipality" => "Mercedes", "zip_code" => "4601"],
  ["province" => "CAMARINES NORTE", "municipality" => "Paracale", "zip_code" => "4605"],
  ["province" => "CAMARINES NORTE", "municipality" => "San Vicente", "zip_code" => "4609"],
  ["province" => "CAMARINES NORTE", "municipality" => "Sta. Elena", "zip_code" => "4611"],
  ["province" => "CAMARINES NORTE", "municipality" => "Talisay", "zip_code" => "4602"],
  ["province" => "CAMARINES NORTE", "municipality" => "Tulay na Lupa", "zip_code" => "4612"],
  ["province" => "CAMARINES NORTE", "municipality" => "Vinzons", "zip_code" => "4603"],

  ["province" => "CAMARINES SUR", "municipality" => "Baao", "zip_code" => "4432"],
  ["province" => "CAMARINES SUR", "municipality" => "Balatan", "zip_code" => "4436"],
  ["province" => "CAMARINES SUR", "municipality" => "Bato", "zip_code" => "4435"],
  ["province" => "CAMARINES SUR", "municipality" => "Bombon", "zip_code" => "4404"],
  ["province" => "CAMARINES SUR", "municipality" => "Buhi", "zip_code" => "4433"],
  ["province" => "CAMARINES SUR", "municipality" => "Bula", "zip_code" => "4430"],
  ["province" => "CAMARINES SUR", "municipality" => "Cabusao", "zip_code" => "4406"],
  ["province" => "CAMARINES SUR", "municipality" => "Calabanga", "zip_code" => "4405"],
  ["province" => "CAMARINES SUR", "municipality" => "Camaligan", "zip_code" => "4401"],
  ["province" => "CAMARINES SUR", "municipality" => "Canaman", "zip_code" => "4402"],
  ["province" => "CAMARINES SUR", "municipality" => "Caramoan", "zip_code" => "4429"],
  ["province" => "CAMARINES SUR", "municipality" => "Del Gallego", "zip_code" => "4411"],
  ["province" => "CAMARINES SUR", "municipality" => "Gainza", "zip_code" => "4412"],
  ["province" => "CAMARINES SUR", "municipality" => "Garchitorena", "zip_code" => "4428"],
  ["province" => "CAMARINES SUR", "municipality" => "Goa", "zip_code" => "4422"],
  ["province" => "CAMARINES SUR", "municipality" => "Iriga City", "zip_code" => "4431"],
  ["province" => "CAMARINES SUR", "municipality" => "Lagonoy", "zip_code" => "4425"],
  ["province" => "CAMARINES SUR", "municipality" => "Libmanan", "zip_code" => "4407"],
  ["province" => "CAMARINES SUR", "municipality" => "Lupi", "zip_code" => "4409"],
  ["province" => "CAMARINES SUR", "municipality" => "Magarao", "zip_code" => "4403"],
  ["province" => "CAMARINES SUR", "municipality" => "Milaor", "zip_code" => "4413"],
  ["province" => "CAMARINES SUR", "municipality" => "Minalabac", "zip_code" => "4414"],
  ["province" => "CAMARINES SUR", "municipality" => "Nabua", "zip_code" => "4434"],
  ["province" => "CAMARINES SUR", "municipality" => "Naga City", "zip_code" => "4400"],
  ["province" => "CAMARINES SUR", "municipality" => "Ocampo", "zip_code" => "4419"],
  ["province" => "CAMARINES SUR", "municipality" => "Pamplona", "zip_code" => "4416"],
  ["province" => "CAMARINES SUR", "municipality" => "Pasacao", "zip_code" => "4417"],
  ["province" => "CAMARINES SUR", "municipality" => "Pili", "zip_code" => "4418"],
  ["province" => "CAMARINES SUR", "municipality" => "Presentacion", "zip_code" => "4424"],
  ["province" => "CAMARINES SUR", "municipality" => "Ragay", "zip_code" => "4410"],
  ["province" => "CAMARINES SUR", "municipality" => "Sagnay", "zip_code" => "4421"],
  ["province" => "CAMARINES SUR", "municipality" => "San Fernando", "zip_code" => "4415"],
  ["province" => "CAMARINES SUR", "municipality" => "San Jose", "zip_code" => "4423"],
  ["province" => "CAMARINES SUR", "municipality" => "Sipocot", "zip_code" => "4408"],
  ["province" => "CAMARINES SUR", "municipality" => "Siruma", "zip_code" => "4427"],
  ["province" => "CAMARINES SUR", "municipality" => "Tigaon", "zip_code" => "4420"],
  ["province" => "CAMARINES SUR", "municipality" => "Tinambac", "zip_code" => "4426"],

  ["province" => "CATANDUANES", "municipality" => "Bagamanoc", "zip_code" => "4807"],
  ["province" => "CATANDUANES", "municipality" => "Baras", "zip_code" => "4803"],
  ["province" => "CATANDUANES", "municipality" => "Bato", "zip_code" => "4801"],
  ["province" => "CATANDUANES", "municipality" => "Caramoran", "zip_code" => "4808"],
  ["province" => "CATANDUANES", "municipality" => "Gigmoto", "zip_code" => "4804"],
  ["province" => "CATANDUANES", "municipality" => "Pandan", "zip_code" => "4809"],
  ["province" => "CATANDUANES", "municipality" => "Panganiban", "zip_code" => "4806"],
  ["province" => "CATANDUANES", "municipality" => "San Andres", "zip_code" => "4810"],
  ["province" => "CATANDUANES", "municipality" => "San Miguel", "zip_code" => "4802"],
  ["province" => "CATANDUANES", "municipality" => "Viga", "zip_code" => "4805"],
  ["province" => "CATANDUANES", "municipality" => "Virac", "zip_code" => "4800"],

  ["province" => "MASBATE", "municipality" => "Aroroy", "zip_code" => "5414"],
  ["province" => "MASBATE", "municipality" => "Baleno", "zip_code" => "5413"],
  ["province" => "MASBATE", "municipality" => "Balud", "zip_code" => "5412"],
  ["province" => "MASBATE", "municipality" => "Batuan", "zip_code" => "5415"],
  ["province" => "MASBATE", "municipality" => "Buenavista", "zip_code" => "5421"],
  ["province" => "MASBATE", "municipality" => "Cataingan", "zip_code" => "5405"],
  ["province" => "MASBATE", "municipality" => "Cawayan", "zip_code" => "5409"],
  ["province" => "MASBATE", "municipality" => "Claveria", "zip_code" => "5419"],
  ["province" => "MASBATE", "municipality" => "Dimasalang", "zip_code" => "5403"],
  ["province" => "MASBATE", "municipality" => "Esperanza", "zip_code" => "5407"],
  ["province" => "MASBATE", "municipality" => "Mandaon", "zip_code" => "5411"],
  ["province" => "MASBATE", "municipality" => "Masbate     ", "zip_code" => "5400"],
  ["province" => "MASBATE", "municipality" => "Milagros", "zip_code" => "5410"],
  ["province" => "MASBATE", "municipality" => "Mobo", "zip_code" => "5401"],
  ["province" => "MASBATE", "municipality" => "Monreal ", "zip_code" => "5418"],
  ["province" => "MASBATE", "municipality" => "Palanas", "zip_code" => "5404"],
  ["province" => "MASBATE", "municipality" => "Pio V. Corpuz", "zip_code" => "5406"],
  ["province" => "MASBATE", "municipality" => "Placer", "zip_code" => "5408"],
  ["province" => "MASBATE", "municipality" => "San Fernando", "zip_code" => "5416"],
  ["province" => "MASBATE", "municipality" => "San Jacinto", "zip_code" => "5417"],
  ["province" => "MASBATE", "municipality" => "San Pascual", "zip_code" => "5420"],
  ["province" => "MASBATE", "municipality" => "Uson", "zip_code" => "5402"],

  ["province" => "SORSOGON", "municipality" => "Bacon", "zip_code" => "4701"],
  ["province" => "SORSOGON", "municipality" => "Barcelona", "zip_code" => "4712"],
  ["province" => "SORSOGON", "municipality" => "Bulan", "zip_code" => "4706"],
  ["province" => "SORSOGON", "municipality" => "Bulusan", "zip_code" => "4704"],
  ["province" => "SORSOGON", "municipality" => "Casiguran", "zip_code" => "4702"],
  ["province" => "SORSOGON", "municipality" => "Castilla", "zip_code" => "4713"],
  ["province" => "SORSOGON", "municipality" => "Donsol", "zip_code" => "4715"],
  ["province" => "SORSOGON", "municipality" => "Gubat", "zip_code" => "4710"],
  ["province" => "SORSOGON", "municipality" => "Irosin", "zip_code" => "4707"],
  ["province" => "SORSOGON", "municipality" => "Juban", "zip_code" => "4703"],
  ["province" => "SORSOGON", "municipality" => "Magallanes", "zip_code" => "4705"],
  ["province" => "SORSOGON", "municipality" => "Matnog", "zip_code" => "4708"],
  ["province" => "SORSOGON", "municipality" => "Pilar", "zip_code" => "4714"],
  ["province" => "SORSOGON", "municipality" => "Prieto Diaz", "zip_code" => "4711"],
  ["province" => "SORSOGON", "municipality" => "Sorsogon  ", "zip_code" => "4700"],
  ["province" => "SORSOGON", "municipality" => "Sta. Magdalena", "zip_code" => "4709"],
]);
