<?php

declare(strict_types=1);
return [
    ['province' => 'ALBAY', 'municipality' => 'BACACAY', 'zip_code' => '4509'],
    ['province' => 'ALBAY', 'municipality' => 'CAMALIG', 'zip_code' => '4502'],
    ['province' => 'ALBAY', 'municipality' => 'DARAGA (LOCSIN)', 'zip_code' => '4501'],
    ['province' => 'ALBAY', 'municipality' => 'GUINOBATAN', 'zip_code' => '4503'],
    ['province' => 'ALBAY', 'municipality' => 'JOVELLAR', 'zip_code' => '4515'],
    ['province' => 'ALBAY', 'municipality' => 'LEGAZPI CITY', 'zip_code' => '4500'],
    ['province' => 'ALBAY', 'municipality' => 'LIBON', 'zip_code' => '4507'],
    ['province' => 'ALBAY', 'municipality' => 'LIGAO', 'zip_code' => '4504'],
    ['province' => 'ALBAY', 'municipality' => 'MALILIPOT', 'zip_code' => '4510'],
    ['province' => 'ALBAY', 'municipality' => 'MALINAO', 'zip_code' => '4512'],
    ['province' => 'ALBAY', 'municipality' => 'MANITO', 'zip_code' => '4514'],
    ['province' => 'ALBAY', 'municipality' => 'OAS', 'zip_code' => '4505'],
    ['province' => 'ALBAY', 'municipality' => 'PIO DURAN (MALACBALAC)', 'zip_code' => '4516'],
    ['province' => 'ALBAY', 'municipality' => 'POLANGUI', 'zip_code' => '4506'],
    ['province' => 'ALBAY', 'municipality' => 'RAPU-RAPU', 'zip_code' => '4517'],
    ['province' => 'ALBAY', 'municipality' => 'STO. DOMINGO', 'zip_code' => '4508'],
    ['province' => 'ALBAY', 'municipality' => 'TABACO', 'zip_code' => '4511'],
    ['province' => 'ALBAY', 'municipality' => 'TIWI', 'zip_code' => '4513'],

    ['province' => 'CAMARINES NORTE', 'municipality' => 'BASUD', 'zip_code' => '4608'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'CAPALONGA', 'zip_code' => '4607'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'DAET', 'zip_code' => '4600'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'SAN LORENZO RUIZ (FORMERLY IMELDA)', 'zip_code' => '4610'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'JOSE PANGANIBAN', 'zip_code' => '4606'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'LABO', 'zip_code' => '4604'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'MERCEDES', 'zip_code' => '4601'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'PARACALE', 'zip_code' => '4605'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'SAN VICENTE', 'zip_code' => '4609'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'STA. ELENA', 'zip_code' => '4611'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'TALISAY', 'zip_code' => '4602'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'TULAY NA LUPA', 'zip_code' => '4612'],
    ['province' => 'CAMARINES NORTE', 'municipality' => 'VINZONS', 'zip_code' => '4603'],

    ['province' => 'CAMARINES SUR', 'municipality' => 'BAAO', 'zip_code' => '4432'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'BALATAN', 'zip_code' => '4436'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'BATO', 'zip_code' => '4435'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'BOMBON', 'zip_code' => '4404'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'BUHI', 'zip_code' => '4433'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'BULA', 'zip_code' => '4430'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'CABUSAO', 'zip_code' => '4406'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'CALABANGA', 'zip_code' => '4405'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'CAMALIGAN', 'zip_code' => '4401'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'CANAMAN', 'zip_code' => '4402'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'CARAMOAN', 'zip_code' => '4429'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'DEL GALLEGO', 'zip_code' => '4411'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'GAINZA', 'zip_code' => '4412'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'GARCHITORENA', 'zip_code' => '4428'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'GOA', 'zip_code' => '4422'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'IRIGA CITY', 'zip_code' => '4431'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'LAGONOY', 'zip_code' => '4425'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'LIBMANAN', 'zip_code' => '4407'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'LUPI', 'zip_code' => '4409'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'MAGARAO', 'zip_code' => '4403'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'MILAOR', 'zip_code' => '4413'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'MINALABAC', 'zip_code' => '4414'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'NABUA', 'zip_code' => '4434'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'NAGA CITY', 'zip_code' => '4400'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'OCAMPO', 'zip_code' => '4419'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'PAMPLONA', 'zip_code' => '4416'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'PASACAO', 'zip_code' => '4417'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'PILI', 'zip_code' => '4418'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'PRESENTACION', 'zip_code' => '4424'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'RAGAY', 'zip_code' => '4410'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'SAGNAY', 'zip_code' => '4421'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'SAN FERNANDO', 'zip_code' => '4415'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'SAN JOSE', 'zip_code' => '4423'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'SIPOCOT', 'zip_code' => '4408'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'SIRUMA', 'zip_code' => '4427'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'TIGAON', 'zip_code' => '4420'],
    ['province' => 'CAMARINES SUR', 'municipality' => 'TINAMBAC', 'zip_code' => '4426'],

    ['province' => 'CATANDUANES', 'municipality' => 'BAGAMANOC', 'zip_code' => '4807'],
    ['province' => 'CATANDUANES', 'municipality' => 'BARAS', 'zip_code' => '4803'],
    ['province' => 'CATANDUANES', 'municipality' => 'BATO', 'zip_code' => '4801'],
    ['province' => 'CATANDUANES', 'municipality' => 'CARAMORAN', 'zip_code' => '4808'],
    ['province' => 'CATANDUANES', 'municipality' => 'GIGMOTO', 'zip_code' => '4804'],
    ['province' => 'CATANDUANES', 'municipality' => 'PANDAN', 'zip_code' => '4809'],
    ['province' => 'CATANDUANES', 'municipality' => 'PANGANIBAN', 'zip_code' => '4806'],
    ['province' => 'CATANDUANES', 'municipality' => 'SAN ANDRES', 'zip_code' => '4810'],
    ['province' => 'CATANDUANES', 'municipality' => 'SAN MIGUEL', 'zip_code' => '4802'],
    ['province' => 'CATANDUANES', 'municipality' => 'VIGA', 'zip_code' => '4805'],
    ['province' => 'CATANDUANES', 'municipality' => 'VIRAC', 'zip_code' => '4800'],

    ['province' => 'MASBATE', 'municipality' => 'AROROY', 'zip_code' => '5414'],
    ['province' => 'MASBATE', 'municipality' => 'BALENO', 'zip_code' => '5413'],
    ['province' => 'MASBATE', 'municipality' => 'BALUD', 'zip_code' => '5412'],
    ['province' => 'MASBATE', 'municipality' => 'BATUAN', 'zip_code' => '5415'],
    ['province' => 'MASBATE', 'municipality' => 'BUENAVISTA', 'zip_code' => '5421'],
    ['province' => 'MASBATE', 'municipality' => 'CATAINGAN', 'zip_code' => '5405'],
    ['province' => 'MASBATE', 'municipality' => 'CAWAYAN', 'zip_code' => '5409'],
    ['province' => 'MASBATE', 'municipality' => 'CLAVERIA', 'zip_code' => '5419'],
    ['province' => 'MASBATE', 'municipality' => 'DIMASALANG', 'zip_code' => '5403'],
    ['province' => 'MASBATE', 'municipality' => 'ESPERANZA', 'zip_code' => '5407'],
    ['province' => 'MASBATE', 'municipality' => 'MANDAON', 'zip_code' => '5411'],
    ['province' => 'MASBATE', 'municipality' => 'MASBATE', 'zip_code' => '5400'],
    ['province' => 'MASBATE', 'municipality' => 'MILAGROS', 'zip_code' => '5410'],
    ['province' => 'MASBATE', 'municipality' => 'MOBO', 'zip_code' => '5401'],
    ['province' => 'MASBATE', 'municipality' => 'MONREAL ', 'zip_code' => '5418'],
    ['province' => 'MASBATE', 'municipality' => 'PALANAS', 'zip_code' => '5404'],
    ['province' => 'MASBATE', 'municipality' => 'PIO V. CORPUZ', 'zip_code' => '5406'],
    ['province' => 'MASBATE', 'municipality' => 'PLACER', 'zip_code' => '5408'],
    ['province' => 'MASBATE', 'municipality' => 'SAN FERNANDO', 'zip_code' => '5416'],
    ['province' => 'MASBATE', 'municipality' => 'SAN JACINTO', 'zip_code' => '5417'],
    ['province' => 'MASBATE', 'municipality' => 'SAN PASCUAL', 'zip_code' => '5420'],
    ['province' => 'MASBATE', 'municipality' => 'USON', 'zip_code' => '5402'],

    ['province' => 'SORSOGON', 'municipality' => 'BACON', 'zip_code' => '4701'],
    ['province' => 'SORSOGON', 'municipality' => 'BARCELONA', 'zip_code' => '4712'],
    ['province' => 'SORSOGON', 'municipality' => 'BULAN', 'zip_code' => '4706'],
    ['province' => 'SORSOGON', 'municipality' => 'BULUSAN', 'zip_code' => '4704'],
    ['province' => 'SORSOGON', 'municipality' => 'CASIGURAN', 'zip_code' => '4702'],
    ['province' => 'SORSOGON', 'municipality' => 'CASTILLA', 'zip_code' => '4713'],
    ['province' => 'SORSOGON', 'municipality' => 'DONSOL', 'zip_code' => '4715'],
    ['province' => 'SORSOGON', 'municipality' => 'GUBAT', 'zip_code' => '4710'],
    ['province' => 'SORSOGON', 'municipality' => 'IROSIN', 'zip_code' => '4707'],
    ['province' => 'SORSOGON', 'municipality' => 'JUBAN', 'zip_code' => '4703'],
    ['province' => 'SORSOGON', 'municipality' => 'MAGALLANES', 'zip_code' => '4705'],
    ['province' => 'SORSOGON', 'municipality' => 'MATNOG', 'zip_code' => '4708'],
    ['province' => 'SORSOGON', 'municipality' => 'PILAR', 'zip_code' => '4714'],
    ['province' => 'SORSOGON', 'municipality' => 'PRIETO DIAZ', 'zip_code' => '4711'],
    ['province' => 'SORSOGON', 'municipality' => 'SORSOGON', 'zip_code' => '4700'],
    ['province' => 'SORSOGON', 'municipality' => 'STA. MAGDALENA', 'zip_code' => '4709'],
];
