<?php
return array_map('trim', [
  ["province" => "BATANGAS", "municipality" => "Agoncillo", "zip_code" => "4211"],
  ["province" => "BATANGAS", "municipality" => "Alitagtag", "zip_code" => "4205"],
  ["province" => "BATANGAS", "municipality" => "Balayan", "zip_code" => "4213"],
  ["province" => "BATANGAS", "municipality" => "Balete", "zip_code" => "4219"],
  ["province" => "BATANGAS", "municipality" => "Batangas City", "zip_code" => "4200"],
  ["province" => "BATANGAS", "municipality" => "Bauan", "zip_code" => "4201"],
  ["province" => "BATANGAS", "municipality" => "Calaca", "zip_code" => "4212"],
  ["province" => "BATANGAS", "municipality" => "Calatagan", "zip_code" => "4215"],
  ["province" => "BATANGAS", "municipality" => "Cuenca", "zip_code" => "4222"],
  ["province" => "BATANGAS", "municipality" => "Fernando Airbase", "zip_code" => "4218"],
  ["province" => "BATANGAS", "municipality" => "Ibaan", "zip_code" => "4230"],
  ["province" => "BATANGAS", "municipality" => "Laurel", "zip_code" => "4221"],
  ["province" => "BATANGAS", "municipality" => "Lemery", "zip_code" => "4209"],
  ["province" => "BATANGAS", "municipality" => "Lian", "zip_code" => "4216"],
  ["province" => "BATANGAS", "municipality" => "Lipa City", "zip_code" => "4217"],
  ["province" => "BATANGAS", "municipality" => "Lobo", "zip_code" => "4229"],
  ["province" => "BATANGAS", "municipality" => "Mabini", "zip_code" => "4202"],
  ["province" => "BATANGAS", "municipality" => "Malvar", "zip_code" => "4233"],
  ["province" => "BATANGAS", "municipality" => "Mataas na Kahoy", "zip_code" => "4223"],
  ["province" => "BATANGAS", "municipality" => "Nasugbu", "zip_code" => "4231"],
  ["province" => "BATANGAS", "municipality" => "Padre Garcia", "zip_code" => "4224"],
  ["province" => "BATANGAS", "municipality" => "Rosario", "zip_code" => "4225"],
  ["province" => "BATANGAS", "municipality" => "San Jose", "zip_code" => "4227"],
  ["province" => "BATANGAS", "municipality" => "San Juan", "zip_code" => "4226"],
  ["province" => "BATANGAS", "municipality" => "San Luis", "zip_code" => "4210"],
  ["province" => "BATANGAS", "municipality" => "San Nicolas", "zip_code" => "4207"],
  ["province" => "BATANGAS", "municipality" => "San Pascual", "zip_code" => "4204"],
  ["province" => "BATANGAS", "municipality" => "Sta. Teresita", "zip_code" => "4206"],
  ["province" => "BATANGAS", "municipality" => "Sto. Tomas", "zip_code" => "4234"],
  ["province" => "BATANGAS", "municipality" => "Taal", "zip_code" => "4208"],
  ["province" => "BATANGAS", "municipality" => "Talisay", "zip_code" => "4220"],
  ["province" => "BATANGAS", "municipality" => "Tanauan", "zip_code" => "4232"],
  ["province" => "BATANGAS", "municipality" => "Taysan", "zip_code" => "4228"],
  ["province" => "BATANGAS", "municipality" => "Tingloy", "zip_code" => "4203"],
  ["province" => "BATANGAS", "municipality" => "Tuy", "zip_code" => "4214"],

  ["province" => "CAVITE", "municipality" => "1st Cavite IND. Estate", "zip_code" => "4126"],
  ["province" => "CAVITE", "municipality" => "Alfonso", "zip_code" => "4123"],
  ["province" => "CAVITE", "municipality" => "Amadeo", "zip_code" => "4119"],
  ["province" => "CAVITE", "municipality" => "Bacoor", "zip_code" => "4102"],
  ["province" => "CAVITE", "municipality" => "Carmona", "zip_code" => "4116"],
  ["province" => "CAVITE", "municipality" => "Cavite City", "zip_code" => "4100"],
  ["province" => "CAVITE", "municipality" => "Cavite Naval Base", "zip_code" => "4101"],
  ["province" => "CAVITE", "municipality" => "Corregidor", "zip_code" => "4125"],
  ["province" => "CAVITE", "municipality" => "Dasmariñas", "zip_code" => "4114"],
  ["province" => "CAVITE", "municipality" => "Dasmariñas Resettlement Area", "zip_code" => "4115"],
  ["province" => "CAVITE", "municipality" => "Gen. Aguinaldo (Bailen)", "zip_code" => "4124"],
  ["province" => "CAVITE", "municipality" => "Gen. Mariano Alvarez", "zip_code" => "4117"],
  ["province" => "CAVITE", "municipality" => "Gen. Trias", "zip_code" => "4107"],
  ["province" => "CAVITE", "municipality" => "Imus", "zip_code" => "4103"],
  ["province" => "CAVITE", "municipality" => "Indang", "zip_code" => "4122"],
  ["province" => "CAVITE", "municipality" => "Kawit", "zip_code" => "4104"],
  ["province" => "CAVITE", "municipality" => "Magallanes", "zip_code" => "4113"],
  ["province" => "CAVITE", "municipality" => "Maragondon", "zip_code" => "4112"],
  ["province" => "CAVITE", "municipality" => "Mendez", "zip_code" => "4121"],
  ["province" => "CAVITE", "municipality" => "Molino", "zip_code" => "4135"],
  ["province" => "CAVITE", "municipality" => "Naic", "zip_code" => "4110"],
  ["province" => "CAVITE", "municipality" => "Noveleta", "zip_code" => "4105"],
  ["province" => "CAVITE", "municipality" => "Rosario", "zip_code" => "4106"],
  ["province" => "CAVITE", "municipality" => "Silang", "zip_code" => "4118"],
  ["province" => "CAVITE", "municipality" => "Tagaytay", "zip_code" => "4120"],
  ["province" => "CAVITE", "municipality" => "Tanza", "zip_code" => "4108"],
  ["province" => "CAVITE", "municipality" => "Ternate", "zip_code" => "4111"],
  ["province" => "CAVITE", "municipality" => "Trece Martirez City", "zip_code" => "4109"],

  ["province" => "LAGUNA", "municipality" => "Alaminos", "zip_code" => "4001"],
  ["province" => "LAGUNA", "municipality" => "Bay", "zip_code" => "4033"],
  ["province" => "LAGUNA", "municipality" => "Biñan", "zip_code" => "4024"],
  ["province" => "LAGUNA", "municipality" => "Botocan", "zip_code" => "4006"],
  ["province" => "LAGUNA", "municipality" => "Cabuyao", "zip_code" => "4025"],
  ["province" => "LAGUNA", "municipality" => "Calamba", "zip_code" => "4027"],
  ["province" => "LAGUNA", "municipality" => "Caluan", "zip_code" => "4012"],
  ["province" => "LAGUNA", "municipality" => "Camp Vicente Lim", "zip_code" => "4029"],
  ["province" => "LAGUNA", "municipality" => "Canlubang", "zip_code" => "4028"],
  ["province" => "LAGUNA", "municipality" => "Cavinti", "zip_code" => "4013"],
  ["province" => "LAGUNA", "municipality" => "College Los Baños", "zip_code" => "4031"],
  ["province" => "LAGUNA", "municipality" => "Famy", "zip_code" => "4021"],
  ["province" => "LAGUNA", "municipality" => "Kalayaan", "zip_code" => "4015"],
  ["province" => "LAGUNA", "municipality" => "Laguna Technopark", "zip_code" => "4034"],
  ["province" => "LAGUNA", "municipality" => "Liliw", "zip_code" => "4004"],
  ["province" => "LAGUNA", "municipality" => "Los Baños", "zip_code" => "4030"],
  ["province" => "LAGUNA", "municipality" => "Luisiana", "zip_code" => "4032"],
  ["province" => "LAGUNA", "municipality" => "Lumban", "zip_code" => "4014"],
  ["province" => "LAGUNA", "municipality" => "Mabitac", "zip_code" => "4020"],
  ["province" => "LAGUNA", "municipality" => "Magdalena", "zip_code" => "4007"],
  ["province" => "LAGUNA", "municipality" => "Majayjay", "zip_code" => "4005"],
  ["province" => "LAGUNA", "municipality" => "Nagcarlan", "zip_code" => "4002"],
  ["province" => "LAGUNA", "municipality" => "Paete", "zip_code" => "4016"],
  ["province" => "LAGUNA", "municipality" => "Pagsanjan", "zip_code" => "4008"],
  ["province" => "LAGUNA", "municipality" => "Pakil", "zip_code" => "4017"],
  ["province" => "LAGUNA", "municipality" => "Pangil", "zip_code" => "4018"],
  ["province" => "LAGUNA", "municipality" => "Pila", "zip_code" => "4010"],
  ["province" => "LAGUNA", "municipality" => "Rizal", "zip_code" => "4003"],
  ["province" => "LAGUNA", "municipality" => "San Pablo City", "zip_code" => "4000"],
  ["province" => "LAGUNA", "municipality" => "San Pedro", "zip_code" => "4023"],
  ["province" => "LAGUNA", "municipality" => "Siniloan", "zip_code" => "4019"],
  ["province" => "LAGUNA", "municipality" => "Sta. Cruz", "zip_code" => "4009"],
  ["province" => "LAGUNA", "municipality" => "Sta. Maria", "zip_code" => "4022"],
  ["province" => "LAGUNA", "municipality" => "Sta. Rosa", "zip_code" => "4026"],
  ["province" => "LAGUNA", "municipality" => "Victoria", "zip_code" => "4011"],

  ["province" => "QUEZON PROVINCE", "municipality" => "Agdangan", "zip_code" => "4304"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Alabat", "zip_code" => "4333"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Atimonan", "zip_code" => "4331"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Buenavista", "zip_code" => "4320"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Burdeos", "zip_code" => "4340"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Calauag", "zip_code" => "4318"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Candelaria", "zip_code" => "4323"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Catanauan", "zip_code" => "4311"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Dolores", "zip_code" => "4326"],
  ["province" => "QUEZON PROVINCE", "municipality" => "General Luna", "zip_code" => "4310"],
  ["province" => "QUEZON PROVINCE", "municipality" => "General Nakar", "zip_code" => "4338"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Guinayangan", "zip_code" => "4319"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Gumaca", "zip_code" => "4307"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Hondagua", "zip_code" => "4317"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Infanta", "zip_code" => "4336"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Jomalig", "zip_code" => "4342"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Lopez", "zip_code" => "4316"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Lucban", "zip_code" => "4328"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Lucena City", "zip_code" => "4301"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Macalelon", "zip_code" => "4309"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Mauban", "zip_code" => "4330"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Mulanay", "zip_code" => "4312"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Padre Burgos", "zip_code" => "4303"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Pagbilao", "zip_code" => "4302"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Panukulan", "zip_code" => "4337"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Patnanungan", "zip_code" => "4341"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Perez", "zip_code" => "4334"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Pitogo", "zip_code" => "4308"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Plaridel", "zip_code" => "4306"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Polilio", "zip_code" => "4339"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Quezon     ", "zip_code" => "4332"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Quezon Capitol", "zip_code" => "4300"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Real", "zip_code" => "4335"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Sampaloc", "zip_code" => "4329"],
  ["province" => "QUEZON PROVINCE", "municipality" => "San Andres", "zip_code" => "4314"],
  ["province" => "QUEZON PROVINCE", "municipality" => "San Antonio", "zip_code" => "4324"],
  ["province" => "QUEZON PROVINCE", "municipality" => "San Francisco", "zip_code" => "4315"],
  ["province" => "QUEZON PROVINCE", "municipality" => "San Narciso", "zip_code" => "4313"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Sariaya", "zip_code" => "4322"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Tagkawayan", "zip_code" => "4321"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Tayabas", "zip_code" => "4327"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Tiaong", "zip_code" => "4325"],
  ["province" => "QUEZON PROVINCE", "municipality" => "Unisan", "zip_code" => "4305"],

  ["province" => "RIZAL PROVINCE", "municipality" => "Angono", "zip_code" => "1930"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Antipolo", "zip_code" => "1870"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Bagong Nayon (Cogeo)", "zip_code" => "1872"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Baras", "zip_code" => "1970"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Binangonan", "zip_code" => "1940"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Cainta", "zip_code" => "1900"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Cardona", "zip_code" => "1950"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Cupang", "zip_code" => "1873"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Jalajala", "zip_code" => "1990"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Langhaya", "zip_code" => "1874"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Mambagat", "zip_code" => "1875"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Mayamot", "zip_code" => "1871"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Rodriguez (Montalban)", "zip_code" => "1860"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Morong", "zip_code" => "1960"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Pililla", "zip_code" => "1910"],
  ["province" => "RIZAL PROVINCE", "municipality" => "San Mateo", "zip_code" => "1850"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Tanay", "zip_code" => "1980"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Taytay", "zip_code" => "1920"],
  ["province" => "RIZAL PROVINCE", "municipality" => "Teresa", "zip_code" => "1880"],
]);
