<?php

declare(strict_types=1);

return [
    [
        'province' => 'ZAMBOANGA DEL NORTE',
        'zip_codes' => [
            ['municipality' => 'BALIGUIAN', 'zip_code' => '7123'],
            ['municipality' => 'DAPITAN CITY', 'zip_code' => '7101'],
            ['municipality' => 'DIPOLOG CITY', 'zip_code' => '7100'],
            ['municipality' => 'GODOD', 'zip_code' => '7126'],
            ['municipality' => 'GUTALAC', 'zip_code' => '7118'],
            ['municipality' => 'JOSE DALMAN (PONOT)', 'zip_code' => '7111'],
            ['municipality' => 'KALAWIT', 'zip_code' => '7124'],
            ['municipality' => 'KATIPUNAN', 'zip_code' => '7109'],
            ['municipality' => 'LA LIBERTAD', 'zip_code' => '7119'],
            ['municipality' => 'LABASON', 'zip_code' => '7117'],
            ['municipality' => 'LEON B. POSTIGO (BACUNGAN)', 'zip_code' => '7125'],
            ['municipality' => 'LILOY', 'zip_code' => '7115'],
            ['municipality' => 'MANUKAN', 'zip_code' => '7110'],
            ['municipality' => 'MUTIA', 'zip_code' => '7107'],
            ['municipality' => 'PIÑAN (NEW PIÑAN)', 'zip_code' => '7105'],
            ['municipality' => 'POLANCO', 'zip_code' => '7106'],
            ['municipality' => 'PRESIDENT MANUEL A. ROXAS', 'zip_code' => '7102'],
            ['municipality' => 'RIZAL', 'zip_code' => '7104'],
            ['municipality' => 'SALUG', 'zip_code' => '7114'],
            ['municipality' => 'SERGIO OSMEÑA', 'zip_code' => '7108'],
            ['municipality' => 'SIAYAN', 'zip_code' => '7113'],
            ['municipality' => 'SIBUCO', 'zip_code' => '7122'],
            ['municipality' => 'SIBUTAD', 'zip_code' => '7103'],
            ['municipality' => 'SINDANGAN', 'zip_code' => '7112'],
            ['municipality' => 'SIOCON', 'zip_code' => '7120'],
            ['municipality' => 'SIRAWAY', 'zip_code' => '7121'],
            ['municipality' => 'TAMPILISAN', 'zip_code' => '7116'],
        ]
    ],

    [
        'province' => 'ZAMBOANGA DEL SUR',
        'zip_codes' => [
            ['municipality' => 'AURORA', 'zip_code' => '7020'],
            ['municipality' => 'BAYOG', 'zip_code' => '7011'],
            ['municipality' => 'DIMATALING', 'zip_code' => '7032'],
            ['municipality' => 'DINAS', 'zip_code' => '7030'],
            ['municipality' => 'DON MARIANO MARCOS', 'zip_code' => '7022'],
            ['municipality' => 'DUMALINAO', 'zip_code' => '7015'],
            ['municipality' => 'DUMINGAG', 'zip_code' => '7028'],
            ['municipality' => 'GUIPOS', 'zip_code' => '7042'],
            ['municipality' => 'JOSEFINA', 'zip_code' => '7027'],
            ['municipality' => 'KUMALARANG', 'zip_code' => '7013'],
            ['municipality' => 'LABANGAN', 'zip_code' => '7017'],
            ['municipality' => 'LAKEWOOD', 'zip_code' => '7014'],
            ['municipality' => 'LAPUYAN', 'zip_code' => '7037'],
            ['municipality' => 'MAHAYAG', 'zip_code' => '7026'],
            ['municipality' => 'MARGO SA TUBIG', 'zip_code' => '7035'],
            ['municipality' => 'MIDSALIP', 'zip_code' => '7021'],
            ['municipality' => 'MOLAVE', 'zip_code' => '7023'],
            ['municipality' => 'PAGADIAN CITY', 'zip_code' => '7016'],
            ['municipality' => 'PITOGO', 'zip_code' => '7033'],
            ['municipality' => 'RAMON MAGSAYSAY', 'zip_code' => '7024'],
            ['municipality' => 'SAN MIGUEL', 'zip_code' => '7029'],
            ['municipality' => 'SAN PABLO', 'zip_code' => '7031'],
            ['municipality' => 'TABINA', 'zip_code' => '7034'],
            ['municipality' => 'TAMBULIG', 'zip_code' => '7025'],
            ['municipality' => 'TIGBAO', 'zip_code' => '7043'],
            ['municipality' => 'TUKURAN', 'zip_code' => '7019'],
            ['municipality' => 'VICENCIO SAGUN', 'zip_code' => '7036'],
            ['municipality' => 'ZAMBOANGA CITY', 'zip_code' => '7000'],
        ]
    ],

    [
        'province' => 'ZAMBOANGA SIBUGAY',
        'zip_codes' => [
            ['municipality' => 'ALICIA', 'zip_code' => '7040'],
            ['municipality' => 'BUUG', 'zip_code' => '7009'],
            ['municipality' => 'DIPLAHAN', 'zip_code' => '7039'],
            ['municipality' => 'IMELDA', 'zip_code' => '7007'],
            ['municipality' => 'IPIL', 'zip_code' => '7001'],
            ['municipality' => 'KABASALAN', 'zip_code' => '7005'],
            ['municipality' => 'MABUHAY', 'zip_code' => '7010'],
            ['municipality' => 'MALANGAS', 'zip_code' => '7038'],
            ['municipality' => 'NAGA', 'zip_code' => '7004'],
            ['municipality' => 'OLUTANGA', 'zip_code' => '7041'],
            ['municipality' => 'PAYAO', 'zip_code' => '7008'],
            ['municipality' => 'ROSELLER LIM', 'zip_code' => '7002'],
            ['municipality' => 'SIAY', 'zip_code' => '7006'],
            ['municipality' => 'TALUSAN', 'zip_code' => '7012'],
            ['municipality' => 'TITAY', 'zip_code' => '7003'],
            ['municipality' => 'TUNGAWAN', 'zip_code' => '7018'],
        ]
    ],
];
