<?php
return  [
  ["province" => "BOHOL", "municipality" => "Alburquerque", "zip_code" => "6302"],
  ["province" => "BOHOL", "municipality" => "Alicia", "zip_code" => "6314"],
  ["province" => "BOHOL", "municipality" => "Anda", "zip_code" => "6311"],
  ["province" => "BOHOL", "municipality" => "Antequera", "zip_code" => "6335"],
  ["province" => "BOHOL", "municipality" => "Baclayon", "zip_code" => "6301"],
  ["province" => "BOHOL", "municipality" => "Balilihan", "zip_code" => "6342"],
  ["province" => "BOHOL", "municipality" => "Batuan", "zip_code" => "6318"],
  ["province" => "BOHOL", "municipality" => "Bien Unido", "zip_code" => "6326"],
  ["province" => "BOHOL", "municipality" => "Bilar", "zip_code" => "6317"],
  ["province" => "BOHOL", "municipality" => "Buenavista", "zip_code" => "6333"],
  ["province" => "BOHOL", "municipality" => "Calape", "zip_code" => "6328"],
  ["province" => "BOHOL", "municipality" => "Candijay", "zip_code" => "6312"],
  ["province" => "BOHOL", "municipality" => "Carmen", "zip_code" => "6319"],
  ["province" => "BOHOL", "municipality" => "Catigbian", "zip_code" => "6343"],
  ["province" => "BOHOL", "municipality" => "Clarin", "zip_code" => "6330"],
  ["province" => "BOHOL", "municipality" => "Corella", "zip_code" => "6337"],
  ["province" => "BOHOL", "municipality" => "Cortes", "zip_code" => "6341"],
  ["province" => "BOHOL", "municipality" => "Dagohoy", "zip_code" => "6322"],
  ["province" => "BOHOL", "municipality" => "Danao", "zip_code" => "6344"],
  ["province" => "BOHOL", "municipality" => "Dauis", "zip_code" => "6339"],
  ["province" => "BOHOL", "municipality" => "Dimiao", "zip_code" => "6305"],
  ["province" => "BOHOL", "municipality" => "Duero", "zip_code" => "6309"],
  ["province" => "BOHOL", "municipality" => "Garcia Hernandez", "zip_code" => "6307"],
  ["province" => "BOHOL", "municipality" => "Guindulman", "zip_code" => "6310"],
  ["province" => "BOHOL", "municipality" => "Inabanga", "zip_code" => "6332"],
  ["province" => "BOHOL", "municipality" => "Jagna", "zip_code" => "6308"],
  ["province" => "BOHOL", "municipality" => "Jetafe", "zip_code" => "6334"],
  ["province" => "BOHOL", "municipality" => "Lila", "zip_code" => "6304"],
  ["province" => "BOHOL", "municipality" => "Loay", "zip_code" => "6303"],
  ["province" => "BOHOL", "municipality" => "Loboc", "zip_code" => "6316"],
  ["province" => "BOHOL", "municipality" => "Loon", "zip_code" => "6327"],
  ["province" => "BOHOL", "municipality" => "Mabini", "zip_code" => "6313"],
  ["province" => "BOHOL", "municipality" => "Maribojoc", "zip_code" => "6336"],
  ["province" => "BOHOL", "municipality" => "Panglao", "zip_code" => "6340"],
  ["province" => "BOHOL", "municipality" => "Pilar", "zip_code" => "6321"],
  ["province" => "BOHOL", "municipality" => "President Carlos P. Garcia (Pitogo)", "zip_code" => "6346"],
  ["province" => "BOHOL", "municipality" => "Sagbayan (Borja)", "zip_code" => "6331"],
  ["province" => "BOHOL", "municipality" => "San Isidro", "zip_code" => "6345"],
  ["province" => "BOHOL", "municipality" => "San Miguel", "zip_code" => "6323"],
  ["province" => "BOHOL", "municipality" => "Sevilla", "zip_code" => "6347"],
  ["province" => "BOHOL", "municipality" => "Sierra Bullones", "zip_code" => "6320"],
  ["province" => "BOHOL", "municipality" => "Sikatuna", "zip_code" => "6338"],
  ["province" => "BOHOL", "municipality" => "Tagbilaran City", "zip_code" => "6300"],
  ["province" => "BOHOL", "municipality" => "Talibon", "zip_code" => "6325"],
  ["province" => "BOHOL", "municipality" => "Trinidad", "zip_code" => "6324"],
  ["province" => "BOHOL", "municipality" => "Tubigon", "zip_code" => "6329"],
  ["province" => "BOHOL", "municipality" => "Ubay", "zip_code" => "6315"],
  ["province" => "BOHOL", "municipality" => "Valencia", "zip_code" => "6306"],

  ["province" => "CEBU", "municipality" => "Alcantara", "zip_code" => "6033"],
  ["province" => "CEBU", "municipality" => "Alcoy", "zip_code" => "6023"],
  ["province" => "CEBU", "municipality" => "Alegria", "zip_code" => "6030"],
  ["province" => "CEBU", "municipality" => "Aloguinsan", "zip_code" => "6040"],
  ["province" => "CEBU", "municipality" => "Argao", "zip_code" => "6021"],
  ["province" => "CEBU", "municipality" => "Asturias", "zip_code" => "6042"],
  ["province" => "CEBU", "municipality" => "Badian", "zip_code" => "6031"],
  ["province" => "CEBU", "municipality" => "Balamban", "zip_code" => "6041"],
  ["province" => "CEBU", "municipality" => "Bantayan", "zip_code" => "6052"],
  ["province" => "CEBU", "municipality" => "Barili", "zip_code" => "6036"],
  ["province" => "CEBU", "municipality" => "Bogo", "zip_code" => "6010"],
  ["province" => "CEBU", "municipality" => "Boljoon", "zip_code" => "6024"],
  ["province" => "CEBU", "municipality" => "Borbon", "zip_code" => "6008"],
  ["province" => "CEBU", "municipality" => "Carcar", "zip_code" => "6019"],
  ["province" => "CEBU", "municipality" => "Carmen", "zip_code" => "6005"],
  ["province" => "CEBU", "municipality" => "Catmon", "zip_code" => "6006"],
  ["province" => "CEBU", "municipality" => "Cebu City", "zip_code" => "6000"],
  ["province" => "CEBU", "municipality" => "Compostela", "zip_code" => "6003"],
  ["province" => "CEBU", "municipality" => "Consolacion", "zip_code" => "6001"],
  ["province" => "CEBU", "municipality" => "Cordova", "zip_code" => "6017"],
  ["province" => "CEBU", "municipality" => "DaanBantayan", "zip_code" => "6013"],
  ["province" => "CEBU", "municipality" => "Dalaguete", "zip_code" => "6022"],
  ["province" => "CEBU", "municipality" => "Danao City", "zip_code" => "6004"],
  ["province" => "CEBU", "municipality" => "Dumanjug", "zip_code" => "6035"],
  ["province" => "CEBU", "municipality" => "Ginatilan", "zip_code" => "6028"],
  ["province" => "CEBU", "municipality" => "Lapu-Lapu City", "zip_code" => "6015"],
  ["province" => "CEBU", "municipality" => "Liloan", "zip_code" => "6002"],
  ["province" => "CEBU", "municipality" => "Mactan Airport", "zip_code" => "6016"],
  ["province" => "CEBU", "municipality" => "Madridejos", "zip_code" => "6053"],
  ["province" => "CEBU", "municipality" => "Malabuyoc", "zip_code" => "6029"],
  ["province" => "CEBU", "municipality" => "Mandaue City", "zip_code" => "6014"],
  ["province" => "CEBU", "municipality" => "Medellin", "zip_code" => "6012"],
  ["province" => "CEBU", "municipality" => "Minglanilla", "zip_code" => "6046"],
  ["province" => "CEBU", "municipality" => "Moalboal", "zip_code" => "6032"],
  ["province" => "CEBU", "municipality" => "Naga", "zip_code" => "6037"],
  ["province" => "CEBU", "municipality" => "Oslob", "zip_code" => "6025"],
  ["province" => "CEBU", "municipality" => "Pilar", "zip_code" => "6048"],
  ["province" => "CEBU", "municipality" => "Pinamungajan", "zip_code" => "6039"],
  ["province" => "CEBU", "municipality" => "Poro", "zip_code" => "6049"],
  ["province" => "CEBU", "municipality" => "Ronda", "zip_code" => "6034"],
  ["province" => "CEBU", "municipality" => "Samboan", "zip_code" => "6027"],
  ["province" => "CEBU", "municipality" => "San Fernando", "zip_code" => "6018"],
  ["province" => "CEBU", "municipality" => "San Francisco", "zip_code" => "6050"],
  ["province" => "CEBU", "municipality" => "San Remegio", "zip_code" => "6011"],
  ["province" => "CEBU", "municipality" => "Santa Fe", "zip_code" => "6047"],
  ["province" => "CEBU", "municipality" => "Santander", "zip_code" => "6026"],
  ["province" => "CEBU", "municipality" => "Sibonga", "zip_code" => "6020"],
  ["province" => "CEBU", "municipality" => "Sogod", "zip_code" => "6007"],
  ["province" => "CEBU", "municipality" => "Tabogon", "zip_code" => "6009"],
  ["province" => "CEBU", "municipality" => "Tabuelan", "zip_code" => "6044"],
  ["province" => "CEBU", "municipality" => "Talisay", "zip_code" => "6045"],
  ["province" => "CEBU", "municipality" => "Toledo City", "zip_code" => "6038"],
  ["province" => "CEBU", "municipality" => "Tuburan", "zip_code" => "6043"],
  ["province" => "CEBU", "municipality" => "Tudela", "zip_code" => "6051"],

  ["province" => "CEBU", "municipality" => "Amlan (Ayuquitan)", "zip_code" => "6203"],
  ["province" => "CEBU", "municipality" => "Ayungon", "zip_code" => "6210"],
  ["province" => "CEBU", "municipality" => "Bacong", "zip_code" => "6216"],
  ["province" => "CEBU", "municipality" => "Bais City", "zip_code" => "6206"],
  ["province" => "CEBU", "municipality" => "Basay", "zip_code" => "6222"],
  ["province" => "CEBU", "municipality" => "Bayawan (Tulong)", "zip_code" => "6221"],
  ["province" => "CEBU", "municipality" => "Bindoy (Payabon)", "zip_code" => "6209"],
  ["province" => "CEBU", "municipality" => "Canlaon City", "zip_code" => "6223"],
  ["province" => "CEBU", "municipality" => "Dauin", "zip_code" => "6217"],
  ["province" => "CEBU", "municipality" => "Dumaguete City", "zip_code" => "6200"],
  ["province" => "CEBU", "municipality" => "Guihulngan", "zip_code" => "6214"],
  ["province" => "CEBU", "municipality" => "Jimalalud", "zip_code" => "6212"],
  ["province" => "CEBU", "municipality" => "La Libertad", "zip_code" => "6213"],
  ["province" => "CEBU", "municipality" => "Mabinay", "zip_code" => "6207"],
  ["province" => "CEBU", "municipality" => "Manjuyod", "zip_code" => "6208"],
  ["province" => "CEBU", "municipality" => "Pamplona", "zip_code" => "6205"],
  ["province" => "CEBU", "municipality" => "San Jose", "zip_code" => "6202"],
  ["province" => "CEBU", "municipality" => "Siaton", "zip_code" => "6219"],
  ["province" => "CEBU", "municipality" => "Sibulan", "zip_code" => "6201"],
  ["province" => "CEBU", "municipality" => "Santa Catalina", "zip_code" => "6220"],
  ["province" => "CEBU", "municipality" => "Tanjay", "zip_code" => "6204"],
  ["province" => "CEBU", "municipality" => "Tayasan", "zip_code" => "6211"],
  ["province" => "CEBU", "municipality" => "Valencia (Luzurriaga)", "zip_code" => "6215"],
  ["province" => "CEBU", "municipality" => "Vallehermoso", "zip_code" => "6224"],
  ["province" => "CEBU", "municipality" => "Zamboanguita", "zip_code" => "6218"],

  ["province" => "SIQUIJOR", "municipality" => "Enrique Villanueva", "zip_code" => "6230"],
  ["province" => "SIQUIJOR", "municipality" => "Larena", "zip_code" => "6226"],
  ["province" => "SIQUIJOR", "municipality" => "Lazi", "zip_code" => "6228"],
  ["province" => "SIQUIJOR", "municipality" => "Maria", "zip_code" => "6229"],
  ["province" => "SIQUIJOR", "municipality" => "San Juan", "zip_code" => "6227"],
  ["province" => "SIQUIJOR", "municipality" => "Siquijor    ", "zip_code" => "6225"],
];
