<?php

declare(strict_types=1);
return [
    ['province' => 'BOHOL', 'municipality' => 'ALBURQUERQUE', 'zip_code' => '6302'],
    ['province' => 'BOHOL', 'municipality' => 'ALICIA', 'zip_code' => '6314'],
    ['province' => 'BOHOL', 'municipality' => 'ANDA', 'zip_code' => '6311'],
    ['province' => 'BOHOL', 'municipality' => 'ANTEQUERA', 'zip_code' => '6335'],
    ['province' => 'BOHOL', 'municipality' => 'BACLAYON', 'zip_code' => '6301'],
    ['province' => 'BOHOL', 'municipality' => 'BALILIHAN', 'zip_code' => '6342'],
    ['province' => 'BOHOL', 'municipality' => 'BATUAN', 'zip_code' => '6318'],
    ['province' => 'BOHOL', 'municipality' => 'BIEN UNIDO', 'zip_code' => '6326'],
    ['province' => 'BOHOL', 'municipality' => 'BILAR', 'zip_code' => '6317'],
    ['province' => 'BOHOL', 'municipality' => 'BUENAVISTA', 'zip_code' => '6333'],
    ['province' => 'BOHOL', 'municipality' => 'CALAPE', 'zip_code' => '6328'],
    ['province' => 'BOHOL', 'municipality' => 'CANDIJAY', 'zip_code' => '6312'],
    ['province' => 'BOHOL', 'municipality' => 'CARMEN', 'zip_code' => '6319'],
    ['province' => 'BOHOL', 'municipality' => 'CATIGBIAN', 'zip_code' => '6343'],
    ['province' => 'BOHOL', 'municipality' => 'CLARIN', 'zip_code' => '6330'],
    ['province' => 'BOHOL', 'municipality' => 'CORELLA', 'zip_code' => '6337'],
    ['province' => 'BOHOL', 'municipality' => 'CORTES', 'zip_code' => '6341'],
    ['province' => 'BOHOL', 'municipality' => 'DAGOHOY', 'zip_code' => '6322'],
    ['province' => 'BOHOL', 'municipality' => 'DANAO', 'zip_code' => '6344'],
    ['province' => 'BOHOL', 'municipality' => 'DAUIS', 'zip_code' => '6339'],
    ['province' => 'BOHOL', 'municipality' => 'DIMIAO', 'zip_code' => '6305'],
    ['province' => 'BOHOL', 'municipality' => 'DUERO', 'zip_code' => '6309'],
    ['province' => 'BOHOL', 'municipality' => 'GARCIA HERNANDEZ', 'zip_code' => '6307'],
    ['province' => 'BOHOL', 'municipality' => 'GUINDULMAN', 'zip_code' => '6310'],
    ['province' => 'BOHOL', 'municipality' => 'INABANGA', 'zip_code' => '6332'],
    ['province' => 'BOHOL', 'municipality' => 'JAGNA', 'zip_code' => '6308'],
    ['province' => 'BOHOL', 'municipality' => 'JETAFE', 'zip_code' => '6334'],
    ['province' => 'BOHOL', 'municipality' => 'LILA', 'zip_code' => '6304'],
    ['province' => 'BOHOL', 'municipality' => 'LOAY', 'zip_code' => '6303'],
    ['province' => 'BOHOL', 'municipality' => 'LOBOC', 'zip_code' => '6316'],
    ['province' => 'BOHOL', 'municipality' => 'LOON', 'zip_code' => '6327'],
    ['province' => 'BOHOL', 'municipality' => 'MABINI', 'zip_code' => '6313'],
    ['province' => 'BOHOL', 'municipality' => 'MARIBOJOC', 'zip_code' => '6336'],
    ['province' => 'BOHOL', 'municipality' => 'PANGLAO', 'zip_code' => '6340'],
    ['province' => 'BOHOL', 'municipality' => 'PILAR', 'zip_code' => '6321'],
    ['province' => 'BOHOL', 'municipality' => 'PRESIDENT CARLOS P. GARCIA (PITOGO)', 'zip_code' => '6346'],
    ['province' => 'BOHOL', 'municipality' => 'SAGBAYAN (BORJA)', 'zip_code' => '6331'],
    ['province' => 'BOHOL', 'municipality' => 'SAN ISIDRO', 'zip_code' => '6345'],
    ['province' => 'BOHOL', 'municipality' => 'SAN MIGUEL', 'zip_code' => '6323'],
    ['province' => 'BOHOL', 'municipality' => 'SEVILLA', 'zip_code' => '6347'],
    ['province' => 'BOHOL', 'municipality' => 'SIERRA BULLONES', 'zip_code' => '6320'],
    ['province' => 'BOHOL', 'municipality' => 'SIKATUNA', 'zip_code' => '6338'],
    ['province' => 'BOHOL', 'municipality' => 'TAGBILARAN CITY', 'zip_code' => '6300'],
    ['province' => 'BOHOL', 'municipality' => 'TALIBON', 'zip_code' => '6325'],
    ['province' => 'BOHOL', 'municipality' => 'TRINIDAD', 'zip_code' => '6324'],
    ['province' => 'BOHOL', 'municipality' => 'TUBIGON', 'zip_code' => '6329'],
    ['province' => 'BOHOL', 'municipality' => 'UBAY', 'zip_code' => '6315'],
    ['province' => 'BOHOL', 'municipality' => 'VALENCIA', 'zip_code' => '6306'],

    ['province' => 'CEBU', 'municipality' => 'ALCANTARA', 'zip_code' => '6033'],
    ['province' => 'CEBU', 'municipality' => 'ALCOY', 'zip_code' => '6023'],
    ['province' => 'CEBU', 'municipality' => 'ALEGRIA', 'zip_code' => '6030'],
    ['province' => 'CEBU', 'municipality' => 'ALOGUINSAN', 'zip_code' => '6040'],
    ['province' => 'CEBU', 'municipality' => 'ARGAO', 'zip_code' => '6021'],
    ['province' => 'CEBU', 'municipality' => 'ASTURIAS', 'zip_code' => '6042'],
    ['province' => 'CEBU', 'municipality' => 'BADIAN', 'zip_code' => '6031'],
    ['province' => 'CEBU', 'municipality' => 'BALAMBAN', 'zip_code' => '6041'],
    ['province' => 'CEBU', 'municipality' => 'BANTAYAN', 'zip_code' => '6052'],
    ['province' => 'CEBU', 'municipality' => 'BARILI', 'zip_code' => '6036'],
    ['province' => 'CEBU', 'municipality' => 'BOGO', 'zip_code' => '6010'],
    ['province' => 'CEBU', 'municipality' => 'BOLJOON', 'zip_code' => '6024'],
    ['province' => 'CEBU', 'municipality' => 'BORBON', 'zip_code' => '6008'],
    ['province' => 'CEBU', 'municipality' => 'CARCAR', 'zip_code' => '6019'],
    ['province' => 'CEBU', 'municipality' => 'CARMEN', 'zip_code' => '6005'],
    ['province' => 'CEBU', 'municipality' => 'CATMON', 'zip_code' => '6006'],
    ['province' => 'CEBU', 'municipality' => 'CEBU CITY', 'zip_code' => '6000'],
    ['province' => 'CEBU', 'municipality' => 'COMPOSTELA', 'zip_code' => '6003'],
    ['province' => 'CEBU', 'municipality' => 'CONSOLACION', 'zip_code' => '6001'],
    ['province' => 'CEBU', 'municipality' => 'CORDOVA', 'zip_code' => '6017'],
    ['province' => 'CEBU', 'municipality' => 'DAANBANTAYAN', 'zip_code' => '6013'],
    ['province' => 'CEBU', 'municipality' => 'DALAGUETE', 'zip_code' => '6022'],
    ['province' => 'CEBU', 'municipality' => 'DANAO CITY', 'zip_code' => '6004'],
    ['province' => 'CEBU', 'municipality' => 'DUMANJUG', 'zip_code' => '6035'],
    ['province' => 'CEBU', 'municipality' => 'GINATILAN', 'zip_code' => '6028'],
    ['province' => 'CEBU', 'municipality' => 'LAPU-LAPU CITY', 'zip_code' => '6015'],
    ['province' => 'CEBU', 'municipality' => 'LILOAN', 'zip_code' => '6002'],
    ['province' => 'CEBU', 'municipality' => 'MACTAN AIRPORT', 'zip_code' => '6016'],
    ['province' => 'CEBU', 'municipality' => 'MADRIDEJOS', 'zip_code' => '6053'],
    ['province' => 'CEBU', 'municipality' => 'MALABUYOC', 'zip_code' => '6029'],
    ['province' => 'CEBU', 'municipality' => 'MANDAUE CITY', 'zip_code' => '6014'],
    ['province' => 'CEBU', 'municipality' => 'MEDELLIN', 'zip_code' => '6012'],
    ['province' => 'CEBU', 'municipality' => 'MINGLANILLA', 'zip_code' => '6046'],
    ['province' => 'CEBU', 'municipality' => 'MOALBOAL', 'zip_code' => '6032'],
    ['province' => 'CEBU', 'municipality' => 'NAGA', 'zip_code' => '6037'],
    ['province' => 'CEBU', 'municipality' => 'OSLOB', 'zip_code' => '6025'],
    ['province' => 'CEBU', 'municipality' => 'PILAR', 'zip_code' => '6048'],
    ['province' => 'CEBU', 'municipality' => 'PINAMUNGAJAN', 'zip_code' => '6039'],
    ['province' => 'CEBU', 'municipality' => 'PORO', 'zip_code' => '6049'],
    ['province' => 'CEBU', 'municipality' => 'RONDA', 'zip_code' => '6034'],
    ['province' => 'CEBU', 'municipality' => 'SAMBOAN', 'zip_code' => '6027'],
    ['province' => 'CEBU', 'municipality' => 'SAN FERNANDO', 'zip_code' => '6018'],
    ['province' => 'CEBU', 'municipality' => 'SAN FRANCISCO', 'zip_code' => '6050'],
    ['province' => 'CEBU', 'municipality' => 'SAN REMEGIO', 'zip_code' => '6011'],
    ['province' => 'CEBU', 'municipality' => 'SANTA FE', 'zip_code' => '6047'],
    ['province' => 'CEBU', 'municipality' => 'SANTANDER', 'zip_code' => '6026'],
    ['province' => 'CEBU', 'municipality' => 'SIBONGA', 'zip_code' => '6020'],
    ['province' => 'CEBU', 'municipality' => 'SOGOD', 'zip_code' => '6007'],
    ['province' => 'CEBU', 'municipality' => 'TABOGON', 'zip_code' => '6009'],
    ['province' => 'CEBU', 'municipality' => 'TABUELAN', 'zip_code' => '6044'],
    ['province' => 'CEBU', 'municipality' => 'TALISAY', 'zip_code' => '6045'],
    ['province' => 'CEBU', 'municipality' => 'TOLEDO CITY', 'zip_code' => '6038'],
    ['province' => 'CEBU', 'municipality' => 'TUBURAN', 'zip_code' => '6043'],
    ['province' => 'CEBU', 'municipality' => 'TUDELA', 'zip_code' => '6051'],

    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'AMLAN (AYUQUITAN)', 'zip_code' => '6203'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'AYUNGON', 'zip_code' => '6210'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'BACONG', 'zip_code' => '6216'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'BAIS CITY', 'zip_code' => '6206'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'BASAY', 'zip_code' => '6222'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'BAYAWAN (TULONG)', 'zip_code' => '6221'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'BINDOY (PAYABON)', 'zip_code' => '6209'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'CANLAON CITY', 'zip_code' => '6223'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'DAUIN', 'zip_code' => '6217'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'DUMAGUETE CITY', 'zip_code' => '6200'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'GUIHULNGAN', 'zip_code' => '6214'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'JIMALALUD', 'zip_code' => '6212'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'LA LIBERTAD', 'zip_code' => '6213'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'MABINAY', 'zip_code' => '6207'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'MANJUYOD', 'zip_code' => '6208'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'PAMPLONA', 'zip_code' => '6205'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'SAN JOSE', 'zip_code' => '6202'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'SIATON', 'zip_code' => '6219'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'SIBULAN', 'zip_code' => '6201'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'SANTA CATALINA', 'zip_code' => '6220'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'TANJAY', 'zip_code' => '6204'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'TAYASAN', 'zip_code' => '6211'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'VALENCIA (LUZURRIAGA)', 'zip_code' => '6215'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'VALLEHERMOSO', 'zip_code' => '6224'],
    ['province' => 'NEGROS ORIENTAL', 'municipality' => 'ZAMBOANGUITA', 'zip_code' => '6218'],

    ['province' => 'SIQUIJOR', 'municipality' => 'ENRIQUE VILLANUEVA', 'zip_code' => '6230'],
    ['province' => 'SIQUIJOR', 'municipality' => 'LARENA', 'zip_code' => '6226'],
    ['province' => 'SIQUIJOR', 'municipality' => 'LAZI', 'zip_code' => '6228'],
    ['province' => 'SIQUIJOR', 'municipality' => 'MARIA', 'zip_code' => '6229'],
    ['province' => 'SIQUIJOR', 'municipality' => 'SAN JUAN', 'zip_code' => '6227'],
    ['province' => 'SIQUIJOR', 'municipality' => 'SIQUIJOR', 'zip_code' => '6225'],
];
