<?php

declare(strict_types=1);
return  [
    [
        'province' => 'ABRA',
        'municipalities' => [
            ['municipality' => 'BANGUED', 'barangays' => ['AGTANGAO', 'ANGAD', 'BANGBANGAR', 'BAÑACAO', 'CABULOAN', 'CALABA', 'COSILI EAST (PROPER)', 'COSILI WEST (BUAYA)', 'DANGDANGLA', 'LINGTAN', 'LIPCAN', 'LUBONG', 'MACARCARMAY', 'MACRAY', 'MALITA', 'MAOAY', 'PALAO', 'PATUCANNAY', 'SAGAP', 'SAN ANTONIO', 'SANTA ROSA', 'SAO-ATAN', 'SAPPAAC', 'TABLAC (CALOT)', 'ZONE 1 POB. (NALASIN)', 'ZONE 2 POB. (CONSILIMAN)', 'ZONE 3 POB. (LALAUD)', 'ZONE 4 POB. (TOWN PROPER)', 'ZONE 5 POB. (BO. BARIKIR)', 'ZONE 6 POB. (SINAPANGAN)', 'ZONE 7 POB. (BALILING)']],
            ['municipality' => 'BOLINEY', 'barangays' => ['AMTI', 'BAO-YAN', 'DANAC EAST', 'DANAC WEST', 'DAO-ANGAN', 'DUMAGAS', 'KILONG-OLAO', 'POBLACION (BOLINEY)']],
            ['municipality' => 'BUCAY', 'barangays' => ['ABANG', 'BANGBANGCAG', 'BANGCAGAN', 'BANGLOLAO', 'BUGBOG', 'CALAO', 'DUGONG', 'LABON', 'LAYUGAN', 'MADALIPAY', 'NORTH POBLACION', 'PAGALA', 'PAKILING', 'PALAQUIO', 'PATOC', 'QUIMLOONG', 'SALNEC', 'SAN MIGUEL', 'SIBLONG', 'SOUTH POBLACION', 'TABIOG']],
            ['municipality' => 'BUCLOC', 'barangays' => ['DUCLIGAN', 'LABAAN', 'LAMAO (POB.)', 'LINGAY']],
            ['municipality' => 'DAGUIOMAN', 'barangays' => ['ABLEG', 'CABARUYAN', 'PIKEK', 'TUI (POB.)']],
            ['municipality' => 'DANGLAS', 'barangays' => ['ABAQUID', 'CABARUAN', 'CAUPASAN (POB.)', 'DANGLAS', 'NAGAPARAN', 'PADANGITAN', 'PANGAL']],
            ['municipality' => 'DOLORES', 'barangays' => ['BAYAAN', 'CABAROAN', 'CALUMBAYA', 'CARDONA', 'ISIT', 'KIMMALABA', 'LIBTEC', 'LUB-LUBBA', 'MUDIIT', 'NAMIT-INGAN', 'PACAC', 'POBLACION', 'SALUCAG', 'TALOGTOG', 'TAPING']],
            ['municipality' => 'LA PAZ', 'barangays' => ['BENBEN (BONBON)', 'BULBULALA', 'BULI', 'CANAN (GAPAN)', 'LIGUIS', 'MALABBAGA', 'MUDENG', 'PIDIPID', 'POBLACION', 'SAN GREGORIO', 'TOON', 'UDANGAN']],
            ['municipality' => 'LACUB', 'barangays' => ['BACAG', 'BUNEG', 'GUINGUINABANG', 'LAN-AG', 'PACOC', 'POBLACION (TALAMPAC)']],
            ['municipality' => 'LAGANGILANG', 'barangays' => ['AGUET', 'BACOOC', 'BALAIS', 'CAYAPA', 'DALAGUISEN', 'LAANG', 'LAGBEN', 'LAGUIBEN', 'NAGTIPULAN', 'NAGTUPACAN', 'PAGANAO', 'PAWA', 'POBLACION', 'PRESENTAR', 'SAN ISIDRO', 'TAGODTOD', 'TAPING']],
            ['municipality' => 'LAGAYAN', 'barangays' => ['BA-I', 'COLLAGO', 'PANG-OT', 'POBLACION', 'PULOT']],
            ['municipality' => 'LANGIDEN', 'barangays' => ['BAAC', 'DALAYAP (NALAAS)', 'MABUNGTOT', 'MALAPAAO', 'POBLACION', 'QUILLAT']],
            ['municipality' => 'LICUAN-BAAY', 'barangays' => ['BONGLO (PATAGUI)', 'BULBULALA', 'CAWAYAN', 'DOMENGLAY', 'LENNENG', 'MAPISLA', 'MOGAO', 'NALBUAN', 'POBLACION', 'SUBAGAN', 'TUMALIP']],
            ['municipality' => 'LUBA', 'barangays' => ['AMPALIOC', 'BARIT', 'GAYAMAN', 'LUL-LUNO', 'LUZONG', 'NAGBUKEL-TUQUIPA', 'POBLACION', 'SABNANGAN']],
            ['municipality' => 'MALIBCONG', 'barangays' => ['BAYABAS', 'BINASARAN', 'BUANAO', 'DULAO', 'DULDULAO', 'GACAB', 'LAT-EY', 'MALIBCONG (POB.)', 'MATARAGAN', 'PACGUED', 'TARIPAN', 'UMNAP']],
            ['municipality' => 'MANABO', 'barangays' => ['AYYENG (POB.)', 'CATACDEGAN NUEVO', 'CATACDEGAN VIEJO', 'LUZONG', 'SAN JOSE NORTE', 'SAN JOSE SUR', 'SAN JUAN NORTE', 'SAN JUAN SUR', 'SAN RAMON EAST', 'SAN RAMON WEST', 'SANTO TOMAS']],
            ['municipality' => 'PEÑARRUBIA', 'barangays' => ['DUMAYCO', 'LUSUAC', 'MALAMSIT (PAU-MALAMSIT)', 'NAMARABAR', 'PATIAO', 'POBLACION', 'RIANG (TIANG)', 'SANTA ROSA', 'TATTAWA']],
            ['municipality' => 'PIDIGAN', 'barangays' => ['ALINAYA', 'ARAB', 'GARRETA', 'IMMULI', 'LASKIG', 'MONGGOC', 'NAGUIRAYAN', 'PAMUTIC', 'PANGTUD', 'POBLACION EAST', 'POBLACION WEST', 'SAN DIEGO', 'SULBEC', 'SUYO (MALIDONG)', 'YUYENG']],
            ['municipality' => 'PILAR', 'barangays' => ['BOLBOLO', 'BROOKSIDE', 'DALIT', 'DINTAN', 'GAPANG', 'KINABITI', 'MALIPLIPIT', 'NAGCANASAN', 'NANANGDUAN', 'NARNARA', 'OCUP', 'PANG-OT', 'PATAD', 'POBLACION', 'SAN JUAN EAST', 'SAN JUAN WEST', 'SOUTH BALIOAG', 'TIKITIK', 'VILLAVIEJA']],
            ['municipality' => 'SALLAPADAN', 'barangays' => ['BAZAR', 'BILABILA', 'GANGAL (POB.)', 'MAGUYEPYEP', 'NAGUILIAN', 'SACCAANG', 'SALLAPADAN', 'SUBUSOB', 'UD-UDIAO']],
            ['municipality' => 'SAN ISIDRO', 'barangays' => ['CABAYOGAN', 'DALIMAG', 'LANGBABAN', 'MANAYDAY', 'PANTOC', 'POBLACION', 'SABTAN-OLO', 'SAN MARCIAL', 'TANGBAO']],
            ['municipality' => 'SAN JUAN', 'barangays' => ['ABUALAN', 'BA-UG', 'BADAS', 'CABCABORAO', 'COLABAOAN', 'CULIONG', 'DAOIDAO', 'GUIMBA', 'LAM-AG', 'LUMOBANG', 'NANGOBONGAN', 'PATTAOIG', 'POBLACION NORTH', 'POBLACION SOUTH', 'QUIDAOEN', 'SABANGAN', 'SILET', 'SUPI-IL', 'TAGAYTAY']],
            ['municipality' => 'SAN QUINTIN', 'barangays' => ['LABAAN', 'PALANG', 'PANTOC', 'POBLACION', 'TANGADAN', 'VILLA MERCEDES']],
            ['municipality' => 'TAYUM', 'barangays' => ['BAGALAY', 'BASBASA', 'BUDAC', 'BUMAGCAT', 'CABAROAN', 'DEET', 'GADDANI', 'PATUCANNAY', 'PIAS', 'POBLACION', 'VELASCO']],
            ['municipality' => 'TINEG', 'barangays' => ['ALAOA', 'ANAYAN', 'APAO', 'BELAAT', 'CAGANAYAN', 'COGON', 'LANEC', 'LAPAT-BALANTAY', 'NAGLIBACAN', 'POBLACION (AGSIMAO)']],
            ['municipality' => 'TUBO', 'barangays' => ['ALANGTIN', 'AMTUAGAN', 'DILONG', 'KILI', 'POBLACION (MAYABO)', 'SUPO', 'TABACDA', 'TIEMPO', 'TUBTUBA', 'WAYANGAN']],
            ['municipality' => 'VILLAVICIOSA', 'barangays' => ['AP-APAYA', 'BOL-LILISING', 'CAL-LAO', 'LAP-LAPOG', 'LUMABA', 'POBLACION', 'TAMAC', 'TUQUIB']],
        ]
    ],

    [
        'province' => 'BENGUET',
        'municipalities' => [
            ['municipality' => 'ATOK', 'barangays' => ['ABIANG', 'CALIKING', 'CATTUBO', 'NAGUEY', 'PAOAY', 'PASDONG', 'POBLACION', 'TOPDAC']],
            ['municipality' => 'BAGUIO CITY', 'barangays' => ['A. BONIFACIO-CAGUIOA-RIMANDO (ABCR)', 'ABANAO-ZANDUETA-KAYONG-CHUGUM-OTEK (AZKCO)', 'ALFONSO  TABORA', 'AMBIONG', 'ANDRES BONIFACIO (LOWER BOKAWKAN)', 'APUGAN-LOAKAN', 'ASIN ROAD', 'ATOK TRAIL', 'AURORA HILL PROPER (MALVAR-SGT. FLORESCA)', 'AURORA HILL, NORTH CENTRAL', 'AURORA HILL, SOUTH CENTRAL', 'BAKAKENG CENTRAL', 'BAKAKENG NORTH', 'BAL-MARCOVILLE (MARCOVILLE)', 'BALSIGAN', 'BAYAN PARK EAST', 'BAYAN PARK VILLAGE', 'BAYAN PARK WEST (BAYAN PARK)', 'BGH COMPOUND', 'BROOKSIDE', 'BROOKSPOINT', "CABINET HILL-TEACHER'S CAMP", 'CAMDAS SUBDIVISION', 'CAMP  7', 'CAMP  8', 'CAMP ALLEN', 'CAMPO FILIPINO', 'CITY CAMP CENTRAL', 'CITY CAMP PROPER', 'COUNTRY CLUB VILLAGE', 'CRESENCIA VILLAGE', 'DAGSIAN, LOWER', 'DAGSIAN, UPPER', 'DIZON SUBDIVISION', 'DOMINICAN HILL-MIRADOR', 'DONTOGAN', 'DPS AREA', "ENGINEERS' HILL", 'FAIRVIEW  VILLAGE', 'FERDINAND (HAPPY HOMES-CAMPO SIOCO)', 'FORT DEL PILAR', 'GABRIELA SILANG', 'GENERAL EMILIO F. AGUINALDO (QUIRINO-MAGSAYSAY, LOWER)', 'GENERAL LUNA, LOWER', 'GENERAL LUNA, UPPER', 'GIBRALTAR', 'GREENWATER VILLAGE', 'GUISAD CENTRAL', 'GUISAD SORONG', 'HAPPY HOLLOW', 'HAPPY HOMES (HAPPY HOMES-LUCBAN)', 'HARRISON-CLAUDIO CARANTES', 'HILLSIDE', 'HOLY GHOST EXTENSION', 'HOLY GHOST PROPER', 'HONEYMOON (HONEYMOON-HOLY GHOST)', 'IMELDA R. MARCOS (LA SALLE)', 'IMELDA VILLAGE', 'IRISAN', 'KABAYANIHAN', 'KAGITINGAN', 'KAYANG EXTENSION', 'KAYANG-HILLTOP', 'KIAS', 'LEGARDA-BURNHAM-KISAD', 'LIWANAG-LOAKAN', 'LOAKAN PROPER', 'LOPEZ JAENA', 'LOURDES SUBDIVISION EXTENSION', 'LOURDES SUBDIVISION, LOWER', 'LOURDES SUBDIVISION, PROPER', 'LUALHATI', 'LUCNAB', 'MAGSAYSAY PRIVATE ROAD', 'MAGSAYSAY, LOWER', 'MAGSAYSAY, UPPER', 'MALCOLM SQUARE-PERFECTO (JOSE ABAD SANTOS)', 'MANUEL A. ROXAS', 'MARKET SUBDIVISION, UPPER', 'MIDDLE QUEZON HILL SUBDIVISION(QUEZON HILL MIDDLE)', 'MILITARY CUT-OFF', 'MINES VIEW PARK', 'MODERN SITE, EAST', 'MODERN SITE, WEST', 'MRR-QUEEN OF PEACE', 'NEW LUCBAN', 'OUTLOOK DRIVE', 'PACDAL', 'PADRE BURGOS', 'PADRE ZAMORA', 'PALMA-URBANO (CARIÑO-PALMA)', 'PHIL-AM', 'PINGET', 'PINSAO PILOT PROJECT', 'PINSAO PROPER', 'POLIWES', 'PUCSUSAN', 'QUEZON HILL PROPER', 'QUEZON HILL, UPPER', 'QUIRINO HILL, EAST', 'QUIRINO HILL, LOWER', 'QUIRINO HILL, MIDDLE', 'QUIRINO HILL, WEST', 'QUIRINO-MAGSAYSAY, UPPER (UPPER QM)', 'RIZAL MONUMENT AREA', 'ROCK QUARRY, LOWER', 'ROCK QUARRY, MIDDLE', 'ROCK QUARRY, UPPER', 'SAINT JOSEPH VILLAGE', 'SALUD MITRA', 'SAN ANTONIO VILLAGE', 'SAN LUIS VILLAGE', 'SAN ROQUE VILLAGE', 'SAN VICENTE', 'SANITARY CAMP, NORTH', 'SANITARY CAMP, SOUTH', 'SANTA ESCOLASTICA', 'SANTO ROSARIO', 'SANTO TOMAS PROPER', 'SANTO TOMAS SCHOOL AREA', 'SCOUT BARRIO', 'SESSION ROAD AREA', 'SLAUGHTER HOUSE AREA  (SANTO NIÑO SLAUGHTER)', 'SLU-SVP HOUSING VILLAGE', 'SOUTH DRIVE', 'TEODORA ALONZO', 'TRANCOVILLE', 'VICTORIA VILLAGE']],
            ['municipality' => 'BAKUN', 'barangays' => ['AMPUSONGAN', 'BAGU', 'DALIPEY', 'GAMBANG', 'KAYAPA', 'POBLACION (CENTRAL)', 'SINACBAT']],
            ['municipality' => 'BOKOD', 'barangays' => ['AMBUCLAO', 'BILA', 'BOBOK-BISAL', 'DACLAN', 'EKIP', 'KARAO', 'NAWAL', 'PITO', 'POBLACION', 'TIKEY']],
            ['municipality' => 'BUGUIAS', 'barangays' => ['ABATAN', 'AMGALEYGUEY', 'AMLIMAY', 'BACULONGAN NORTE', 'BACULONGAN SUR', 'BANGAO', 'BUYACAOAN', 'CALAMAGAN', 'CATLUBONG', 'LENGAOAN', 'LOO', 'NATUBLENG', 'POBLACION (CENTRAL)', 'SEBANG']],
            ['municipality' => 'ITOGON', 'barangays' => ['AMPUCAO', 'DALUPIRIP', 'GUMATDANG', 'LOACAN', 'POBLACION (CENTRAL)', 'TINONGDAN', 'TUDING', 'UCAB', 'VIRAC']],
            ['municipality' => 'KABAYAN', 'barangays' => ['ADAOAY', 'ANCHUKEY', 'BALLAY', 'BASHOY', 'BATAN', 'DUACAN', 'EDDET', 'GUSARAN', 'KABAYAN  BARRIO', 'LUSOD', 'PACSO', 'POBLACION (CENTRAL)', 'TAWANGAN']],
            ['municipality' => 'KAPANGAN', 'barangays' => ['BALAKBAK', 'BELENG-BELIS', 'BOKLAOAN', 'CAYAPES', 'CUBA', 'DATAKAN', 'GADANG', 'GASWELING', 'LABUEG', 'PAYKEK', 'POBLACION CENTRAL', 'PONGAYAN', 'PUDONG', 'SAGUBO', 'TABA-AO']],
            ['municipality' => 'KIBUNGAN', 'barangays' => ['BADEO', 'LUBO', 'MADAYMEN', 'PALINA', 'POBLACION', 'SAGPAT', 'TACADANG']],
            ['municipality' => 'LA TRINIDAD', 'barangays' => ['ALAPANG', 'ALNO', 'AMBIONG', 'BAHONG', 'BALILI', 'BECKEL', 'BETAG', 'BINENG', 'CRUZ', 'LUBAS', 'PICO', 'POBLACION', 'PUGUIS', 'SHILAN', 'TAWANG', 'WANGAL']],
            ['municipality' => 'MANKAYAN', 'barangays' => ['BALILI', 'BEDBED', 'BULALACAO', 'CABITEN', 'COLALO', 'GUINAOANG', 'PACO', 'PALASAAN', 'POBLACION', 'SAPID', 'TABIO', 'TANEG']],
            ['municipality' => 'SABLAN', 'barangays' => ['BAGONG', 'BALLUAY', 'BANANGAN', 'BANENGBENG', 'BAYABAS', 'KAMOG', 'PAPPA', 'POBLACION']],
            ['municipality' => 'TUBA', 'barangays' => ['ANSAGAN', 'CAMP  3', 'CAMP  4', 'CAMP ONE', 'NANGALISAN', 'POBLACION', 'SAN PASCUAL', 'TABAAN NORTE', 'TABAAN SUR', 'TADIANGAN', 'TALOY NORTE', 'TALOY SUR', 'TWIN PEAKS']],
            ['municipality' => 'TUBLAY', 'barangays' => ['AMBASSADOR', 'AMBONGDOLAN', 'BA-AYAN', 'BASIL', 'CAPONGA (POB.)', 'DACLAN', 'TUBLAY CENTRAL', 'TUEL']],
        ]
    ],

    [
        'province' => 'IFUGAO',
        'municipalities' => [
            ['municipality' => 'AGUINALDO', 'barangays' => ['AWAYAN', 'BUNHIAN', 'BUTAC', 'BUWAG', 'CHALALO', 'DAMAG', 'GALONOGON', 'HALAG', 'ITAB', 'JACMAL', 'MAJLONG', 'MONGAYANG', 'POSNAAN', 'TA-ANG', 'TALITE', 'UBAO']],
            ['municipality' => 'ALFONSO LISTA', 'barangays' => ['BANGAR', 'BUSILAC', 'CALIMAG', 'CALUPAAN', 'CARAGASAN', 'DOLOWOG', 'KILING', 'LAYA', 'LITTLE TADIAN', 'NAMILLANGAN', 'NAMNAMA', 'NGILEB', 'PINTO', 'POBLACION', 'SAN JOSE', 'SAN JUAN', 'SAN MARCOS', 'SAN QUINTIN', 'SANTA MARIA', 'SANTO DOMINGO (CABICALAN)']],
            ['municipality' => 'ASIPULO', 'barangays' => ['AMDUNTOG', 'ANTIPOLO', 'CAMANDAG', 'CAWAYAN', 'HALLAP', 'NAMAL', 'NUNGAWA', 'PANUBTUBAN', 'PULA']],
            ['municipality' => 'BANAUE', 'barangays' => ['AMGANAD', 'ANABA', 'BALAWIS', 'BANAO', 'BANGAAN', 'BATAD', 'BOCOS', 'CAMBULO', 'DUCLIGAN', 'GOHANG', 'KINAKIN', 'OHAJ', 'POBLACION', 'POITAN', 'PULA', 'SAN FERNANDO', 'TAM-AN', 'VIEW POINT']],
            ['municipality' => 'HINGYON', 'barangays' => ['ANAO', 'BANGTINON', 'BITU', 'CABABUYAN', 'MOMPOLIA', 'NAMULDITAN', 'NORTHERN CABABUYAN', 'O-ONG', 'PIWONG', 'POBLACION (HINGYON)', 'UBUAG', 'UMALBONG']],
            ['municipality' => 'HUNGDUAN', 'barangays' => ['ABATAN', 'BA-ANG', 'BANGBANG', 'BOKIAWAN', 'HAPAO', 'LUBO-ONG', 'MAGGOK', 'NUNGULUNAN', 'POBLACION']],
            ['municipality' => 'KIANGAN', 'barangays' => ['AMBABAG', 'BAGUINGE', 'BOKIAWAN', 'BOLOG', 'DALLIGAN', 'DUIT', 'HUCAB', 'JULONGAN', 'LINGAY', 'MUNGAYANG', 'NAGACADAN', 'PINDONGAN', 'POBLACION', 'TUPLAC']],
            ['municipality' => 'LAGAWE', 'barangays' => ['ABINUAN', 'BANGA', 'BOLIWONG', 'BURNAY', 'BUYABUYAN', 'CABA', 'CUDOG', 'DULAO', 'JUCBONG', 'LUTA', 'MONTABIONG', 'OLILICON', 'POBLACION EAST', 'POBLACION NORTH', 'POBLACION SOUTH', 'POBLACION WEST', 'PONGHAL', 'PULLAAN', 'TUNGNGOD', 'TUPAYA']],
            ['municipality' => 'LAMUT', 'barangays' => ['AMBASA', 'BIMPAL', 'HAPID', 'HOLOWON', 'LAWIG', 'LUCBAN', 'MABATOBATO (LAMUT)', 'MAGULON', 'NAYON', 'PANOPDOPAN', 'PAYAWAN', 'PIEZA', 'POBLACION EAST', 'POBLACION WEST', 'PUGOL (IFUGAO RESERVATION)', 'SALAMAGUE', 'SANAFE', 'UMILAG']],
            ['municipality' => 'MAYOYAO', 'barangays' => ['ADUYONGAN', 'ALIMIT', 'AYANGAN', 'BALANGBANG', 'BANAO', 'BANHAL', 'BATO-ALATBANG', 'BONGAN', 'BUNINAN', 'CHAYA', 'CHUMANG', 'EPENG', 'GUINIHON', 'INWALOY', 'LANGAYAN', 'LIWO', 'MAGA', 'MAGULON', 'MAPAWOY', 'MAYOYAO PROPER', 'MONGOL', 'NALBU', 'NATTUM', 'PALAAD', 'POBLACION', 'TALBOC', 'TULAED']],
            ['municipality' => 'TINOC', 'barangays' => ['AHIN', 'AP-APID', 'BINABLAYAN', 'DANGGO', 'EHEB', 'GUMHANG', 'IMPUGONG', 'LUHONG', 'TINOC', 'TUKUCAN', 'TULLUDAN', 'WANGWANG']],
        ]
    ],

    [
        'province' => 'KALINGA-APAYAO',
        'municipalities' => [
            ['municipality' => 'BALBALAN', 'barangays' => ['ABABA-AN', 'BALANTOY', 'BALBALAN PROPER', 'BALBALASANG', 'BUAYA', 'DAO-ANGAN', 'GAWA-AN', 'MABACA', 'MALING (KABUGAO)', 'PANTIKIAN', 'POBLACION (SALEGSEG)', 'POSWOY', 'TALALANG', 'TAWANG']],
            ['municipality' => 'CALANASAN', 'barangays' => ['BUTAO', 'CADACLAN', 'DON ROQUE ABLAN SR.', 'ELEAZAR', 'EVA PUZON', 'KABUGAWAN', 'LANGNAO', 'LUBONG', 'MACALINO', 'NAGUILIAN', 'NAMALTUGAN', 'POBLACION', 'SABANGAN', 'SANTA ELENA', 'SANTA FILOMENA', 'TANGLAGAN', 'TUBANG', 'TUBONGAN']],
            ['municipality' => 'CONNER', 'barangays' => ['ALLANGIGAN', 'BANBAN', 'BULUAN', 'CAGLAYAN (NEW POB.)', 'CALAFUG', 'CUPIS', 'DAGA', 'GUINAANG', 'GUINAMGAMAN', 'ILI', 'KARIKITAN', 'KATABLANGAN', 'MALAMA', 'MANAG', 'MAWEGUI', 'NABUANGAN', 'PADDAOAN', 'PUGUIN', 'RIPANG (OLD POB.)', 'SACPIL', 'TALIFUGO']],
            ['municipality' => 'FLORA', 'barangays' => ['ALLIG', 'ANNINIPAN', 'ATOK', 'BAGUTONG', 'BALASI', 'BALLUYAN', 'MALAYUGAN', 'MALLIG', 'MALUBIBIT NORTE', 'MALUBIBIT SUR', 'POBLACION EAST', 'POBLACION WEST', 'SAN JOSE', 'SANTA MARIA', 'TAMALUNOG', 'UPPER ATOK (COLIMAN)']],
            ['municipality' => 'KABUGAO', 'barangays' => ['BADDUAT', 'BALIWANAN', 'BULU', 'CABETAYAN', 'DAGARA', 'DIBAGAT', 'KARAGAWAN', 'KUMAO', 'LACO', 'LENNENG (LIYYENG)', 'LUCAB', 'LUTTUACAN', 'MADATAG', 'MADDUANG', 'MAGABTA', 'MARAGAT', 'MUSIMUT', 'NAGBABALAYAN', 'POBLACION', 'TUYANGAN', 'WAGA']],
            ['municipality' => 'LUBUAGAN', 'barangays' => ['ANTONIO CANAO', 'DANGOY', 'LOWER UMA', 'MABILONG', 'MABONGTOT', 'POBLACION', 'TANGLAG', 'UMA DEL NORTE (WESTERN LUNA UMA)', 'UPPER UMA']],
            ['municipality' => 'LUNA', 'barangays' => ['BACSAY', 'CAGANDUNGAN', 'CALABIGAN', 'CANGISITAN', 'CAPAGAYPAYAN', 'DAGUPAN', 'LAPPA', 'LUYON', 'MARAG', 'POBLACION', 'QUIRINO', 'SALVACION', 'SAN FRANCISCO', 'SAN GREGORIO', 'SAN ISIDRO NORTE', 'SAN ISIDRO SUR', 'SAN SEBASTIAN', 'SANTA LINA', 'SHALOM', 'TUMOG', 'TUROD', 'ZUMIGUI']],
            ['municipality' => 'PASIL', 'barangays' => ['ABLEG', 'BAGTAYAN', 'BALATOC', 'BALENCIAGAO SUR', 'BALINCIAGAO NORTE', 'CAGALUAN', 'COLAYO', 'DALUPA', 'DANGTALAN', 'GALDANG (CASALOAN)', 'GUINA-ANG (POB.)', 'MAGSILAY', 'MALUCSAD', 'PUGONG']],
            ['municipality' => 'PINUKPUK', 'barangays' => ['ACIGA', 'ALLAGUIA', 'AMMACIAN', 'APATAN', 'ASIBANGLAN', 'BA-AY', 'BALLAYANGON', 'BAYAO', 'CAMALOG', 'CAWAGAYAN', 'DUGPA', 'KATABBOGAN', 'LIMOS', 'MAGAOGAO', 'MALAGNAT', 'MAPACO', 'PAKAWIT', 'PINOCOC', 'PINUKPUK JUNCTION', 'SOCBOT', 'TAGA (POB.)', 'TAGGAY', 'WAGUD']],
            ['municipality' => 'PUDTOL', 'barangays' => ['AGA', 'ALEM', 'AMADO', 'AURORA', 'CABATACAN', 'CACALAGGAN', 'CAPANNIKIAN', 'DOÑA LORETA', 'EMILIA', 'IMELDA', 'LOWER MATON', 'LT. BILAG', 'LYDIA', 'MALIBANG', 'MATAGUISI', 'POBLACION', 'SAN ANTONIO (PUGO)', 'SAN JOSE', 'SAN LUIS', 'SAN MARIANO', 'SWAN', 'UPPER MATON']],
            ['municipality' => 'RIZAL', 'barangays' => ['BABALAG EAST (POB.)', 'BABALAG WEST (POB.)', 'BULBOL', 'CALAOCAN', 'KINAMA', 'LIWAN EAST', 'LIWAN WEST', 'MACUTAY', 'ROMUALDEZ', 'SAN FRANCISCO', 'SAN PASCUAL', 'SAN PEDRO', 'SAN QUINTIN', 'SANTOR']],
            ['municipality' => 'SANTA MARCELA', 'barangays' => ['BAROCBOC', 'CONSUELO', 'EMILIANA', 'IMELDA (SIPA ANNEX)', 'MALEKKEG', 'MARCELA (POB.)', 'NUEVA', 'PANAY', 'SAN ANTONIO', 'SAN CARLOS', 'SAN JUAN', 'SAN MARIANO', 'SIPA PROPER']],
            ['municipality' => 'TABUK CITY', 'barangays' => ['AGBANNAWAG', 'AMLAO', 'APPAS', 'BADO DANGWA', 'BAGUMBAYAN', 'BALAWAG', 'BALONG', 'BANTAY', 'BULANAO', 'BULANAO NORTE', 'BULO', 'CABARITAN', 'CABARUAN', 'CALACCAD', 'CALANAN', 'CASIGAYAN', 'CUDAL', 'DAGUPAN CENTRO (POB.)', 'DAGUPAN WESTE', 'DILAG', 'DUPAG', 'GOBGOB', 'GUILAYON', 'IPIL', 'LACNOG', 'LANNA', 'LAYA EAST', 'LAYA WEST', 'LUCOG', 'MAGNAO', 'MAGSAYSAY', 'MALALAO', 'MALIN-AWA', 'MASABLANG', 'NAMBARAN', 'NAMBUCAYAN', 'NANENG', 'NEW TANGLAG', 'SAN JUAN', 'SAN JULIAN', 'SUYANG', 'TUGA']],
            ['municipality' => 'TANUDAN', 'barangays' => ['ANGGACAN', 'ANGGACAN SUR', 'BABBANOY', 'DACALAN', 'DUPLIGAN', 'GAANG', 'LAY-ASAN', 'LOWER LUBO', 'LOWER MANGALI', 'LOWER TALOCTOC', 'MABACA', 'MANGALI CENTRO', 'PANGOL', 'POBLACION', 'UPPER LUBO', 'UPPER TALOCTOC']],
            ['municipality' => 'TINGLAYAN', 'barangays' => ['AMBATO LEGLEG', 'BANGAD CENTRO', 'BASAO', 'BELONG MANUBAL', 'BUGNAY', 'BUSCALAN (BUSCALAN-LOCONG)', 'BUTBUT (BUTBUT-NGIBAT)', 'DANANAO', 'LOCCONG', 'LOWER BANGAD', 'LUPLUPA', 'MALLANGO', 'NGIBAT', 'OLD TINGLAYAN', 'POBLACION', 'SUMADEL  1', 'SUMADEL  2', 'TULGAO EAST', 'TULGAO WEST', 'UPPER BANGAD']],
        ]
    ],

    [
        'province' => 'MOUNTAIN PROVINCE',
        'municipalities' => [
            ['municipality' => 'BARLIG', 'barangays' => ['CHUPAC', 'FIANGTIN', 'GAWANA (POB.)', 'KALEO', 'LATANG', 'LIAS KANLURAN', 'LIAS SILANGAN', 'LINGOY', 'LUNAS', 'MACALANA', 'OGOOG']],
            ['municipality' => 'BAUKO', 'barangays' => ['ABATAN', 'BAGNEN ORIENTE', 'BAGNEN PROPER', 'BALINTAUGAN', 'BANAO', 'BILA (BUA)', 'GUINZADAN CENTRAL', 'GUINZADAN NORTE', 'GUINZADAN SUR', 'LAGAWA', 'LESEB', 'MABAAY', 'MAYAG', 'MONAMON NORTE', 'MONAMON SUR', 'MOUNT DATA', 'OTUCAN NORTE', 'OTUCAN SUR', 'POBLACION (BAUKO)', 'SADSADAN', 'SINTO', 'TAPAPAN']],
            ['municipality' => 'BESAO', 'barangays' => ['AGAWA', 'AMBAGUIO', 'BANGUITAN', 'BESAO EAST (BESAO PROPER)', 'BESAO WEST', 'CATENGAN', 'GUEDAY', 'KIN-IWAY (POB.)', 'LACMAAN', 'LAYLAYA', 'PANDANGAN', 'PAYEO', 'SUQUIB', 'TAMBOAN']],
            ['municipality' => 'BONTOC', 'barangays' => ['ALAB ORIENTE', 'ALAB PROPER', 'BALILI', 'BAYYO', 'BONTOC ILI', 'CALUTIT', 'CANEO', 'DALICAN', 'GONOGON', 'GUINAANG', 'MAINIT', 'MALIGCONG', 'POBLACION (BONTOC)', 'SAMOKI', 'TALUBIN', 'TOCUCAN']],
            ['municipality' => 'NATONIN', 'barangays' => ['ALUNOGAN', 'BALANGAO', 'BANAO', 'BANAWAL', 'BUTAC', 'MADUCAYAN', 'POBLACION', 'PUDO', 'SALIOK', 'SANTA ISABEL', 'TONGLAYAN']],
            ['municipality' => 'PARACELIS', 'barangays' => ['ANONAT', 'BACARNI', 'BANANAO', 'BANTAY', 'BUNOT', 'BURINGAL', 'BUTIGUE', 'PALITOD', 'POBLACION']],
            ['municipality' => 'SABANGAN', 'barangays' => ['BAO-ANGAN', 'BUN-AYAN', 'BUSA', 'CAMATAGAN', 'CAPINITAN', 'DATA', 'GAYANG', 'LAGAN', 'LOSAD', 'NAMATEC', 'NAPUA', 'PINGAD', 'POBLACION', 'SUPANG', 'TAMBINGAN']],
            ['municipality' => 'SADANGA', 'barangays' => ['ANABEL', 'BEKIGAN', 'BELWANG', 'BETWAGAN', 'DEMANG', 'POBLACION', 'SACASACAN', 'SACLIT']],
            ['municipality' => 'SAGADA', 'barangays' => ['AGUID', 'AMBASING', 'ANGKELING', 'ANTADAO', 'BALUGAN', 'BANGAAN', 'DAGDAG (POB.)', 'DEMANG (POB.)', 'FIDELISAN', 'KILONG', 'MADONGO', 'NACAGANG', 'PIDE', 'POBLACION (PATAY)', 'SUYO', 'TACCONG', 'TANULONG', 'TETEPAN NORTE', 'TETEPAN SUR']],
            ['municipality' => 'TADIAN', 'barangays' => ['BALAOA', 'BANAAO', 'BANTEY', 'BATAYAN', 'BUNGA', 'CADAD-ANAN', 'CAGUBATAN', 'DACUDAC', 'DUAGAN', 'KAYAN EAST', 'KAYAN WEST', 'LENGA', 'LUBON', 'MABALITE', 'MASLA', 'PANDAYAN', 'POBLACION', 'SUMADEL', 'TUE']],
        ]
    ],
];
