<?php
return array_map('trim', [
  ["province" => "AKLAN", "municipality" => "Altavas", "zip_code" => "5616"],
  ["province" => "AKLAN", "municipality" => "Balete", "zip_code" => "5614"],
  ["province" => "AKLAN", "municipality" => "Banga", "zip_code" => "5601"],
  ["province" => "AKLAN", "municipality" => "Batan", "zip_code" => "5615"],
  ["province" => "AKLAN", "municipality" => "Buruanga", "zip_code" => "5609"],
  ["province" => "AKLAN", "municipality" => "Ibajay", "zip_code" => "5613"],
  ["province" => "AKLAN", "municipality" => "Kalibo", "zip_code" => "5600"],
  ["province" => "AKLAN", "municipality" => "Lezo", "zip_code" => "5605"],
  ["province" => "AKLAN", "municipality" => "Libacao", "zip_code" => "5602"],
  ["province" => "AKLAN", "municipality" => "Madalag", "zip_code" => "5603"],
  ["province" => "AKLAN", "municipality" => "Makato", "zip_code" => "5611"],
  ["province" => "AKLAN", "municipality" => "Malay", "zip_code" => "5608"],
  ["province" => "AKLAN", "municipality" => "Malinao", "zip_code" => "5606"],
  ["province" => "AKLAN", "municipality" => "Nabas", "zip_code" => "5607"],
  ["province" => "AKLAN", "municipality" => "New Washington", "zip_code" => "5610"],
  ["province" => "AKLAN", "municipality" => "Numancia", "zip_code" => "5604"],
  ["province" => "AKLAN", "municipality" => "Tangalan", "zip_code" => "5612"],

  ["province" => "ANTIQUE", "municipality" => "Anini-y", "zip_code" => "5717"],
  ["province" => "ANTIQUE", "municipality" => "Barbaza", "zip_code" => "5706"],
  ["province" => "ANTIQUE", "municipality" => "Belison", "zip_code" => "5701"],
  ["province" => "ANTIQUE", "municipality" => "Bugasong", "zip_code" => "5704"],
  ["province" => "ANTIQUE", "municipality" => "Caluya", "zip_code" => "5711"],
  ["province" => "ANTIQUE", "municipality" => "Culasi", "zip_code" => "5708"],
  ["province" => "ANTIQUE", "municipality" => "Hamtic", "zip_code" => "5715"],
  ["province" => "ANTIQUE", "municipality" => "Laua-an", "zip_code" => "5705"],
  ["province" => "ANTIQUE", "municipality" => "Libertad", "zip_code" => "5710"],
  ["province" => "ANTIQUE", "municipality" => "Pandan", "zip_code" => "5712"],
  ["province" => "ANTIQUE", "municipality" => "Patnongon", "zip_code" => "5702"],
  ["province" => "ANTIQUE", "municipality" => "San Jose de Buanavista", "zip_code" => "5700"],
  ["province" => "ANTIQUE", "municipality" => "San Remegio", "zip_code" => "5714"],
  ["province" => "ANTIQUE", "municipality" => "Sebaste", "zip_code" => "5709"],
  ["province" => "ANTIQUE", "municipality" => "Sibalom", "zip_code" => "5713"],
  ["province" => "ANTIQUE", "municipality" => "Tibiao", "zip_code" => "5707"],
  ["province" => "ANTIQUE", "municipality" => "Tobias Fornier (Dao)", "zip_code" => "5716"],
  ["province" => "ANTIQUE", "municipality" => "Valderrama", "zip_code" => "5703"],

  ["province" => "CAPIZ", "municipality" => "Cuartero", "zip_code" => "5811"],
  ["province" => "CAPIZ", "municipality" => "Dao", "zip_code" => "5810"],
  ["province" => "CAPIZ", "municipality" => "Dumalag", "zip_code" => "5813"],
  ["province" => "CAPIZ", "municipality" => "Dumarao", "zip_code" => "5812"],
  ["province" => "CAPIZ", "municipality" => "Ivisan", "zip_code" => "5805"],
  ["province" => "CAPIZ", "municipality" => "Jamindan", "zip_code" => "5808"],
  ["province" => "CAPIZ", "municipality" => "Maayon", "zip_code" => "5809"],
  ["province" => "CAPIZ", "municipality" => "Mambusao", "zip_code" => "5807"],
  ["province" => "CAPIZ", "municipality" => "Panay", "zip_code" => "5801"],
  ["province" => "CAPIZ", "municipality" => "Panitan", "zip_code" => "5815"],
  ["province" => "CAPIZ", "municipality" => "Pilar", "zip_code" => "5804"],
  ["province" => "CAPIZ", "municipality" => "President Roxas", "zip_code" => "5803"],
  ["province" => "CAPIZ", "municipality" => "Pontevedra", "zip_code" => "5802"],
  ["province" => "CAPIZ", "municipality" => "Roxas City", "zip_code" => "5800"],
  ["province" => "CAPIZ", "municipality" => "Sapian", "zip_code" => "5806"],
  ["province" => "CAPIZ", "municipality" => "Sigma", "zip_code" => "5816"],
  ["province" => "CAPIZ", "municipality" => "Tapaz", "zip_code" => "5814"],

  ["province" => "GUIMARAS", "municipality" => "Buenavista", "zip_code" => "5044"],
  ["province" => "GUIMARAS", "municipality" => "Jordan", "zip_code" => "5045"],
  ["province" => "GUIMARAS", "municipality" => "Nueva Valencia", "zip_code" => "5046"],
  ["province" => "GUIMARAS", "municipality" => "San Lorenzo", "zip_code" => "5047"],
  ["province" => "GUIMARAS", "municipality" => "Sibunag", "zip_code" => "5048"],

  ["province" => "ILOILO", "municipality" => "Ajuy", "zip_code" => "5012"],
  ["province" => "ILOILO", "municipality" => "Alimodian", "zip_code" => "5028"],
  ["province" => "ILOILO", "municipality" => "Anilao", "zip_code" => "5009"],
  ["province" => "ILOILO", "municipality" => "Badiangan", "zip_code" => "5033"],
  ["province" => "ILOILO", "municipality" => "Balasan", "zip_code" => "5018"],
  ["province" => "ILOILO", "municipality" => "Banate", "zip_code" => "5010"],
  ["province" => "ILOILO", "municipality" => "Barotac Nuevo", "zip_code" => "5007"],
  ["province" => "ILOILO", "municipality" => "Barotac Viejo", "zip_code" => "5011"],
  ["province" => "ILOILO", "municipality" => "Batad", "zip_code" => "5016"],
  ["province" => "ILOILO", "municipality" => "Bingawan", "zip_code" => "5041"],
  ["province" => "ILOILO", "municipality" => "Cabatuan", "zip_code" => "5031"],
  ["province" => "ILOILO", "municipality" => "Calinog", "zip_code" => "5040"],
  ["province" => "ILOILO", "municipality" => "Carles", "zip_code" => "5019"],
  ["province" => "ILOILO", "municipality" => "Concepcion", "zip_code" => "5013"],
  ["province" => "ILOILO", "municipality" => "Dingle", "zip_code" => "5035"],
  ["province" => "ILOILO", "municipality" => "Dueñas", "zip_code" => "5038"],
  ["province" => "ILOILO", "municipality" => "Dumangas", "zip_code" => "5006"],
  ["province" => "ILOILO", "municipality" => "Estancia", "zip_code" => "5017"],
  ["province" => "ILOILO", "municipality" => "Guimbal", "zip_code" => "5022"],
  ["province" => "ILOILO", "municipality" => "Igbaras", "zip_code" => "5029"],
  ["province" => "ILOILO", "municipality" => "Iloilo City", "zip_code" => "5000"],
  ["province" => "ILOILO", "municipality" => "Janiuay", "zip_code" => "5034"],
  ["province" => "ILOILO", "municipality" => "Lambunao", "zip_code" => "5042"],
  ["province" => "ILOILO", "municipality" => "Leganes", "zip_code" => "5003"],
  ["province" => "ILOILO", "municipality" => "Lemery", "zip_code" => "5043"],
  ["province" => "ILOILO", "municipality" => "Leon", "zip_code" => "5026"],
  ["province" => "ILOILO", "municipality" => "Maasin", "zip_code" => "5030"],
  ["province" => "ILOILO", "municipality" => "Miagao", "zip_code" => "5023"],
  ["province" => "ILOILO", "municipality" => "Mina", "zip_code" => "5032"],
  ["province" => "ILOILO", "municipality" => "New Lucena", "zip_code" => "5005"],
  ["province" => "ILOILO", "municipality" => "Oton", "zip_code" => "5020"],
  ["province" => "ILOILO", "municipality" => "Passi", "zip_code" => "5037"],
  ["province" => "ILOILO", "municipality" => "Pavia", "zip_code" => "5001"],
  ["province" => "ILOILO", "municipality" => "Pototan", "zip_code" => "5008"],
  ["province" => "ILOILO", "municipality" => "San Dionisio", "zip_code" => "5015"],
  ["province" => "ILOILO", "municipality" => "San Enrique", "zip_code" => "5036"],
  ["province" => "ILOILO", "municipality" => "San Joaquin", "zip_code" => "5024"],
  ["province" => "ILOILO", "municipality" => "San Miguel", "zip_code" => "5025"],
  ["province" => "ILOILO", "municipality" => "San Rafael", "zip_code" => "5039"],
  ["province" => "ILOILO", "municipality" => "Santa Barbara", "zip_code" => "5002"],
  ["province" => "ILOILO", "municipality" => "Sara", "zip_code" => "5014"],
  ["province" => "ILOILO", "municipality" => "Tigbauan", "zip_code" => "5021"],
  ["province" => "ILOILO", "municipality" => "Tubungan", "zip_code" => "5027"],
  ["province" => "ILOILO", "municipality" => "Zarraga", "zip_code" => "5004"],

  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Bacolod City", "zip_code" => "6100"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Bago City", "zip_code" => "6101"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Binalbagan", "zip_code" => "6107"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Cadiz City", "zip_code" => "6121"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Calatrava", "zip_code" => "6126"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Candoni", "zip_code" => "6110"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Cauayan", "zip_code" => "6112"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Don Salvador Benedicto    ", "zip_code" => "6133"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Enrique Magalona      ", "zip_code" => "6118"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Escalante", "zip_code" => "6124"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Himamaylan", "zip_code" => "6108"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Hinigaran", "zip_code" => "6106"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Hinoba-an (Asia)", "zip_code" => "6114"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Ilog", "zip_code" => "6109"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Isabela", "zip_code" => "6128"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Kabankalan", "zip_code" => "6111"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "La Carlota City", "zip_code" => "6130"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "La Castellana", "zip_code" => "6131"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Manapla", "zip_code" => "6120"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Moises Padilla (Magallon)", "zip_code" => "6132"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Murcia", "zip_code" => "6129"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Paraiso (Fabrica)", "zip_code" => "6123"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Pontevedra", "zip_code" => "6105"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Pulupandan", "zip_code" => "6102"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Sagay", "zip_code" => "6122"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "San Carlos City", "zip_code" => "6127"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "San Enrique", "zip_code" => "6104"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Silay City", "zip_code" => "6116"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Silay Hawaiian Central", "zip_code" => "6117"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Sipalay", "zip_code" => "6113"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Talisay", "zip_code" => "6115"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Toboso", "zip_code" => "6125"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Valladolid", "zip_code" => "6103"],
  ["province" => "NEGROS OCCIDENTAL", "municipality" => "Victorias", "zip_code" => "6119"],
]);
