<?php
return array_map('trim', [
  ["province" => "NORTH COTABATO", "municipality" => "Alamada", "zip_code" => "9413"],
  ["province" => "NORTH COTABATO", "municipality" => "Aleosan", "zip_code" => "9415"],
  ["province" => "NORTH COTABATO", "municipality" => "Antipas", "zip_code" => "9414"],
  ["province" => "NORTH COTABATO", "municipality" => "Arakan", "zip_code" => "9417"],
  ["province" => "NORTH COTABATO", "municipality" => "Banisilan", "zip_code" => "9416"],
  ["province" => "NORTH COTABATO", "municipality" => "Carmen", "zip_code" => "9408"],
  ["province" => "NORTH COTABATO", "municipality" => "Kabacan", "zip_code" => "9407"],
  ["province" => "NORTH COTABATO", "municipality" => "Kidapawan", "zip_code" => "9400"],
  ["province" => "NORTH COTABATO", "municipality" => "Libungan", "zip_code" => "9411"],
  ["province" => "NORTH COTABATO", "municipality" => "Magpet", "zip_code" => "9404"],
  ["province" => "NORTH COTABATO", "municipality" => "Makilala", "zip_code" => "9401"],
  ["province" => "NORTH COTABATO", "municipality" => "Matalam", "zip_code" => "9406"],
  ["province" => "NORTH COTABATO", "municipality" => "Midsayap", "zip_code" => "9410"],
  ["province" => "NORTH COTABATO", "municipality" => "M'lang", "zip_code" => "9402"],
  ["province" => "NORTH COTABATO", "municipality" => "Pigkawayan", "zip_code" => "9412"],
  ["province" => "NORTH COTABATO", "municipality" => "Pikit", "zip_code" => "9409"],
  ["province" => "NORTH COTABATO", "municipality" => "Pre. Roxas", "zip_code" => "9405"],
  ["province" => "NORTH COTABATO", "municipality" => "Tulunan", "zip_code" => "9403"],

  ["province" => "SARANGANI", "municipality" => "Alabel", "zip_code" => "9501"],
  ["province" => "SARANGANI", "municipality" => "Glan", "zip_code" => "9517"],
  ["province" => "SARANGANI", "municipality" => "Kiamba", "zip_code" => "9514"],
  ["province" => "SARANGANI", "municipality" => "Maasim", "zip_code" => "9502"],
  ["province" => "SARANGANI", "municipality" => "Maitum", "zip_code" => "9515"],
  ["province" => "SARANGANI", "municipality" => "Malapatan", "zip_code" => "9516"],
  ["province" => "SARANGANI", "municipality" => "Malungon", "zip_code" => "9503"],

  ["province" => "SOUTH COTABATO", "municipality" => "Banga", "zip_code" => "9511"],
  ["province" => "SOUTH COTABATO", "municipality" => "Gen. Santos City", "zip_code" => "9500"],
  ["province" => "SOUTH COTABATO", "municipality" => "Koronadal", "zip_code" => "9506"],
  ["province" => "SOUTH COTABATO", "municipality" => "Lake Sebu", "zip_code" => "9518"],
  ["province" => "SOUTH COTABATO", "municipality" => "Norala", "zip_code" => "9508"],
  ["province" => "SOUTH COTABATO", "municipality" => "Polomolok", "zip_code" => "9504"],
  ["province" => "SOUTH COTABATO", "municipality" => "Sto. Niño", "zip_code" => "9509"],
  ["province" => "SOUTH COTABATO", "municipality" => "Surallah", "zip_code" => "9512"],
  ["province" => "SOUTH COTABATO", "municipality" => "Tampakan", "zip_code" => "9507"],
  ["province" => "SOUTH COTABATO", "municipality" => "Tantangan", "zip_code" => "9510"],
  ["province" => "SOUTH COTABATO", "municipality" => "T'boli", "zip_code" => "9513"],
  ["province" => "SOUTH COTABATO", "municipality" => "Tupi", "zip_code" => "9505"],

  ["province" => "SULTAN KUDARAT", "municipality" => "Bagumbayan", "zip_code" => "9810"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Columbio", "zip_code" => "9801"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Esperanza (Ampatuan)", "zip_code" => "9806"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Isulan", "zip_code" => "9805"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Kalamansig", "zip_code" => "9808"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Lebak (Salaman)", "zip_code" => "9807"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Lutayan", "zip_code" => "9803"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Mariano Marcos", "zip_code" => "9802"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Palimbang", "zip_code" => "9809"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Pres. Quirino", "zip_code" => "9804"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Sen. Ninoy Aquino", "zip_code" => "9811"],
  ["province" => "SULTAN KUDARAT", "municipality" => "Tacurong", "zip_code" => "9800"],
]);
