<?php
return [
  ["province" => "NORTH COTABATO", "municipality" => "ALAMADA", "zip_code" => "9413"],
  ["province" => "NORTH COTABATO", "municipality" => "ALEOSAN", "zip_code" => "9415"],
  ["province" => "NORTH COTABATO", "municipality" => "ANTIPAS", "zip_code" => "9414"],
  ["province" => "NORTH COTABATO", "municipality" => "ARAKAN", "zip_code" => "9417"],
  ["province" => "NORTH COTABATO", "municipality" => "BANISILAN", "zip_code" => "9416"],
  ["province" => "NORTH COTABATO", "municipality" => "CARMEN", "zip_code" => "9408"],
  ["province" => "NORTH COTABATO", "municipality" => "KABACAN", "zip_code" => "9407"],
  ["province" => "NORTH COTABATO", "municipality" => "KIDAPAWAN", "zip_code" => "9400"],
  ["province" => "NORTH COTABATO", "municipality" => "LIBUNGAN", "zip_code" => "9411"],
  ["province" => "NORTH COTABATO", "municipality" => "MAGPET", "zip_code" => "9404"],
  ["province" => "NORTH COTABATO", "municipality" => "MAKILALA", "zip_code" => "9401"],
  ["province" => "NORTH COTABATO", "municipality" => "MATALAM", "zip_code" => "9406"],
  ["province" => "NORTH COTABATO", "municipality" => "MIDSAYAP", "zip_code" => "9410"],
  ["province" => "NORTH COTABATO", "municipality" => "M'LANG", "zip_code" => "9402"],
  ["province" => "NORTH COTABATO", "municipality" => "PIGKAWAYAN", "zip_code" => "9412"],
  ["province" => "NORTH COTABATO", "municipality" => "PIKIT", "zip_code" => "9409"],
  ["province" => "NORTH COTABATO", "municipality" => "PRES. ROXAS", "zip_code" => "9405"],
  ["province" => "NORTH COTABATO", "municipality" => "TULUNAN", "zip_code" => "9403"],

  ["province" => "SARANGANI", "municipality" => "ALABEL", "zip_code" => "9501"],
  ["province" => "SARANGANI", "municipality" => "GLAN", "zip_code" => "9517"],
  ["province" => "SARANGANI", "municipality" => "KIAMBA", "zip_code" => "9514"],
  ["province" => "SARANGANI", "municipality" => "MAASIM", "zip_code" => "9502"],
  ["province" => "SARANGANI", "municipality" => "MAITUM", "zip_code" => "9515"],
  ["province" => "SARANGANI", "municipality" => "MALAPATAN", "zip_code" => "9516"],
  ["province" => "SARANGANI", "municipality" => "MALUNGON", "zip_code" => "9503"],

  ["province" => "SOUTH COTABATO", "municipality" => "BANGA", "zip_code" => "9511"],
  ["province" => "SOUTH COTABATO", "municipality" => "GEN. SANTOS CITY", "zip_code" => "9500"],
  ["province" => "SOUTH COTABATO", "municipality" => "KORONADAL", "zip_code" => "9506"],
  ["province" => "SOUTH COTABATO", "municipality" => "LAKE SEBU", "zip_code" => "9518"],
  ["province" => "SOUTH COTABATO", "municipality" => "NORALA", "zip_code" => "9508"],
  ["province" => "SOUTH COTABATO", "municipality" => "POLOMOLOK", "zip_code" => "9504"],
  ["province" => "SOUTH COTABATO", "municipality" => "STO. NIÑO", "zip_code" => "9509"],
  ["province" => "SOUTH COTABATO", "municipality" => "SURALLAH", "zip_code" => "9512"],
  ["province" => "SOUTH COTABATO", "municipality" => "TAMPAKAN", "zip_code" => "9507"],
  ["province" => "SOUTH COTABATO", "municipality" => "TANTANGAN", "zip_code" => "9510"],
  ["province" => "SOUTH COTABATO", "municipality" => "T'BOLI", "zip_code" => "9513"],
  ["province" => "SOUTH COTABATO", "municipality" => "TUPI", "zip_code" => "9505"],

  ["province" => "SULTAN KUDARAT", "municipality" => "BAGUMBAYAN", "zip_code" => "9810"],
  ["province" => "SULTAN KUDARAT", "municipality" => "COLUMBIO", "zip_code" => "9801"],
  ["province" => "SULTAN KUDARAT", "municipality" => "ESPERANZA (AMPATUAN)", "zip_code" => "9806"],
  ["province" => "SULTAN KUDARAT", "municipality" => "ISULAN", "zip_code" => "9805"],
  ["province" => "SULTAN KUDARAT", "municipality" => "KALAMANSIG", "zip_code" => "9808"],
  ["province" => "SULTAN KUDARAT", "municipality" => "LEBAK (SALAMAN)", "zip_code" => "9807"],
  ["province" => "SULTAN KUDARAT", "municipality" => "LUTAYAN", "zip_code" => "9803"],
  ["province" => "SULTAN KUDARAT", "municipality" => "MARIANO MARCOS", "zip_code" => "9802"],
  ["province" => "SULTAN KUDARAT", "municipality" => "PALIMBANG", "zip_code" => "9809"],
  ["province" => "SULTAN KUDARAT", "municipality" => "PRES. QUIRINO", "zip_code" => "9804"],
  ["province" => "SULTAN KUDARAT", "municipality" => "SEN. NINOY AQUINO", "zip_code" => "9811"],
  ["province" => "SULTAN KUDARAT", "municipality" => "TACURONG", "zip_code" => "9800"],
];
