<?php
return  [
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Baliguian", "zip_code" => "7123"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Dapitan City", "zip_code" => "7101"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Dipolog City", "zip_code" => "7100"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Godod", "zip_code" => "7126"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Gutalac", "zip_code" => "7118"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Jose Dalman (Ponot)", "zip_code" => "7111"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Kalawit", "zip_code" => "7124"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Katipunan", "zip_code" => "7109"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "La Libertad", "zip_code" => "7119"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Labason", "zip_code" => "7117"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Leon B. Postigo (Bacungan)", "zip_code" => "7125"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Liloy", "zip_code" => "7115"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Manukan", "zip_code" => "7110"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Mutia", "zip_code" => "7107"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Piñan (New Piñan)", "zip_code" => "7105"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Polanco", "zip_code" => "7106"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "President Manuel A. Roxas", "zip_code" => "7102"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Rizal", "zip_code" => "7104"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Salug", "zip_code" => "7114"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Sergio Osmeña", "zip_code" => "7108"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Siayan", "zip_code" => "7113"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Sibuco", "zip_code" => "7122"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Sibutad", "zip_code" => "7103"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Sindangan", "zip_code" => "7112"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Siocon", "zip_code" => "7120"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Siraway", "zip_code" => "7121"],
  ["province" => "ZAMBOANGA DEL NORTE", "municipality" => "Tampilisan", "zip_code" => "7116"],

  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Aurora", "zip_code" => "7020"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Bayog", "zip_code" => "7011"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Dimataling", "zip_code" => "7032"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Dinas", "zip_code" => "7030"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Don Mariano Marcos", "zip_code" => "7022"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Dumalinao", "zip_code" => "7015"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Dumingag", "zip_code" => "7028"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Guipos", "zip_code" => "7042"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Josefina", "zip_code" => "7027"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Kumalarang", "zip_code" => "7013"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Labangan", "zip_code" => "7017"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Lakewood", "zip_code" => "7014"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Lapuyan", "zip_code" => "7037"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Mahayag", "zip_code" => "7026"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Margo sa Tubig", "zip_code" => "7035"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Midsalip", "zip_code" => "7021"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Molave", "zip_code" => "7023"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Pagadian City", "zip_code" => "7016"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Pitogo", "zip_code" => "7033"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Ramon Magsaysay", "zip_code" => "7024"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "San Miguel", "zip_code" => "7029"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "San Pablo", "zip_code" => "7031"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Tabina", "zip_code" => "7034"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Tambulig", "zip_code" => "7025"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Tigbao", "zip_code" => "7043"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Tukuran", "zip_code" => "7019"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Vicencio Sagun", "zip_code" => "7036"],
  ["province" => "ZAMBOANGA DEL SUR", "municipality" => "Zamboanga City", "zip_code" => "7000"],

  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Alicia", "zip_code" => "7040"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Buug", "zip_code" => "7009"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Diplahan", "zip_code" => "7039"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Imelda", "zip_code" => "7007"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Ipil", "zip_code" => "7001"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Kabasalan", "zip_code" => "7005"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Mabuhay", "zip_code" => "7010"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Malangas", "zip_code" => "7038"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Naga", "zip_code" => "7004"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Olutanga", "zip_code" => "7041"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Payao", "zip_code" => "7008"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Roseller Lim", "zip_code" => "7002"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Siay", "zip_code" => "7006"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Talusan", "zip_code" => "7012"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Titay", "zip_code" => "7003"],
  ["province" => "ZAMBOANGA SIBUGAY", "municipality" => "Tungawan", "zip_code" => "7018"],
];
