<?php

declare(strict_types=1);
return [
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'BALIGUIAN', 'zip_code' => '7123'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'DAPITAN CITY', 'zip_code' => '7101'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'DIPOLOG CITY', 'zip_code' => '7100'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'GODOD', 'zip_code' => '7126'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'GUTALAC', 'zip_code' => '7118'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'JOSE DALMAN (PONOT)', 'zip_code' => '7111'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'KALAWIT', 'zip_code' => '7124'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'KATIPUNAN', 'zip_code' => '7109'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'LA LIBERTAD', 'zip_code' => '7119'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'LABASON', 'zip_code' => '7117'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'LEON B. POSTIGO (BACUNGAN)', 'zip_code' => '7125'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'LILOY', 'zip_code' => '7115'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'MANUKAN', 'zip_code' => '7110'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'MUTIA', 'zip_code' => '7107'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'PIÑAN (NEW PIÑAN)', 'zip_code' => '7105'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'POLANCO', 'zip_code' => '7106'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'PRESIDENT MANUEL A. ROXAS', 'zip_code' => '7102'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'RIZAL', 'zip_code' => '7104'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SALUG', 'zip_code' => '7114'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SERGIO OSMEÑA', 'zip_code' => '7108'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SIAYAN', 'zip_code' => '7113'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SIBUCO', 'zip_code' => '7122'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SIBUTAD', 'zip_code' => '7103'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SINDANGAN', 'zip_code' => '7112'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SIOCON', 'zip_code' => '7120'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'SIRAWAY', 'zip_code' => '7121'],
    ['province' => 'ZAMBOANGA DEL NORTE', 'municipality' => 'TAMPILISAN', 'zip_code' => '7116'],

    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'AURORA', 'zip_code' => '7020'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'BAYOG', 'zip_code' => '7011'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'DIMATALING', 'zip_code' => '7032'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'DINAS', 'zip_code' => '7030'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'DON MARIANO MARCOS', 'zip_code' => '7022'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'DUMALINAO', 'zip_code' => '7015'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'DUMINGAG', 'zip_code' => '7028'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'GUIPOS', 'zip_code' => '7042'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'JOSEFINA', 'zip_code' => '7027'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'KUMALARANG', 'zip_code' => '7013'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'LABANGAN', 'zip_code' => '7017'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'LAKEWOOD', 'zip_code' => '7014'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'LAPUYAN', 'zip_code' => '7037'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'MAHAYAG', 'zip_code' => '7026'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'MARGO SA TUBIG', 'zip_code' => '7035'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'MIDSALIP', 'zip_code' => '7021'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'MOLAVE', 'zip_code' => '7023'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'PAGADIAN CITY', 'zip_code' => '7016'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'PITOGO', 'zip_code' => '7033'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'RAMON MAGSAYSAY', 'zip_code' => '7024'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'SAN MIGUEL', 'zip_code' => '7029'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'SAN PABLO', 'zip_code' => '7031'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'TABINA', 'zip_code' => '7034'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'TAMBULIG', 'zip_code' => '7025'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'TIGBAO', 'zip_code' => '7043'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'TUKURAN', 'zip_code' => '7019'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'VICENCIO SAGUN', 'zip_code' => '7036'],
    ['province' => 'ZAMBOANGA DEL SUR', 'municipality' => 'ZAMBOANGA CITY', 'zip_code' => '7000'],

    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'ALICIA', 'zip_code' => '7040'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'BUUG', 'zip_code' => '7009'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'DIPLAHAN', 'zip_code' => '7039'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'IMELDA', 'zip_code' => '7007'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'IPIL', 'zip_code' => '7001'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'KABASALAN', 'zip_code' => '7005'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'MABUHAY', 'zip_code' => '7010'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'MALANGAS', 'zip_code' => '7038'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'NAGA', 'zip_code' => '7004'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'OLUTANGA', 'zip_code' => '7041'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'PAYAO', 'zip_code' => '7008'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'ROSELLER LIM', 'zip_code' => '7002'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'SIAY', 'zip_code' => '7006'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'TALUSAN', 'zip_code' => '7012'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'TITAY', 'zip_code' => '7003'],
    ['province' => 'ZAMBOANGA SIBUGAY', 'municipality' => 'TUNGAWAN', 'zip_code' => '7018'],
];
