<?php
return  [
  ["province" => "BASILAN", "municipality" => "Akbar", "zip_code" => "7307"],
  ["province" => "BASILAN", "municipality" => "Al-Barka", "zip_code" => "7308"],
  ["province" => "BASILAN", "municipality" => "Hadji Mohammad Ajul", "zip_code" => "7309"],
  ["province" => "BASILAN", "municipality" => "Hadji Muhtamad", "zip_code" => "7310"],
  ["province" => "BASILAN", "municipality" => "Isabela de Basilan         ", "zip_code" => "7300"],
  ["province" => "BASILAN", "municipality" => "Lamitan", "zip_code" => "7302"],
  ["province" => "BASILAN", "municipality" => "Lantawan", "zip_code" => "7301"],
  ["province" => "BASILAN", "municipality" => "Maluso", "zip_code" => "7303"],
  ["province" => "BASILAN", "municipality" => "Sumisip", "zip_code" => "7305"],
  ["province" => "BASILAN", "municipality" => "Tabuan-Lasa", "zip_code" => "7312"],
  ["province" => "BASILAN", "municipality" => "Tipo-Tipo", "zip_code" => "7304"],
  ["province" => "BASILAN", "municipality" => "Tuburan", "zip_code" => "7306"],
  ["province" => "BASILAN", "municipality" => "Ungkaya Pukan", "zip_code" => "7311"],

  ["province" => "LANAO DEL SUR", "municipality" => "Bacolod Grande", "zip_code" => "9316"],
  ["province" => "LANAO DEL SUR", "municipality" => "Balabagan", "zip_code" => "9302"],
  ["province" => "LANAO DEL SUR", "municipality" => "Bayang", "zip_code" => "9309"],
  ["province" => "LANAO DEL SUR", "municipality" => "Balindong", "zip_code" => "9318"],
  ["province" => "LANAO DEL SUR", "municipality" => "Binidayan", "zip_code" => "9310"],
  ["province" => "LANAO DEL SUR", "municipality" => "Buadiposo Buntong", "zip_code" => "9714"],
  ["province" => "LANAO DEL SUR", "municipality" => "Bubong", "zip_code" => "9708"],
  ["province" => "LANAO DEL SUR", "municipality" => "Bumbaran", "zip_code" => "9320"],
  ["province" => "LANAO DEL SUR", "municipality" => "Butig", "zip_code" => "9305"],
  ["province" => "LANAO DEL SUR", "municipality" => "Calanogas", "zip_code" => "9319"],
  ["province" => "LANAO DEL SUR", "municipality" => "Ganassi", "zip_code" => "9311"],
  ["province" => "LANAO DEL SUR", "municipality" => "Kapai", "zip_code" => "9709"],
  ["province" => "LANAO DEL SUR", "municipality" => "Kapatagan", "zip_code" => "9322"],
  ["province" => "LANAO DEL SUR", "municipality" => "Lumba Bayabao", "zip_code" => "9703"],
  ["province" => "LANAO DEL SUR", "municipality" => "Lumbaca Unayan", "zip_code" => "9323"],
  ["province" => "LANAO DEL SUR", "municipality" => "Lumbatan", "zip_code" => "9307"],
  ["province" => "LANAO DEL SUR", "municipality" => "Lumbayanague", "zip_code" => "9306"],
  ["province" => "LANAO DEL SUR", "municipality" => "Macador Andong", "zip_code" => "9308"],
  ["province" => "LANAO DEL SUR", "municipality" => "Madalum", "zip_code" => "9315"],
  ["province" => "LANAO DEL SUR", "municipality" => "Madamba", "zip_code" => "9314"],
  ["province" => "LANAO DEL SUR", "municipality" => "Maguing", "zip_code" => "9715"],
  ["province" => "LANAO DEL SUR", "municipality" => "Malabang", "zip_code" => "9300"],
  ["province" => "LANAO DEL SUR", "municipality" => "Marantao", "zip_code" => "9711"],
  ["province" => "LANAO DEL SUR", "municipality" => "Marawi City", "zip_code" => "9700"],
  ["province" => "LANAO DEL SUR", "municipality" => "Marogong", "zip_code" => "9303"],
  ["province" => "LANAO DEL SUR", "municipality" => "Masiu", "zip_code" => "9706"],
  ["province" => "LANAO DEL SUR", "municipality" => "Mulondo", "zip_code" => "9702"],
  ["province" => "LANAO DEL SUR", "municipality" => "Pagayawan", "zip_code" => "9312"],
  ["province" => "LANAO DEL SUR", "municipality" => "Piagapo", "zip_code" => "9710"],
  ["province" => "LANAO DEL SUR", "municipality" => "Picong (formerly Sultan Gumander)", "zip_code" => "9301"],
  ["province" => "LANAO DEL SUR", "municipality" => "Poona Bayabao", "zip_code" => "9705"],
  ["province" => "LANAO DEL SUR", "municipality" => "Pualas", "zip_code" => "9313"],
  ["province" => "LANAO DEL SUR", "municipality" => "Ramain-Ditsaan", "zip_code" => "9713"],
  ["province" => "LANAO DEL SUR", "municipality" => "Saguiaran", "zip_code" => "9701"],
  ["province" => "LANAO DEL SUR", "municipality" => "Sultan Domalondong", "zip_code" => "9324"],
  ["province" => "LANAO DEL SUR", "municipality" => "Sultan Gumander", "zip_code" => "9301"],
  ["province" => "LANAO DEL SUR", "municipality" => "Tagoloan - II", "zip_code" => "9321"],
  ["province" => "LANAO DEL SUR", "municipality" => "Tamparan", "zip_code" => "9704"],
  ["province" => "LANAO DEL SUR", "municipality" => "Taraka", "zip_code" => "9712"],
  ["province" => "LANAO DEL SUR", "municipality" => "Tubaran", "zip_code" => "9304"],
  ["province" => "LANAO DEL SUR", "municipality" => "Tugaya", "zip_code" => "9317"],
  ["province" => "LANAO DEL SUR", "municipality" => "Wao", "zip_code" => "9716"],

  ["province" => "MAGUINDANAO", "municipality" => "Ampatuan", "zip_code" => "9609"],
  ["province" => "MAGUINDANAO", "municipality" => "Barira", "zip_code" => "9614"],
  ["province" => "MAGUINDANAO", "municipality" => "Buldon", "zip_code" => "9615"],
  ["province" => "MAGUINDANAO", "municipality" => "Buluan", "zip_code" => "9616"],
  ["province" => "MAGUINDANAO", "municipality" => "Cotabato City", "zip_code" => "9600"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Odin Sinsuat (Dinaig)", "zip_code" => "9601"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Paglas", "zip_code" => "9617"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Piang", "zip_code" => "9607"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Abdullah Sangki", "zip_code" => "9621"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Anggal Midtimbang", "zip_code" => "9622"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Blah T. Sinsuat", "zip_code" => "9623"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Hoffer Ampatuan", "zip_code" => "9624"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Montawal (formerly Pagagawan)", "zip_code" => "9631"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Salibo", "zip_code" => "9625"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Saudi-Ampatuan", "zip_code" => "9626"],
  ["province" => "MAGUINDANAO", "municipality" => "Datu Unsay", "zip_code" => "9627"],
  ["province" => "MAGUINDANAO", "municipality" => "General Salipada K. Pendatun", "zip_code" => "9618"],
  ["province" => "MAGUINDANAO", "municipality" => "Guindulungan", "zip_code" => "9628"],
  ["province" => "MAGUINDANAO", "municipality" => "Kabuntulan", "zip_code" => "9606"],
  ["province" => "MAGUINDANAO", "municipality" => "Shariff Aguak (formerly Maganoy)", "zip_code" => "9608"],
  ["province" => "MAGUINDANAO", "municipality" => "Mamasapano", "zip_code" => "9629"],
  ["province" => "MAGUINDANAO", "municipality" => "Mangudadatu", "zip_code" => "9620"],
  ["province" => "MAGUINDANAO", "municipality" => "Matanog", "zip_code" => "9613"],
  ["province" => "MAGUINDANAO", "municipality" => "Northern Kabuntalan", "zip_code" => "9630"],
  ["province" => "MAGUINDANAO", "municipality" => "Paglat", "zip_code" => "9632"],
  ["province" => "MAGUINDANAO", "municipality" => "Pandag", "zip_code" => "9633"],
  ["province" => "MAGUINDANAO", "municipality" => "Pagalungan", "zip_code" => "9610"],
  ["province" => "MAGUINDANAO", "municipality" => "Parang", "zip_code" => "9604"],
  ["province" => "MAGUINDANAO", "municipality" => "Rajah Buayan", "zip_code" => "9634"],
  ["province" => "MAGUINDANAO", "municipality" => "Shariff Saydona Mustapha", "zip_code" => "9635"],
  ["province" => "MAGUINDANAO", "municipality" => "Sultan Mastura", "zip_code" => "9636"],
  ["province" => "MAGUINDANAO", "municipality" => "Sultan Sumagka (formerly Talitay)", "zip_code" => "9637"],
  ["province" => "MAGUINDANAO", "municipality" => "South Upi", "zip_code" => "9603"],
  ["province" => "MAGUINDANAO", "municipality" => "Sultan Kudarat", "zip_code" => "9605"],
  ["province" => "MAGUINDANAO", "municipality" => "Sultan Sa Barongis", "zip_code" => "9611"],
  ["province" => "MAGUINDANAO", "municipality" => "Talayan", "zip_code" => "9612"],
  ["province" => "MAGUINDANAO", "municipality" => "Upi", "zip_code" => "9602"],

  ["province" => "SULU", "municipality" => "Banguingui (formerly Tongkil) ", "zip_code" => "7406"],
  ["province" => "SULU", "municipality" => "Hadji Panglima Tahil (formerly Marungas)", "zip_code" => "7413"],
  ["province" => "SULU", "municipality" => "Indanan", "zip_code" => "7407"],
  ["province" => "SULU", "municipality" => "Jolo", "zip_code" => "7400"],
  ["province" => "SULU", "municipality" => "Kalingalan Kalauang", "zip_code" => "7416"],
  ["province" => "SULU", "municipality" => "Lugus", "zip_code" => "7411"],
  ["province" => "SULU", "municipality" => "Luuk", "zip_code" => "7404"],
  ["province" => "SULU", "municipality" => "Maimbung", "zip_code" => "7409"],
  ["province" => "SULU", "municipality" => "Omar", "zip_code" => "7417"],
  ["province" => "SULU", "municipality" => "Panamao", "zip_code" => "7402"],
  ["province" => "SULU", "municipality" => "Pandami", "zip_code" => "7418"],
  ["province" => "SULU", "municipality" => "Panglima Estino", "zip_code" => "7415"],
  ["province" => "SULU", "municipality" => "Panguntaran", "zip_code" => "7414"],
  ["province" => "SULU", "municipality" => "Parang", "zip_code" => "7408"],
  ["province" => "SULU", "municipality" => "Pata", "zip_code" => "7405"],
  ["province" => "SULU", "municipality" => "Patikul", "zip_code" => "7401"],
  ["province" => "SULU", "municipality" => "Siasi", "zip_code" => "7412"],
  ["province" => "SULU", "municipality" => "Talipao", "zip_code" => "7403"],
  ["province" => "SULU", "municipality" => "Tapul", "zip_code" => "7410"],

  ["province" => "TAWI-TAWI", "municipality" => "Bongao", "zip_code" => "7500"],
  ["province" => "TAWI-TAWI", "municipality" => "Languyan ", "zip_code" => "7509"],
  ["province" => "TAWI-TAWI", "municipality" => "Mapun (formerly Cagayan de Sulu)", "zip_code" => "7508"],
  ["province" => "TAWI-TAWI", "municipality" => "Panglima Sugala (formerly Balimbing)", "zip_code" => "7501"],
  ["province" => "TAWI-TAWI", "municipality" => "Sapa-Sapa", "zip_code" => "7503"],
  ["province" => "TAWI-TAWI", "municipality" => "Sibutu", "zip_code" => "7510"],
  ["province" => "TAWI-TAWI", "municipality" => "Simunul", "zip_code" => "7505"],
  ["province" => "TAWI-TAWI", "municipality" => "Sitangkai", "zip_code" => "7506"],
  ["province" => "TAWI-TAWI", "municipality" => "South Ubian", "zip_code" => "7504"],
  ["province" => "TAWI-TAWI", "municipality" => "Turtle Island (Taganak)", "zip_code" => "7507"],
  ["province" => "TAWI-TAWI", "municipality" => "Tandu Bas", "zip_code" => "7502"],
];
