<?php

declare(strict_types=1);

return [
    [
        'province' => 'BILIRAN',
        'zip_codes' => [
            ['municipality' => 'ALMERIA', 'zip_code' => '6544'],
            ['municipality' => 'BILIRAN', 'zip_code' => '6549'],
            ['municipality' => 'CABUCGAYAN', 'zip_code' => '6550'],
            ['municipality' => 'CAIBIRAN', 'zip_code' => '6548'],
            ['municipality' => 'CULABA', 'zip_code' => '6547'],
            ['municipality' => 'KAWAYAN', 'zip_code' => '6545'],
            ['municipality' => 'MARIPIPI', 'zip_code' => '6546'],
            ['municipality' => 'NAVAL', 'zip_code' => '6543'],
        ]
    ],

    [
        'province' => 'EASTERN SAMAR',
        'zip_codes' => [
            ['municipality' => 'ARTECHE', 'zip_code' => '6822'],
            ['municipality' => 'BALANGIGA', 'zip_code' => '6812'],
            ['municipality' => 'BALANGKAYAN', 'zip_code' => '6801'],
            ['municipality' => 'BORONGAN', 'zip_code' => '6800'],
            ['municipality' => 'CAN-AVID', 'zip_code' => '6806'],
            ['municipality' => 'DOLORES', 'zip_code' => '6817'],
            ['municipality' => 'GENERAL MACARTHUR', 'zip_code' => '6805'],
            ['municipality' => 'GIPORLOS', 'zip_code' => '6811'],
            ['municipality' => 'GUIUAN', 'zip_code' => '6809'],
            ['municipality' => 'HERNANI', 'zip_code' => '6804'],
            ['municipality' => 'JIPAPAD', 'zip_code' => '6819'],
            ['municipality' => 'LAWAAN', 'zip_code' => '6813'],
            ['municipality' => 'LLORENTE', 'zip_code' => '6803'],
            ['municipality' => 'MASLOG', 'zip_code' => '6820'],
            ['municipality' => 'MAYDOLONG', 'zip_code' => '6802'],
            ['municipality' => 'MERCEDES', 'zip_code' => '6808'],
            ['municipality' => 'ORAS', 'zip_code' => '6818'],
            ['municipality' => 'QUINAPONDAN', 'zip_code' => '6810'],
            ['municipality' => 'SALCEDO', 'zip_code' => '6807'],
            ['municipality' => 'SAN JULIAN', 'zip_code' => '6814'],
            ['municipality' => 'SAN POLICARPIO', 'zip_code' => '6821'],
            ['municipality' => 'SULAT', 'zip_code' => '6815'],
            ['municipality' => 'TAFT', 'zip_code' => '6816'],
        ]
    ],

    [
        'province' => 'LEYTE',
        'zip_codes' => [
            ['municipality' => 'ABUYOG', 'zip_code' => '6510'],
            ['municipality' => 'ALANGALANG', 'zip_code' => '6517'],
            ['municipality' => 'ALBUERA', 'zip_code' => '6542'],
            ['municipality' => 'BABATNGON', 'zip_code' => '6520'],
            ['municipality' => 'BURAUEN', 'zip_code' => '6516'],
            ['municipality' => 'BARUGO', 'zip_code' => '6519'],
            ['municipality' => 'BATO', 'zip_code' => '6525'],
            ['municipality' => 'BAYBAY', 'zip_code' => '6521'],
            ['municipality' => 'CALUBIAN', 'zip_code' => '6534'],
            ['municipality' => 'CAPOOCAN', 'zip_code' => '6530'],
            ['municipality' => 'CARIGARA', 'zip_code' => '6529'],
            ['municipality' => 'DAGAMI', 'zip_code' => '6515'],
            ['municipality' => 'DULAG', 'zip_code' => '6505'],
            ['municipality' => 'HILONGOS', 'zip_code' => '6524'],
            ['municipality' => 'HINDANG', 'zip_code' => '6523'],
            ['municipality' => 'INOPACAN', 'zip_code' => '6522'],
            ['municipality' => 'ISABEL', 'zip_code' => '6539'],
            ['municipality' => 'JARO', 'zip_code' => '6527'],
            ['municipality' => 'JAVIER (BUGHO)', 'zip_code' => '6511'],
            ['municipality' => 'JULITA', 'zip_code' => '6506'],
            ['municipality' => 'KANANGA', 'zip_code' => '6531'],
            ['municipality' => 'LA PAZ', 'zip_code' => '6508'],
            ['municipality' => 'LEYTE', 'zip_code' => '6533'],
            ['municipality' => 'MACARTHUR', 'zip_code' => '6509'],
            ['municipality' => 'MAHAPLAG', 'zip_code' => '6512'],
            ['municipality' => 'MATAG-OB', 'zip_code' => '6532'],
            ['municipality' => 'MATALOM', 'zip_code' => '6526'],
            ['municipality' => 'MAYORGA', 'zip_code' => '6507'],
            ['municipality' => 'MERIDA', 'zip_code' => '6540'],
            ['municipality' => 'ORMOC CITY', 'zip_code' => '6541'],
            ['municipality' => 'PALO', 'zip_code' => '6501'],
            ['municipality' => 'PALOMPON', 'zip_code' => '6538'],
            ['municipality' => 'PASTRANA', 'zip_code' => '6514'],
            ['municipality' => 'SAN ISIDRO', 'zip_code' => '6535'],
            ['municipality' => 'SAN MIGUEL', 'zip_code' => '6518'],
            ['municipality' => 'STA. FE', 'zip_code' => '6513'],
            ['municipality' => 'TABANGO', 'zip_code' => '6536'],
            ['municipality' => 'TABONTABON', 'zip_code' => '6504'],
            ['municipality' => 'TACLOBAN CITY', 'zip_code' => '6500'],
            ['municipality' => 'TANAUAN', 'zip_code' => '6502'],
            ['municipality' => 'TOLOSA', 'zip_code' => '6503'],
            ['municipality' => 'TUNGA', 'zip_code' => '6528'],
            ['municipality' => 'VILLABA', 'zip_code' => '6537'],
        ]
    ],

    [
        'province' => 'NORTHERN SAMAR',
        'zip_codes' => [
            ['municipality' => 'ALLEN', 'zip_code' => '6405'],
            ['municipality' => 'BIRI', 'zip_code' => '6410'],
            ['municipality' => 'BOBON', 'zip_code' => '6401'],
            ['municipality' => 'CAPUL', 'zip_code' => '6408'],
            ['municipality' => 'CATARMAN', 'zip_code' => '6400'],
            ['municipality' => 'CATUBIG', 'zip_code' => '6418'],
            ['municipality' => 'GAMAY', 'zip_code' => '6422'],
            ['municipality' => 'LAS NAVAS', 'zip_code' => '6420'],
            ['municipality' => 'LAOANG', 'zip_code' => '6411'],
            ['municipality' => 'LAPINIG', 'zip_code' => '6423'],
            ['municipality' => 'LAVEZARES', 'zip_code' => '6404'],
            ['municipality' => 'LOPE DE VEGA', 'zip_code' => '6403'],
            ['municipality' => 'MAPANAS', 'zip_code' => '6412'],
            ['municipality' => 'MONDRAGON', 'zip_code' => '6417'],
            ['municipality' => 'PALAPAG', 'zip_code' => '6421'],
            ['municipality' => 'PAMBUJAN', 'zip_code' => '6413'],
            ['municipality' => 'ROSARIO', 'zip_code' => '6416'],
            ['municipality' => 'SAN ANTONIO', 'zip_code' => '6407'],
            ['municipality' => 'SAN ISIDRO', 'zip_code' => '6409'],
            ['municipality' => 'SAN JOSE', 'zip_code' => '6402'],
            ['municipality' => 'SAN ROQUE', 'zip_code' => '6415'],
            ['municipality' => 'SAN VICENTE', 'zip_code' => '6419'],
            ['municipality' => 'SILVINO LOBOS', 'zip_code' => '6414'],
            ['municipality' => 'VICTORIA', 'zip_code' => '6406'],
        ]
    ],

    [
        'province' => 'SOUTHERN LEYTE',
        'zip_codes' => [
            ['municipality' => 'ANAHAWAN', 'zip_code' => '6610'],
            ['municipality' => 'BONTOC', 'zip_code' => '6604'],
            ['municipality' => 'HINUNANGAN', 'zip_code' => '6608'],
            ['municipality' => 'HINUNDAYAN', 'zip_code' => '6609'],
            ['municipality' => 'LIBAGON', 'zip_code' => '6615'],
            ['municipality' => 'LILOAN', 'zip_code' => '6612'],
            ['municipality' => 'LIMASAWA', 'zip_code' => '6618'],
            ['municipality' => 'MAASIN', 'zip_code' => '6600'],
            ['municipality' => 'MACROHON', 'zip_code' => '6601'],
            ['municipality' => 'MALITBOG', 'zip_code' => '6603'],
            ['municipality' => 'PADRE BURGOS', 'zip_code' => '6602'],
            ['municipality' => 'PINTUYAN', 'zip_code' => '6614'],
            ['municipality' => 'SAN FRANCISCO', 'zip_code' => '6613'],
            ['municipality' => 'SAN JUAN (CABALIAN)', 'zip_code' => '6611'],
            ['municipality' => 'SAN RICARDO', 'zip_code' => '6617'],
            ['municipality' => 'SILAGO', 'zip_code' => '6607'],
            ['municipality' => 'SOGOD', 'zip_code' => '6606'],
            ['municipality' => 'SAINT BERNARD', 'zip_code' => '6616'],
            ['municipality' => 'TOMAS OPPUS', 'zip_code' => '6605'],
        ]
    ],

    [
        'province' => 'WESTERN SAMAR',
        'zip_codes' => [
            ['municipality' => 'ALMAGRO', 'zip_code' => '6724'],
            ['municipality' => 'BASEY', 'zip_code' => '6720'],
            ['municipality' => 'CALBAYOG CITY', 'zip_code' => '6710'],
            ['municipality' => 'CALBIGA', 'zip_code' => '6715'],
            ['municipality' => 'CATBALOGAN', 'zip_code' => '6700'],
            ['municipality' => 'DARAM', 'zip_code' => '6722'],
            ['municipality' => 'GANDARA', 'zip_code' => '6706'],
            ['municipality' => 'HINABANGAN', 'zip_code' => '6713'],
            ['municipality' => 'JIABONG', 'zip_code' => '6701'],
            ['municipality' => 'MARABUT', 'zip_code' => '6721'],
            ['municipality' => 'MATUGUINAO', 'zip_code' => '6708'],
            ['municipality' => 'MOTIONG', 'zip_code' => '6702'],
            ['municipality' => 'PAGSANGHAN', 'zip_code' => '6705'],
            ['municipality' => 'PINABACDAO', 'zip_code' => '6716'],
            ['municipality' => 'SAN JORGE', 'zip_code' => '6707'],
            ['municipality' => 'SAN JOSE DE BUAN', 'zip_code' => '6723'],
            ['municipality' => 'SAN SEBASTIAN', 'zip_code' => '6714'],
            ['municipality' => 'STA. MARGARITA', 'zip_code' => '6709'],
            ['municipality' => 'STA. RITA', 'zip_code' => '6718'],
            ['municipality' => 'STO. NIÑO', 'zip_code' => '6711'],
            ['municipality' => 'TAGAPUL-AN', 'zip_code' => '6712'],
            ['municipality' => 'TALALORA', 'zip_code' => '6719'],
            ['municipality' => 'TARANGNAN', 'zip_code' => '6704'],
            ['municipality' => 'VILLAREAL', 'zip_code' => '6717'],
            ['municipality' => 'WRIGHT', 'zip_code' => '6703'],
            ['municipality' => 'ZUMARRAGA', 'zip_code' => '6725'],
        ]
    ],
];
