<?php
return array_map('trim', [
  ["province" => "ABRA", "municipality" => "Bangued", "zip_code" => "2800"],
  ["province" => "ABRA", "municipality" => "Boliney", "zip_code" => "2815"],
  ["province" => "ABRA", "municipality" => "Bucloc", "zip_code" => "2817"],
  ["province" => "ABRA", "municipality" => "Bucay", "zip_code" => "2805"],
  ["province" => "ABRA", "municipality" => "Daguioman", "zip_code" => "2816"],
  ["province" => "ABRA", "municipality" => "Danglas", "zip_code" => "2825"],
  ["province" => "ABRA", "municipality" => "Dolores", "zip_code" => "2801"],
  ["province" => "ABRA", "municipality" => "La Paz", "zip_code" => "2826"],
  ["province" => "ABRA", "municipality" => "Lacub", "zip_code" => "2821"],
  ["province" => "ABRA", "municipality" => "Lagayan", "zip_code" => "2824"],
  ["province" => "ABRA", "municipality" => "Lagangilang", "zip_code" => "2802"],
  ["province" => "ABRA", "municipality" => "Langiden", "zip_code" => "2807"],
  ["province" => "ABRA", "municipality" => "Licuan-Baay", "zip_code" => "2819"],
  ["province" => "ABRA", "municipality" => "Luba", "zip_code" => "2813"],
  ["province" => "ABRA", "municipality" => "Malibcong", "zip_code" => "2820"],
  ["province" => "ABRA", "municipality" => "Manabo", "zip_code" => "2810"],
  ["province" => "ABRA", "municipality" => "Peñarrubia", "zip_code" => "2804"],
  ["province" => "ABRA", "municipality" => "Pidigan", "zip_code" => "2806"],
  ["province" => "ABRA", "municipality" => "Pilar", "zip_code" => "2812"],
  ["province" => "ABRA", "municipality" => "Sallapadan", "zip_code" => "2818"],
  ["province" => "ABRA", "municipality" => "San Isidro", "zip_code" => "2809"],
  ["province" => "ABRA", "municipality" => "San Juan", "zip_code" => "2823"],
  ["province" => "ABRA", "municipality" => "San Quintin", "zip_code" => "2808"],
  ["province" => "ABRA", "municipality" => "Tayum", "zip_code" => "2803"],
  ["province" => "ABRA", "municipality" => "Tineg", "zip_code" => "2822"],
  ["province" => "ABRA", "municipality" => "Tubo", "zip_code" => "2814"],
  ["province" => "ABRA", "municipality" => "Villaviciosa", "zip_code" => "2811"],

  ["province" => "BENGUET", "municipality" => "Atok", "zip_code" => "2612"],
  ["province" => "BENGUET", "municipality" => "Baguio City", "zip_code" => "2600"],
  ["province" => "BENGUET", "municipality" => "Bakun", "zip_code" => "2610"],
  ["province" => "BENGUET", "municipality" => "Bokod", "zip_code" => "2605"],
  ["province" => "BENGUET", "municipality" => "Buguias", "zip_code" => "2607"],
  ["province" => "BENGUET", "municipality" => "Itogon", "zip_code" => "2604"],
  ["province" => "BENGUET", "municipality" => "Kabayan", "zip_code" => "2606"],
  ["province" => "BENGUET", "municipality" => "Kapangan", "zip_code" => "2613"],
  ["province" => "BENGUET", "municipality" => "Kibungan", "zip_code" => "2611"],
  ["province" => "BENGUET", "municipality" => "La Trinidad", "zip_code" => "2601"],
  ["province" => "BENGUET", "municipality" => "Lepanto", "zip_code" => "2609"],
  ["province" => "BENGUET", "municipality" => "Mankayan", "zip_code" => "2608"],
  ["province" => "BENGUET", "municipality" => "Philippine Military Academy (PMA)", "zip_code" => "2602"],
  ["province" => "BENGUET", "municipality" => "Sablan", "zip_code" => "2614"],
  ["province" => "BENGUET", "municipality" => "Tuba", "zip_code" => "2603"],
  ["province" => "BENGUET", "municipality" => "Tublay", "zip_code" => "2615"],

  ["province" => "IFUGAO", "municipality" => "Aguinaldo", "zip_code" => "3606"],
  ["province" => "IFUGAO", "municipality" => "Asipulo", "zip_code" => "3610"],
  ["province" => "IFUGAO", "municipality" => "Banaue", "zip_code" => "3601"],
  ["province" => "IFUGAO", "municipality" => "Hingyon", "zip_code" => "3607"],
  ["province" => "IFUGAO", "municipality" => "Hungduan", "zip_code" => "3603"],
  ["province" => "IFUGAO", "municipality" => "Kiangan", "zip_code" => "3604"],
  ["province" => "IFUGAO", "municipality" => "Lagawe", "zip_code" => "3600"],
  ["province" => "IFUGAO", "municipality" => "Lamut", "zip_code" => "3605"],
  ["province" => "IFUGAO", "municipality" => "Mayoyao", "zip_code" => "3602"],
  ["province" => "IFUGAO", "municipality" => "Alfonso Lista (formerly Potia)", "zip_code" => "3608"],
  ["province" => "IFUGAO", "municipality" => "Tinoc", "zip_code" => "3609"],

  ["province" => "KALINGA-APAYAO", "municipality" => "Balbalan", "zip_code" => "3801"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Calanasan", "zip_code" => "3814"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Conner", "zip_code" => "3807"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Flora", "zip_code" => "3810"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Kabugao", "zip_code" => "3809"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Lubuagan", "zip_code" => "3802"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Luna", "zip_code" => "3813"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Pasil", "zip_code" => "3803"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Pinukpuk", "zip_code" => "3806"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Pudtol", "zip_code" => "3812"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Rizal", "zip_code" => "3808"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Santa Marcela", "zip_code" => "3811"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Tabuk City", "zip_code" => "3800"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Tanudan", "zip_code" => "3805"],
  ["province" => "KALINGA-APAYAO", "municipality" => "Tinglayan", "zip_code" => "3804"],

  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Barlig", "zip_code" => "2623"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Bauko", "zip_code" => "2621"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Besao", "zip_code" => "2618"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Bontoc", "zip_code" => "2616"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Natonin", "zip_code" => "2624"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Paracelis", "zip_code" => "2625"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Sabangan", "zip_code" => "2622"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Sadanga", "zip_code" => "2617"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Sagada", "zip_code" => "2619"],
  ["province" => "MOUNTAIN PROVINCE", "municipality" => "Tadian", "zip_code" => "2620"],
]);
