<?php

declare(strict_types=1);
return [
    ['province' => 'ABRA', 'municipality' => 'BANGUED', 'zip_code' => '2800'],
    ['province' => 'ABRA', 'municipality' => 'BOLINEY', 'zip_code' => '2815'],
    ['province' => 'ABRA', 'municipality' => 'BUCLOC', 'zip_code' => '2817'],
    ['province' => 'ABRA', 'municipality' => 'BUCAY', 'zip_code' => '2805'],
    ['province' => 'ABRA', 'municipality' => 'DAGUIOMAN', 'zip_code' => '2816'],
    ['province' => 'ABRA', 'municipality' => 'DANGLAS', 'zip_code' => '2825'],
    ['province' => 'ABRA', 'municipality' => 'DOLORES', 'zip_code' => '2801'],
    ['province' => 'ABRA', 'municipality' => 'LA PAZ', 'zip_code' => '2826'],
    ['province' => 'ABRA', 'municipality' => 'LACUB', 'zip_code' => '2821'],
    ['province' => 'ABRA', 'municipality' => 'LAGAYAN', 'zip_code' => '2824'],
    ['province' => 'ABRA', 'municipality' => 'LAGANGILANG', 'zip_code' => '2802'],
    ['province' => 'ABRA', 'municipality' => 'LANGIDEN', 'zip_code' => '2807'],
    ['province' => 'ABRA', 'municipality' => 'LICUAN-BAAY', 'zip_code' => '2819'],
    ['province' => 'ABRA', 'municipality' => 'LUBA', 'zip_code' => '2813'],
    ['province' => 'ABRA', 'municipality' => 'MALIBCONG', 'zip_code' => '2820'],
    ['province' => 'ABRA', 'municipality' => 'MANABO', 'zip_code' => '2810'],
    ['province' => 'ABRA', 'municipality' => 'PEÑARRUBIA', 'zip_code' => '2804'],
    ['province' => 'ABRA', 'municipality' => 'PIDIGAN', 'zip_code' => '2806'],
    ['province' => 'ABRA', 'municipality' => 'PILAR', 'zip_code' => '2812'],
    ['province' => 'ABRA', 'municipality' => 'SALLAPADAN', 'zip_code' => '2818'],
    ['province' => 'ABRA', 'municipality' => 'SAN ISIDRO', 'zip_code' => '2809'],
    ['province' => 'ABRA', 'municipality' => 'SAN JUAN', 'zip_code' => '2823'],
    ['province' => 'ABRA', 'municipality' => 'SAN QUINTIN', 'zip_code' => '2808'],
    ['province' => 'ABRA', 'municipality' => 'TAYUM', 'zip_code' => '2803'],
    ['province' => 'ABRA', 'municipality' => 'TINEG', 'zip_code' => '2822'],
    ['province' => 'ABRA', 'municipality' => 'TUBO', 'zip_code' => '2814'],
    ['province' => 'ABRA', 'municipality' => 'VILLAVICIOSA', 'zip_code' => '2811'],

    ['province' => 'BENGUET', 'municipality' => 'ATOK', 'zip_code' => '2612'],
    ['province' => 'BENGUET', 'municipality' => 'BAGUIO CITY', 'zip_code' => '2600'],
    ['province' => 'BENGUET', 'municipality' => 'BAKUN', 'zip_code' => '2610'],
    ['province' => 'BENGUET', 'municipality' => 'BOKOD', 'zip_code' => '2605'],
    ['province' => 'BENGUET', 'municipality' => 'BUGUIAS', 'zip_code' => '2607'],
    ['province' => 'BENGUET', 'municipality' => 'ITOGON', 'zip_code' => '2604'],
    ['province' => 'BENGUET', 'municipality' => 'KABAYAN', 'zip_code' => '2606'],
    ['province' => 'BENGUET', 'municipality' => 'KAPANGAN', 'zip_code' => '2613'],
    ['province' => 'BENGUET', 'municipality' => 'KIBUNGAN', 'zip_code' => '2611'],
    ['province' => 'BENGUET', 'municipality' => 'LA TRINIDAD', 'zip_code' => '2601'],
    ['province' => 'BENGUET', 'municipality' => 'LEPANTO', 'zip_code' => '2609'],
    ['province' => 'BENGUET', 'municipality' => 'MANKAYAN', 'zip_code' => '2608'],
    ['province' => 'BENGUET', 'municipality' => 'PHILIPPINE MILITARY ACADEMY (PMA)', 'zip_code' => '2602'],
    ['province' => 'BENGUET', 'municipality' => 'SABLAN', 'zip_code' => '2614'],
    ['province' => 'BENGUET', 'municipality' => 'TUBA', 'zip_code' => '2603'],
    ['province' => 'BENGUET', 'municipality' => 'TUBLAY', 'zip_code' => '2615'],

    ['province' => 'IFUGAO', 'municipality' => 'AGUINALDO', 'zip_code' => '3606'],
    ['province' => 'IFUGAO', 'municipality' => 'ASIPULO', 'zip_code' => '3610'],
    ['province' => 'IFUGAO', 'municipality' => 'BANAUE', 'zip_code' => '3601'],
    ['province' => 'IFUGAO', 'municipality' => 'HINGYON', 'zip_code' => '3607'],
    ['province' => 'IFUGAO', 'municipality' => 'HUNGDUAN', 'zip_code' => '3603'],
    ['province' => 'IFUGAO', 'municipality' => 'KIANGAN', 'zip_code' => '3604'],
    ['province' => 'IFUGAO', 'municipality' => 'LAGAWE', 'zip_code' => '3600'],
    ['province' => 'IFUGAO', 'municipality' => 'LAMUT', 'zip_code' => '3605'],
    ['province' => 'IFUGAO', 'municipality' => 'MAYOYAO', 'zip_code' => '3602'],
    ['province' => 'IFUGAO', 'municipality' => 'ALFONSO LISTA (FORMERLY POTIA)', 'zip_code' => '3608'],
    ['province' => 'IFUGAO', 'municipality' => 'TINOC', 'zip_code' => '3609'],

    ['province' => 'KALINGA-APAYAO', 'municipality' => 'BALBALAN', 'zip_code' => '3801'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'CALANASAN', 'zip_code' => '3814'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'CONNER', 'zip_code' => '3807'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'FLORA', 'zip_code' => '3810'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'KABUGAO', 'zip_code' => '3809'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'LUBUAGAN', 'zip_code' => '3802'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'LUNA', 'zip_code' => '3813'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'PASIL', 'zip_code' => '3803'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'PINUKPUK', 'zip_code' => '3806'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'PUDTOL', 'zip_code' => '3812'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'RIZAL', 'zip_code' => '3808'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'SANTA MARCELA', 'zip_code' => '3811'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'TABUK CITY', 'zip_code' => '3800'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'TANUDAN', 'zip_code' => '3805'],
    ['province' => 'KALINGA-APAYAO', 'municipality' => 'TINGLAYAN', 'zip_code' => '3804'],

    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'BARLIG', 'zip_code' => '2623'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'BAUKO', 'zip_code' => '2621'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'BESAO', 'zip_code' => '2618'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'BONTOC', 'zip_code' => '2616'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'NATONIN', 'zip_code' => '2624'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'PARACELIS', 'zip_code' => '2625'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'SABANGAN', 'zip_code' => '2622'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'SADANGA', 'zip_code' => '2617'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'SAGADA', 'zip_code' => '2619'],
    ['province' => 'MOUNTAIN PROVINCE', 'municipality' => 'TADIAN', 'zip_code' => '2620'],
];
