<?php
return [
  [
    "province" => "ILOCOS NORTE",
    "zip_codes" => [
      ["municipality" => "ADAMS", "zip_code" => "2922"],
      ["municipality" => "BACARRA", "zip_code" => "2916"],
      ["municipality" => "BADOC", "zip_code" => "2904"],
      ["municipality" => "BANGUI", "zip_code" => "2920"],
      ["municipality" => "BATAC", "zip_code" => "2906"],
      ["municipality" => "BURGOS", "zip_code" => "2918"],
      ["municipality" => "CARASI", "zip_code" => "2911"],
      ["municipality" => "CURRIMAO", "zip_code" => "2903"],
      ["municipality" => "DINGRAS", "zip_code" => "2913"],
      ["municipality" => "DUMALNEG", "zip_code" => "2921"],
      ["municipality" => "BANNA (FORMERLY ESPIRITU)", "zip_code" => "2908"],
      ["municipality" => "LAOAG CITY", "zip_code" => "2900"],
      ["municipality" => "MARCOS", "zip_code" => "2907"],
      ["municipality" => "NUEVA ERA", "zip_code" => "2909"],
      ["municipality" => "PAGUDPUD", "zip_code" => "2919"],
      ["municipality" => "PAOAY", "zip_code" => "2902"],
      ["municipality" => "PASUQUIN", "zip_code" => "2917"],
      ["municipality" => "PIDDIG", "zip_code" => "2912"],
      ["municipality" => "PINILI", "zip_code" => "2905"],
      ["municipality" => "SAN NICOLAS", "zip_code" => "2901"],
      ["municipality" => "SARRAT", "zip_code" => "2914"],
      ["municipality" => "SOLSONA", "zip_code" => "2910"],
      ["municipality" => "VINTAR", "zip_code" => "2915"],
    ]
  ],

  [
    "province" => "ILOCOS SUR",
    "zip_codes" => [
      ["municipality" => "ALILEM", "zip_code" => "2716"],
      ["municipality" => "BANAYOYO", "zip_code" => "2708"],
      ["municipality" => "BANTAY", "zip_code" => "2727"],
      ["municipality" => "BURGOS", "zip_code" => "2724"],
      ["municipality" => "CABUGAO", "zip_code" => "2732"],
      ["municipality" => "CANDON", "zip_code" => "2710"],
      ["municipality" => "CAOAYAN", "zip_code" => "2702"],
      ["municipality" => "CERVANTES", "zip_code" => "2718"],
      ["municipality" => "GALIMUYOD", "zip_code" => "2709"],
      ["municipality" => "GREGORIO DEL PILAR (CONCEPCION)", "zip_code" => "2720"],
      ["municipality" => "LIDLIDDA", "zip_code" => "2723"],
      ["municipality" => "MAGSINGAL", "zip_code" => "2730"],
      ["municipality" => "NAGBUKEL", "zip_code" => "2725"],
      ["municipality" => "NARVACAN", "zip_code" => "2704"],
      ["municipality" => "QUIRINO (ANGKAKI)", "zip_code" => "2721"],
      ["municipality" => "SALCEDO (BAUGEN)", "zip_code" => "2711"],
      ["municipality" => "SAN EMILIO", "zip_code" => "2722"],
      ["municipality" => "SAN ESTEBAN", "zip_code" => "2706"],
      ["municipality" => "SAN ILDEFONSO", "zip_code" => "2728"],
      ["municipality" => "SAN JUAN (LAPOG)", "zip_code" => "2731"],
      ["municipality" => "SAN VICENTE", "zip_code" => "2726"],
      ["municipality" => "SANTA", "zip_code" => "2703"],
      ["municipality" => "SANTA CATALINA", "zip_code" => "2701"],
      ["municipality" => "SANTA CRUZ", "zip_code" => "2713"],
      ["municipality" => "SANTA LUCIA", "zip_code" => "2712"],
      ["municipality" => "SANTA MARIA", "zip_code" => "2705"],
      ["municipality" => "SANTIAGO", "zip_code" => "2707"],
      ["municipality" => "SANTO DOMINGO", "zip_code" => "2729"],
      ["municipality" => "SIGAY", "zip_code" => "2719"],
      ["municipality" => "SINAIT", "zip_code" => "2733"],
      ["municipality" => "SUGPON", "zip_code" => "2717"],
      ["municipality" => "SUYO", "zip_code" => "2715"],
      ["municipality" => "TAGUDIN", "zip_code" => "2714"],
      ["municipality" => "VIGAN", "zip_code" => "2700"],
    ]
  ],

  [
    "province" => "LA UNION",
    "zip_codes" => [
      ["municipality" => "AGOO", "zip_code" => "2504"],
      ["municipality" => "ARINGAY", "zip_code" => "2503"],
      ["municipality" => "BACNOTAN", "zip_code" => "2515"],
      ["municipality" => "BAGULIN", "zip_code" => "2512"],
      ["municipality" => "BALAOAN", "zip_code" => "2517"],
      ["municipality" => "BANGAR", "zip_code" => "2519"],
      ["municipality" => "BAUANG", "zip_code" => "2501"],
      ["municipality" => "BURGOS", "zip_code" => "2510"],
      ["municipality" => "CABA", "zip_code" => "2502"],
      ["municipality" => "DAMORTIS", "zip_code" => "2507"],
      ["municipality" => "LUNA", "zip_code" => "2518"],
      ["municipality" => "NAGUILIAN", "zip_code" => "2511"],
      ["municipality" => "PUGO", "zip_code" => "2508"],
      ["municipality" => "ROSARIO", "zip_code" => "2506"],
      ["municipality" => "SAN FERNANDO CITY", "zip_code" => "2500"],
      ["municipality" => "SAN GABRIEL", "zip_code" => "2513"],
      ["municipality" => "SAN JUAN", "zip_code" => "2514"],
      ["municipality" => "SANTOL", "zip_code" => "2516"],
      ["municipality" => "SANTO TOMAS", "zip_code" => "2505"],
      ["municipality" => "SUDIPEN", "zip_code" => "2520"],
      ["municipality" => "TUBAO", "zip_code" => "2509"],
    ]
  ],

  [
    "province" => "PANGASINAN",
    "zip_codes" => [
      ["municipality" => "AGNO", "zip_code" => "2408"],
      ["municipality" => "AGUILAR", "zip_code" => "2415"],
      ["municipality" => "ALAMINOS", "zip_code" => "2404"],
      ["municipality" => "ALCALA", "zip_code" => "2425"],
      ["municipality" => "ANDA", "zip_code" => "2405"],
      ["municipality" => "ASINGAN", "zip_code" => "2439"],
      ["municipality" => "BALUNGAO", "zip_code" => "2442"],
      ["municipality" => "BANI", "zip_code" => "2407"],
      ["municipality" => "BASISTA", "zip_code" => "2422"],
      ["municipality" => "BAUTISTA", "zip_code" => "2424"],
      ["municipality" => "BAYAMBANG", "zip_code" => "2423"],
      ["municipality" => "BINALONAN", "zip_code" => "2436"],
      ["municipality" => "BINMALEY", "zip_code" => "2417"],
      ["municipality" => "BOLINAO", "zip_code" => "2406"],
      ["municipality" => "BUGALLON", "zip_code" => "2416"],
      ["municipality" => "BURGOS", "zip_code" => "2410"],
      ["municipality" => "CALASIAO", "zip_code" => "2418"],
      ["municipality" => "DAGUPAN CITY", "zip_code" => "2400"],
      ["municipality" => "DASOL", "zip_code" => "2411"],
      ["municipality" => "INFANTA", "zip_code" => "2412"],
      ["municipality" => "LABRADOR", "zip_code" => "2402"],
      ["municipality" => "LAOAC", "zip_code" => "2437"],
      ["municipality" => "LINGAYEN", "zip_code" => "2401"],
      ["municipality" => "MABINI", "zip_code" => "2409"],
      ["municipality" => "MALASIQUI", "zip_code" => "2421"],
      ["municipality" => "MANAOAG", "zip_code" => "2430"],
      ["municipality" => "MANGALDAN", "zip_code" => "2432"],
      ["municipality" => "MANGATAREM", "zip_code" => "2413"],
      ["municipality" => "MAPANDAN", "zip_code" => "2429"],
      ["municipality" => "NATIVIDAD", "zip_code" => "2446"],
      ["municipality" => "POZORRUBIO", "zip_code" => "2435"],
      ["municipality" => "ROSALES", "zip_code" => "2441"],
      ["municipality" => "SAN CARLOS CITY", "zip_code" => "2420"],
      ["municipality" => "SAN FABIAN", "zip_code" => "2433"],
      ["municipality" => "SAN JACINTO", "zip_code" => "2431"],
      ["municipality" => "SAN MANUEL", "zip_code" => "2438"],
      ["municipality" => "SAN NICOLAS", "zip_code" => "2447"],
      ["municipality" => "SAN QUINTIN", "zip_code" => "2444"],
      ["municipality" => "SISON", "zip_code" => "2434"],
      ["municipality" => "SANTA BARBARA", "zip_code" => "2419"],
      ["municipality" => "SANTA MARIA", "zip_code" => "2440"],
      ["municipality" => "SANTOTOMAS", "zip_code" => "2426"],
      ["municipality" => "SUAL", "zip_code" => "2403"],
      ["municipality" => "TAYUG", "zip_code" => "2445"],
      ["municipality" => "UMINGAN", "zip_code" => "2443"],
      ["municipality" => "URBIZTONDO", "zip_code" => "2414"],
      ["municipality" => "URDANETA", "zip_code" => "2428"],
      ["municipality" => "VILLASIS", "zip_code" => "2427"],
    ]
  ]
];
