<?php
return  [
  ["province" => "BUKIDNON", "municipality" => "Baungon", "zip_code" => "8707"],
  ["province" => "BUKIDNON", "municipality" => "Cabanglasan", "zip_code" => "8723"],
  ["province" => "BUKIDNON", "municipality" => "Damulog", "zip_code" => "8721"],
  ["province" => "BUKIDNON", "municipality" => "Dangcagan", "zip_code" => "8719"],
  ["province" => "BUKIDNON", "municipality" => "Don Carlos", "zip_code" => "8712"],
  ["province" => "BUKIDNON", "municipality" => "Impasugong", "zip_code" => "8702"],
  ["province" => "BUKIDNON", "municipality" => "Kadingilan", "zip_code" => "8713"],
  ["province" => "BUKIDNON", "municipality" => "Kalilangan", "zip_code" => "8718"],
  ["province" => "BUKIDNON", "municipality" => "Kibawe", "zip_code" => "8720"],
  ["province" => "BUKIDNON", "municipality" => "Kitaotao", "zip_code" => "8716"],
  ["province" => "BUKIDNON", "municipality" => "Lantapan", "zip_code" => "8722"],
  ["province" => "BUKIDNON", "municipality" => "Libona", "zip_code" => "8706"],
  ["province" => "BUKIDNON", "municipality" => "Malaybalay", "zip_code" => "8700"],
  ["province" => "BUKIDNON", "municipality" => "Malitbog", "zip_code" => "8704"],
  ["province" => "BUKIDNON", "municipality" => "Manolo Fortich", "zip_code" => "8703"],
  ["province" => "BUKIDNON", "municipality" => "Maramag", "zip_code" => "8714"],
  ["province" => "BUKIDNON", "municipality" => "Musuan", "zip_code" => "8710"],
  ["province" => "BUKIDNON", "municipality" => "Pangantucan", "zip_code" => "8717"],
  ["province" => "BUKIDNON", "municipality" => "Phillips", "zip_code" => "8705"],
  ["province" => "BUKIDNON", "municipality" => "Quezon", "zip_code" => "8715"],
  ["province" => "BUKIDNON", "municipality" => "San Fernando", "zip_code" => "8711"],
  ["province" => "BUKIDNON", "municipality" => "Sumilao", "zip_code" => "8701"],
  ["province" => "BUKIDNON", "municipality" => "Talakag", "zip_code" => "8708"],
  ["province" => "BUKIDNON", "municipality" => "Valencia", "zip_code" => "8709"],

  ["province" => "CAMIGUIN", "municipality" => "Catarman", "zip_code" => "9104"],
  ["province" => "CAMIGUIN", "municipality" => "Guinsiliban", "zip_code" => "9102"],
  ["province" => "CAMIGUIN", "municipality" => "Mahinog", "zip_code" => "9101"],
  ["province" => "CAMIGUIN", "municipality" => "Mambajao", "zip_code" => "9100"],
  ["province" => "CAMIGUIN", "municipality" => "Sagay", "zip_code" => "9103"],

  ["province" => "LANAO DEL NORTE", "municipality" => "Bacolod", "zip_code" => "9205"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Baloi", "zip_code" => "9217"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Baroy", "zip_code" => "9210"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Iligan City", "zip_code" => "9200"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Kapatagan", "zip_code" => "9214"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Kauswagan", "zip_code" => "9202"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Kolambugan", "zip_code" => "9207"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Lala", "zip_code" => "9211"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Linamon", "zip_code" => "9201"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Magsaysay", "zip_code" => "9221"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Maigo", "zip_code" => "9206"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Matungao", "zip_code" => "9203"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Munai", "zip_code" => "9219"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Nunungan", "zip_code" => "9216"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Pantao Ragat", "zip_code" => "9208"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Pantar", "zip_code" => "9218"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Poona Piagapo", "zip_code" => "9204"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Salvador", "zip_code" => "9212"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Sapad", "zip_code" => "9213"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Sultan Naga Dimaporo (formerly Karomatan) ", "zip_code" => "9215"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Tagoloan", "zip_code" => "9222"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Tangcal", "zip_code" => "9220"],
  ["province" => "LANAO DEL NORTE", "municipality" => "Tubod", "zip_code" => "9209"],

  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Aloran", "zip_code" => "7206"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Baliangao", "zip_code" => "7211"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Bonifacio", "zip_code" => "7215"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Calamba", "zip_code" => "7210"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Clarin", "zip_code" => "7201"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Concepcion", "zip_code" => "7213"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Don Victoriano Chiongbian", "zip_code" => "7216"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Jimenez", "zip_code" => "7204"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Lopez Jaena", "zip_code" => "7208"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Oroquieta City", "zip_code" => "7207"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Ozamis City", "zip_code" => "7200"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Panaon", "zip_code" => "7205"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Plaridel", "zip_code" => "7209"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Sapang dalaga", "zip_code" => "7212"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Sinacaban", "zip_code" => "7203"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Tangub City", "zip_code" => "7214"],
  ["province" => "MISAMIS OCCIDENTAL", "municipality" => "Tudela", "zip_code" => "7202"],

  ["province" => "MISAMIS ORIENTAL", "municipality" => "Alubijid", "zip_code" => "9018"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Balingasag", "zip_code" => "9005"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Balingoan", "zip_code" => "9011"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Binuangan", "zip_code" => "9008"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Cagayan de Oro City", "zip_code" => "9000"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Claveria", "zip_code" => "9004"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "El Salvador", "zip_code" => "9017"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Gingoog City", "zip_code" => "9014"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Gitagum", "zip_code" => "9020"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Initao", "zip_code" => "9022"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Jasaan", "zip_code" => "9003"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Kinoguitan", "zip_code" => "9010"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Laguindingan", "zip_code" => "9019"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Lagonglong", "zip_code" => "9006"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Libertad", "zip_code" => "9021"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Lugait", "zip_code" => "9025"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Magsaysay", "zip_code" => "9015"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Manticao", "zip_code" => "9024"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Medina", "zip_code" => "9013"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Naawan", "zip_code" => "9023"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Opol", "zip_code" => "9016"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Salay", "zip_code" => "9007"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Sugbongcogon", "zip_code" => "9009"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Tagoloan", "zip_code" => "9001"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Talisayan", "zip_code" => "9012"],
  ["province" => "MISAMIS ORIENTAL", "municipality" => "Villanueva", "zip_code" => "9002"],
];
