<?php
return array_map('trim', [
  ["province" => "ILOCOS NORTE", "municipality" => "Adams", "zip_code" => "2922"],
  ["province" => "ILOCOS NORTE", "municipality" => "Bacarra", "zip_code" => "2916"],
  ["province" => "ILOCOS NORTE", "municipality" => "Badoc", "zip_code" => "2904"],
  ["province" => "ILOCOS NORTE", "municipality" => "Bangui", "zip_code" => "2920"],
  ["province" => "ILOCOS NORTE", "municipality" => "Batac", "zip_code" => "2906"],
  ["province" => "ILOCOS NORTE", "municipality" => "Burgos", "zip_code" => "2918"],
  ["province" => "ILOCOS NORTE", "municipality" => "Carasi", "zip_code" => "2911"],
  ["province" => "ILOCOS NORTE", "municipality" => "Currimao", "zip_code" => "2903"],
  ["province" => "ILOCOS NORTE", "municipality" => "Dingras", "zip_code" => "2913"],
  ["province" => "ILOCOS NORTE", "municipality" => "Dumalneg", "zip_code" => "2921"],
  ["province" => "ILOCOS NORTE", "municipality" => "Banna (formerly Espiritu)", "zip_code" => "2908"],
  ["province" => "ILOCOS NORTE", "municipality" => "Laoag City", "zip_code" => "2900"],
  ["province" => "ILOCOS NORTE", "municipality" => "Marcos", "zip_code" => "2907"],
  ["province" => "ILOCOS NORTE", "municipality" => "Nueva Era", "zip_code" => "2909"],
  ["province" => "ILOCOS NORTE", "municipality" => "Pagudpud", "zip_code" => "2919"],
  ["province" => "ILOCOS NORTE", "municipality" => "Paoay", "zip_code" => "2902"],
  ["province" => "ILOCOS NORTE", "municipality" => "Pasuquin", "zip_code" => "2917"],
  ["province" => "ILOCOS NORTE", "municipality" => "Piddig", "zip_code" => "2912"],
  ["province" => "ILOCOS NORTE", "municipality" => "Pinili", "zip_code" => "2905"],
  ["province" => "ILOCOS NORTE", "municipality" => "San Nicolas", "zip_code" => "2901"],
  ["province" => "ILOCOS NORTE", "municipality" => "Sarrat", "zip_code" => "2914"],
  ["province" => "ILOCOS NORTE", "municipality" => "Solsona", "zip_code" => "2910"],
  ["province" => "ILOCOS NORTE", "municipality" => "Vintar", "zip_code" => "2915"],

  ["province" => "ILOCOS SUR", "municipality" => "Alilem", "zip_code" => "2716"],
  ["province" => "ILOCOS SUR", "municipality" => "Banayoyo", "zip_code" => "2708"],
  ["province" => "ILOCOS SUR", "municipality" => "Bantay", "zip_code" => "2727"],
  ["province" => "ILOCOS SUR", "municipality" => "Burgos", "zip_code" => "2724"],
  ["province" => "ILOCOS SUR", "municipality" => "Cabugao", "zip_code" => "2732"],
  ["province" => "ILOCOS SUR", "municipality" => "Candon", "zip_code" => "2710"],
  ["province" => "ILOCOS SUR", "municipality" => "Caoayan", "zip_code" => "2702"],
  ["province" => "ILOCOS SUR", "municipality" => "Cervantes", "zip_code" => "2718"],
  ["province" => "ILOCOS SUR", "municipality" => "Galimuyod", "zip_code" => "2709"],
  ["province" => "ILOCOS SUR", "municipality" => "Gregorio del Pilar (Concepcion)", "zip_code" => "2720"],
  ["province" => "ILOCOS SUR", "municipality" => "Lidlidda", "zip_code" => "2723"],
  ["province" => "ILOCOS SUR", "municipality" => "Magsingal", "zip_code" => "2730"],
  ["province" => "ILOCOS SUR", "municipality" => "Nagbukel", "zip_code" => "2725"],
  ["province" => "ILOCOS SUR", "municipality" => "Narvacan", "zip_code" => "2704"],
  ["province" => "ILOCOS SUR", "municipality" => "Quirino (Angkaki)", "zip_code" => "2721"],
  ["province" => "ILOCOS SUR", "municipality" => "Salcedo (Baugen)", "zip_code" => "2711"],
  ["province" => "ILOCOS SUR", "municipality" => "San Emilio", "zip_code" => "2722"],
  ["province" => "ILOCOS SUR", "municipality" => "San Esteban", "zip_code" => "2706"],
  ["province" => "ILOCOS SUR", "municipality" => "San Ildefonso", "zip_code" => "2728"],
  ["province" => "ILOCOS SUR", "municipality" => "San Juan (Lapog)", "zip_code" => "2731"],
  ["province" => "ILOCOS SUR", "municipality" => "San Vicente", "zip_code" => "2726"],
  ["province" => "ILOCOS SUR", "municipality" => "Santa", "zip_code" => "2703"],
  ["province" => "ILOCOS SUR", "municipality" => "Santa Catalina", "zip_code" => "2701"],
  ["province" => "ILOCOS SUR", "municipality" => "Santa Cruz", "zip_code" => "2713"],
  ["province" => "ILOCOS SUR", "municipality" => "Santa Lucia", "zip_code" => "2712"],
  ["province" => "ILOCOS SUR", "municipality" => "Santa Maria", "zip_code" => "2705"],
  ["province" => "ILOCOS SUR", "municipality" => "Santiago", "zip_code" => "2707"],
  ["province" => "ILOCOS SUR", "municipality" => "Santo Domingo", "zip_code" => "2729"],
  ["province" => "ILOCOS SUR", "municipality" => "Sigay", "zip_code" => "2719"],
  ["province" => "ILOCOS SUR", "municipality" => "Sinait", "zip_code" => "2733"],
  ["province" => "ILOCOS SUR", "municipality" => "Sugpon", "zip_code" => "2717"],
  ["province" => "ILOCOS SUR", "municipality" => "Suyo", "zip_code" => "2715"],
  ["province" => "ILOCOS SUR", "municipality" => "Tagudin", "zip_code" => "2714"],
  ["province" => "ILOCOS SUR", "municipality" => "Vigan", "zip_code" => "2700"],

  ["province" => "PANGASINAN", "municipality" => "Agno", "zip_code" => "2408"],
  ["province" => "PANGASINAN", "municipality" => "Aguilar", "zip_code" => "2415"],
  ["province" => "PANGASINAN", "municipality" => "Alaminos", "zip_code" => "2404"],
  ["province" => "PANGASINAN", "municipality" => "Alcala", "zip_code" => "2425"],
  ["province" => "PANGASINAN", "municipality" => "Anda", "zip_code" => "2405"],
  ["province" => "PANGASINAN", "municipality" => "Asingan", "zip_code" => "2439"],
  ["province" => "PANGASINAN", "municipality" => "Balungao", "zip_code" => "2442"],
  ["province" => "PANGASINAN", "municipality" => "Bani", "zip_code" => "2407"],
  ["province" => "PANGASINAN", "municipality" => "Basista", "zip_code" => "2422"],
  ["province" => "PANGASINAN", "municipality" => "Bautista", "zip_code" => "2424"],
  ["province" => "PANGASINAN", "municipality" => "Bayambang", "zip_code" => "2423"],
  ["province" => "PANGASINAN", "municipality" => "Binalonan", "zip_code" => "2436"],
  ["province" => "PANGASINAN", "municipality" => "Binmaley", "zip_code" => "2417"],
  ["province" => "PANGASINAN", "municipality" => "Bolinao", "zip_code" => "2406"],
  ["province" => "PANGASINAN", "municipality" => "Bugallon", "zip_code" => "2416"],
  ["province" => "PANGASINAN", "municipality" => "Burgos", "zip_code" => "2410"],
  ["province" => "PANGASINAN", "municipality" => "Calasiao", "zip_code" => "2418"],
  ["province" => "PANGASINAN", "municipality" => "Dagupan City", "zip_code" => "2400"],
  ["province" => "PANGASINAN", "municipality" => "Dasol", "zip_code" => "2411"],
  ["province" => "PANGASINAN", "municipality" => "Infanta", "zip_code" => "2412"],
  ["province" => "PANGASINAN", "municipality" => "Labrador", "zip_code" => "2402"],
  ["province" => "PANGASINAN", "municipality" => "Laoac", "zip_code" => "2437"],
  ["province" => "PANGASINAN", "municipality" => "Lingayen", "zip_code" => "2401"],
  ["province" => "PANGASINAN", "municipality" => "Mabini", "zip_code" => "2409"],
  ["province" => "PANGASINAN", "municipality" => "Malasiqui", "zip_code" => "2421"],
  ["province" => "PANGASINAN", "municipality" => "Manaoag", "zip_code" => "2430"],
  ["province" => "PANGASINAN", "municipality" => "Mangaldan", "zip_code" => "2432"],
  ["province" => "PANGASINAN", "municipality" => "Mangatarem", "zip_code" => "2413"],
  ["province" => "PANGASINAN", "municipality" => "Mapandan", "zip_code" => "2429"],
  ["province" => "PANGASINAN", "municipality" => "Natividad", "zip_code" => "2446"],
  ["province" => "PANGASINAN", "municipality" => "Pozorrubio", "zip_code" => "2435"],
  ["province" => "PANGASINAN", "municipality" => "Rosales", "zip_code" => "2441"],
  ["province" => "PANGASINAN", "municipality" => "San Carlos City", "zip_code" => "2420"],
  ["province" => "PANGASINAN", "municipality" => "San Fabian", "zip_code" => "2433"],
  ["province" => "PANGASINAN", "municipality" => "San Jacinto", "zip_code" => "2431"],
  ["province" => "PANGASINAN", "municipality" => "San Manuel", "zip_code" => "2438"],
  ["province" => "PANGASINAN", "municipality" => "San Nicolas", "zip_code" => "2447"],
  ["province" => "PANGASINAN", "municipality" => "San Quintin", "zip_code" => "2444"],
  ["province" => "PANGASINAN", "municipality" => "Sison", "zip_code" => "2434"],
  ["province" => "PANGASINAN", "municipality" => "Santa Barbara", "zip_code" => "2419"],
  ["province" => "PANGASINAN", "municipality" => "Santa Maria", "zip_code" => "2440"],
  ["province" => "PANGASINAN", "municipality" => "SantoTomas", "zip_code" => "2426"],
  ["province" => "PANGASINAN", "municipality" => "Sual", "zip_code" => "2403"],
  ["province" => "PANGASINAN", "municipality" => "Tayug", "zip_code" => "2445"],
  ["province" => "PANGASINAN", "municipality" => "Umingan", "zip_code" => "2443"],
  ["province" => "PANGASINAN", "municipality" => "Urbiztondo", "zip_code" => "2414"],
  ["province" => "PANGASINAN", "municipality" => "Urdaneta", "zip_code" => "2428"],
  ["province" => "PANGASINAN", "municipality" => "Villasis", "zip_code" => "2427"],
]);
