<?php
return [
  ["province" => "ILOCOS NORTE", "municipality" => "ADAMS", "zip_code" => "2922"],
  ["province" => "ILOCOS NORTE", "municipality" => "BACARRA", "zip_code" => "2916"],
  ["province" => "ILOCOS NORTE", "municipality" => "BADOC", "zip_code" => "2904"],
  ["province" => "ILOCOS NORTE", "municipality" => "BANGUI", "zip_code" => "2920"],
  ["province" => "ILOCOS NORTE", "municipality" => "BATAC", "zip_code" => "2906"],
  ["province" => "ILOCOS NORTE", "municipality" => "BURGOS", "zip_code" => "2918"],
  ["province" => "ILOCOS NORTE", "municipality" => "CARASI", "zip_code" => "2911"],
  ["province" => "ILOCOS NORTE", "municipality" => "CURRIMAO", "zip_code" => "2903"],
  ["province" => "ILOCOS NORTE", "municipality" => "DINGRAS", "zip_code" => "2913"],
  ["province" => "ILOCOS NORTE", "municipality" => "DUMALNEG", "zip_code" => "2921"],
  ["province" => "ILOCOS NORTE", "municipality" => "BANNA (FORMERLY ESPIRITU)", "zip_code" => "2908"],
  ["province" => "ILOCOS NORTE", "municipality" => "LAOAG CITY", "zip_code" => "2900"],
  ["province" => "ILOCOS NORTE", "municipality" => "MARCOS", "zip_code" => "2907"],
  ["province" => "ILOCOS NORTE", "municipality" => "NUEVA ERA", "zip_code" => "2909"],
  ["province" => "ILOCOS NORTE", "municipality" => "PAGUDPUD", "zip_code" => "2919"],
  ["province" => "ILOCOS NORTE", "municipality" => "PAOAY", "zip_code" => "2902"],
  ["province" => "ILOCOS NORTE", "municipality" => "PASUQUIN", "zip_code" => "2917"],
  ["province" => "ILOCOS NORTE", "municipality" => "PIDDIG", "zip_code" => "2912"],
  ["province" => "ILOCOS NORTE", "municipality" => "PINILI", "zip_code" => "2905"],
  ["province" => "ILOCOS NORTE", "municipality" => "SAN NICOLAS", "zip_code" => "2901"],
  ["province" => "ILOCOS NORTE", "municipality" => "SARRAT", "zip_code" => "2914"],
  ["province" => "ILOCOS NORTE", "municipality" => "SOLSONA", "zip_code" => "2910"],
  ["province" => "ILOCOS NORTE", "municipality" => "VINTAR", "zip_code" => "2915"],

  ["province" => "ILOCOS SUR", "municipality" => "ALILEM", "zip_code" => "2716"],
  ["province" => "ILOCOS SUR", "municipality" => "BANAYOYO", "zip_code" => "2708"],
  ["province" => "ILOCOS SUR", "municipality" => "BANTAY", "zip_code" => "2727"],
  ["province" => "ILOCOS SUR", "municipality" => "BURGOS", "zip_code" => "2724"],
  ["province" => "ILOCOS SUR", "municipality" => "CABUGAO", "zip_code" => "2732"],
  ["province" => "ILOCOS SUR", "municipality" => "CANDON", "zip_code" => "2710"],
  ["province" => "ILOCOS SUR", "municipality" => "CAOAYAN", "zip_code" => "2702"],
  ["province" => "ILOCOS SUR", "municipality" => "CERVANTES", "zip_code" => "2718"],
  ["province" => "ILOCOS SUR", "municipality" => "GALIMUYOD", "zip_code" => "2709"],
  ["province" => "ILOCOS SUR", "municipality" => "GREGORIO DEL PILAR (CONCEPCION)", "zip_code" => "2720"],
  ["province" => "ILOCOS SUR", "municipality" => "LIDLIDDA", "zip_code" => "2723"],
  ["province" => "ILOCOS SUR", "municipality" => "MAGSINGAL", "zip_code" => "2730"],
  ["province" => "ILOCOS SUR", "municipality" => "NAGBUKEL", "zip_code" => "2725"],
  ["province" => "ILOCOS SUR", "municipality" => "NARVACAN", "zip_code" => "2704"],
  ["province" => "ILOCOS SUR", "municipality" => "QUIRINO (ANGKAKI)", "zip_code" => "2721"],
  ["province" => "ILOCOS SUR", "municipality" => "SALCEDO (BAUGEN)", "zip_code" => "2711"],
  ["province" => "ILOCOS SUR", "municipality" => "SAN EMILIO", "zip_code" => "2722"],
  ["province" => "ILOCOS SUR", "municipality" => "SAN ESTEBAN", "zip_code" => "2706"],
  ["province" => "ILOCOS SUR", "municipality" => "SAN ILDEFONSO", "zip_code" => "2728"],
  ["province" => "ILOCOS SUR", "municipality" => "SAN JUAN (LAPOG)", "zip_code" => "2731"],
  ["province" => "ILOCOS SUR", "municipality" => "SAN VICENTE", "zip_code" => "2726"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTA", "zip_code" => "2703"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTA CATALINA", "zip_code" => "2701"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTA CRUZ", "zip_code" => "2713"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTA LUCIA", "zip_code" => "2712"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTA MARIA", "zip_code" => "2705"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTIAGO", "zip_code" => "2707"],
  ["province" => "ILOCOS SUR", "municipality" => "SANTO DOMINGO", "zip_code" => "2729"],
  ["province" => "ILOCOS SUR", "municipality" => "SIGAY", "zip_code" => "2719"],
  ["province" => "ILOCOS SUR", "municipality" => "SINAIT", "zip_code" => "2733"],
  ["province" => "ILOCOS SUR", "municipality" => "SUGPON", "zip_code" => "2717"],
  ["province" => "ILOCOS SUR", "municipality" => "SUYO", "zip_code" => "2715"],
  ["province" => "ILOCOS SUR", "municipality" => "TAGUDIN", "zip_code" => "2714"],
  ["province" => "ILOCOS SUR", "municipality" => "VIGAN", "zip_code" => "2700"],

  ["province" => "LA UNION", "municipality" => "AGOO", "zip_code" => "2504"],
  ["province" => "LA UNION", "municipality" => "ARINGAY", "zip_code" => "2503"],
  ["province" => "LA UNION", "municipality" => "BACNOTAN", "zip_code" => "2515"],
  ["province" => "LA UNION", "municipality" => "BAGULIN", "zip_code" => "2512"],
  ["province" => "LA UNION", "municipality" => "BALAOAN", "zip_code" => "2517"],
  ["province" => "LA UNION", "municipality" => "BANGAR", "zip_code" => "2519"],
  ["province" => "LA UNION", "municipality" => "BAUANG", "zip_code" => "2501"],
  ["province" => "LA UNION", "municipality" => "BURGOS", "zip_code" => "2510"],
  ["province" => "LA UNION", "municipality" => "CABA", "zip_code" => "2502"],
  ["province" => "LA UNION", "municipality" => "DAMORTIS", "zip_code" => "2507"],
  ["province" => "LA UNION", "municipality" => "LUNA", "zip_code" => "2518"],
  ["province" => "LA UNION", "municipality" => "NAGUILIAN", "zip_code" => "2511"],
  ["province" => "LA UNION", "municipality" => "PUGO", "zip_code" => "2508"],
  ["province" => "LA UNION", "municipality" => "ROSARIO", "zip_code" => "2506"],
  ["province" => "LA UNION", "municipality" => "SAN FERNANDO CITY", "zip_code" => "2500"],
  ["province" => "LA UNION", "municipality" => "SAN GABRIEL", "zip_code" => "2513"],
  ["province" => "LA UNION", "municipality" => "SAN JUAN", "zip_code" => "2514"],
  ["province" => "LA UNION", "municipality" => "SANTOL", "zip_code" => "2516"],
  ["province" => "LA UNION", "municipality" => "SANTO TOMAS", "zip_code" => "2505"],
  ["province" => "LA UNION", "municipality" => "SUDIPEN", "zip_code" => "2520"],
  ["province" => "LA UNION", "municipality" => "TUBAO", "zip_code" => "2509"],

  ["province" => "PANGASINAN", "municipality" => "AGNO", "zip_code" => "2408"],
  ["province" => "PANGASINAN", "municipality" => "AGUILAR", "zip_code" => "2415"],
  ["province" => "PANGASINAN", "municipality" => "ALAMINOS", "zip_code" => "2404"],
  ["province" => "PANGASINAN", "municipality" => "ALCALA", "zip_code" => "2425"],
  ["province" => "PANGASINAN", "municipality" => "ANDA", "zip_code" => "2405"],
  ["province" => "PANGASINAN", "municipality" => "ASINGAN", "zip_code" => "2439"],
  ["province" => "PANGASINAN", "municipality" => "BALUNGAO", "zip_code" => "2442"],
  ["province" => "PANGASINAN", "municipality" => "BANI", "zip_code" => "2407"],
  ["province" => "PANGASINAN", "municipality" => "BASISTA", "zip_code" => "2422"],
  ["province" => "PANGASINAN", "municipality" => "BAUTISTA", "zip_code" => "2424"],
  ["province" => "PANGASINAN", "municipality" => "BAYAMBANG", "zip_code" => "2423"],
  ["province" => "PANGASINAN", "municipality" => "BINALONAN", "zip_code" => "2436"],
  ["province" => "PANGASINAN", "municipality" => "BINMALEY", "zip_code" => "2417"],
  ["province" => "PANGASINAN", "municipality" => "BOLINAO", "zip_code" => "2406"],
  ["province" => "PANGASINAN", "municipality" => "BUGALLON", "zip_code" => "2416"],
  ["province" => "PANGASINAN", "municipality" => "BURGOS", "zip_code" => "2410"],
  ["province" => "PANGASINAN", "municipality" => "CALASIAO", "zip_code" => "2418"],
  ["province" => "PANGASINAN", "municipality" => "DAGUPAN CITY", "zip_code" => "2400"],
  ["province" => "PANGASINAN", "municipality" => "DASOL", "zip_code" => "2411"],
  ["province" => "PANGASINAN", "municipality" => "INFANTA", "zip_code" => "2412"],
  ["province" => "PANGASINAN", "municipality" => "LABRADOR", "zip_code" => "2402"],
  ["province" => "PANGASINAN", "municipality" => "LAOAC", "zip_code" => "2437"],
  ["province" => "PANGASINAN", "municipality" => "LINGAYEN", "zip_code" => "2401"],
  ["province" => "PANGASINAN", "municipality" => "MABINI", "zip_code" => "2409"],
  ["province" => "PANGASINAN", "municipality" => "MALASIQUI", "zip_code" => "2421"],
  ["province" => "PANGASINAN", "municipality" => "MANAOAG", "zip_code" => "2430"],
  ["province" => "PANGASINAN", "municipality" => "MANGALDAN", "zip_code" => "2432"],
  ["province" => "PANGASINAN", "municipality" => "MANGATAREM", "zip_code" => "2413"],
  ["province" => "PANGASINAN", "municipality" => "MAPANDAN", "zip_code" => "2429"],
  ["province" => "PANGASINAN", "municipality" => "NATIVIDAD", "zip_code" => "2446"],
  ["province" => "PANGASINAN", "municipality" => "POZORRUBIO", "zip_code" => "2435"],
  ["province" => "PANGASINAN", "municipality" => "ROSALES", "zip_code" => "2441"],
  ["province" => "PANGASINAN", "municipality" => "SAN CARLOS CITY", "zip_code" => "2420"],
  ["province" => "PANGASINAN", "municipality" => "SAN FABIAN", "zip_code" => "2433"],
  ["province" => "PANGASINAN", "municipality" => "SAN JACINTO", "zip_code" => "2431"],
  ["province" => "PANGASINAN", "municipality" => "SAN MANUEL", "zip_code" => "2438"],
  ["province" => "PANGASINAN", "municipality" => "SAN NICOLAS", "zip_code" => "2447"],
  ["province" => "PANGASINAN", "municipality" => "SAN QUINTIN", "zip_code" => "2444"],
  ["province" => "PANGASINAN", "municipality" => "SISON", "zip_code" => "2434"],
  ["province" => "PANGASINAN", "municipality" => "SANTA BARBARA", "zip_code" => "2419"],
  ["province" => "PANGASINAN", "municipality" => "SANTA MARIA", "zip_code" => "2440"],
  ["province" => "PANGASINAN", "municipality" => "SANTOTOMAS", "zip_code" => "2426"],
  ["province" => "PANGASINAN", "municipality" => "SUAL", "zip_code" => "2403"],
  ["province" => "PANGASINAN", "municipality" => "TAYUG", "zip_code" => "2445"],
  ["province" => "PANGASINAN", "municipality" => "UMINGAN", "zip_code" => "2443"],
  ["province" => "PANGASINAN", "municipality" => "URBIZTONDO", "zip_code" => "2414"],
  ["province" => "PANGASINAN", "municipality" => "URDANETA", "zip_code" => "2428"],
  ["province" => "PANGASINAN", "municipality" => "VILLASIS", "zip_code" => "2427"],
];
