<?php
return array_map('trim', [
  ["province" => "BATANES", "municipality" => "Basco", "zip_code" => "3900"],
  ["province" => "BATANES", "municipality" => "Itbayat", "zip_code" => "3905"],
  ["province" => "BATANES", "municipality" => "Ivana", "zip_code" => "3902"],
  ["province" => "BATANES", "municipality" => "Mahatao", "zip_code" => "3901"],
  ["province" => "BATANES", "municipality" => "Sabtang", "zip_code" => "3904"],
  ["province" => "BATANES", "municipality" => "Uyugan", "zip_code" => "3903"],

  ["province" => "CAGAYAN", "municipality" => "Abulug", "zip_code" => "3517"],
  ["province" => "CAGAYAN", "municipality" => "Alcala", "zip_code" => "3507"],
  ["province" => "CAGAYAN", "municipality" => "Allacapan", "zip_code" => "3523"],
  ["province" => "CAGAYAN", "municipality" => "Amulung", "zip_code" => "3505"],
  ["province" => "CAGAYAN", "municipality" => "Aparri", "zip_code" => "3515"],
  ["province" => "CAGAYAN", "municipality" => "Baggao", "zip_code" => "3506"],
  ["province" => "CAGAYAN", "municipality" => "Ballesteros", "zip_code" => "3516"],
  ["province" => "CAGAYAN", "municipality" => "Buguey", "zip_code" => "3511"],
  ["province" => "CAGAYAN", "municipality" => "Calayan", "zip_code" => "3520"],
  ["province" => "CAGAYAN", "municipality" => "Camalaniugan", "zip_code" => "3510"],
  ["province" => "CAGAYAN", "municipality" => "Claveria", "zip_code" => "3519"],
  ["province" => "CAGAYAN", "municipality" => "Enrile", "zip_code" => "3501"],
  ["province" => "CAGAYAN", "municipality" => "Gattaran", "zip_code" => "3508"],
  ["province" => "CAGAYAN", "municipality" => "Gonzaga", "zip_code" => "3513"],
  ["province" => "CAGAYAN", "municipality" => "Iguig", "zip_code" => "3504"],
  ["province" => "CAGAYAN", "municipality" => "Lal-lo", "zip_code" => "3509"],
  ["province" => "CAGAYAN", "municipality" => "Lasam", "zip_code" => "3524"],
  ["province" => "CAGAYAN", "municipality" => "Pamplona", "zip_code" => "3522"],
  ["province" => "CAGAYAN", "municipality" => "Peñablanca", "zip_code" => "3502"],
  ["province" => "CAGAYAN", "municipality" => "Piat", "zip_code" => "3527"],
  ["province" => "CAGAYAN", "municipality" => "Rizal", "zip_code" => "3526"],
  ["province" => "CAGAYAN", "municipality" => "Sanchez-Mira", "zip_code" => "3518"],
  ["province" => "CAGAYAN", "municipality" => "Solana", "zip_code" => "3503"],
  ["province" => "CAGAYAN", "municipality" => "Sta. Ana", "zip_code" => "3514"],
  ["province" => "CAGAYAN", "municipality" => "Santa Praxedes", "zip_code" => "3521"],
  ["province" => "CAGAYAN", "municipality" => "Sta. Teresita", "zip_code" => "3512"],
  ["province" => "CAGAYAN", "municipality" => "Santo Niño", "zip_code" => "3525"],
  ["province" => "CAGAYAN", "municipality" => "Tuao", "zip_code" => "3528"],
  ["province" => "CAGAYAN", "municipality" => "Tuguegarao City", "zip_code" => "3500"],

  ["province" => "ISABELA", "municipality" => "Alicia", "zip_code" => "3306"],
  ["province" => "ISABELA", "municipality" => "Angadanan", "zip_code" => "3307"],
  ["province" => "ISABELA", "municipality" => "Aurora", "zip_code" => "3316"],
  ["province" => "ISABELA", "municipality" => "Benito Soliven", "zip_code" => "3331"],
  ["province" => "ISABELA", "municipality" => "Burgos", "zip_code" => "3322"],
  ["province" => "ISABELA", "municipality" => "Cabagan", "zip_code" => "3328"],
  ["province" => "ISABELA", "municipality" => "Cabatuan", "zip_code" => "3315"],
  ["province" => "ISABELA", "municipality" => "City of Cauayan", "zip_code" => "3305"],
  ["province" => "ISABELA", "municipality" => "City of Ilagan", "zip_code" => "3300"],
  ["province" => "ISABELA", "municipality" => "Cordon", "zip_code" => "3312"],
  ["province" => "ISABELA", "municipality" => "Delfin Albano", "zip_code" => "3326"],
  ["province" => "ISABELA", "municipality" => "Dinapigue", "zip_code" => "3336"],
  ["province" => "ISABELA", "municipality" => "Divilacan", "zip_code" => "3335"],
  ["province" => "ISABELA", "municipality" => "Echague", "zip_code" => "3309"],
  ["province" => "ISABELA", "municipality" => "Gamu", "zip_code" => "3301"],
  ["province" => "ISABELA", "municipality" => "Jones", "zip_code" => "3313"],
  ["province" => "ISABELA", "municipality" => "Luna", "zip_code" => "3304"],
  ["province" => "ISABELA", "municipality" => "Maconacon", "zip_code" => "3333"],
  ["province" => "ISABELA", "municipality" => "Mallig", "zip_code" => "3323"],
  ["province" => "ISABELA", "municipality" => "Naguillan", "zip_code" => "3302"],
  ["province" => "ISABELA", "municipality" => "Palanan", "zip_code" => "3334"],
  ["province" => "ISABELA", "municipality" => "Quezon", "zip_code" => "3324"],
  ["province" => "ISABELA", "municipality" => "Quirino", "zip_code" => "3321"],
  ["province" => "ISABELA", "municipality" => "Ramon", "zip_code" => "3319"],
  ["province" => "ISABELA", "municipality" => "Reina Mercedes", "zip_code" => "3303"],
  ["province" => "ISABELA", "municipality" => "Roxas", "zip_code" => "3320"],
  ["province" => "ISABELA", "municipality" => "San Agustin", "zip_code" => "3314"],
  ["province" => "ISABELA", "municipality" => "San Guillermo", "zip_code" => "3308"],
  ["province" => "ISABELA", "municipality" => "San Isidro", "zip_code" => "3310"],
  ["province" => "ISABELA", "municipality" => "San Manuel", "zip_code" => "3317"],
  ["province" => "ISABELA", "municipality" => "San Mariano", "zip_code" => "3332"],
  ["province" => "ISABELA", "municipality" => "San Mateo", "zip_code" => "3318"],
  ["province" => "ISABELA", "municipality" => "San Pablo", "zip_code" => "3329"],
  ["province" => "ISABELA", "municipality" => "Santiago CIty", "zip_code" => "3311"],
  ["province" => "ISABELA", "municipality" => "Sta. Maria", "zip_code" => "3330"],
  ["province" => "ISABELA", "municipality" => "Sto. Tomas", "zip_code" => "3327"],
  ["province" => "ISABELA", "municipality" => "Tumauini", "zip_code" => "3325"],

  ["province" => "NUEVA VIZCAYA", "municipality" => "Alfonso Castañeda", "zip_code" => "3714"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Ambaguio", "zip_code" => "3701"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Aritao", "zip_code" => "3704"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Bagabag", "zip_code" => "3711"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Bambang", "zip_code" => "3702"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Bayombong", "zip_code" => "3700"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Diadi", "zip_code" => "3712"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Dupax del Norte", "zip_code" => "3706"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Dupax del Sur", "zip_code" => "3707"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Kasibu", "zip_code" => "3703"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Kayapa", "zip_code" => "3708"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Quezon", "zip_code" => "3713"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Solano", "zip_code" => "3709"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Sta. Fe", "zip_code" => "3705"],
  ["province" => "NUEVA VIZCAYA", "municipality" => "Villaverde", "zip_code" => "3710"],

  ["province" => "QUIRINO", "municipality" => "Aglipay", "zip_code" => "3403"],
  ["province" => "QUIRINO", "municipality" => "Cabarroguis", "zip_code" => "3400"],
  ["province" => "QUIRINO", "municipality" => "Diffun", "zip_code" => "3401"],
  ["province" => "QUIRINO", "municipality" => "Maddela", "zip_code" => "3404"],
  ["province" => "QUIRINO", "municipality" => "Nagtipunan", "zip_code" => "3405"],
  ["province" => "QUIRINO", "municipality" => "Saguday", "zip_code" => "3402"],

]);
