<?php

declare(strict_types=1);

return [
    ['province' => 'BATANES', 'municipality' => 'BASCO', 'zip_code' => '3900'],
    ['province' => 'BATANES', 'municipality' => 'ITBAYAT', 'zip_code' => '3905'],
    ['province' => 'BATANES', 'municipality' => 'IVANA', 'zip_code' => '3902'],
    ['province' => 'BATANES', 'municipality' => 'MAHATAO', 'zip_code' => '3901'],
    ['province' => 'BATANES', 'municipality' => 'SABTANG', 'zip_code' => '3904'],
    ['province' => 'BATANES', 'municipality' => 'UYUGAN', 'zip_code' => '3903'],

    ['province' => 'CAGAYAN', 'municipality' => 'ABULUG', 'zip_code' => '3517'],
    ['province' => 'CAGAYAN', 'municipality' => 'ALCALA', 'zip_code' => '3507'],
    ['province' => 'CAGAYAN', 'municipality' => 'ALLACAPAN', 'zip_code' => '3523'],
    ['province' => 'CAGAYAN', 'municipality' => 'AMULUNG', 'zip_code' => '3505'],
    ['province' => 'CAGAYAN', 'municipality' => 'APARRI', 'zip_code' => '3515'],
    ['province' => 'CAGAYAN', 'municipality' => 'BAGGAO', 'zip_code' => '3506'],
    ['province' => 'CAGAYAN', 'municipality' => 'BALLESTEROS', 'zip_code' => '3516'],
    ['province' => 'CAGAYAN', 'municipality' => 'BUGUEY', 'zip_code' => '3511'],
    ['province' => 'CAGAYAN', 'municipality' => 'CALAYAN', 'zip_code' => '3520'],
    ['province' => 'CAGAYAN', 'municipality' => 'CAMALANIUGAN', 'zip_code' => '3510'],
    ['province' => 'CAGAYAN', 'municipality' => 'CLAVERIA', 'zip_code' => '3519'],
    ['province' => 'CAGAYAN', 'municipality' => 'ENRILE', 'zip_code' => '3501'],
    ['province' => 'CAGAYAN', 'municipality' => 'GATTARAN', 'zip_code' => '3508'],
    ['province' => 'CAGAYAN', 'municipality' => 'GONZAGA', 'zip_code' => '3513'],
    ['province' => 'CAGAYAN', 'municipality' => 'IGUIG', 'zip_code' => '3504'],
    ['province' => 'CAGAYAN', 'municipality' => 'LAL-LO', 'zip_code' => '3509'],
    ['province' => 'CAGAYAN', 'municipality' => 'LASAM', 'zip_code' => '3524'],
    ['province' => 'CAGAYAN', 'municipality' => 'PAMPLONA', 'zip_code' => '3522'],
    ['province' => 'CAGAYAN', 'municipality' => 'PEÑABLANCA', 'zip_code' => '3502'],
    ['province' => 'CAGAYAN', 'municipality' => 'PIAT', 'zip_code' => '3527'],
    ['province' => 'CAGAYAN', 'municipality' => 'RIZAL', 'zip_code' => '3526'],
    ['province' => 'CAGAYAN', 'municipality' => 'SANCHEZ-MIRA', 'zip_code' => '3518'],
    ['province' => 'CAGAYAN', 'municipality' => 'SOLANA', 'zip_code' => '3503'],
    ['province' => 'CAGAYAN', 'municipality' => 'STA. ANA', 'zip_code' => '3514'],
    ['province' => 'CAGAYAN', 'municipality' => 'SANTA PRAXEDES', 'zip_code' => '3521'],
    ['province' => 'CAGAYAN', 'municipality' => 'STA. TERESITA', 'zip_code' => '3512'],
    ['province' => 'CAGAYAN', 'municipality' => 'SANTO NIÑO', 'zip_code' => '3525'],
    ['province' => 'CAGAYAN', 'municipality' => 'TUAO', 'zip_code' => '3528'],
    ['province' => 'CAGAYAN', 'municipality' => 'TUGUEGARAO CITY', 'zip_code' => '3500'],

    ['province' => 'ISABELA', 'municipality' => 'ALICIA', 'zip_code' => '3306'],
    ['province' => 'ISABELA', 'municipality' => 'ANGADANAN', 'zip_code' => '3307'],
    ['province' => 'ISABELA', 'municipality' => 'AURORA', 'zip_code' => '3316'],
    ['province' => 'ISABELA', 'municipality' => 'BENITO SOLIVEN', 'zip_code' => '3331'],
    ['province' => 'ISABELA', 'municipality' => 'BURGOS', 'zip_code' => '3322'],
    ['province' => 'ISABELA', 'municipality' => 'CABAGAN', 'zip_code' => '3328'],
    ['province' => 'ISABELA', 'municipality' => 'CABATUAN', 'zip_code' => '3315'],
    ['province' => 'ISABELA', 'municipality' => 'CITY OF CAUAYAN', 'zip_code' => '3305'],
    ['province' => 'ISABELA', 'municipality' => 'CITY OF ILAGAN', 'zip_code' => '3300'],
    ['province' => 'ISABELA', 'municipality' => 'CORDON', 'zip_code' => '3312'],
    ['province' => 'ISABELA', 'municipality' => 'DELFIN ALBANO', 'zip_code' => '3326'],
    ['province' => 'ISABELA', 'municipality' => 'DINAPIGUE', 'zip_code' => '3336'],
    ['province' => 'ISABELA', 'municipality' => 'DIVILACAN', 'zip_code' => '3335'],
    ['province' => 'ISABELA', 'municipality' => 'ECHAGUE', 'zip_code' => '3309'],
    ['province' => 'ISABELA', 'municipality' => 'GAMU', 'zip_code' => '3301'],
    ['province' => 'ISABELA', 'municipality' => 'JONES', 'zip_code' => '3313'],
    ['province' => 'ISABELA', 'municipality' => 'LUNA', 'zip_code' => '3304'],
    ['province' => 'ISABELA', 'municipality' => 'MACONACON', 'zip_code' => '3333'],
    ['province' => 'ISABELA', 'municipality' => 'MALLIG', 'zip_code' => '3323'],
    ['province' => 'ISABELA', 'municipality' => 'NAGUILIAN', 'zip_code' => '3302'],
    ['province' => 'ISABELA', 'municipality' => 'PALANAN', 'zip_code' => '3334'],
    ['province' => 'ISABELA', 'municipality' => 'QUEZON', 'zip_code' => '3324'],
    ['province' => 'ISABELA', 'municipality' => 'QUIRINO', 'zip_code' => '3321'],
    ['province' => 'ISABELA', 'municipality' => 'RAMON', 'zip_code' => '3319'],
    ['province' => 'ISABELA', 'municipality' => 'REINA MERCEDES', 'zip_code' => '3303'],
    ['province' => 'ISABELA', 'municipality' => 'ROXAS', 'zip_code' => '3320'],
    ['province' => 'ISABELA', 'municipality' => 'SAN AGUSTIN', 'zip_code' => '3314'],
    ['province' => 'ISABELA', 'municipality' => 'SAN GUILLERMO', 'zip_code' => '3308'],
    ['province' => 'ISABELA', 'municipality' => 'SAN ISIDRO', 'zip_code' => '3310'],
    ['province' => 'ISABELA', 'municipality' => 'SAN MANUEL', 'zip_code' => '3317'],
    ['province' => 'ISABELA', 'municipality' => 'SAN MARIANO', 'zip_code' => '3332'],
    ['province' => 'ISABELA', 'municipality' => 'SAN MATEO', 'zip_code' => '3318'],
    ['province' => 'ISABELA', 'municipality' => 'SAN PABLO', 'zip_code' => '3329'],
    ['province' => 'ISABELA', 'municipality' => 'SANTIAGO CITY', 'zip_code' => '3311'],
    ['province' => 'ISABELA', 'municipality' => 'STA. MARIA', 'zip_code' => '3330'],
    ['province' => 'ISABELA', 'municipality' => 'STO. TOMAS', 'zip_code' => '3327'],
    ['province' => 'ISABELA', 'municipality' => 'TUMAUINI', 'zip_code' => '3325'],

    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'ALFONSO CASTAÑEDA', 'zip_code' => '3714'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'AMBAGUIO', 'zip_code' => '3701'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'ARITAO', 'zip_code' => '3704'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'BAGABAG', 'zip_code' => '3711'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'BAMBANG', 'zip_code' => '3702'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'BAYOMBONG', 'zip_code' => '3700'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'DIADI', 'zip_code' => '3712'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'DUPAX DEL NORTE', 'zip_code' => '3706'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'DUPAX DEL SUR', 'zip_code' => '3707'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'KASIBU', 'zip_code' => '3703'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'KAYAPA', 'zip_code' => '3708'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'QUEZON', 'zip_code' => '3713'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'SOLANO', 'zip_code' => '3709'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'STA. FE', 'zip_code' => '3705'],
    ['province' => 'NUEVA VIZCAYA', 'municipality' => 'VILLAVERDE', 'zip_code' => '3710'],

    ['province' => 'QUIRINO', 'municipality' => 'AGLIPAY', 'zip_code' => '3403'],
    ['province' => 'QUIRINO', 'municipality' => 'CABARROGUIS', 'zip_code' => '3400'],
    ['province' => 'QUIRINO', 'municipality' => 'DIFFUN', 'zip_code' => '3401'],
    ['province' => 'QUIRINO', 'municipality' => 'MADDELA', 'zip_code' => '3404'],
    ['province' => 'QUIRINO', 'municipality' => 'NAGTIPUNAN', 'zip_code' => '3405'],
    ['province' => 'QUIRINO', 'municipality' => 'SAGUDAY', 'zip_code' => '3402'],
];
