<?php

declare(strict_types=1);

return [
    [
        'province' => 'BATANGAS',
        'zip_codes' => [
            ['municipality' => 'AGONCILLO', 'zip_code' => '4211'],
            ['municipality' => 'ALITAGTAG', 'zip_code' => '4205'],
            ['municipality' => 'BALAYAN', 'zip_code' => '4213'],
            ['municipality' => 'BALETE', 'zip_code' => '4219'],
            ['municipality' => 'BATANGAS CITY', 'zip_code' => '4200'],
            ['municipality' => 'BAUAN', 'zip_code' => '4201'],
            ['municipality' => 'CALACA', 'zip_code' => '4212'],
            ['municipality' => 'CALATAGAN', 'zip_code' => '4215'],
            ['municipality' => 'CUENCA', 'zip_code' => '4222'],
            ['municipality' => 'FERNANDO AIRBASE', 'zip_code' => '4218'],
            ['municipality' => 'IBAAN', 'zip_code' => '4230'],
            ['municipality' => 'LAUREL', 'zip_code' => '4221'],
            ['municipality' => 'LEMERY', 'zip_code' => '4209'],
            ['municipality' => 'LIAN', 'zip_code' => '4216'],
            ['municipality' => 'LIPA CITY', 'zip_code' => '4217'],
            ['municipality' => 'LOBO', 'zip_code' => '4229'],
            ['municipality' => 'MABINI', 'zip_code' => '4202'],
            ['municipality' => 'MALVAR', 'zip_code' => '4233'],
            ['municipality' => 'MATAAS NA KAHOY', 'zip_code' => '4223'],
            ['municipality' => 'NASUGBU', 'zip_code' => '4231'],
            ['municipality' => 'PADRE GARCIA', 'zip_code' => '4224'],
            ['municipality' => 'ROSARIO', 'zip_code' => '4225'],
            ['municipality' => 'SAN JOSE', 'zip_code' => '4227'],
            ['municipality' => 'SAN JUAN', 'zip_code' => '4226'],
            ['municipality' => 'SAN LUIS', 'zip_code' => '4210'],
            ['municipality' => 'SAN NICOLAS', 'zip_code' => '4207'],
            ['municipality' => 'SAN PASCUAL', 'zip_code' => '4204'],
            ['municipality' => 'STA. TERESITA', 'zip_code' => '4206'],
            ['municipality' => 'STO. TOMAS', 'zip_code' => '4234'],
            ['municipality' => 'TAAL', 'zip_code' => '4208'],
            ['municipality' => 'TALISAY', 'zip_code' => '4220'],
            ['municipality' => 'TANAUAN', 'zip_code' => '4232'],
            ['municipality' => 'TAYSAN', 'zip_code' => '4228'],
            ['municipality' => 'TINGLOY', 'zip_code' => '4203'],
            ['municipality' => 'TUY', 'zip_code' => '4214'],
        ]
    ],

    [
        'province' => 'CAVITE',
        'zip_codes' => [
            ['municipality' => 'IST CAVITE IND. ESTATE', 'zip_code' => '4126'],
            ['municipality' => 'ALFONSO', 'zip_code' => '4123'],
            ['municipality' => 'AMADEO', 'zip_code' => '4119'],
            ['municipality' => 'BACOOR', 'zip_code' => '4102'],
            ['municipality' => 'CARMONA', 'zip_code' => '4116'],
            ['municipality' => 'CAVITE CITY', 'zip_code' => '4100'],
            ['municipality' => 'CAVITE NAVAL BASE', 'zip_code' => '4101'],
            ['municipality' => 'CORREGIDOR', 'zip_code' => '4125'],
            ['municipality' => 'DASMARIÑAS', 'zip_code' => '4114'],
            ['municipality' => 'DASMARIÑAS RESETTLEMENT AREA', 'zip_code' => '4115'],
            ['municipality' => 'GEN. AGUINALDO (BAILEN)', 'zip_code' => '4124'],
            ['municipality' => 'GEN. MARIANO ALVAREZ', 'zip_code' => '4117'],
            ['municipality' => 'GEN. TRIAS', 'zip_code' => '4107'],
            ['municipality' => 'IMUS', 'zip_code' => '4103'],
            ['municipality' => 'INDANG', 'zip_code' => '4122'],
            ['municipality' => 'KAWIT', 'zip_code' => '4104'],
            ['municipality' => 'MAGALLANES', 'zip_code' => '4113'],
            ['municipality' => 'MARAGONDON', 'zip_code' => '4112'],
            ['municipality' => 'MENDEZ', 'zip_code' => '4121'],
            ['municipality' => 'MOLINO', 'zip_code' => '4135'],
            ['municipality' => 'NAIC', 'zip_code' => '4110'],
            ['municipality' => 'NOVELETA', 'zip_code' => '4105'],
            ['municipality' => 'ROSARIO', 'zip_code' => '4106'],
            ['municipality' => 'SILANG', 'zip_code' => '4118'],
            ['municipality' => 'TAGAYTAY', 'zip_code' => '4120'],
            ['municipality' => 'TANZA', 'zip_code' => '4108'],
            ['municipality' => 'TERNATE', 'zip_code' => '4111'],
            ['municipality' => 'TRECE MARTIREZ CITY', 'zip_code' => '4109'],
        ]
    ],

    [
        'province' => 'LAGUNA',
        'zip_codes' => [
            ['municipality' => 'ALAMINOS', 'zip_code' => '4001'],
            ['municipality' => 'BAY', 'zip_code' => '4033'],
            ['municipality' => 'BIÑAN', 'zip_code' => '4024'],
            ['municipality' => 'BOTOCAN', 'zip_code' => '4006'],
            ['municipality' => 'CABUYAO', 'zip_code' => '4025'],
            ['municipality' => 'CALAMBA', 'zip_code' => '4027'],
            ['municipality' => 'CALUAN', 'zip_code' => '4012'],
            ['municipality' => 'CAMP VICENTE LIM', 'zip_code' => '4029'],
            ['municipality' => 'CANLUBANG', 'zip_code' => '4028'],
            ['municipality' => 'CAVINTI', 'zip_code' => '4013'],
            ['municipality' => 'COLLEGE LOS BAÑOS', 'zip_code' => '4031'],
            ['municipality' => 'FAMY', 'zip_code' => '4021'],
            ['municipality' => 'KALAYAAN', 'zip_code' => '4015'],
            ['municipality' => 'LAGUNA TECHNOPARK', 'zip_code' => '4034'],
            ['municipality' => 'LILIW', 'zip_code' => '4004'],
            ['municipality' => 'LOS BAÑOS', 'zip_code' => '4030'],
            ['municipality' => 'LUISIANA', 'zip_code' => '4032'],
            ['municipality' => 'LUMBAN', 'zip_code' => '4014'],
            ['municipality' => 'MABITAC', 'zip_code' => '4020'],
            ['municipality' => 'MAGDALENA', 'zip_code' => '4007'],
            ['municipality' => 'MAJAYJAY', 'zip_code' => '4005'],
            ['municipality' => 'NAGCARLAN', 'zip_code' => '4002'],
            ['municipality' => 'PAETE', 'zip_code' => '4016'],
            ['municipality' => 'PAGSANJAN', 'zip_code' => '4008'],
            ['municipality' => 'PAKIL', 'zip_code' => '4017'],
            ['municipality' => 'PANGIL', 'zip_code' => '4018'],
            ['municipality' => 'PILA', 'zip_code' => '4010'],
            ['municipality' => 'RIZAL', 'zip_code' => '4003'],
            ['municipality' => 'SAN PABLO CITY', 'zip_code' => '4000'],
            ['municipality' => 'SAN PEDRO', 'zip_code' => '4023'],
            ['municipality' => 'SINILOAN', 'zip_code' => '4019'],
            ['municipality' => 'STA. CRUZ', 'zip_code' => '4009'],
            ['municipality' => 'STA. MARIA', 'zip_code' => '4022'],
            ['municipality' => 'STA. ROSA', 'zip_code' => '4026'],
            ['municipality' => 'VICTORIA', 'zip_code' => '4011'],
        ]
    ],

    [
        'province' => 'QUEZON PROVINCE',
        'zip_codes' => [
            ['municipality' => 'AGDANGAN', 'zip_code' => '4304'],
            ['municipality' => 'ALABAT', 'zip_code' => '4333'],
            ['municipality' => 'ATIMONAN', 'zip_code' => '4331'],
            ['municipality' => 'BUENAVISTA', 'zip_code' => '4320'],
            ['municipality' => 'BURDEOS', 'zip_code' => '4340'],
            ['municipality' => 'CALAUAG', 'zip_code' => '4318'],
            ['municipality' => 'CANDELARIA', 'zip_code' => '4323'],
            ['municipality' => 'CATANAUAN', 'zip_code' => '4311'],
            ['municipality' => 'DOLORES', 'zip_code' => '4326'],
            ['municipality' => 'GENERAL LUNA', 'zip_code' => '4310'],
            ['municipality' => 'GENERAL NAKAR', 'zip_code' => '4338'],
            ['municipality' => 'GUINAYANGAN', 'zip_code' => '4319'],
            ['municipality' => 'GUMACA', 'zip_code' => '4307'],
            ['municipality' => 'HONDAGUA', 'zip_code' => '4317'],
            ['municipality' => 'INFANTA', 'zip_code' => '4336'],
            ['municipality' => 'JOMALIG', 'zip_code' => '4342'],
            ['municipality' => 'LOPEZ', 'zip_code' => '4316'],
            ['municipality' => 'LUCBAN', 'zip_code' => '4328'],
            ['municipality' => 'LUCENA CITY', 'zip_code' => '4301'],
            ['municipality' => 'MACALELON', 'zip_code' => '4309'],
            ['municipality' => 'MAUBAN', 'zip_code' => '4330'],
            ['municipality' => 'MULANAY', 'zip_code' => '4312'],
            ['municipality' => 'PADRE BURGOS', 'zip_code' => '4303'],
            ['municipality' => 'PAGBILAO', 'zip_code' => '4302'],
            ['municipality' => 'PANUKULAN', 'zip_code' => '4337'],
            ['municipality' => 'PATNANUNGAN', 'zip_code' => '4341'],
            ['municipality' => 'PEREZ', 'zip_code' => '4334'],
            ['municipality' => 'PITOGO', 'zip_code' => '4308'],
            ['municipality' => 'PLARIDEL', 'zip_code' => '4306'],
            ['municipality' => 'POLILIO', 'zip_code' => '4339'],
            ['municipality' => 'QUEZON     ', 'zip_code' => '4332'],
            ['municipality' => 'QUEZON CAPITOL', 'zip_code' => '4300'],
            ['municipality' => 'REAL', 'zip_code' => '4335'],
            ['municipality' => 'SAMPALOC', 'zip_code' => '4329'],
            ['municipality' => 'SAN ANDRES', 'zip_code' => '4314'],
            ['municipality' => 'SAN ANTONIO', 'zip_code' => '4324'],
            ['municipality' => 'SAN FRANCISCO', 'zip_code' => '4315'],
            ['municipality' => 'SAN NARCISO', 'zip_code' => '4313'],
            ['municipality' => 'SARIAYA', 'zip_code' => '4322'],
            ['municipality' => 'TAGKAWAYAN', 'zip_code' => '4321'],
            ['municipality' => 'TAYABAS', 'zip_code' => '4327'],
            ['municipality' => 'TIAONG', 'zip_code' => '4325'],
            ['municipality' => 'UNISAN', 'zip_code' => '4305'],
        ]
    ],

    [
        'province' => 'RIZAL PROVINCE',
        'zip_codes' => [
            ['municipality' => 'ANGONO', 'zip_code' => '1930'],
            ['municipality' => 'ANTIPOLO', 'zip_code' => '1870'],
            ['municipality' => 'BAGONG NAYON (COGEO)', 'zip_code' => '1872'],
            ['municipality' => 'BARAS', 'zip_code' => '1970'],
            ['municipality' => 'BINANGONAN', 'zip_code' => '1940'],
            ['municipality' => 'CAINTA', 'zip_code' => '1900'],
            ['municipality' => 'CARDONA', 'zip_code' => '1950'],
            ['municipality' => 'CUPANG', 'zip_code' => '1873'],
            ['municipality' => 'JALAJALA', 'zip_code' => '1990'],
            ['municipality' => 'LANGHAYA', 'zip_code' => '1874'],
            ['municipality' => 'MAMBAGAT', 'zip_code' => '1875'],
            ['municipality' => 'MAYAMOT', 'zip_code' => '1871'],
            ['municipality' => 'RODRIGUEZ (MONTALBAN)', 'zip_code' => '1860'],
            ['municipality' => 'MORONG', 'zip_code' => '1960'],
            ['municipality' => 'PILILLA', 'zip_code' => '1910'],
            ['municipality' => 'SAN MATEO', 'zip_code' => '1850'],
            ['municipality' => 'TANAY', 'zip_code' => '1980'],
            ['municipality' => 'TAYTAY', 'zip_code' => '1920'],
            ['municipality' => 'TERESA', 'zip_code' => '1880'],
        ]
    ],
];
