<?php
return [
  ["province" => "BATANGAS", "municipality" => "AGONCILLO", "zip_code" => "4211"],
  ["province" => "BATANGAS", "municipality" => "ALITAGTAG", "zip_code" => "4205"],
  ["province" => "BATANGAS", "municipality" => "BALAYAN", "zip_code" => "4213"],
  ["province" => "BATANGAS", "municipality" => "BALETE", "zip_code" => "4219"],
  ["province" => "BATANGAS", "municipality" => "BATANGAS CITY", "zip_code" => "4200"],
  ["province" => "BATANGAS", "municipality" => "BAUAN", "zip_code" => "4201"],
  ["province" => "BATANGAS", "municipality" => "CALACA", "zip_code" => "4212"],
  ["province" => "BATANGAS", "municipality" => "CALATAGAN", "zip_code" => "4215"],
  ["province" => "BATANGAS", "municipality" => "CUENCA", "zip_code" => "4222"],
  ["province" => "BATANGAS", "municipality" => "FERNANDO AIRBASE", "zip_code" => "4218"],
  ["province" => "BATANGAS", "municipality" => "IBAAN", "zip_code" => "4230"],
  ["province" => "BATANGAS", "municipality" => "LAUREL", "zip_code" => "4221"],
  ["province" => "BATANGAS", "municipality" => "LEMERY", "zip_code" => "4209"],
  ["province" => "BATANGAS", "municipality" => "LIAN", "zip_code" => "4216"],
  ["province" => "BATANGAS", "municipality" => "LIPA CITY", "zip_code" => "4217"],
  ["province" => "BATANGAS", "municipality" => "LOBO", "zip_code" => "4229"],
  ["province" => "BATANGAS", "municipality" => "MABINI", "zip_code" => "4202"],
  ["province" => "BATANGAS", "municipality" => "MALVAR", "zip_code" => "4233"],
  ["province" => "BATANGAS", "municipality" => "MATAAS NA KAHOY", "zip_code" => "4223"],
  ["province" => "BATANGAS", "municipality" => "NASUGBU", "zip_code" => "4231"],
  ["province" => "BATANGAS", "municipality" => "PADRE GARCIA", "zip_code" => "4224"],
  ["province" => "BATANGAS", "municipality" => "ROSARIO", "zip_code" => "4225"],
  ["province" => "BATANGAS", "municipality" => "SAN JOSE", "zip_code" => "4227"],
  ["province" => "BATANGAS", "municipality" => "SAN JUAN", "zip_code" => "4226"],
  ["province" => "BATANGAS", "municipality" => "SAN LUIS", "zip_code" => "4210"],
  ["province" => "BATANGAS", "municipality" => "SAN NICOLAS", "zip_code" => "4207"],
  ["province" => "BATANGAS", "municipality" => "SAN PASCUAL", "zip_code" => "4204"],
  ["province" => "BATANGAS", "municipality" => "STA. TERESITA", "zip_code" => "4206"],
  ["province" => "BATANGAS", "municipality" => "STO. TOMAS", "zip_code" => "4234"],
  ["province" => "BATANGAS", "municipality" => "TAAL", "zip_code" => "4208"],
  ["province" => "BATANGAS", "municipality" => "TALISAY", "zip_code" => "4220"],
  ["province" => "BATANGAS", "municipality" => "TANAUAN", "zip_code" => "4232"],
  ["province" => "BATANGAS", "municipality" => "TAYSAN", "zip_code" => "4228"],
  ["province" => "BATANGAS", "municipality" => "TINGLOY", "zip_code" => "4203"],
  ["province" => "BATANGAS", "municipality" => "TUY", "zip_code" => "4214"],

  ["province" => "CAVITE", "municipality" => "IST CAVITE IND. ESTATE", "zip_code" => "4126"],
  ["province" => "CAVITE", "municipality" => "ALFONSO", "zip_code" => "4123"],
  ["province" => "CAVITE", "municipality" => "AMADEO", "zip_code" => "4119"],
  ["province" => "CAVITE", "municipality" => "BACOOR", "zip_code" => "4102"],
  ["province" => "CAVITE", "municipality" => "CARMONA", "zip_code" => "4116"],
  ["province" => "CAVITE", "municipality" => "CAVITE CITY", "zip_code" => "4100"],
  ["province" => "CAVITE", "municipality" => "CAVITE NAVAL BASE", "zip_code" => "4101"],
  ["province" => "CAVITE", "municipality" => "CORREGIDOR", "zip_code" => "4125"],
  ["province" => "CAVITE", "municipality" => "DASMARIÑAS", "zip_code" => "4114"],
  ["province" => "CAVITE", "municipality" => "DASMARIÑAS RESETTLEMENT AREA", "zip_code" => "4115"],
  ["province" => "CAVITE", "municipality" => "GEN. AGUINALDO (BAILEN)", "zip_code" => "4124"],
  ["province" => "CAVITE", "municipality" => "GEN. MARIANO ALVAREZ", "zip_code" => "4117"],
  ["province" => "CAVITE", "municipality" => "GEN. TRIAS", "zip_code" => "4107"],
  ["province" => "CAVITE", "municipality" => "IMUS", "zip_code" => "4103"],
  ["province" => "CAVITE", "municipality" => "INDANG", "zip_code" => "4122"],
  ["province" => "CAVITE", "municipality" => "KAWIT", "zip_code" => "4104"],
  ["province" => "CAVITE", "municipality" => "MAGALLANES", "zip_code" => "4113"],
  ["province" => "CAVITE", "municipality" => "MARAGONDON", "zip_code" => "4112"],
  ["province" => "CAVITE", "municipality" => "MENDEZ", "zip_code" => "4121"],
  ["province" => "CAVITE", "municipality" => "MOLINO", "zip_code" => "4135"],
  ["province" => "CAVITE", "municipality" => "NAIC", "zip_code" => "4110"],
  ["province" => "CAVITE", "municipality" => "NOVELETA", "zip_code" => "4105"],
  ["province" => "CAVITE", "municipality" => "ROSARIO", "zip_code" => "4106"],
  ["province" => "CAVITE", "municipality" => "SILANG", "zip_code" => "4118"],
  ["province" => "CAVITE", "municipality" => "TAGAYTAY", "zip_code" => "4120"],
  ["province" => "CAVITE", "municipality" => "TANZA", "zip_code" => "4108"],
  ["province" => "CAVITE", "municipality" => "TERNATE", "zip_code" => "4111"],
  ["province" => "CAVITE", "municipality" => "TRECE MARTIREZ CITY", "zip_code" => "4109"],

  ["province" => "LAGUNA", "municipality" => "ALAMINOS", "zip_code" => "4001"],
  ["province" => "LAGUNA", "municipality" => "BAY", "zip_code" => "4033"],
  ["province" => "LAGUNA", "municipality" => "BIÑAN", "zip_code" => "4024"],
  ["province" => "LAGUNA", "municipality" => "BOTOCAN", "zip_code" => "4006"],
  ["province" => "LAGUNA", "municipality" => "CABUYAO", "zip_code" => "4025"],
  ["province" => "LAGUNA", "municipality" => "CALAMBA", "zip_code" => "4027"],
  ["province" => "LAGUNA", "municipality" => "CALUAN", "zip_code" => "4012"],
  ["province" => "LAGUNA", "municipality" => "CAMP VICENTE LIM", "zip_code" => "4029"],
  ["province" => "LAGUNA", "municipality" => "CANLUBANG", "zip_code" => "4028"],
  ["province" => "LAGUNA", "municipality" => "CAVINTI", "zip_code" => "4013"],
  ["province" => "LAGUNA", "municipality" => "COLLEGE LOS BAÑOS", "zip_code" => "4031"],
  ["province" => "LAGUNA", "municipality" => "FAMY", "zip_code" => "4021"],
  ["province" => "LAGUNA", "municipality" => "KALAYAAN", "zip_code" => "4015"],
  ["province" => "LAGUNA", "municipality" => "LAGUNA TECHNOPARK", "zip_code" => "4034"],
  ["province" => "LAGUNA", "municipality" => "LILIW", "zip_code" => "4004"],
  ["province" => "LAGUNA", "municipality" => "LOS BAÑOS", "zip_code" => "4030"],
  ["province" => "LAGUNA", "municipality" => "LUISIANA", "zip_code" => "4032"],
  ["province" => "LAGUNA", "municipality" => "LUMBAN", "zip_code" => "4014"],
  ["province" => "LAGUNA", "municipality" => "MABITAC", "zip_code" => "4020"],
  ["province" => "LAGUNA", "municipality" => "MAGDALENA", "zip_code" => "4007"],
  ["province" => "LAGUNA", "municipality" => "MAJAYJAY", "zip_code" => "4005"],
  ["province" => "LAGUNA", "municipality" => "NAGCARLAN", "zip_code" => "4002"],
  ["province" => "LAGUNA", "municipality" => "PAETE", "zip_code" => "4016"],
  ["province" => "LAGUNA", "municipality" => "PAGSANJAN", "zip_code" => "4008"],
  ["province" => "LAGUNA", "municipality" => "PAKIL", "zip_code" => "4017"],
  ["province" => "LAGUNA", "municipality" => "PANGIL", "zip_code" => "4018"],
  ["province" => "LAGUNA", "municipality" => "PILA", "zip_code" => "4010"],
  ["province" => "LAGUNA", "municipality" => "RIZAL", "zip_code" => "4003"],
  ["province" => "LAGUNA", "municipality" => "SAN PABLO CITY", "zip_code" => "4000"],
  ["province" => "LAGUNA", "municipality" => "SAN PEDRO", "zip_code" => "4023"],
  ["province" => "LAGUNA", "municipality" => "SINILOAN", "zip_code" => "4019"],
  ["province" => "LAGUNA", "municipality" => "STA. CRUZ", "zip_code" => "4009"],
  ["province" => "LAGUNA", "municipality" => "STA. MARIA", "zip_code" => "4022"],
  ["province" => "LAGUNA", "municipality" => "STA. ROSA", "zip_code" => "4026"],
  ["province" => "LAGUNA", "municipality" => "VICTORIA", "zip_code" => "4011"],

  ["province" => "QUEZON PROVINCE", "municipality" => "AGDANGAN", "zip_code" => "4304"],
  ["province" => "QUEZON PROVINCE", "municipality" => "ALABAT", "zip_code" => "4333"],
  ["province" => "QUEZON PROVINCE", "municipality" => "ATIMONAN", "zip_code" => "4331"],
  ["province" => "QUEZON PROVINCE", "municipality" => "BUENAVISTA", "zip_code" => "4320"],
  ["province" => "QUEZON PROVINCE", "municipality" => "BURDEOS", "zip_code" => "4340"],
  ["province" => "QUEZON PROVINCE", "municipality" => "CALAUAG", "zip_code" => "4318"],
  ["province" => "QUEZON PROVINCE", "municipality" => "CANDELARIA", "zip_code" => "4323"],
  ["province" => "QUEZON PROVINCE", "municipality" => "CATANAUAN", "zip_code" => "4311"],
  ["province" => "QUEZON PROVINCE", "municipality" => "DOLORES", "zip_code" => "4326"],
  ["province" => "QUEZON PROVINCE", "municipality" => "GENERAL LUNA", "zip_code" => "4310"],
  ["province" => "QUEZON PROVINCE", "municipality" => "GENERAL NAKAR", "zip_code" => "4338"],
  ["province" => "QUEZON PROVINCE", "municipality" => "GUINAYANGAN", "zip_code" => "4319"],
  ["province" => "QUEZON PROVINCE", "municipality" => "GUMACA", "zip_code" => "4307"],
  ["province" => "QUEZON PROVINCE", "municipality" => "HONDAGUA", "zip_code" => "4317"],
  ["province" => "QUEZON PROVINCE", "municipality" => "INFANTA", "zip_code" => "4336"],
  ["province" => "QUEZON PROVINCE", "municipality" => "JOMALIG", "zip_code" => "4342"],
  ["province" => "QUEZON PROVINCE", "municipality" => "LOPEZ", "zip_code" => "4316"],
  ["province" => "QUEZON PROVINCE", "municipality" => "LUCBAN", "zip_code" => "4328"],
  ["province" => "QUEZON PROVINCE", "municipality" => "LUCENA CITY", "zip_code" => "4301"],
  ["province" => "QUEZON PROVINCE", "municipality" => "MACALELON", "zip_code" => "4309"],
  ["province" => "QUEZON PROVINCE", "municipality" => "MAUBAN", "zip_code" => "4330"],
  ["province" => "QUEZON PROVINCE", "municipality" => "MULANAY", "zip_code" => "4312"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PADRE BURGOS", "zip_code" => "4303"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PAGBILAO", "zip_code" => "4302"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PANUKULAN", "zip_code" => "4337"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PATNANUNGAN", "zip_code" => "4341"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PEREZ", "zip_code" => "4334"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PITOGO", "zip_code" => "4308"],
  ["province" => "QUEZON PROVINCE", "municipality" => "PLARIDEL", "zip_code" => "4306"],
  ["province" => "QUEZON PROVINCE", "municipality" => "POLILIO", "zip_code" => "4339"],
  ["province" => "QUEZON PROVINCE", "municipality" => "QUEZON     ", "zip_code" => "4332"],
  ["province" => "QUEZON PROVINCE", "municipality" => "QUEZON CAPITOL", "zip_code" => "4300"],
  ["province" => "QUEZON PROVINCE", "municipality" => "REAL", "zip_code" => "4335"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SAMPALOC", "zip_code" => "4329"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SAN ANDRES", "zip_code" => "4314"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SAN ANTONIO", "zip_code" => "4324"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SAN FRANCISCO", "zip_code" => "4315"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SAN NARCISO", "zip_code" => "4313"],
  ["province" => "QUEZON PROVINCE", "municipality" => "SARIAYA", "zip_code" => "4322"],
  ["province" => "QUEZON PROVINCE", "municipality" => "TAGKAWAYAN", "zip_code" => "4321"],
  ["province" => "QUEZON PROVINCE", "municipality" => "TAYABAS", "zip_code" => "4327"],
  ["province" => "QUEZON PROVINCE", "municipality" => "TIAONG", "zip_code" => "4325"],
  ["province" => "QUEZON PROVINCE", "municipality" => "UNISAN", "zip_code" => "4305"],

  ["province" => "RIZAL PROVINCE", "municipality" => "ANGONO", "zip_code" => "1930"],
  ["province" => "RIZAL PROVINCE", "municipality" => "ANTIPOLO", "zip_code" => "1870"],
  ["province" => "RIZAL PROVINCE", "municipality" => "BAGONG NAYON (COGEO)", "zip_code" => "1872"],
  ["province" => "RIZAL PROVINCE", "municipality" => "BARAS", "zip_code" => "1970"],
  ["province" => "RIZAL PROVINCE", "municipality" => "BINANGONAN", "zip_code" => "1940"],
  ["province" => "RIZAL PROVINCE", "municipality" => "CAINTA", "zip_code" => "1900"],
  ["province" => "RIZAL PROVINCE", "municipality" => "CARDONA", "zip_code" => "1950"],
  ["province" => "RIZAL PROVINCE", "municipality" => "CUPANG", "zip_code" => "1873"],
  ["province" => "RIZAL PROVINCE", "municipality" => "JALAJALA", "zip_code" => "1990"],
  ["province" => "RIZAL PROVINCE", "municipality" => "LANGHAYA", "zip_code" => "1874"],
  ["province" => "RIZAL PROVINCE", "municipality" => "MAMBAGAT", "zip_code" => "1875"],
  ["province" => "RIZAL PROVINCE", "municipality" => "MAYAMOT", "zip_code" => "1871"],
  ["province" => "RIZAL PROVINCE", "municipality" => "RODRIGUEZ (MONTALBAN)", "zip_code" => "1860"],
  ["province" => "RIZAL PROVINCE", "municipality" => "MORONG", "zip_code" => "1960"],
  ["province" => "RIZAL PROVINCE", "municipality" => "PILILLA", "zip_code" => "1910"],
  ["province" => "RIZAL PROVINCE", "municipality" => "SAN MATEO", "zip_code" => "1850"],
  ["province" => "RIZAL PROVINCE", "municipality" => "TANAY", "zip_code" => "1980"],
  ["province" => "RIZAL PROVINCE", "municipality" => "TAYTAY", "zip_code" => "1920"],
  ["province" => "RIZAL PROVINCE", "municipality" => "TERESA", "zip_code" => "1880"],
];
